// Canonical (mock) model for the Integrations & Connectivity screen.
// All state is local simulation — no live connections are ever made.

export type IntegrationStatus =
  | "connected"
  | "degraded"
  | "not_configured"
  | "disabled"
  | "failed"
  | "testing"
  | "stale"
  | "blocked";

export type AccessMode =
  | "read_only"
  | "discovery"
  | "discovery_scoped_execution"
  | "approved_write"
  | "policy_governed_execution"
  | "disabled";

export type Maturity = "available" | "demo" | "customer_specific" | "planned";

export type ConnectivityScenario =
  | "normal"
  | "aws_discovery_failure"
  | "sql_auth_failure"
  | "windows_runner_offline"
  | "git_unavailable"
  | "secret_store_unreachable"
  | "rate_limit_warning";

export interface CapabilityImpact {
  capability: string;
  state: "available" | "degraded" | "partial" | "blocked";
}

export interface ScopeRow {
  label: string;
  value: string;
}

export interface Integration {
  id: string;
  name: string;
  category: string;
  domain: string;
  purpose: string;
  connectionType: string;
  accessMode: AccessMode;
  status: IntegrationStatus;
  health: number;
  lastActivity: string;
  maturity: Maturity;
  executionCapable: boolean;
  businessOwner: string;
  technicalOwner: string;
  supportGroup: string;
  ownership: "CUSTOMER" | "SHARED" | "SERVICE TEAM";
  environments: string[];
  discoveryIdentity: string;
  executionIdentity: string | null;
  credentialSource: string;
  expiration: string;
  rotation: string;
  lastValidation: string;
  dependencies: string[];
  capabilities: string[];
  discoveryPerms: string[];
  executionPerms: string[];
  excluded: string[];
  scope: ScopeRow[];
  assets: string[];
  testCount: number;
  useCaseRole?: string;
}

export const CATEGORIES = [
  "All Integrations",
  "Cloud & Infrastructure",
  "Compute & OS",
  "Data & Applications",
  "Enterprise Services",
  "Security & Identity",
  "Monitoring & Observability",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const INTEGRATIONS: Integration[] = [
  {
    id: "aws",
    name: "AWS (12 Accounts)",
    category: "Cloud & Infrastructure",
    domain: "Cloud",
    purpose: "AWS APIs, Resources & Telemetry",
    connectionType: "AWS IAM Role (Read + Write)",
    accessMode: "discovery_scoped_execution",
    status: "connected",
    health: 98,
    lastActivity: "2 min ago",
    maturity: "demo",
    executionCapable: true,
    businessOwner: "Cloud Platform",
    technicalOwner: "Cloud Engineering",
    supportGroup: "Infrastructure Operations",
    ownership: "CUSTOMER",
    environments: ["Production", "Non-Production", "Shared Services", "Development"],
    discoveryIdentity: "iac-discovery-prod",
    executionIdentity: "iac-execution-prod",
    credentialSource: "AWS IAM / AssumeRole",
    expiration: "Session based",
    rotation: "N/A — trust policy",
    lastValidation: "2 min ago",
    dependencies: ["secrets", "cloudwatch"],
    capabilities: ["Resource Inventory", "Configuration State", "Tag & Metadata", "Metrics & Alarms", "Logs & Events", "IaC Execution", "Validation & Testing"],
    discoveryPerms: ["Describe* APIs", "List* APIs", "Get* APIs", "CloudWatch (Read)", "AWS Config (Read)"],
    executionPerms: ["Create / Modify (Approved)", "Update / Patch (Approved)", "Tag / Untag Resources", "Read After Write"],
    excluded: ["IAM changes", "KMS policy changes", "Organization administration", "Route53 changes unless explicitly enabled", "No Delete / Destroy by default"],
    scope: [
      { label: "Accounts", value: "4 Production Accounts" },
      { label: "Regions", value: "us-east-1, us-west-2" },
      { label: "Resource Types", value: "EC2, EBS, ELB" },
      { label: "Allowed Tags", value: "ManagedBy = IntelligentIaC" },
      { label: "Scope Expansion Requires", value: "Customer approval" },
    ],
    assets: ["EC2", "EBS", "S3", "VPC", "IAM (read)", "Load Balancers", "EKS"],
    testCount: 7,
    useCaseRole: "Discover EC2/EBS state and execute approved EBS mutation.",
  },
  {
    id: "azure",
    name: "Azure (3 Subscriptions)",
    category: "Cloud & Infrastructure",
    domain: "Cloud",
    purpose: "Azure Resource Manager",
    connectionType: "Service Principal (Read + Write)",
    accessMode: "discovery_scoped_execution",
    status: "not_configured",
    health: 0,
    lastActivity: "—",
    maturity: "available",
    executionCapable: true,
    businessOwner: "Cloud Platform",
    technicalOwner: "Cloud Engineering",
    supportGroup: "Infrastructure Operations",
    ownership: "CUSTOMER",
    environments: ["Production", "Non-Production"],
    discoveryIdentity: "sp-iac-discovery",
    executionIdentity: "sp-iac-execution",
    credentialSource: "Managed Identity / Service Principal",
    expiration: "—",
    rotation: "—",
    lastValidation: "—",
    dependencies: ["secrets"],
    capabilities: ["Resource Inventory", "Configuration State", "IaC Execution"],
    discoveryPerms: ["Reader role", "Resource Graph query"],
    executionPerms: ["Scoped Contributor (Approved targets)", "Terraform / Bicep apply"],
    excluded: ["Role assignment changes", "Subscription administration", "Key Vault policy changes"],
    scope: [
      { label: "Subscriptions", value: "Not configured" },
      { label: "Regions", value: "—" },
      { label: "Scope Expansion Requires", value: "Customer approval" },
    ],
    assets: ["VMs", "Managed Disks", "VNets", "Load Balancers"],
    testCount: 6,
  },
  {
    id: "gcp",
    name: "GCP (2 Projects)",
    category: "Cloud & Infrastructure",
    domain: "Cloud",
    purpose: "GCP APIs & Resources",
    connectionType: "Service Account (Read + Write)",
    accessMode: "discovery_scoped_execution",
    status: "not_configured",
    health: 0,
    lastActivity: "—",
    maturity: "available",
    executionCapable: true,
    businessOwner: "Cloud Platform",
    technicalOwner: "Cloud Engineering",
    supportGroup: "Infrastructure Operations",
    ownership: "CUSTOMER",
    environments: ["Non-Production"],
    discoveryIdentity: "sa-iac-discovery",
    executionIdentity: "sa-iac-execution",
    credentialSource: "GCP Service Account / Workload Identity",
    expiration: "—",
    rotation: "—",
    lastValidation: "—",
    dependencies: ["secrets"],
    capabilities: ["Resource Inventory", "Configuration State", "IaC Execution"],
    discoveryPerms: ["Viewer role", "Asset Inventory read"],
    executionPerms: ["Scoped resource mutation (Approved)", "Terraform apply"],
    excluded: ["IAM policy changes", "Org policy changes"],
    scope: [
      { label: "Projects", value: "Not configured" },
      { label: "Scope Expansion Requires", value: "Customer approval" },
    ],
    assets: ["Compute Engine", "Persistent Disks", "VPC"],
    testCount: 6,
  },
  {
    id: "kubernetes",
    name: "Kubernetes (EKS + AKS)",
    category: "Cloud & Infrastructure",
    domain: "Containers",
    purpose: "Cluster Inventory & APIs",
    connectionType: "Kubeconfig / OIDC",
    accessMode: "discovery_scoped_execution",
    status: "connected",
    health: 97,
    lastActivity: "5 min ago",
    maturity: "available",
    executionCapable: true,
    businessOwner: "Platform Engineering",
    technicalOwner: "Container Platform Team",
    supportGroup: "Platform Operations",
    ownership: "CUSTOMER",
    environments: ["Production", "Non-Production", "Development"],
    discoveryIdentity: "sa-iac-read (namespace scoped)",
    executionIdentity: "sa-iac-exec (namespace + action scoped)",
    credentialSource: "OIDC / Service Account token",
    expiration: "1 hour (projected token)",
    rotation: "Automatic",
    lastValidation: "5 min ago",
    dependencies: ["secrets"],
    capabilities: ["Clusters", "Namespaces", "Workloads", "Services", "Nodes", "Storage"],
    discoveryPerms: ["get / list / watch (namespace scoped)"],
    executionPerms: ["Scale workload", "Restart rollout", "Manifest deployment (Approved)", "Config update", "Resource-limit change"],
    excluded: ["cluster-admin", "CRD deletion", "Namespace deletion"],
    scope: [
      { label: "Clusters", value: "6 (EKS 4 / AKS 2)" },
      { label: "Namespaces", value: "Explicitly allow-listed" },
      { label: "Policy", value: "Namespace + action scoped" },
    ],
    assets: ["Deployments", "StatefulSets", "Services", "Nodes", "PVCs"],
    testCount: 6,
  },
  {
    id: "vmware",
    name: "VMware vCenter",
    category: "Cloud & Infrastructure",
    domain: "Virtualization",
    purpose: "VM Inventory & Configuration",
    connectionType: "vSphere API",
    accessMode: "discovery_scoped_execution",
    status: "connected",
    health: 95,
    lastActivity: "7 min ago",
    maturity: "available",
    executionCapable: true,
    businessOwner: "Infrastructure",
    technicalOwner: "Virtualization Team",
    supportGroup: "Infrastructure Operations",
    ownership: "CUSTOMER",
    environments: ["Production", "Non-Production"],
    discoveryIdentity: "svc-iac-vsphere-read",
    executionIdentity: "svc-iac-vsphere-exec",
    credentialSource: "CyberArk",
    expiration: "90 days",
    rotation: "Compliant",
    lastValidation: "7 min ago",
    dependencies: ["secrets"],
    capabilities: ["vCenter", "Clusters", "Hosts", "VMs", "Datastores", "Networks"],
    discoveryPerms: ["vSphere API Read"],
    executionPerms: ["Power operations", "Resize", "Snapshot", "Migration", "Storage operation"],
    excluded: ["VM deletion", "Datastore deletion", "Permission changes"],
    scope: [
      { label: "vCenters", value: "2" },
      { label: "Clusters", value: "9" },
      { label: "Execution Controlled By", value: "Package + Policy + vCenter service identity" },
      { label: "Validation", value: "vSphere state + guest state where available" },
    ],
    assets: ["VMs", "Hosts", "Datastores", "Port Groups"],
    testCount: 6,
  },
  {
    id: "nutanix",
    name: "Nutanix Prism",
    category: "Cloud & Infrastructure",
    domain: "Virtualization",
    purpose: "Infrastructure & VM Data",
    connectionType: "Prism Central API",
    accessMode: "discovery_scoped_execution",
    status: "connected",
    health: 94,
    lastActivity: "10 min ago",
    maturity: "customer_specific",
    executionCapable: true,
    businessOwner: "Infrastructure",
    technicalOwner: "Virtualization Team",
    supportGroup: "Infrastructure Operations",
    ownership: "CUSTOMER",
    environments: ["Non-Production"],
    discoveryIdentity: "svc-iac-prism-read",
    executionIdentity: "svc-iac-prism-exec",
    credentialSource: "CyberArk",
    expiration: "90 days",
    rotation: "Compliant",
    lastValidation: "10 min ago",
    dependencies: ["secrets"],
    capabilities: ["Prism Central", "Clusters", "VMs", "Storage", "Networks"],
    discoveryPerms: ["Prism API read"],
    executionPerms: ["Scoped API actions (Approved)"],
    excluded: ["Cluster destroy", "Storage container deletion"],
    scope: [
      { label: "Prism Central", value: "1" },
      { label: "Clusters", value: "4" },
      { label: "Validation", value: "Prism state" },
    ],
    assets: ["VMs", "Storage Containers", "Subnets"],
    testCount: 5,
  },
  {
    id: "windows",
    name: "Windows Servers",
    category: "Compute & OS",
    domain: "Operating System",
    purpose: "Inventory & Configuration",
    connectionType: "WinRM (TLS)",
    accessMode: "discovery_scoped_execution",
    status: "connected",
    health: 98,
    lastActivity: "1 min ago",
    maturity: "demo",
    executionCapable: true,
    businessOwner: "Infrastructure",
    technicalOwner: "Windows Platform Team",
    supportGroup: "Server Operations",
    ownership: "CUSTOMER",
    environments: ["Production", "Non-Production"],
    discoveryIdentity: "svc-iac-win-read",
    executionIdentity: "svc-iac-win-exec",
    credentialSource: "CyberArk",
    expiration: "60 days",
    rotation: "Compliant",
    lastValidation: "1 min ago",
    dependencies: ["secrets", "activedirectory"],
    capabilities: ["Extend filesystem", "Restart service", "Modify IIS", "Patch server", "Certificate deployment", "Windows configuration change"],
    discoveryPerms: ["WMI / CIM read", "Filesystem inventory", "Service inventory"],
    executionPerms: ["Approved PowerShell package only", "Volume extend", "Service restart"],
    excluded: ["Interactive logon", "Local admin group changes", "Arbitrary script execution"],
    scope: [
      { label: "Servers", value: "418" },
      { label: "Management Endpoint", value: "WinRM 5986 (TLS)" },
      { label: "Runner", value: "Customer Execution Zone" },
    ],
    assets: ["Volumes", "Services", "Scheduled Tasks", "IIS Sites"],
    testCount: 7,
    useCaseRole: "Discover and extend the L: volume on SQL-PROD-07.",
  },
  {
    id: "linux",
    name: "Linux Servers",
    category: "Compute & OS",
    domain: "Operating System",
    purpose: "Inventory & Configuration",
    connectionType: "SSH / Ansible",
    accessMode: "discovery",
    status: "connected",
    health: 96,
    lastActivity: "4 min ago",
    maturity: "available",
    executionCapable: true,
    businessOwner: "Infrastructure",
    technicalOwner: "Linux Platform Team",
    supportGroup: "Server Operations",
    ownership: "CUSTOMER",
    environments: ["Production", "Non-Production", "Development"],
    discoveryIdentity: "svc-iac-nix-read",
    executionIdentity: "svc-iac-nix-exec",
    credentialSource: "CyberArk",
    expiration: "60 days",
    rotation: "Compliant",
    lastValidation: "4 min ago",
    dependencies: ["secrets"],
    capabilities: ["Package inventory", "Filesystem", "Services", "Configuration"],
    discoveryPerms: ["Read-only facts gathering"],
    executionPerms: ["Approved playbook only"],
    excluded: ["Root shell", "Arbitrary command execution"],
    scope: [
      { label: "Servers", value: "612" },
      { label: "Execution", value: "Not enabled" },
    ],
    assets: ["Filesystems", "systemd units", "Packages"],
    testCount: 5,
  },
  {
    id: "sqlserver",
    name: "SQL Server (14 Instances)",
    category: "Data & Applications",
    domain: "Database",
    purpose: "Diagnostics & State",
    connectionType: "TDS / Integrated Security",
    accessMode: "discovery_scoped_execution",
    status: "connected",
    health: 99,
    lastActivity: "1 min ago",
    maturity: "demo",
    executionCapable: true,
    businessOwner: "Application Services",
    technicalOwner: "Database Engineering",
    supportGroup: "Database Operations",
    ownership: "CUSTOMER",
    environments: ["Production", "Non-Production"],
    discoveryIdentity: "svc-iac-sql-read",
    executionIdentity: "svc-iac-sql-exec",
    credentialSource: "Integrated Security / CyberArk",
    expiration: "Kerberos ticket",
    rotation: "Compliant",
    lastValidation: "1 min ago",
    dependencies: ["secrets", "windows"],
    capabilities: ["Instance inventory", "Database state", "Log space diagnostics", "Backup state", "Approved transaction-log actions"],
    discoveryPerms: ["VIEW SERVER STATE", "VIEW ANY DEFINITION", "DMV read"],
    executionPerms: ["Approved T-SQL package only", "BACKUP LOG (approved)", "File growth (approved)"],
    excluded: ["DROP / TRUNCATE", "Schema modification", "Security principal changes"],
    scope: [
      { label: "Instances", value: "14" },
      { label: "Authentication Method", value: "Integrated Security" },
      { label: "Backup Access", value: "Validated" },
    ],
    assets: ["Instances", "Databases", "Log Files", "Backup Jobs"],
    testCount: 6,
    useCaseRole: "Diagnose LOG_BACKUP and execute approved transaction-log action.",
  },
  {
    id: "activedirectory",
    name: "Active Directory",
    category: "Security & Identity",
    domain: "Identity",
    purpose: "AD Objects & Relationships",
    connectionType: "LDAPS / PowerShell",
    accessMode: "discovery",
    status: "connected",
    health: 96,
    lastActivity: "6 min ago",
    maturity: "available",
    executionCapable: true,
    businessOwner: "Enterprise IT",
    technicalOwner: "Identity Engineering",
    supportGroup: "Identity Operations",
    ownership: "CUSTOMER",
    environments: ["Production", "Shared Services"],
    discoveryIdentity: "svc-iac-ad-read",
    executionIdentity: "svc-iac-ad-exec",
    credentialSource: "CyberArk",
    expiration: "90 days",
    rotation: "Compliant",
    lastValidation: "6 min ago",
    dependencies: ["secrets"],
    capabilities: ["Domains", "Domain Controllers", "OUs", "Groups", "Users", "GPO relationships"],
    discoveryPerms: ["Directory read"],
    executionPerms: ["Group membership (approved)", "OU operations (approved)", "Approved object creation", "Approved configuration change"],
    excluded: ["Schema modification", "Forest-level changes", "Privileged group changes without elevated authorization"],
    scope: [
      { label: "Domains", value: "3" },
      { label: "Execution", value: "Policy gated" },
    ],
    assets: ["Users", "Groups", "OUs", "GPOs"],
    testCount: 5,
  },
  {
    id: "m365",
    name: "Microsoft 365",
    category: "Enterprise Services",
    domain: "SaaS",
    purpose: "Users, Groups, Services",
    connectionType: "Microsoft Graph API",
    accessMode: "read_only",
    status: "connected",
    health: 93,
    lastActivity: "8 min ago",
    maturity: "available",
    executionCapable: true,
    businessOwner: "Enterprise IT",
    technicalOwner: "Collaboration Team",
    supportGroup: "Workplace Services",
    ownership: "CUSTOMER",
    environments: ["Production"],
    discoveryIdentity: "app-iac-graph-read",
    executionIdentity: "app-iac-graph-write",
    credentialSource: "Entra ID app registration",
    expiration: "180 days (client secret)",
    rotation: "Compliant",
    lastValidation: "8 min ago",
    dependencies: ["secrets"],
    capabilities: ["Users", "Groups", "Licenses", "Teams / service configuration"],
    discoveryPerms: ["Graph read (User.Read.All, Group.Read.All)"],
    executionPerms: ["Scoped Graph write with customer consent"],
    excluded: ["Directory role assignment", "Tenant-wide policy changes"],
    scope: [
      { label: "Customer Consent", value: "Required" },
      { label: "Secrets", value: "Customer controlled" },
      { label: "Production Policy", value: "Applied" },
    ],
    assets: ["Users", "Groups", "Licenses"],
    testCount: 4,
  },
  {
    id: "servicenow",
    name: "ServiceNow",
    category: "Enterprise Services",
    domain: "ITSM / CMDB",
    purpose: "Change, Incident, CMDB",
    connectionType: "REST API",
    accessMode: "approved_write",
    status: "connected",
    health: 96,
    lastActivity: "3 min ago",
    maturity: "demo",
    executionCapable: false,
    businessOwner: "Service Management",
    technicalOwner: "ITSM Platform Team",
    supportGroup: "ITSM Operations",
    ownership: "SHARED",
    environments: ["Production"],
    discoveryIdentity: "svc-iac-snow-read",
    executionIdentity: "svc-iac-snow-write",
    credentialSource: "OAuth client credential",
    expiration: "Token based",
    rotation: "Compliant",
    lastValidation: "3 min ago",
    dependencies: [],
    capabilities: ["CI data", "Relationships", "Ownership", "Incidents", "Changes", "Maintenance windows"],
    discoveryPerms: ["CI read", "Change read", "Incident read", "Maintenance window read"],
    executionPerms: ["Create change record", "Update execution status", "Attach evidence", "Close change"],
    excluded: ["Infrastructure execution — ServiceNow does not perform infrastructure mutation"],
    scope: [
      { label: "Infrastructure Execution", value: "No" },
      { label: "Role", value: "Governance / context integration" },
    ],
    assets: ["CIs", "Change Requests", "Incidents"],
    testCount: 5,
    useCaseRole: "Change record, CI context and ownership for CP-2026-01842.",
  },
  {
    id: "github",
    name: "GitHub Enterprise",
    category: "Enterprise Services",
    domain: "Source Control",
    purpose: "IaC & Code Repositories",
    connectionType: "HTTPS / PAT",
    accessMode: "approved_write",
    status: "connected",
    health: 100,
    lastActivity: "1 min ago",
    maturity: "demo",
    executionCapable: false,
    businessOwner: "Engineering",
    technicalOwner: "DevOps Platform Team",
    supportGroup: "Engineering Enablement",
    ownership: "CUSTOMER",
    environments: ["Production", "Non-Production"],
    discoveryIdentity: "iac-app-read",
    executionIdentity: "iac-app-write",
    credentialSource: "GitHub App installation token",
    expiration: "1 hour",
    rotation: "Automatic",
    lastValidation: "1 min ago",
    dependencies: [],
    capabilities: ["Repositories", "Branches", "Pull Requests", "Commit history", "IaC files", "Runbooks"],
    discoveryPerms: ["Read existing desired state", "Read commit history"],
    executionPerms: ["Create approved branch", "Create / update generated artifacts", "Create pull request"],
    excluded: ["No production infrastructure credentials", "No force push to protected branches", "Execution is separate from Git access"],
    scope: [
      { label: "Organizations", value: "2" },
      { label: "Repositories", value: "18 IaC repositories" },
      { label: "Branch Policy", value: "PR required" },
    ],
    assets: ["Repos", "Branches", "PRs"],
    testCount: 5,
    useCaseRole: "Version generated Terraform artifacts for the EBS change.",
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "Enterprise Services",
    domain: "Source Control",
    purpose: "IaC & Code Repositories",
    connectionType: "HTTPS / Token",
    accessMode: "approved_write",
    status: "connected",
    health: 99,
    lastActivity: "2 min ago",
    maturity: "available",
    executionCapable: false,
    businessOwner: "Engineering",
    technicalOwner: "DevOps Platform Team",
    supportGroup: "Engineering Enablement",
    ownership: "CUSTOMER",
    environments: ["Non-Production"],
    discoveryIdentity: "iac-gl-read",
    executionIdentity: "iac-gl-write",
    credentialSource: "Project access token",
    expiration: "90 days",
    rotation: "Compliant",
    lastValidation: "2 min ago",
    dependencies: [],
    capabilities: ["Repositories", "Branches", "Merge Requests"],
    discoveryPerms: ["Repository read"],
    executionPerms: ["Create branch", "Create merge request"],
    excluded: ["No production infrastructure credentials"],
    scope: [{ label: "Groups", value: "1" }],
    assets: ["Repos", "MRs"],
    testCount: 4,
  },
  {
    id: "terraform",
    name: "Terraform Cloud",
    category: "Enterprise Services",
    domain: "IaC / State",
    purpose: "Remote State & Runs",
    connectionType: "HTTPS / Token",
    accessMode: "policy_governed_execution",
    status: "connected",
    health: 98,
    lastActivity: "2 min ago",
    maturity: "demo",
    executionCapable: true,
    businessOwner: "Engineering",
    technicalOwner: "DevOps Platform Team",
    supportGroup: "Engineering Enablement",
    ownership: "CUSTOMER",
    environments: ["Production", "Non-Production"],
    discoveryIdentity: "tfc-read",
    executionIdentity: "tfc-apply (approved workspace)",
    credentialSource: "Workspace token",
    expiration: "Token based",
    rotation: "Compliant",
    lastValidation: "2 min ago",
    dependencies: ["github", "secrets"],
    capabilities: ["Remote state", "Plan", "Approved apply", "Drift detection"],
    discoveryPerms: ["State read", "Run history read"],
    executionPerms: ["Apply approved plan only"],
    excluded: ["Destroy plans", "Workspace deletion"],
    scope: [
      { label: "Workspaces", value: "24" },
      { label: "Apply", value: "Approved package only" },
    ],
    assets: ["Workspaces", "State versions"],
    testCount: 4,
    useCaseRole: "Execute the approved Terraform plan for aws_ebs_volume.",
  },
  {
    id: "ansible",
    name: "Ansible Automation",
    category: "Enterprise Services",
    domain: "Automation",
    purpose: "Configuration Automation",
    connectionType: "Ansible Controller API",
    accessMode: "policy_governed_execution",
    status: "connected",
    health: 94,
    lastActivity: "12 min ago",
    maturity: "available",
    executionCapable: true,
    businessOwner: "Infrastructure",
    technicalOwner: "Automation Team",
    supportGroup: "Infrastructure Operations",
    ownership: "CUSTOMER",
    environments: ["Production", "Non-Production"],
    discoveryIdentity: "aap-read",
    executionIdentity: "aap-exec",
    credentialSource: "Controller token / CyberArk",
    expiration: "90 days",
    rotation: "Compliant",
    lastValidation: "12 min ago",
    dependencies: ["secrets"],
    capabilities: ["Job templates", "Inventory", "Approved configuration runs"],
    discoveryPerms: ["Inventory read", "Job history read"],
    executionPerms: ["Approved job template execution"],
    excluded: ["Ad-hoc command execution"],
    scope: [{ label: "Job Templates", value: "37 approved" }],
    assets: ["Inventories", "Job Templates"],
    testCount: 4,
  },
  {
    id: "cloudwatch",
    name: "CloudWatch",
    category: "Monitoring & Observability",
    domain: "Monitoring",
    purpose: "Metrics, Logs & Alarms",
    connectionType: "AWS IAM Role (Read)",
    accessMode: "read_only",
    status: "connected",
    health: 99,
    lastActivity: "30 sec ago",
    maturity: "demo",
    executionCapable: false,
    businessOwner: "Operations",
    technicalOwner: "Observability Team",
    supportGroup: "Infrastructure Operations",
    ownership: "SHARED",
    environments: ["Production", "Non-Production"],
    discoveryIdentity: "iac-discovery-prod",
    executionIdentity: null,
    credentialSource: "AWS IAM / AssumeRole",
    expiration: "Session based",
    rotation: "N/A",
    lastValidation: "30 sec ago",
    dependencies: ["aws"],
    capabilities: ["Telemetry", "Health", "Logs", "Metrics", "Alerts", "Baseline", "Validation Evidence"],
    discoveryPerms: ["GetMetricData", "DescribeAlarms", "FilterLogEvents"],
    executionPerms: [],
    excluded: ["No mutation — observability is a validation input, not a change target"],
    scope: [{ label: "Default Access", value: "Read Only" }, { label: "Mutation", value: "None" }],
    assets: ["Metrics", "Alarms", "Log Groups"],
    testCount: 4,
    useCaseRole: "Telemetry and runtime health for validation.",
  },
  {
    id: "datadog",
    name: "Datadog",
    category: "Monitoring & Observability",
    domain: "Monitoring",
    purpose: "APM, Metrics & Monitors",
    connectionType: "REST API (Read)",
    accessMode: "read_only",
    status: "connected",
    health: 97,
    lastActivity: "1 min ago",
    maturity: "available",
    executionCapable: false,
    businessOwner: "Operations",
    technicalOwner: "Observability Team",
    supportGroup: "Application Operations",
    ownership: "SHARED",
    environments: ["Production"],
    discoveryIdentity: "dd-iac-read",
    executionIdentity: null,
    credentialSource: "API / App key (customer vault)",
    expiration: "N/A",
    rotation: "Compliant",
    lastValidation: "1 min ago",
    dependencies: [],
    capabilities: ["Telemetry", "APM", "Monitors", "Baseline"],
    discoveryPerms: ["Metrics read", "Monitor read", "APM read"],
    executionPerms: [],
    excluded: ["No mutation"],
    scope: [{ label: "Default Access", value: "Read Only" }],
    assets: ["Monitors", "Dashboards", "Services"],
    testCount: 3,
  },
  {
    id: "appmonitoring",
    name: "Application Monitoring",
    category: "Monitoring & Observability",
    domain: "Monitoring",
    purpose: "Business-service Validation",
    connectionType: "REST API (Read)",
    accessMode: "read_only",
    status: "connected",
    health: 98,
    lastActivity: "45 sec ago",
    maturity: "demo",
    executionCapable: false,
    businessOwner: "Application Services",
    technicalOwner: "Application Operations",
    supportGroup: "Application Operations",
    ownership: "SHARED",
    environments: ["Production"],
    discoveryIdentity: "apm-iac-read",
    executionIdentity: null,
    credentialSource: "API key (customer vault)",
    expiration: "N/A",
    rotation: "Compliant",
    lastValidation: "45 sec ago",
    dependencies: [],
    capabilities: ["Business service health", "Transaction throughput", "Latency", "Error rate"],
    discoveryPerms: ["Service metrics read"],
    executionPerms: [],
    excluded: ["No mutation"],
    scope: [{ label: "Services", value: "Order Processing Service + 31 others" }],
    assets: ["Services", "Transactions"],
    testCount: 3,
    useCaseRole: "Business-service validation for Order Processing.",
  },
  {
    id: "splunk",
    name: "Splunk",
    category: "Monitoring & Observability",
    domain: "SIEM",
    purpose: "Security & Audit Events",
    connectionType: "HEC / REST API",
    accessMode: "approved_write",
    status: "connected",
    health: 95,
    lastActivity: "3 min ago",
    maturity: "available",
    executionCapable: false,
    businessOwner: "Security",
    technicalOwner: "Security Engineering",
    supportGroup: "Security Operations",
    ownership: "SHARED",
    environments: ["Production", "Shared Services"],
    discoveryIdentity: "splunk-iac-read",
    executionIdentity: "splunk-iac-hec",
    credentialSource: "HEC token (customer vault)",
    expiration: "365 days",
    rotation: "Compliant",
    lastValidation: "3 min ago",
    dependencies: [],
    capabilities: ["Audit forwarding", "Security event correlation"],
    discoveryPerms: ["Search read"],
    executionPerms: ["Forward platform audit events"],
    excluded: ["No infrastructure mutation"],
    scope: [{ label: "Indexes", value: "iac_audit, iac_exec" }],
    assets: ["Indexes", "Searches"],
    testCount: 3,
  },
  {
    id: "secrets",
    name: "Secrets / PAM (CyberArk)",
    category: "Security & Identity",
    domain: "Secrets",
    purpose: "Credential Reference & Retrieval",
    connectionType: "PAM REST / Central Credential Provider",
    accessMode: "read_only",
    status: "connected",
    health: 99,
    lastActivity: "1 min ago",
    maturity: "demo",
    executionCapable: false,
    businessOwner: "Security",
    technicalOwner: "Privileged Access Team",
    supportGroup: "Security Operations",
    ownership: "CUSTOMER",
    environments: ["Production", "Non-Production", "Shared Services"],
    discoveryIdentity: "iac-pam-app-id",
    executionIdentity: "iac-pam-app-id (execution safe)",
    credentialSource: "CyberArk (customer controlled)",
    expiration: "Just-in-time",
    rotation: "Compliant",
    lastValidation: "1 min ago",
    dependencies: [],
    capabilities: ["Credential reference", "Temporary credential retrieval", "Rotation", "Session auditing"],
    discoveryPerms: ["Credential reference resolution"],
    executionPerms: ["Just-in-time credential retrieval for approved execution"],
    excluded: [
      "No secret shown in UI",
      "No secret stored in change package",
      "No secret stored in Digital Twin",
      "No secret sent to AI inference",
      "No secret persisted in evidence",
    ],
    scope: [
      { label: "Systems Served", value: "AWS, Windows, SQL, Network, VMware, Nutanix" },
      { label: "Fallback Credential", value: "None" },
    ],
    assets: ["Safes", "Credential references"],
    testCount: 6,
    useCaseRole: "Resolve execution credentials at runtime — never stored by agents.",
  },
  {
    id: "sso",
    name: "SSO / Identity Provider",
    category: "Security & Identity",
    domain: "Identity",
    purpose: "User Authentication & RBAC",
    connectionType: "SAML / OIDC",
    accessMode: "read_only",
    status: "connected",
    health: 100,
    lastActivity: "1 min ago",
    maturity: "available",
    executionCapable: false,
    businessOwner: "Enterprise IT",
    technicalOwner: "Identity Engineering",
    supportGroup: "Identity Operations",
    ownership: "CUSTOMER",
    environments: ["Production"],
    discoveryIdentity: "iac-oidc-client",
    executionIdentity: null,
    credentialSource: "OIDC client secret (customer vault)",
    expiration: "365 days",
    rotation: "Compliant",
    lastValidation: "1 min ago",
    dependencies: [],
    capabilities: ["Authentication", "Group-based RBAC"],
    discoveryPerms: ["Claims read"],
    executionPerms: [],
    excluded: ["No directory mutation"],
    scope: [{ label: "Protocol", value: "OIDC" }],
    assets: ["Claims", "Groups"],
    testCount: 3,
  },
  {
    id: "policystore",
    name: "Policy Store",
    category: "Enterprise Services",
    domain: "Governance",
    purpose: "Enterprise Automation Policies",
    connectionType: "Policy Repository API",
    accessMode: "read_only",
    status: "connected",
    health: 97,
    lastActivity: "6 min ago",
    maturity: "demo",
    executionCapable: false,
    businessOwner: "Governance",
    technicalOwner: "Platform Governance",
    supportGroup: "Governance Operations",
    ownership: "SHARED",
    environments: ["Production", "Non-Production"],
    discoveryIdentity: "policy-read",
    executionIdentity: null,
    credentialSource: "Service token (customer vault)",
    expiration: "180 days",
    rotation: "Compliant",
    lastValidation: "6 min ago",
    dependencies: [],
    capabilities: ["Automation authority", "Approval requirements", "Guardrails"],
    discoveryPerms: ["Policy read"],
    executionPerms: [],
    excluded: ["No infrastructure mutation"],
    scope: [{ label: "Policies", value: "48 active" }],
    assets: ["Policies", "Guardrails"],
    testCount: 3,
    useCaseRole: "Resolve automation authority for the change package.",
  },
  {
    id: "evidence",
    name: "Evidence Store",
    category: "Enterprise Services",
    domain: "Evidence",
    purpose: "Execution & Validation Evidence",
    connectionType: "Object Storage (Customer)",
    accessMode: "approved_write",
    status: "connected",
    health: 98,
    lastActivity: "2 min ago",
    maturity: "demo",
    executionCapable: false,
    businessOwner: "Governance",
    technicalOwner: "Platform Governance",
    supportGroup: "Governance Operations",
    ownership: "CUSTOMER",
    environments: ["Production"],
    discoveryIdentity: "evidence-read",
    executionIdentity: "evidence-write",
    credentialSource: "Customer object storage IAM",
    expiration: "Session based",
    rotation: "N/A",
    lastValidation: "2 min ago",
    dependencies: [],
    capabilities: ["Evidence retention", "Integrity manifest", "Immutable history"],
    discoveryPerms: ["Evidence read"],
    executionPerms: ["Append evidence objects"],
    excluded: ["Evidence deletion"],
    scope: [{ label: "Retention", value: "Customer defined" }],
    assets: ["Evidence packages"],
    testCount: 3,
    useCaseRole: "Retain execution and validation evidence (EV-2026-01842).",
  },
  {
    id: "backup",
    name: "Backup & Recovery",
    category: "Enterprise Services",
    domain: "Data Protection",
    purpose: "Protection-state Validation",
    connectionType: "REST API (Read)",
    accessMode: "read_only",
    status: "connected",
    health: 92,
    lastActivity: "15 min ago",
    maturity: "available",
    executionCapable: false,
    businessOwner: "Infrastructure",
    technicalOwner: "Data Protection Team",
    supportGroup: "Infrastructure Operations",
    ownership: "SHARED",
    environments: ["Production"],
    discoveryIdentity: "backup-read",
    executionIdentity: null,
    credentialSource: "Service token (customer vault)",
    expiration: "180 days",
    rotation: "Compliant",
    lastValidation: "15 min ago",
    dependencies: [],
    capabilities: ["Backup state", "Recovery point verification"],
    discoveryPerms: ["Job and policy read"],
    executionPerms: [],
    excluded: ["No backup deletion", "No policy mutation"],
    scope: [{ label: "Protected Assets", value: "1,204" }],
    assets: ["Backup jobs", "Recovery points"],
    testCount: 3,
  },
  {
    id: "paloalto",
    name: "Palo Alto Firewalls",
    category: "Cloud & Infrastructure",
    domain: "Network",
    purpose: "Policy, Objects & NAT",
    connectionType: "REST API / Management Endpoint",
    accessMode: "discovery_scoped_execution",
    status: "disabled",
    health: 0,
    lastActivity: "—",
    maturity: "planned",
    executionCapable: true,
    businessOwner: "Security",
    technicalOwner: "Network Security",
    supportGroup: "Network Operations",
    ownership: "CUSTOMER",
    environments: ["Production"],
    discoveryIdentity: "svc-iac-pan-read",
    executionIdentity: "svc-iac-pan-exec",
    credentialSource: "CyberArk",
    expiration: "—",
    rotation: "—",
    lastValidation: "—",
    dependencies: ["secrets"],
    capabilities: ["Policy", "Objects", "NAT"],
    discoveryPerms: ["Configuration read"],
    executionPerms: ["Scoped object / policy change (approved)"],
    excluded: ["Default-deny rule modification", "Policy deletion"],
    scope: [{ label: "Devices", value: "Not enabled" }],
    assets: ["Rules", "Address objects", "NAT policies"],
    testCount: 4,
  },
  {
    id: "f5",
    name: "F5 Load Balancers",
    category: "Cloud & Infrastructure",
    domain: "Network",
    purpose: "VIP, Pool, Member & Health",
    connectionType: "iControl REST",
    accessMode: "discovery",
    status: "connected",
    health: 91,
    lastActivity: "9 min ago",
    maturity: "customer_specific",
    executionCapable: true,
    businessOwner: "Infrastructure",
    technicalOwner: "Network Engineering",
    supportGroup: "Network Operations",
    ownership: "CUSTOMER",
    environments: ["Production", "Non-Production"],
    discoveryIdentity: "svc-iac-f5-read",
    executionIdentity: "svc-iac-f5-exec",
    credentialSource: "CyberArk",
    expiration: "90 days",
    rotation: "Compliant",
    lastValidation: "9 min ago",
    dependencies: ["secrets"],
    capabilities: ["VIP", "Pool", "Member", "Health monitors"],
    discoveryPerms: ["Configuration read", "Statistics read"],
    executionPerms: ["Member enable / disable (approved)", "Pool member add (approved)"],
    excluded: ["VIP deletion", "Certificate removal"],
    scope: [{ label: "Devices", value: "6" }, { label: "Execution", value: "Not enabled" }],
    assets: ["Virtual servers", "Pools", "Monitors"],
    testCount: 4,
  },
  {
    id: "cisco",
    name: "Cisco Network APIs",
    category: "Cloud & Infrastructure",
    domain: "Network",
    purpose: "Device Inventory & Configuration",
    connectionType: "RESTCONF / NETCONF",
    accessMode: "discovery",
    status: "not_configured",
    health: 0,
    lastActivity: "—",
    maturity: "planned",
    executionCapable: true,
    businessOwner: "Infrastructure",
    technicalOwner: "Network Engineering",
    supportGroup: "Network Operations",
    ownership: "CUSTOMER",
    environments: ["Production"],
    discoveryIdentity: "svc-iac-cisco-read",
    executionIdentity: "svc-iac-cisco-exec",
    credentialSource: "CyberArk",
    expiration: "—",
    rotation: "—",
    lastValidation: "—",
    dependencies: ["secrets"],
    capabilities: ["Interfaces", "VLANs", "Routing state"],
    discoveryPerms: ["Configuration read"],
    executionPerms: ["Scoped configuration change (approved)"],
    excluded: ["Routing protocol changes", "Device reload"],
    scope: [{ label: "Devices", value: "Not configured" }],
    assets: ["Switches", "Routers"],
    testCount: 4,
  },
  {
    id: "dns",
    name: "DNS / DHCP (Infoblox)",
    category: "Cloud & Infrastructure",
    domain: "Network",
    purpose: "Name & Address Management",
    connectionType: "WAPI REST",
    accessMode: "discovery",
    status: "connected",
    health: 90,
    lastActivity: "20 min ago",
    maturity: "available",
    executionCapable: true,
    businessOwner: "Infrastructure",
    technicalOwner: "Network Engineering",
    supportGroup: "Network Operations",
    ownership: "CUSTOMER",
    environments: ["Production", "Shared Services"],
    discoveryIdentity: "svc-iac-ipam-read",
    executionIdentity: "svc-iac-ipam-exec",
    credentialSource: "CyberArk",
    expiration: "90 days",
    rotation: "Compliant",
    lastValidation: "20 min ago",
    dependencies: ["secrets"],
    capabilities: ["Zones", "Records", "IPAM"],
    discoveryPerms: ["Zone / record read"],
    executionPerms: ["Record create / update (approved)"],
    excluded: ["Zone deletion"],
    scope: [{ label: "Zones", value: "112" }, { label: "Execution", value: "Not enabled" }],
    assets: ["Zones", "A / CNAME records", "Networks"],
    testCount: 3,
  },
  {
    id: "storage",
    name: "Enterprise Storage",
    category: "Compute & OS",
    domain: "Storage",
    purpose: "Array & Volume State",
    connectionType: "Vendor REST API",
    accessMode: "discovery",
    status: "connected",
    health: 89,
    lastActivity: "18 min ago",
    maturity: "customer_specific",
    executionCapable: false,
    businessOwner: "Infrastructure",
    technicalOwner: "Storage Engineering",
    supportGroup: "Infrastructure Operations",
    ownership: "CUSTOMER",
    environments: ["Production"],
    discoveryIdentity: "svc-iac-stor-read",
    executionIdentity: null,
    credentialSource: "CyberArk",
    expiration: "90 days",
    rotation: "Compliant",
    lastValidation: "18 min ago",
    dependencies: ["secrets"],
    capabilities: ["Arrays", "Volumes", "Capacity"],
    discoveryPerms: ["Array read"],
    executionPerms: [],
    excluded: ["No mutation"],
    scope: [{ label: "Arrays", value: "5" }],
    assets: ["Volumes", "Pools"],
    testCount: 3,
  },
  {
    id: "notify",
    name: "Notification / Collaboration",
    category: "Enterprise Services",
    domain: "Collaboration",
    purpose: "Approvals & Operational Notifications",
    connectionType: "Webhook / Graph",
    accessMode: "approved_write",
    status: "connected",
    health: 96,
    lastActivity: "4 min ago",
    maturity: "demo",
    executionCapable: false,
    businessOwner: "Service Management",
    technicalOwner: "Collaboration Team",
    supportGroup: "Workplace Services",
    ownership: "SHARED",
    environments: ["Production"],
    discoveryIdentity: "notify-read",
    executionIdentity: "notify-post",
    credentialSource: "Webhook secret (customer vault)",
    expiration: "365 days",
    rotation: "Compliant",
    lastValidation: "4 min ago",
    dependencies: [],
    capabilities: ["Approval requests", "Execution notifications"],
    discoveryPerms: ["Channel read"],
    executionPerms: ["Post approval and status messages"],
    excluded: ["No infrastructure mutation"],
    scope: [{ label: "Channels", value: "6" }],
    assets: ["Channels", "Approval threads"],
    testCount: 3,
    useCaseRole: "Route approval requests for CP-2026-01842.",
  },
];

// ─── Failure scenarios ────────────────────────────────────────────────

export interface ScenarioOverride {
  status?: IntegrationStatus;
  health?: number;
  lastActivity?: string;
  notes?: string[];
  banner?: string;
}

export interface ScenarioDef {
  id: ConnectivityScenario;
  label: string;
  severity: "normal" | "warning" | "critical";
  headline?: string;
  reason?: string;
  overrides: Record<string, ScenarioOverride>;
  impact: string[];
  recommended: string[];
}

export const SCENARIOS: ScenarioDef[] = [
  {
    id: "normal",
    label: "All Systems Operational",
    severity: "normal",
    overrides: {},
    impact: [],
    recommended: [],
  },
  {
    id: "aws_discovery_failure",
    label: "AWS Discovery Failure",
    severity: "warning",
    headline: "AWS DIGITAL TWIN STATE IS STALE",
    reason: "Discovery API calls are failing. Last known state is retained with freshness metadata.",
    overrides: {
      aws: {
        status: "stale",
        health: 62,
        lastActivity: "17 min ago",
        notes: [
          "Last successful sync: 17 min ago",
          "Last known state: Available",
          "Freshness confidence: Degraded",
          "Existing Digital Twin objects are retained — nothing is deleted",
        ],
      },
      cloudwatch: { status: "degraded", health: 84 },
    },
    impact: [
      "AWS Digital Twin freshness degraded",
      "Remediation Intelligence uses last known AWS state",
      "Production execution may be blocked depending on policy",
    ],
    recommended: ["Validate discovery role trust policy", "Validate network path to AWS APIs", "Retest connection"],
  },
  {
    id: "sql_auth_failure",
    label: "SQL Authentication Failure",
    severity: "critical",
    headline: "SQL EXECUTION DISABLED AUTOMATICALLY",
    reason: "Diagnostic access is unavailable. SQL Digital Twin state is marked stale; discovered objects are retained.",
    overrides: {
      sqlserver: {
        status: "failed",
        health: 55,
        lastActivity: "12 min ago",
        notes: [
          "Diagnostic Access: Unavailable",
          "Execution: Disabled automatically",
          "Last Successful SQL Read: 12 minutes ago",
          "Authentication Method: Integrated Security",
          "Affected SQL state marked STALE — Freshness Confidence: Reduced",
        ],
      },
    },
    impact: [
      "SQL Digital Twin state becoming stale",
      "Remediation Intelligence: Limited",
      "Production SQL execution: Blocked",
    ],
    recommended: [
      "Validate service identity",
      "Validate SQL permissions",
      "Validate network path",
      "Validate certificate / TLS state where applicable",
      "Retest connection",
    ],
  },
  {
    id: "windows_runner_offline",
    label: "Windows Runner Offline",
    severity: "warning",
    headline: "WINDOWS EXECUTION UNAVAILABLE — DISCOVERY REMAINS ONLINE",
    reason: "A connectivity problem can disable execution without disabling intelligence.",
    overrides: {
      windows: {
        status: "degraded",
        health: 74,
        lastActivity: "1 min ago",
        notes: [
          "Discovery: Available through existing inventory source",
          "Execution Runner: Offline",
          "Windows validation: Partially available",
          "Production Windows mutation: Blocked",
        ],
      },
    },
    impact: [
      "Affected capabilities: Extend filesystem, Restart service, Modify IIS, Patch server, Certificate deployment, Windows configuration change",
      "Windows configuration visibility remains available",
    ],
    recommended: [
      "Restore runner",
      "Validate management endpoint",
      "Validate runner service",
      "Validate network connectivity",
      "Validate credential retrieval",
    ],
  },
  {
    id: "git_unavailable",
    label: "Git Repository Unavailable",
    severity: "warning",
    headline: "NEW CHANGE ENGINEERING BLOCKED",
    reason: "Repository read and write are failing. Existing Digital Twin, approved packages and evidence are unaffected.",
    overrides: {
      github: {
        status: "degraded",
        health: 68,
        lastActivity: "22 min ago",
        notes: [
          "Repository Read: Failed",
          "Repository Write: Failed",
          "Existing Digital Twin: Unaffected",
          "Remediation Intelligence: Available",
          "Change Engineering: Degraded — IaC package creation blocked",
          "Execution of already approved immutable packages: Policy dependent",
        ],
      },
      terraform: { status: "degraded", health: 80 },
    },
    impact: ["IaC package creation blocked", "Change Engineering degraded", "Existing approved packages and evidence retained"],
    recommended: [
      "Validate repository endpoint",
      "Validate application / token trust",
      "Validate branch permissions",
      "Validate certificate chain",
      "Retest",
    ],
  },
  {
    id: "secret_store_unreachable",
    label: "Secret Store Unreachable",
    severity: "critical",
    headline: "PRODUCTION EXECUTION BLOCKED",
    reason: "Customer credential authority cannot be reached. Credentials are never cached or substituted — Fallback Credential: None.",
    overrides: {
      secrets: {
        status: "failed",
        health: 40,
        lastActivity: "9 min ago",
        notes: [
          "Credential Retrieval: Unavailable",
          "Discovery: May continue where identity does not require secret retrieval",
          "Engineering: Available",
          "Production Execution: BLOCKED",
          "Fallback Credential: None",
        ],
      },
      windows: { status: "blocked", health: 70 },
      sqlserver: { status: "blocked", health: 72 },
      vmware: { status: "blocked", health: 70 },
      nutanix: { status: "blocked", health: 68 },
      f5: { status: "blocked", health: 66 },
      dns: { status: "blocked", health: 66 },
      terraform: { status: "blocked", health: 70 },
    },
    impact: [
      "AWS execution roles where secret / PAM dependency exists",
      "Windows execution identities",
      "SQL execution identities",
      "Network execution credentials",
    ],
    recommended: ["Validate PAM endpoint", "Validate application identity", "Validate network path", "Retest credential resolution"],
  },
  {
    id: "rate_limit_warning",
    label: "AWS Rate Limit Warning",
    severity: "warning",
    headline: "ELEVATED API RATE LIMIT — GRACEFUL DEGRADATION",
    reason: "Authentication is healthy and discovery is operational. The connection is not marked failed.",
    overrides: {
      aws: {
        status: "degraded",
        health: 86,
        lastActivity: "3 min ago",
        notes: [
          "Authentication: Healthy",
          "Discovery: Operational",
          "Rate Limit: Elevated",
          "Digital Twin: Operational — Freshness slightly degraded",
          "Production Execution: Available if execution APIs remain healthy and policy permits",
        ],
      },
    },
    impact: ["Reduce discovery concurrency", "Back off polling", "Preserve last known state", "Prioritize critical asset refresh"],
    recommended: ["Reduce concurrency", "Increase polling interval", "Prioritize critical asset refresh"],
  },
];

// ─── SQL/EBS use-case dependency trace ────────────────────────────────

export interface UseCaseRequirement {
  id: string;
  label: string;
  integrationId: string;
  kind: "discovery" | "execution" | "support";
}

export const USE_CASE_REQUIREMENTS: UseCaseRequirement[] = [
  { id: "aws-disc", label: "AWS Discovery", integrationId: "aws", kind: "discovery" },
  { id: "aws-exec", label: "AWS Execution", integrationId: "aws", kind: "execution" },
  { id: "sql-diag", label: "SQL Diagnostic", integrationId: "sqlserver", kind: "discovery" },
  { id: "sql-exec", label: "SQL Execution", integrationId: "sqlserver", kind: "execution" },
  { id: "win-disc", label: "Windows Discovery", integrationId: "windows", kind: "discovery" },
  { id: "win-exec", label: "Windows Execution", integrationId: "windows", kind: "execution" },
  { id: "git", label: "Git / IaC", integrationId: "github", kind: "support" },
  { id: "tf", label: "Terraform Runner", integrationId: "terraform", kind: "execution" },
  { id: "pam", label: "Secrets / PAM", integrationId: "secrets", kind: "support" },
  { id: "cw", label: "CloudWatch", integrationId: "cloudwatch", kind: "support" },
  { id: "apm", label: "Application Monitoring", integrationId: "appmonitoring", kind: "support" },
  { id: "ev", label: "Evidence Store", integrationId: "evidence", kind: "support" },
  { id: "policy", label: "Policy Store", integrationId: "policystore", kind: "support" },
  { id: "approval", label: "Approval Integration", integrationId: "notify", kind: "support" },
];

export const USE_CASE_INTEGRATION_IDS = [
  "aws", "sqlserver", "windows", "cloudwatch", "github", "terraform",
  "secrets", "appmonitoring", "servicenow", "policystore",
];

// ─── Capability impact mapping ────────────────────────────────────────

export const CAPABILITY_IMPACT: Record<string, CapabilityImpact[]> = {
  aws: [
    { capability: "Asset Digital Twin", state: "degraded" },
    { capability: "Remediation Intelligence", state: "degraded" },
    { capability: "Change Engineering", state: "partial" },
    { capability: "Execution", state: "blocked" },
    { capability: "Validation", state: "degraded" },
    { capability: "Evidence", state: "available" },
  ],
  sqlserver: [
    { capability: "Asset Digital Twin", state: "degraded" },
    { capability: "Remediation Intelligence", state: "degraded" },
    { capability: "Change Engineering", state: "partial" },
    { capability: "Execution", state: "blocked" },
    { capability: "Validation", state: "blocked" },
    { capability: "Evidence", state: "available" },
  ],
  windows: [
    { capability: "Asset Digital Twin", state: "available" },
    { capability: "Remediation Intelligence", state: "available" },
    { capability: "Change Engineering", state: "partial" },
    { capability: "Execution", state: "blocked" },
    { capability: "Validation", state: "partial" },
    { capability: "Evidence", state: "available" },
  ],
  github: [
    { capability: "Asset Digital Twin", state: "available" },
    { capability: "Remediation Intelligence", state: "available" },
    { capability: "Change Engineering", state: "blocked" },
    { capability: "Execution", state: "partial" },
    { capability: "Validation", state: "available" },
    { capability: "Evidence", state: "available" },
  ],
  secrets: [
    { capability: "Asset Digital Twin", state: "partial" },
    { capability: "Remediation Intelligence", state: "available" },
    { capability: "Change Engineering", state: "available" },
    { capability: "Execution", state: "blocked" },
    { capability: "Validation", state: "partial" },
    { capability: "Evidence", state: "available" },
  ],
  cloudwatch: [
    { capability: "Asset Digital Twin", state: "available" },
    { capability: "Remediation Intelligence", state: "degraded" },
    { capability: "Change Engineering", state: "available" },
    { capability: "Execution", state: "available" },
    { capability: "Validation", state: "degraded" },
    { capability: "Evidence", state: "partial" },
  ],
  appmonitoring: [
    { capability: "Asset Digital Twin", state: "available" },
    { capability: "Remediation Intelligence", state: "available" },
    { capability: "Change Engineering", state: "available" },
    { capability: "Execution", state: "available" },
    { capability: "Validation", state: "blocked" },
    { capability: "Evidence", state: "partial" },
  ],
};

export const DEFAULT_CAPABILITY_IMPACT: CapabilityImpact[] = [
  { capability: "Asset Digital Twin", state: "partial" },
  { capability: "Remediation Intelligence", state: "available" },
  { capability: "Change Engineering", state: "available" },
  { capability: "Execution", state: "partial" },
  { capability: "Validation", state: "partial" },
  { capability: "Evidence", state: "available" },
];

// ─── Relationship map ─────────────────────────────────────────────────

export const RELATIONSHIP_EDGES: { integration: string; capability: string; domain: string }[] = [
  { integration: "AWS", capability: "Asset Discovery", domain: "Digital Twin" },
  { integration: "AWS", capability: "Execution Orchestrator", domain: "EC2 / EBS" },
  { integration: "SQL Server", capability: "Remediation Intelligence", domain: "SQL-PROD-07" },
  { integration: "SQL Server", capability: "Execution Orchestrator", domain: "OrdersDB Log" },
  { integration: "Windows Servers", capability: "Execution Runner", domain: "L: Volume" },
  { integration: "GitHub Enterprise", capability: "Change Engineering", domain: "Terraform Package" },
  { integration: "Secrets / PAM", capability: "Execution Runner", domain: "Scoped Identity" },
  { integration: "CloudWatch", capability: "Validation Engine", domain: "Business Service" },
  { integration: "ServiceNow", capability: "Governance", domain: "Change Record" },
  { integration: "Policy Store", capability: "Policy Engine", domain: "Automation Authority" },
];

// ─── Logs / history ───────────────────────────────────────────────────

export interface LogEvent {
  id: string;
  time: string;
  integration: string;
  severity: "info" | "warning" | "error";
  operation: "read" | "write" | "auth" | "config";
  identity: string;
  event: string;
  status: string;
}

export const LOG_EVENTS: LogEvent[] = [
  { id: "L-001", time: "12:59:31", integration: "AWS", severity: "info", operation: "read", identity: "iac-discovery-prod", event: "Discovery completed — 4,182 resources", status: "Success" },
  { id: "L-002", time: "12:58:04", integration: "SQL Server", severity: "info", operation: "auth", identity: "svc-iac-sql-read", event: "Authentication success", status: "Success" },
  { id: "L-003", time: "12:57:52", integration: "Windows Servers", severity: "info", operation: "auth", identity: "runner-win-01", event: "Runner connected", status: "Success" },
  { id: "L-004", time: "12:55:12", integration: "Terraform Cloud", severity: "info", operation: "auth", identity: "tfc-apply", event: "Execution trust validated", status: "Success" },
  { id: "L-005", time: "12:54:40", integration: "AWS", severity: "warning", operation: "read", identity: "iac-discovery-prod", event: "API warning — throttling observed on DescribeVolumes", status: "Backoff applied" },
  { id: "L-006", time: "12:50:03", integration: "Secrets / PAM", severity: "info", operation: "config", identity: "iac-pam-app-id", event: "Credential rotation completed (reference only)", status: "Success" },
  { id: "L-007", time: "12:44:18", integration: "GitHub Enterprise", severity: "info", operation: "write", identity: "iac-app-write", event: "Pull request created for generated Terraform", status: "Success" },
  { id: "L-008", time: "12:40:55", integration: "ServiceNow", severity: "info", operation: "write", identity: "svc-iac-snow-write", event: "Change record updated — CP-2026-01842", status: "Success" },
  { id: "L-009", time: "12:31:09", integration: "Kubernetes", severity: "info", operation: "read", identity: "sa-iac-read", event: "Discovery started", status: "Running" },
  { id: "L-010", time: "12:22:47", integration: "Azure", severity: "error", operation: "auth", identity: "sp-iac-discovery", event: "Connection test failed — service principal not configured", status: "Not Configured" },
  { id: "L-011", time: "12:15:33", integration: "F5 Load Balancers", severity: "info", operation: "config", identity: "admin@customer", event: "Scope changed — execution remains disabled", status: "Recorded" },
  { id: "L-012", time: "12:02:19", integration: "Palo Alto Firewalls", severity: "warning", operation: "config", identity: "admin@customer", event: "Connection disabled by customer", status: "Disabled" },
];

export interface HistoryEvent {
  id: string;
  integration: string;
  action: string;
  actor: string;
  timestamp: string;
  reason: string;
  approval: string;
}

export const HISTORY_EVENTS: HistoryEvent[] = [
  { id: "H-001", integration: "AWS", action: "Created", actor: "cloud.eng@customer", timestamp: "2025-11-04 09:12", reason: "Initial onboarding — discovery only", approval: "CHG0043112" },
  { id: "H-002", integration: "AWS", action: "Discovery Enabled", actor: "cloud.eng@customer", timestamp: "2025-11-04 09:31", reason: "Inventory validation", approval: "CHG0043112" },
  { id: "H-003", integration: "AWS", action: "Execution Enabled", actor: "platform.owner@customer", timestamp: "2026-01-19 14:02", reason: "Approved EBS capacity automation", approval: "CHG0051980" },
  { id: "H-004", integration: "AWS", action: "Scope Changed", actor: "platform.owner@customer", timestamp: "2026-02-11 10:48", reason: "Added us-west-2 to authorized regions", approval: "CHG0053221" },
  { id: "H-005", integration: "SQL Server", action: "Identity Changed", actor: "dba.lead@customer", timestamp: "2026-03-02 08:15", reason: "Rotated execution service account", approval: "CHG0055014" },
  { id: "H-006", integration: "Windows Servers", action: "Connection Tested", actor: "win.platform@customer", timestamp: "2026-08-09 12:57", reason: "Scheduled trust validation", approval: "—" },
  { id: "H-007", integration: "F5 Load Balancers", action: "Execution Disabled", actor: "net.eng@customer", timestamp: "2026-06-22 16:30", reason: "Pending network change policy definition", approval: "CHG0060877" },
  { id: "H-008", integration: "Secrets / PAM", action: "Credential Reference Changed", actor: "pam.admin@customer", timestamp: "2026-07-14 11:05", reason: "Safe restructure", approval: "CHG0062440" },
];

// ─── Static content blocks ────────────────────────────────────────────

export const SECURITY_PRINCIPLES = [
  "Least privilege",
  "Read and execution identities separated",
  "Production execution scoped",
  "Customer-controlled secrets",
  "Short-lived credentials preferred",
  "Private connectivity preferred",
  "All access auditable",
  "No credentials in model context",
  "No silent scope expansion",
  "Execution disabled independently",
  "Failed identity disables affected action",
  "Credentials never displayed",
];

export const ONBOARDING_PATTERN = [
  "Connect read-only discovery",
  "Validate inventory",
  "Build Digital Twin",
  "Connect engineering repositories",
  "Configure runners",
  "Configure policy",
  "Test execution trust",
  "Enable non-production execution",
  "Validate",
  "Enable selected production actions",
];

export const STATUS_TOOLTIPS: Record<IntegrationStatus, string> = {
  connected: "Authentication and required APIs are available.",
  degraded: "Connection remains usable but one or more health checks are outside normal state.",
  not_configured: "This connection has not been configured for this environment.",
  disabled: "Customer intentionally disabled this integration or capability.",
  failed: "Authentication or required APIs are unavailable.",
  testing: "Connectivity tests are currently running.",
  stale: "Latest discovery failed; last known state remains available.",
  blocked: "Policy or dependency prevents execution.",
};

export const STATUS_LABEL: Record<IntegrationStatus, string> = {
  connected: "CONNECTED",
  degraded: "DEGRADED",
  not_configured: "NOT CONFIGURED",
  disabled: "DISABLED",
  failed: "FAILED",
  testing: "TESTING",
  stale: "STALE",
  blocked: "BLOCKED",
};

export const ACCESS_MODE_LABEL: Record<AccessMode, string> = {
  read_only: "Read Only",
  discovery: "Discovery",
  discovery_scoped_execution: "Discovery + Scoped Execution",
  approved_write: "Approved Write",
  policy_governed_execution: "Policy Governed Execution",
  disabled: "Disabled",
};

export const MATURITY_LABEL: Record<Maturity, string> = {
  available: "Available",
  demo: "Demo Enabled",
  customer_specific: "Customer Specific",
  planned: "Planned",
};

export const HEALTH_WEIGHTS = [
  { label: "Network", weight: "15%" },
  { label: "Authentication", weight: "20%" },
  { label: "Discovery", weight: "15%" },
  { label: "API availability", weight: "10%" },
  { label: "Telemetry", weight: "10%" },
  { label: "Execution trust", weight: "15%" },
  { label: "Credential state", weight: "10%" },
  { label: "Audit", weight: "5%" },
];

export const DEPENDENCY_RULES = [
  "If Secret Store fails: production execution blocked across dependent integrations.",
  "If Git fails: new IaC engineering blocked.",
  "If SQL read access fails: SQL diagnosis degraded.",
  "If AWS discovery fails: AWS Twin freshness degraded.",
  "If Windows execution runner fails: Windows actions blocked, discovery remains possible.",
  "If Application Monitoring fails: business-service validation blocked.",
  "If validation is blocked: production change completion cannot be verified.",
];

export const DEMO_STORY = [
  { title: "Connected Estate", message: "Intelligent IaC connects to existing enterprise control planes rather than replacing them." },
  { title: "Read vs Execute", message: "Connection does not automatically grant mutation authority." },
  { title: "AWS", message: "AWS uses separate discovery and execution roles — inspect both below." },
  { title: "Credentials", message: "No standing agent credentials. Credentials resolve at execution time from customer PAM." },
  { title: "SQL/EBS Dependencies", message: "These are the integrations required by change package CP-2026-01842." },
  { title: "Connectivity Test", message: "Connectivity tests validate trust without mutating infrastructure." },
  { title: "Failure Safety", message: "SQL authentication failure blocks production SQL actions while other platform intelligence remains available." },
  { title: "Restore", message: "Returning to all-systems-operational state." },
  { title: "Production Readiness", message: "SQL/EBS use case connectivity readiness: READY." },
];

export const EXPORT_STEPS = [
  "Compiling inventory...",
  "Compiling connection scopes...",
  "Compiling identities...",
  "Compiling permissions...",
  "Compiling health...",
  "Compiling dependency mappings...",
  "Compiling last test results...",
  "Compiling SQL/EBS readiness...",
  "Report prepared.",
];

export const ENVIRONMENTS = ["Production", "Non-Production", "Development", "Shared Services"];

export const AWS_ENVIRONMENT_BREAKDOWN = [
  { label: "Production", value: "4 Accounts", authority: "Human approval required" },
  { label: "Non-Production", value: "5 Accounts", authority: "Policy approved" },
  { label: "Shared Services", value: "2 Accounts", authority: "Human approval required" },
  { label: "Sandbox", value: "1 Account", authority: "Autonomous within defined guardrails" },
];

export const PRODUCTION_READINESS_ITEMS = [
  "Network", "Discovery Identity", "Execution Identity", "Scope", "Policy", "Runner", "Audit", "Validation",
];

// ─── Derived helpers ──────────────────────────────────────────────────

export function applyScenario(
  integrations: Integration[],
  scenario: ConnectivityScenario,
  disabledExecution: Record<string, boolean>,
): Integration[] {
  const def = SCENARIOS.find((s) => s.id === scenario)!;
  return integrations.map((i) => {
    const o = def.overrides[i.id];
    let next: Integration = o ? { ...i, ...o, status: o.status ?? i.status, health: o.health ?? i.health } : i;
    if (disabledExecution[i.id]) {
      next = { ...next, accessMode: next.accessMode === "read_only" ? "read_only" : "discovery" };
    }
    return next;
  });
}

export function scenarioNotes(scenario: ConnectivityScenario, id: string): string[] {
  const def = SCENARIOS.find((s) => s.id === scenario)!;
  return def.overrides[id]?.notes ?? [];
}

export function isExecutionBlocked(
  integration: Integration,
  scenario: ConnectivityScenario,
  disabledExecution: Record<string, boolean>,
): boolean {
  if (!integration.executionCapable) return false;
  if (disabledExecution[integration.id]) return true;
  if (["failed", "blocked", "disabled", "not_configured"].includes(integration.status)) return true;
  if (scenario === "secret_store_unreachable") return true;
  if (scenario === "windows_runner_offline" && integration.id === "windows") return true;
  return false;
}

export function productionReadiness(
  integration: Integration,
  scenario: ConnectivityScenario,
  disabledExecution: Record<string, boolean>,
): { rows: { label: string; pass: boolean }[]; overall: "READY" | "NOT READY" } {
  const blocked = isExecutionBlocked(integration, scenario, disabledExecution);
  const bad = ["failed", "blocked", "not_configured", "disabled", "stale"].includes(integration.status);
  const rows = PRODUCTION_READINESS_ITEMS.map((label) => {
    let pass = true;
    if (bad && ["Network", "Discovery Identity", "Validation"].includes(label)) pass = integration.status === "stale" ? label !== "Validation" : false;
    if (blocked && ["Execution Identity", "Runner", "Policy"].includes(label)) pass = false;
    return { label, pass };
  });
  return { rows, overall: rows.every((r) => r.pass) ? "READY" : "NOT READY" };
}
