/**
 * IndustryProfile catalog — the four canonical industries recognized by NOVA.
 * All content is descriptive only; concrete fixtures live in each tenant
 * profile bundle. Status colors/severity meanings are intentionally NOT
 * industry-specific — those live in tokens.ts.
 */

import type { IndustryProfile } from "./types";

const NOW = "2026-07-01T00:00:00.000Z";

export const genericEnterpriseIndustry: IndustryProfile = {
  id: "ind-generic-enterprise",
  code: "generic-enterprise",
  name: "Generic Enterprise",
  description:
    "Reference enterprise operating model used to demonstrate NOVA against a broad set of digital services.",
  operationalPhilosophy:
    "SRE-led reliability engineering with approval-gated automation for high-impact remediation.",
  journeyLabel: "Customer Journey",
  serviceLabel: "Business Service",
  componentLabel: "Service Component",
  incidentLabel: "Incident",
  impactLabel: "Business Impact",
  sloLabel: "SLO",
  errorBudgetLabel: "Error Budget",
  serviceCategories: ["Customer-facing", "Platform", "Internal", "Data"],
  componentCategories: ["API", "Compute", "Database", "Cache", "Queue", "Network", "Identity", "Vendor"],
  topologyNodeTypes: [
    { key: "service",   label: "Service",   description: "A business or platform service." },
    { key: "component", label: "Component", description: "A technical component owned by a service." },
    { key: "vendor",    label: "Vendor",    description: "Third-party dependency." },
  ],
  criticalityLevels: [
    { key: "tier-1", label: "Tier 1", description: "Business critical." },
    { key: "tier-2", label: "Tier 2", description: "Business important." },
    { key: "tier-3", label: "Tier 3", description: "Business supporting." },
  ],
  impactDimensions: [
    { key: "availability", label: "Availability",    description: "Service is reachable." },
    { key: "latency",      label: "Latency",         description: "Response time within SLO." },
    { key: "success",      label: "Transaction success", description: "Requests succeed end-to-end." },
    { key: "revenue",      label: "Revenue at risk", description: "Monetary exposure during degradation." },
  ],
  hardGuardrails: [
    { id: "gr-enterprise-1", title: "Change control",
      rule: "No production write action bypasses the change-management approval gate configured for its service tier." },
  ],
  standardsMappings: [
    { id: "sm-iso27001", framework: "ISO/IEC 27001", control: "A.12 Operations security",
      appliesTo: "Executions, evidence, audit log", note: "Mapping to how NOVA supports operational security controls.", kind: "mapping" },
    { id: "sm-itilv4", framework: "ITIL 4", control: "Incident, Problem, Change practices",
      appliesTo: "Runbooks, incidents, changes", note: "Mapping to ITIL practice areas; not an ITIL certification.", kind: "mapping" },
  ],
  defaultMetricDefinitions: [
    { id: "m-availability", name: "Availability",  unit: "%",  description: "Successful request ratio.",   source: "OpenTelemetry" },
    { id: "m-p95-latency",  name: "P95 latency",   unit: "ms", description: "95th percentile request latency.", source: "Prometheus" },
    { id: "m-err-budget",   name: "Error budget remaining", unit: "%", description: "Remaining SLO budget over window.", source: "SLO service" },
  ],
  defaultRunbookCategories: ["Mitigation", "Diagnostic", "Validation", "Rollback", "Failover"],
  defaultWorkerCategories: ["Incident Commander", "Application SRE", "Database SRE", "Network SRE", "Communications"],
  defaultConnectorCategories: ["Observability", "ITSM", "Chat", "Change", "Cloud", "Data"],
  presentationGuidance:
    "Consistent NOVA visual design. Industry authenticity comes from terminology, data, topology, and workflows — not decorative theming.",
  glossary: [
    { term: "SLO",  expansion: "Service Level Objective", industry: "cross-industry",
      definition: "A target for a service level indicator over a defined window.", tooltip: "Reliability target.", standardsRef: "Google SRE" },
    { term: "MTTR", expansion: "Mean Time To Restore",    industry: "cross-industry",
      definition: "Average time from detection to service restoration.", tooltip: "Average recovery time." },
  ],
  createdAt: NOW,
  updatedAt: NOW,
};

export const healthcareAmcIndustry: IndustryProfile = {
  id: "ind-healthcare-amc",
  code: "healthcare-amc",
  name: "Healthcare — Academic Medical Center",
  description:
    "Reliability engineering for clinical technology at an academic medical center: EHR, interface engines, imaging, medication administration, patient portals, and research computing.",
  operationalPhilosophy:
    "Clinical continuity and patient safety come before every reliability decision. Reliability tolerance may guide engineering choices but never authorizes clinical, safety, privacy, or data-integrity risk.",
  journeyLabel: "Clinical Workflow",
  serviceLabel: "Clinical or Technology Service",
  componentLabel: "Application, Interface, Device, or Platform Component",
  incidentLabel: "Clinical Technology Incident",
  impactLabel: "Clinical and Patient Impact",
  sloLabel: "Reliability Objective",
  errorBudgetLabel: "Reliability Tolerance",
  serviceCategories: ["Clinical", "Ancillary", "Patient Access", "Revenue Cycle", "Research", "Platform"],
  componentCategories: ["EHR module", "Interface engine", "Imaging system", "Medical device integration", "Portal", "Platform"],
  topologyNodeTypes: [
    { key: "clinical-app",     label: "Clinical application",  description: "Point-of-care software used by clinicians." },
    { key: "interface-engine", label: "Interface engine",      description: "Routes HL7/FHIR messages between systems." },
    { key: "imaging-system",   label: "Imaging system",        description: "PACS, modality worklist, imaging viewers." },
    { key: "device-gateway",   label: "Device gateway",        description: "Medical device integration point." },
    { key: "portal",           label: "Patient portal",        description: "Patient-facing digital front door." },
    { key: "platform",         label: "Platform",              description: "Identity, network, data platform." },
  ],
  criticalityLevels: [
    { key: "life-safety",       label: "Life safety",       description: "Direct impact on patient life-safety systems." },
    { key: "clinical-critical", label: "Clinical critical", description: "Required for real-time care delivery." },
    { key: "clinical-important",label: "Clinical important",description: "Supports care delivery but has clinical workaround." },
    { key: "administrative",    label: "Administrative",    description: "Non-clinical administrative function." },
  ],
  impactDimensions: [
    { key: "patient-safety",     label: "Patient safety",       description: "Risk to patient safety outcomes." },
    { key: "clinical-workflow",  label: "Clinical workflow",    description: "Disruption to clinical work." },
    { key: "care-delivery",      label: "Care delivery",        description: "Ability to deliver ordered care." },
    { key: "clinician-access",   label: "Clinician access",     description: "Clinician ability to reach systems." },
    { key: "patient-access",     label: "Patient access",       description: "Patient ability to reach services." },
    { key: "data-integrity",     label: "Data integrity",       description: "Trustworthiness of clinical records." },
    { key: "privacy",            label: "Privacy",              description: "PHI confidentiality." },
    { key: "regulatory",         label: "Regulatory exposure",  description: "HIPAA / Joint Commission / state exposure." },
    { key: "revenue-cycle",      label: "Revenue cycle",        description: "Charge capture, coding, billing." },
    { key: "reputation",         label: "Reputation",           description: "Institutional reputation." },
  ],
  hardGuardrails: [
    { id: "gr-hc-patient-safety", title: "Patient-safety absolute",
      rule: "Reliability tolerance may guide normal service engineering decisions, but no error budget or automation policy may authorize an action that creates unacceptable patient-safety, medication-safety, data-integrity, privacy, or clinical-continuity risk." },
    { id: "gr-hc-phi", title: "PHI handling",
      rule: "No workflow, worker, or connector exposes PHI outside its minimum-necessary boundary. Synthetic identifiers only in demonstrations." },
    { id: "gr-hc-medadmin", title: "Medication administration",
      rule: "No automated action modifies medication orders, MAR records, or barcode-scan interlocks. Escalate to clinical informatics." },
  ],
  standardsMappings: [
    { id: "sm-hipaa", framework: "HIPAA Security Rule", control: "§164.312 Technical safeguards",
      appliesTo: "Access, audit, integrity of clinical systems", note: "Mapping only — no certification claim.", kind: "mapping" },
    { id: "sm-hitrust", framework: "HITRUST CSF", control: "Operational reliability domains",
      appliesTo: "Reliability engineering evidence", note: "Mapping only — no certification claim.", kind: "mapping" },
    { id: "sm-jc", framework: "The Joint Commission", control: "Information management standards",
      appliesTo: "Clinical technology availability", note: "Mapping only — no accreditation claim.", kind: "mapping" },
  ],
  defaultMetricDefinitions: [
    { id: "m-hc-adt-lag",       name: "ADT message lag",             unit: "seconds", description: "Age of the newest queued ADT message.", source: "Interface engine" },
    { id: "m-hc-order-latency", name: "Order-entry save latency",    unit: "ms",      description: "Time from order submit to persisted acknowledgment.", source: "EHR telemetry" },
    { id: "m-hc-imaging-avail", name: "Imaging retrieval availability", unit: "%",   description: "Success rate for PACS study retrievals.", source: "PACS gateway" },
    { id: "m-hc-portal-avail",  name: "Patient portal availability", unit: "%",       description: "Successful patient portal sessions.", source: "Portal telemetry" },
  ],
  defaultRunbookCategories: [
    "Clinical continuity", "Interface engine recovery", "Imaging recovery", "Downtime procedure activation", "Patient access recovery", "Data integrity check",
  ],
  defaultWorkerCategories: [
    "Clinical Technology Commander", "EHR SRE", "Interface Engine SRE", "Imaging SRE", "Identity/Access SRE", "Communications Coordinator",
  ],
  defaultConnectorCategories: ["Interface engine", "Imaging (PACS)", "Directory/Identity", "EHR telemetry", "Chat", "ITSM", "Observability"],
  presentationGuidance:
    "Use clinical terminology consistently. Never speak or display patient identifiers. Always include the downtime-procedure prompt when clinical continuity is affected.",
  glossary: [
    { term: "ADT",   expansion: "Admission, Discharge, Transfer", industry: "healthcare-amc",
      definition: "The class of HL7 messages that convey patient movement events between systems.",
      tooltip: "Patient admission/discharge/transfer messages.", pronunciation: "A-D-T" },
    { term: "HL7",   expansion: "Health Level Seven",             industry: "healthcare-amc",
      definition: "Messaging standards for clinical and administrative data exchange between healthcare systems.",
      tooltip: "Clinical messaging standard.", pronunciation: "H-L-seven" },
    { term: "FHIR",  expansion: "Fast Healthcare Interoperability Resources", industry: "healthcare-amc",
      definition: "Modern HL7 standard for exchanging healthcare information using RESTful APIs.",
      tooltip: "Modern healthcare API standard.", pronunciation: "fire" },
    { term: "EHR",   expansion: "Electronic Health Record",       industry: "healthcare-amc",
      definition: "The system of record for a patient's clinical information.",
      tooltip: "Electronic health record system.", pronunciation: "E-H-R" },
    { term: "PACS",  expansion: "Picture Archiving and Communication System", industry: "healthcare-amc",
      definition: "Medical imaging archival and retrieval system.",
      tooltip: "Medical imaging archive.", pronunciation: "packs" },
    { term: "MPI",   expansion: "Master Patient Index",           industry: "healthcare-amc",
      definition: "The authoritative index of patient identities across systems.",
      tooltip: "Patient identity index.", pronunciation: "M-P-I" },
    { term: "RCM",   expansion: "Revenue Cycle Management",       industry: "healthcare-amc",
      definition: "Financial workflows from registration through claim adjudication.",
      tooltip: "Healthcare billing lifecycle.", pronunciation: "R-C-M" },
    { term: "MAR",   expansion: "Medication Administration Record", industry: "healthcare-amc",
      definition: "Record of medications administered to a patient.",
      tooltip: "Medication administration record.", pronunciation: "mar" },
  ],
  readinessCategories: [
    { key: "clinical-continuity", label: "Clinical continuity", description: "Care delivery continues during incidents." },
    { key: "downtime",            label: "Downtime procedure",  description: "Paper/manual downtime activation readiness." },
    { key: "patient-safety",      label: "Patient safety",      description: "Patient-safety guardrails and interlocks." },
    { key: "clinical-ownership",  label: "Clinical ownership",  description: "Clinical owner accountable for the service." },
    { key: "phi-controls",        label: "PHI controls",        description: "Minimum-necessary PHI handling and redaction." },
    { key: "integration-resilience", label: "Integration resilience", description: "HL7/FHIR interface engine and message reliability." },
  ],
  communicationsAudiences: [
    { key: "clinical-leadership", label: "Clinical leadership", channelHint: "Clinical exec brief" },
    { key: "nursing",             label: "Nursing",             channelHint: "Nursing operations" },
    { key: "laboratory",          label: "Laboratory",          channelHint: "Lab operations" },
    { key: "pharmacy",            label: "Pharmacy",            channelHint: "Pharmacy operations" },
    { key: "imaging",             label: "Imaging",             channelHint: "Radiology operations" },
    { key: "hospital-operations", label: "Hospital operations", channelHint: "House supervisor / hospital ops" },
    { key: "executive-leadership",label: "Executive leadership",channelHint: "Executive brief" },
  ],
  designerTemplates: [
    { key: "patient-safety-assessment", label: "Patient-safety assessment", kind: "diagnose",  description: "Assess whether an action creates patient-safety risk." },
    { key: "downtime-decision",         label: "Downtime decision",         kind: "approval",  description: "Decide whether to activate paper/manual downtime procedures." },
    { key: "message-reconciliation",    label: "Message reconciliation",    kind: "validate",  description: "Reconcile queued HL7/FHIR messages after interface recovery." },
    { key: "clinical-owner-approval",   label: "Clinical-owner approval",   kind: "approval",  description: "Require explicit clinical-owner approval for the action." },
    { key: "phi-safe-evidence",         label: "PHI-safe evidence",         kind: "evidence",  description: "Capture evidence with PHI redaction enforced." },
    { key: "clinical-workflow-validation", label: "Clinical workflow validation", kind: "validate", description: "Validate the affected clinical workflow end-to-end." },
  ],
  toilCategories: [
    { key: "manual-interface-checks",     label: "Manual interface checks",     description: "Hand-checking HL7/FHIR interface health per shift." },
    { key: "clinical-downtime-coord",     label: "Clinical downtime coordination", description: "Coordinating downtime paper/manual procedures." },
    { key: "vdi-triage",                  label: "VDI session triage",           description: "Triage of clinician VDI sessions and printer/badge issues." },
    { key: "certificate-monitoring",      label: "Certificate monitoring",      description: "Watching cert expirations across clinical systems." },
  ],
  postmortemFactorCategories: [
    { key: "clinical-workflow", label: "Clinical workflow", description: "Care-delivery workflow contributors." },
    { key: "integration",       label: "Integration",       description: "Interface engine and message-flow contributors." },
    { key: "identity-access",   label: "Identity & access", description: "SSO, badge, and directory contributors." },
    { key: "device-integration",label: "Device integration",description: "Medical device gateway contributors." },
    { key: "detection",         label: "Detection",         description: "Monitoring and alerting contributors." },
    { key: "governance",        label: "Governance",        description: "Change, safety, or governance contributors." },
  ],
  scenarioInjections: [
    { id: "inj-hc-interface-node-down",     label: "Clinical interface node unavailable", description: "An interface engine node becomes unavailable.",                reversible: true },
    { id: "inj-hc-message-sequence-fail",   label: "Message-sequence validation failure", description: "Reconciled messages fail sequence validation.",                reversible: true },
    { id: "inj-hc-downtime-threshold",      label: "Downtime threshold reached",          description: "Interface lag exceeds downtime-activation threshold.",         reversible: true },
    { id: "inj-hc-clinical-owner-denies",   label: "Clinical-owner approval denied",      description: "Clinical owner denies the proposed action.",                    reversible: true },
    { id: "inj-hc-phi-redaction-fail",      label: "PHI evidence redaction failure",      description: "Redaction check fails on captured evidence.",                   reversible: true },
  ],
  createdAt: NOW,
  updatedAt: NOW,
};

export const saasProductionIndustry: IndustryProfile = {
  id: "ind-saas-production",
  code: "saas-production",
  name: "SaaS Production",
  description:
    "Multi-tenant SaaS production operations covering the control plane, data plane, ingestion, checkout, and customer-facing product surfaces.",
  operationalPhilosophy:
    "Progressive delivery with SLO-guarded release velocity. Error budgets steer velocity and autonomy, but never authorize security-control bypass or tenant-data exposure.",
  journeyLabel: "Customer Journey",
  serviceLabel: "Product or Platform Service",
  componentLabel: "Service, Workload, or Platform Component",
  incidentLabel: "Production Incident",
  impactLabel: "Customer and Commercial Impact",
  sloLabel: "SLO",
  errorBudgetLabel: "Error Budget",
  serviceCategories: ["Customer product", "Control plane", "Data plane", "Ingestion", "Auth", "Billing", "Platform"],
  componentCategories: ["API service", "Worker", "Database", "Cache", "Stream", "Object store", "CDN", "Identity"],
  topologyNodeTypes: [
    { key: "product-surface",  label: "Product surface", description: "Customer-facing product entrypoint." },
    { key: "api",              label: "API service",     description: "Multi-tenant API service." },
    { key: "worker",           label: "Async worker",    description: "Background job processor." },
    { key: "stream",           label: "Stream",          description: "Event/messaging pipeline." },
    { key: "datastore",        label: "Datastore",       description: "Persistent tenant-scoped datastore." },
    { key: "identity",         label: "Identity",        description: "Auth / tenant isolation boundary." },
    { key: "vendor",           label: "Vendor",          description: "Third-party dependency." },
  ],
  criticalityLevels: [
    { key: "customer-facing", label: "Customer-facing",   description: "Directly on the customer's request path." },
    { key: "revenue-path",    label: "Revenue path",      description: "Required for billing/checkout." },
    { key: "control-plane",   label: "Control plane",     description: "Fleet/tenant management." },
    { key: "internal",        label: "Internal",          description: "Non-customer-facing tooling." },
  ],
  impactDimensions: [
    { key: "cust-availability", label: "Customer availability", description: "Customer requests succeed." },
    { key: "latency",           label: "Latency",               description: "Perceived response time." },
    { key: "tx-success",        label: "Transaction success",   description: "Business transactions complete." },
    { key: "tenant-isolation",  label: "Tenant isolation",      description: "No cross-tenant leakage." },
    { key: "data-durability",   label: "Data durability",       description: "No permanent data loss." },
    { key: "data-freshness",    label: "Data freshness",        description: "Delivered data is current." },
    { key: "security",          label: "Security",              description: "No control bypass or exposure." },
    { key: "sla-exposure",      label: "SLA exposure",          description: "Contractual SLA at risk." },
    { key: "revenue-at-risk",   label: "Revenue at risk",       description: "Monetary exposure during degradation." },
    { key: "support-volume",    label: "Support volume",        description: "Support ticket surge risk." },
  ],
  hardGuardrails: [
    { id: "gr-saas-security", title: "Security absolute",
      rule: "Error budgets may control release velocity and autonomy, but never permit security-control bypass, tenant-data exposure, data-loss risk, or unauthorized access." },
    { id: "gr-saas-tenant-iso", title: "Tenant isolation",
      rule: "No automation may cross tenant boundaries. Cross-tenant reads or writes require explicit change-management approval outside NOVA autonomy." },
  ],
  standardsMappings: [
    { id: "sm-soc2", framework: "SOC 2", control: "Common Criteria (CC7 Operations, CC8 Change)",
      appliesTo: "Executions, evidence, change linkage", note: "Mapping only — no certification claim.", kind: "mapping" },
    { id: "sm-iso27001-saas", framework: "ISO/IEC 27001", control: "A.12 Operations security",
      appliesTo: "Operations, monitoring, change", note: "Mapping only — no certification claim.", kind: "mapping" },
    { id: "sm-google-sre", framework: "Google SRE", control: "SLO and error budget policy",
      appliesTo: "Reliability objectives and release gating", note: "Reference framework mapping.", kind: "mapping" },
  ],
  defaultMetricDefinitions: [
    { id: "m-saas-req-avail",  name: "Request availability", unit: "%",  description: "Success ratio of customer requests.", source: "Edge gateway" },
    { id: "m-saas-p95",         name: "Request p95 latency", unit: "ms", description: "P95 request latency at edge.",        source: "Edge gateway" },
    { id: "m-saas-checkout-succ", name: "Checkout success", unit: "%",   description: "End-to-end checkout success rate.",   source: "Checkout service" },
    { id: "m-saas-queue-lag",   name: "Stream consumer lag",  unit: "s",  description: "Age of oldest un-ack'd stream event.", source: "Stream broker" },
  ],
  defaultRunbookCategories: ["Progressive rollback", "Traffic shift", "Cache invalidation", "Consumer scale-out", "Failover", "Feature flag control"],
  defaultWorkerCategories: ["Incident Commander", "Edge SRE", "Data plane SRE", "Ingestion SRE", "Change Risk Analyst", "Customer Communications"],
  defaultConnectorCategories: ["Observability", "ITSM", "Chat", "Change", "Cloud", "Feature flag", "Data warehouse"],
  presentationGuidance:
    "Use SaaS operations terminology. Frame customer impact in customer/revenue units. Never expose tenant identifiers in demo narration.",
  glossary: [
    { term: "SLO",  expansion: "Service Level Objective", industry: "saas-production",
      definition: "A reliability target over a defined window.", tooltip: "Reliability target." },
    { term: "SLI",  expansion: "Service Level Indicator",  industry: "saas-production",
      definition: "A measured signal used to evaluate an SLO.", tooltip: "Reliability signal." },
    { term: "MTTR", expansion: "Mean Time To Restore",     industry: "saas-production",
      definition: "Average time from detection to restoration.", tooltip: "Average recovery time." },
    { term: "MTTA", expansion: "Mean Time To Acknowledge", industry: "saas-production",
      definition: "Average time from alert to acknowledgment.", tooltip: "Average acknowledgment time." },
    { term: "RPO",  expansion: "Recovery Point Objective", industry: "saas-production",
      definition: "Maximum acceptable data loss window.", tooltip: "Max acceptable data-loss window." },
    { term: "RTO",  expansion: "Recovery Time Objective",  industry: "saas-production",
      definition: "Maximum acceptable outage window.", tooltip: "Max acceptable outage window." },
    { term: "Tenant isolation", industry: "saas-production",
      definition: "The invariant that no request or job can access another tenant's data.", tooltip: "No cross-tenant data access." },
  ],
  readinessCategories: [
    { key: "slo",              label: "SLOs",                description: "Objectives, error budgets, and burn policy." },
    { key: "tenant-isolation", label: "Tenant isolation",    description: "Cross-tenant access is impossible." },
    { key: "regional-resilience", label: "Regional resilience", description: "Traffic can shift across regions with data safety." },
    { key: "release-safety",   label: "Release safety",      description: "Progressive delivery, canary, and rollback readiness." },
    { key: "observability",    label: "Observability",       description: "Metrics, logs, traces, and correlation coverage." },
    { key: "capacity",         label: "Capacity",            description: "Saturation, headroom, autoscaling behaviour." },
    { key: "data-durability",  label: "Data durability",     description: "Backup, replication, and RPO enforcement." },
  ],
  communicationsAudiences: [
    { key: "engineering",       label: "Engineering",         channelHint: "Engineering channel" },
    { key: "executive",         label: "Executive",           channelHint: "Executive brief" },
    { key: "customer-success",  label: "Customer success",    channelHint: "CS channel" },
    { key: "customer-support",  label: "Customer support",    channelHint: "Support channel + macro" },
    { key: "affected-customers",label: "Affected customers",  channelHint: "Customer email + in-product" },
    { key: "status-page",       label: "Public status page",  channelHint: "Public status page" },
  ],
  designerTemplates: [
    { key: "slo-burn-check",       label: "SLO burn check",       kind: "diagnose",  description: "Check burn against configured budget and window." },
    { key: "canary-validation",    label: "Canary validation",    kind: "validate",  description: "Compare canary vs baseline on customer-visible signals." },
    { key: "feature-flag-change",  label: "Feature-flag change",  kind: "mitigate",  description: "Toggle a feature flag under change control." },
    { key: "tenant-impact-analysis", label: "Tenant-impact analysis", kind: "diagnose", description: "Scope customer/tenant impact of a change or incident." },
    { key: "regional-traffic-shift", label: "Regional traffic shift", kind: "mitigate", description: "Shift traffic between regions with data-safety checks." },
    { key: "error-budget-policy",  label: "Error-budget policy",  kind: "approval",  description: "Apply SLO burn policy to gate release velocity." },
  ],
  toilCategories: [
    { key: "deployment-recovery",  label: "Repetitive deployment recovery", description: "Manual rollback and traffic shifts on failed deploys." },
    { key: "queue-triage",         label: "Queue triage",                    description: "Backlog and DLQ inspection." },
    { key: "capacity-adjustments", label: "Capacity adjustments",            description: "Ad hoc scale changes to relieve saturation." },
    { key: "tenant-impact-analysis", label: "Tenant-impact analysis",        description: "Bespoke customer-impact reports per incident." },
  ],
  postmortemFactorCategories: [
    { key: "release",       label: "Release",       description: "Deployment, feature flag, canary contributors." },
    { key: "capacity",      label: "Capacity",      description: "Saturation, hot shard, autoscaling contributors." },
    { key: "dependency",    label: "Dependency",    description: "Upstream/downstream service or vendor contributors." },
    { key: "detection",     label: "Detection",     description: "Alerting and observability contributors." },
    { key: "tenant-scope",  label: "Tenant scope",  description: "Isolation or tenant-specific contributors." },
    { key: "data",          label: "Data",          description: "Data plane, replication, or freshness contributors." },
  ],
  scenarioInjections: [
    { id: "inj-saas-hot-shard-worsens",     label: "Hot shard worsens",         description: "Hot shard saturation escalates during mitigation.",              reversible: true },
    { id: "inj-saas-canary-fails",          label: "Canary validation failure", description: "Canary signals diverge from baseline; rollback required.",       reversible: true },
    { id: "inj-saas-tenant-iso-fails",      label: "Tenant-isolation check fails", description: "Isolation invariant assertion fails during recovery.",        reversible: true },
    { id: "inj-saas-region-unavailable",    label: "Region unavailable",        description: "A primary region becomes unavailable; failover required.",       reversible: true },
    { id: "inj-saas-flag-rollback-fails",   label: "Feature-flag rollback fails", description: "Flag toggle does not propagate; alternate mitigation required.", reversible: true },
  ],
  createdAt: NOW,
  updatedAt: NOW,
};

export const chipManufacturingIndustry: IndustryProfile = {
  id: "ind-chip-manufacturing",
  code: "chip-manufacturing",
  name: "Semiconductor Manufacturing",
  description:
    "Factory IT reliability for a semiconductor fab: MES, EAP, recipe management, SPC/FDC, WIP tracking, and tool controllers.",
  operationalPhilosophy:
    "Operating tolerance may guide factory IT reliability decisions, but never authorizes safety-interlock bypass, process-limit override, recipe change, unauthorized lot release, traceability loss, or QC bypass.",
  journeyLabel: "Production Flow",
  serviceLabel: "Factory Capability or Manufacturing System",
  componentLabel: "Tool, Chamber, Module, Controller, or Factory System",
  incidentLabel: "Fab Operational Event",
  impactLabel: "WIP, Yield, and Factory Impact",
  sloLabel: "Factory Service Objective",
  errorBudgetLabel: "Operating Tolerance",
  serviceCategories: ["MES", "EAP", "Recipe management", "SPC/FDC", "Dispatching", "Metrology", "Facilities"],
  componentCategories: ["Tool controller", "Chamber", "Module", "PLC", "SCADA", "Historian", "Gateway"],
  topologyNodeTypes: [
    { key: "mes",        label: "MES",         description: "Manufacturing execution system." },
    { key: "eap",        label: "EAP",         description: "Equipment automation platform." },
    { key: "tool",       label: "Tool",        description: "Process tool with chambers/modules." },
    { key: "controller", label: "Controller",  description: "Tool controller or PLC." },
    { key: "spc-fdc",    label: "SPC/FDC",     description: "Statistical/fault detection control." },
    { key: "recipe-mgmt",label: "Recipe mgmt", description: "Recipe management system." },
    { key: "wip",        label: "WIP tracker", description: "Work-in-process tracker." },
  ],
  criticalityLevels: [
    { key: "safety",        label: "Safety",        description: "Personnel or facility safety systems." },
    { key: "process-control",label: "Process control", description: "Direct process-control impact." },
    { key: "wip-flow",      label: "WIP flow",      description: "Lot flow and dispatching." },
    { key: "analytics",     label: "Analytics",     description: "Non-real-time analytics." },
  ],
  impactDimensions: [
    { key: "wafers-at-risk",   label: "Wafers at risk",       description: "Wafers exposed to excursion." },
    { key: "lots-at-risk",     label: "Lots at risk",         description: "Lots exposed to excursion." },
    { key: "yield",            label: "Yield",                description: "Yield exposure." },
    { key: "cycle-time",       label: "Cycle time",           description: "Cycle-time impact." },
    { key: "queue-time",       label: "Queue time",           description: "Queue-time impact." },
    { key: "tool-avail",       label: "Tool availability",    description: "Tool uptime." },
    { key: "throughput",       label: "Throughput",           description: "Fab throughput." },
    { key: "recipe-integrity", label: "Recipe integrity",     description: "Correctness of active recipes." },
    { key: "traceability",     label: "Traceability",         description: "Lot/wafer traceability." },
    { key: "quality",          label: "Quality",              description: "Quality-control conformance." },
    { key: "safety",           label: "Safety",               description: "Safety-interlock integrity." },
    { key: "delivery",         label: "Delivery commitment",  description: "Customer delivery commitment." },
  ],
  hardGuardrails: [
    { id: "gr-fab-safety", title: "Safety-interlock absolute",
      rule: "Operating tolerance may guide factory IT and automation reliability decisions, but it must never authorize safety-interlock bypass, process-limit override, recipe change, unauthorized lot release, traceability loss, or quality-control bypass." },
    { id: "gr-fab-recipe", title: "Recipe control",
      rule: "No automation modifies, releases, or activates recipes without process-engineering approval and MES change-record linkage." },
    { id: "gr-fab-lot", title: "Lot release",
      rule: "No automation releases a lot on hold or waives a QC gate. Escalate to process engineering." },
  ],
  standardsMappings: [
    { id: "sm-sema", framework: "SEMI E10", control: "Equipment reliability, availability, maintainability",
      appliesTo: "Tool availability metrics", note: "Mapping only — no certification claim.", kind: "mapping" },
    { id: "sm-secs-gem", framework: "SECS/GEM", control: "Equipment communications standard",
      appliesTo: "EAP integration reliability", note: "Reference protocol mapping.", kind: "mapping" },
    { id: "sm-iso9001-fab", framework: "ISO 9001", control: "Nonconformity and corrective action",
      appliesTo: "Postmortem and corrective actions", note: "Mapping only — no certification claim.", kind: "mapping" },
  ],
  defaultMetricDefinitions: [
    { id: "m-fab-tool-avail",  name: "Tool availability",     unit: "%",  description: "Tool uptime over window.",              source: "EAP" },
    { id: "m-fab-mes-p95",     name: "MES transaction p95",   unit: "ms", description: "P95 MES transaction latency.",           source: "MES" },
    { id: "m-fab-fdc-alarms",  name: "FDC alarms",             unit: "count", description: "Active FDC excursion alarms.",       source: "FDC" },
    { id: "m-fab-wip-at-risk", name: "WIP at risk",           unit: "lots", description: "Lots exposed to current excursion.",   source: "WIP tracker" },
  ],
  defaultRunbookCategories: ["Tool recovery", "MES service recovery", "EAP restart", "FDC alarm response", "WIP dispatch adjustment", "Recipe rollback"],
  defaultWorkerCategories: ["Fab IT Commander", "MES SRE", "EAP SRE", "Tool automation SRE", "Process engineering liaison", "Quality liaison"],
  defaultConnectorCategories: ["EAP", "MES", "Historian", "SPC/FDC", "Dispatcher", "Chat", "ITSM", "Observability"],
  presentationGuidance:
    "Use fab operations terminology. Frame impact in wafers/lots/yield/cycle-time. Never bypass safety/process/QC framings.",
  glossary: [
    { term: "MES",  expansion: "Manufacturing Execution System", industry: "chip-manufacturing",
      definition: "System of record for shop-floor execution and lot tracking.", tooltip: "Manufacturing execution system." },
    { term: "EAP",  expansion: "Equipment Automation Platform",  industry: "chip-manufacturing",
      definition: "Integrates tools and controllers with MES via SECS/GEM.", tooltip: "Equipment automation platform." },
    { term: "FDC",  expansion: "Fault Detection and Classification", industry: "chip-manufacturing",
      definition: "Detects tool/process excursions from statistical baselines.", tooltip: "Fault detection & classification." },
    { term: "SPC",  expansion: "Statistical Process Control",   industry: "chip-manufacturing",
      definition: "Uses control charts to monitor process stability.", tooltip: "Statistical process control." },
    { term: "WIP",  expansion: "Work In Process",               industry: "chip-manufacturing",
      definition: "Lots currently in production.", tooltip: "Lots in production.", pronunciation: "W-I-P" },
    { term: "RMS",  expansion: "Recipe Management System",       industry: "chip-manufacturing",
      definition: "System of record for process recipes.", tooltip: "Recipe management." },
    { term: "OEE",  expansion: "Overall Equipment Effectiveness", industry: "chip-manufacturing",
      definition: "Availability × performance × quality.", tooltip: "Overall equipment effectiveness." },
    { term: "CIM",  expansion: "Computer-Integrated Manufacturing", industry: "chip-manufacturing",
      definition: "The umbrella term for the factory automation stack.", tooltip: "Factory automation stack." },
  ],
  readinessCategories: [
    { key: "equipment-connectivity", label: "Equipment connectivity", description: "SECS/GEM & HSMS session stability, host communication." },
    { key: "lot-genealogy",          label: "Lot genealogy",          description: "MES lot/wafer traceability is complete and unbroken." },
    { key: "recipe-integrity",       label: "Recipe integrity",       description: "Recipe checksum and approved-version enforcement." },
    { key: "fdc-spc-coverage",       label: "FDC and SPC coverage",   description: "Fault detection and statistical process control are collecting and evaluating traces." },
    { key: "amhs-resilience",        label: "AMHS resilience",        description: "Automated material handling recovers from stocker/OHTV faults." },
    { key: "qualification",          label: "Qualification",          description: "PM qualification and chamber matching before production release." },
    { key: "utility-resilience",     label: "Utility resilience",     description: "PCW, bulk gas, vacuum, exhaust, power tolerances." },
  ],
  communicationsAudiences: [
    { key: "production-control",   label: "Production Control",   channelHint: "Fab ops chat + on-call" },
    { key: "process-engineering",  label: "Process Engineering",  channelHint: "Engineering channel + email" },
    { key: "equipment-engineering",label: "Equipment Engineering",channelHint: "Bay chat + on-call" },
    { key: "quality",              label: "Quality",              channelHint: "Quality channel + record" },
    { key: "yield",                label: "Yield",                channelHint: "Yield channel" },
    { key: "facilities",           label: "Facilities",           channelHint: "Facilities on-call" },
    { key: "fab-leadership",       label: "Fab leadership",       channelHint: "Executive brief" },
  ],
  designerTemplates: [
    { key: "tool-hold",            label: "Tool hold",              kind: "mitigate", description: "Place a tool or chamber in a controlled hold state." },
    { key: "lot-hold",             label: "Lot hold",               kind: "mitigate", description: "Place lots on quality hold pending disposition." },
    { key: "wip-reroute",          label: "WIP reroute",            kind: "mitigate", description: "Reroute eligible WIP to qualified alternates preserving hot-lot priority." },
    { key: "recipe-verification",  label: "Recipe verification",    kind: "diagnose", description: "Verify recipe checksum and approved version." },
    { key: "qualification-wafer",  label: "Qualification wafer",    kind: "validate", description: "Run qualification wafers and evaluate chamber matching." },
    { key: "process-quality-approval", label: "Process & quality approval", kind: "approval", description: "Require explicit Process Engineering and Quality approval." },
    { key: "equipment-release",    label: "Equipment release",      kind: "validate", description: "Release equipment to production only after all approvals." },
  ],
  toilCategories: [
    { key: "equipment-state-reconciliation", label: "Equipment-state reconciliation", description: "Reconcile MES and tool state after session flaps." },
    { key: "fdc-trace-triage",               label: "FDC trace triage",               description: "Triage FDC alarms and route to owners." },
    { key: "wip-reroute-analysis",           label: "WIP rerouting analysis",         description: "Analyse eligible alternates when a tool is held." },
    { key: "qualification-evidence",         label: "Qualification evidence collection", description: "Gather qualification wafers, matching data, and evidence." },
  ],
  postmortemFactorCategories: [
    { key: "equipment",     label: "Equipment",     description: "Hardware, chamber, module contributors." },
    { key: "process",       label: "Process",       description: "Recipe, chamber matching, process-window contributors." },
    { key: "maintenance",   label: "Maintenance",   description: "PM scope, seasoning, procedure contributors." },
    { key: "detection",     label: "Detection",     description: "FDC, SPC, alarming contributors." },
    { key: "dispatch",      label: "Dispatch",      description: "RTD, WIP, hot-lot handling contributors." },
    { key: "control-system",label: "Control system",description: "MES, CIM, SECS/GEM, HSMS contributors." },
  ],
  scenarioInjections: [
    { id: "inj-fab-fdc-trace-unavailable", label: "FDC trace unavailable",        description: "FDC platform loses trace stream from Chamber B.",                        reversible: true },
    { id: "inj-fab-alt-chamber-unavailable", label: "Alternate chamber unavailable", description: "Chambers A/C/D become unavailable for reroute.",                     reversible: true },
    { id: "inj-fab-qualification-fails",   label: "Qualification wafer fails",     description: "Qualification wafer result blocks chamber release.",                    reversible: true },
    { id: "inj-fab-recipe-checksum-mismatch", label: "Recipe checksum mismatch",   description: "Downloaded recipe checksum diverges from approved version.",            reversible: true },
    { id: "inj-fab-quality-denied",        label: "Quality approval denied",       description: "Quality disposition denies release; lot remains on hold.",              reversible: true },
    { id: "inj-fab-amhs-reroute-unavailable", label: "AMHS reroute unavailable",   description: "AMHS cannot reroute FOUP delivery to the alternate tool.",              reversible: true },
  ],
  createdAt: NOW,
  updatedAt: NOW,
};

export const industryProfiles: readonly IndustryProfile[] = [
  genericEnterpriseIndustry,
  healthcareAmcIndustry,
  saasProductionIndustry,
  chipManufacturingIndustry,
];

export function getIndustryProfile(code: string): IndustryProfile {
  const found = industryProfiles.find((p) => p.code === code);
  if (!found) return genericEnterpriseIndustry;
  return found;
}
