// Realistic mock data for the Customer Health Dashboard. All impact contexts
// are keyed by id so any object on any page can open the same universal drawer.

import { kpiContexts, kpiOverlays } from "./kpiDetail";
import { deploymentDetails } from "./deploymentDetail";
import type {
  AlertRule, ChangeRecord, CustomerImpactContext, DependencyRow, DeploymentCard,
  KpiTile, RegionRow, ReportItem, RiskSignal, ServiceEvent, SloRow,
} from "./types";

export const tenant = {
  name: "Northwind Logistics",
  service: "Managed Orchestration Service",
  lastUpdated: "12s ago",
  window: "Last 24 hours",
};

export const kpis: KpiTile[] = [
  { id: "k-health", label: "Overall Health", value: "Healthy", caption: "No impact to your services", status: "healthy", icon: "shield", contextId: "overall-health" },
  { id: "k-services", label: "Services", value: "6 / 6", caption: "All services healthy", status: "healthy", icon: "layers", contextId: "services" },
  { id: "k-deploy", label: "Deployments", value: "8", caption: "Across 3 regions", status: "info", icon: "box", contextId: "deployments" },
  { id: "k-avail", label: "Availability (24h)", value: "99.997%", caption: "Above your 99.99% target", status: "healthy", icon: "trend", contextId: "availability-24h" },
  { id: "k-events", label: "Active Events", value: "1 Advisory", caption: "0 Incidents", status: "advisory", icon: "bell", contextId: "evt-blob-latency" },
  { id: "k-risk", label: "At Risk", value: "1", caption: "Deployment", status: "at-risk", icon: "warning", contextId: "risk-storage" },
  { id: "k-azure", label: "Azure Dependencies", value: "17 / 18", caption: "Healthy", status: "info", icon: "cloud", contextId: "azure-dependencies" },
];

export const deployments: DeploymentCard[] = [
  {
    id: "d-east", name: "Production, East US", region: "East US", nodes: 12, tier: "Customer Production",
    environment: "Production", resources: "12 nodes · 64 resources", advisoryCount: 0,
    availability: "99.999%", status: "healthy", alerts: "0 Alerts",
    spark: [58, 62, 60, 66, 63, 68, 65, 70, 67, 72, 69, 74], contextId: "dep-east",
    hover: {
      overallHealth: "Healthy", customerImpact: "None", availability: "99.999% (24h)",
      infrastructureRisk: "Low — no abnormal layer", advisories: "0 active", lastHealthChange: "No change in 14 days",
    },
  },
  {
    id: "d-west", name: "Production, West US 2", region: "West US 2", nodes: 8, tier: "Customer Production",
    environment: "Production", resources: "8 nodes · 46 resources", advisoryCount: 1,
    availability: "99.982%", status: "healthy", alerts: "1 Advisory (not reaching users)",
    spark: [62, 58, 70, 52, 74, 48, 66, 54, 71, 50, 63, 57], contextId: "dep-west",
    hover: {
      overallHealth: "Healthy — service available", customerImpact: "None measurable", availability: "99.982% (24h)",
      infrastructureRisk: "Elevated — storage latency", advisories: "1 active advisory", lastHealthChange: "Advisory raised 08:41 AM PT",
    },
  },
  {
    id: "d-dr", name: "DR, Central US", region: "Central US", nodes: 6, tier: "Customer DR",
    environment: "Disaster Recovery", resources: "6 nodes · 31 resources", advisoryCount: 0,
    availability: "100.00%", status: "healthy", alerts: "0 Alerts",
    spark: [64, 66, 65, 67, 66, 68, 67, 69, 68, 70, 69, 71], contextId: "dep-dr",
    hover: {
      overallHealth: "Healthy — standby ready", customerImpact: "None", availability: "100.00% (24h)",
      infrastructureRisk: "Low — replication within objective", advisories: "0 active", lastHealthChange: "No change in 30 days",
    },
  },
  {
    id: "d-eu", name: "Production, North Europe", region: "North Europe", nodes: 9, tier: "Customer Production",
    environment: "Production", resources: "9 nodes · 52 resources", advisoryCount: 0,
    availability: "99.996%", status: "healthy", alerts: "0 Alerts",
    spark: [60, 63, 61, 65, 64, 66, 65, 68, 66, 69, 68, 70], contextId: "dep-eu",
    hover: {
      overallHealth: "Healthy", customerImpact: "None", availability: "99.996% (24h)",
      infrastructureRisk: "Low — no abnormal layer", advisories: "0 active", lastHealthChange: "No change in 9 days",
    },
  },
  {
    id: "d-stg", name: "Staging, East US", region: "East US", nodes: 4, tier: "Non-production",
    environment: "Non-production", resources: "4 nodes · 18 resources", advisoryCount: 0,
    availability: "99.940%", status: "healthy", alerts: "0 Alerts",
    spark: [55, 60, 57, 62, 58, 64, 60, 63, 61, 66, 62, 65], contextId: "dep-stg",
    hover: {
      overallHealth: "Healthy — non-production", customerImpact: "None (no customer traffic)", availability: "99.940% (24h)",
      infrastructureRisk: "Low", advisories: "0 active", lastHealthChange: "No change in 4 days",
    },
  },
];

export const dependencies: DependencyRow[] = [
  { id: "dep-your", layer: "Your Service", description: "Your deployments and user experience", status: "healthy", contextId: "layer-your-service" },
  { id: "dep-layer", layer: "Service Layer", description: "Service control and orchestration", status: "healthy", contextId: "layer-service" },
  { id: "dep-compute", layer: "Compute", description: "Virtual machines and host infrastructure", status: "healthy", contextId: "layer-compute" },
  { id: "dep-storage", layer: "Storage", description: "Storage accounts and blob services", status: "degraded", contextId: "layer-storage" },
  { id: "dep-network", layer: "Network", description: "Virtual network and connectivity", status: "healthy", contextId: "layer-network" },
  { id: "dep-azure", layer: "Azure Services", description: "Platform services and dependencies", status: "degraded", contextId: "layer-azure-services" },
  { id: "dep-region", layer: "Azure Region", description: "West US 2 experiencing issues", status: "at-risk", contextId: "layer-azure-region" },
];

export const events: ServiceEvent[] = [
  {
    id: "evt-blob-latency", kind: "Advisory",
    title: "Elevated Azure Blob Storage Latency – West US 2",
    started: "08:41 AM PT", updated: "5m ago",
    summary: "We are observing elevated latency when accessing Azure Blob Storage in West US 2. Your services remain available. No action is required.",
    impactToYou: "None", affectedDeployment: "Production – West US 2", affectedDependency: "Azure Blob Storage",
    response: "Monitoring & Microsoft case open", providerReference: "AZ-80456", nextUpdate: "10:00 AM PT",
    status: "advisory", contextId: "evt-blob-latency",
  },
  {
    id: "evt-net-jitter", kind: "Information",
    title: "Transient network jitter – Central US peering",
    started: "Yesterday 21:12 PT", updated: "Resolved 22:04 PT",
    summary: "A short period of packet re-transmission was observed on a peering path serving Central US. Traffic was automatically re-routed.",
    impactToYou: "None", affectedDeployment: "DR – Central US", affectedDependency: "Azure Virtual Network",
    response: "Auto-remediated by traffic steering", providerReference: "AZ-79912", nextUpdate: "Closed",
    status: "info", contextId: "evt-net-jitter",
  },
  {
    id: "evt-cert-rotation", kind: "Maintenance",
    title: "Scheduled certificate rotation – Orchestration endpoints",
    started: "Jun 7, 10:00 PT", updated: "Scheduled",
    summary: "Routine rotation of TLS certificates on orchestration endpoints. Connections are drained gracefully; no downtime is expected.",
    impactToYou: "None expected", affectedDeployment: "All production deployments", affectedDependency: "Service Layer",
    response: "Change approved, staged rollout", providerReference: "CHG-24188", nextUpdate: "Jun 7, 11:00 PT",
    status: "info", contextId: "evt-cert-rotation",
  },
];

export const regions: RegionRow[] = [
  { id: "r-east", name: "East US", status: "healthy", note: "Your service", x: 27, y: 40, contextId: "region-east" },
  { id: "r-central", name: "Central US", status: "healthy", note: "No deployments impacted", x: 23, y: 42, contextId: "region-central" },
  { id: "r-west", name: "West US 2", status: "degraded", note: "Your service affected", x: 15, y: 38, contextId: "region-west" },
  { id: "r-eu", name: "North Europe", status: "healthy", note: "No deployments impacted", x: 48, y: 30, contextId: "region-eu" },
  { id: "r-sea", name: "Southeast Asia", status: "healthy", note: "No deployments", x: 74, y: 58, contextId: "region-sea" },
];

export const slos: SloRow[] = [
  { id: "slo-avail", name: "Availability SLO", target: "99.99%", current: "99.997%", attainment: 99.997, errorBudget: 93.4, status: "healthy", contextId: "slo-availability" },
  { id: "slo-latency", name: "Latency SLO", target: "99.5%", current: "99.7%", attainment: 99.7, errorBudget: 78.2, status: "healthy", contextId: "slo-latency" },
  { id: "slo-reliability", name: "Reliability SLO", target: "99.98%", current: "99.986%", attainment: 99.986, errorBudget: 88.1, status: "healthy", contextId: "slo-reliability" },
  { id: "slo-durability", name: "Durability SLO", target: "99.999%", current: "100%", attainment: 100, errorBudget: 100, status: "healthy", contextId: "slo-durability" },
];

export const risks: RiskSignal[] = [
  { id: "risk-overall", label: "Overall Risk", level: "Low", status: "healthy", spark: [30, 28, 32, 29, 27, 31, 28, 26, 29, 27, 25, 28], contextId: "risk-overall" },
  { id: "risk-storage", label: "Storage Risk", level: "Elevated", status: "degraded", spark: [34, 40, 52, 47, 61, 58, 70, 64, 72, 68, 74, 71], contextId: "risk-storage" },
  { id: "risk-compute", label: "Compute Risk", level: "Low", status: "healthy", spark: [26, 29, 27, 30, 28, 26, 29, 27, 30, 28, 26, 27], contextId: "risk-compute" },
  { id: "risk-network", label: "Network Risk", level: "Low", status: "healthy", spark: [24, 27, 25, 28, 26, 24, 27, 25, 28, 26, 25, 26], contextId: "risk-network" },
];

export const changes: ChangeRecord[] = [
  { id: "chg-az", title: "Azure Maintenance – West US 2", window: "Jun 6, 02:00 – 06:00 AM PT", potentialImpact: "Low", kind: "Provider maintenance", contextId: "chg-azure-westus2" },
  { id: "chg-plat", title: "Platform Update – Orchestration Service", window: "Jun 7, 10:00 – 11:00 AM PT", potentialImpact: "None", kind: "Platform update", contextId: "chg-platform-update" },
  { id: "chg-dr", title: "DR readiness verification – Central US", window: "Jun 9, 01:00 – 03:00 AM PT", potentialImpact: "None", kind: "Platform update", contextId: "chg-dr-verification" },
];

export const availability30d = [
  99.99, 100, 99.998, 99.995, 100, 99.999, 99.997, 100, 99.994, 99.999, 100, 99.998,
  99.996, 100, 99.999, 99.993, 100, 99.997, 99.999, 100, 99.998, 99.982, 99.995, 100,
  99.999, 99.997, 100, 99.998, 99.999, 100,
];

export const alertRules: AlertRule[] = [
  { id: "al-1", name: "Customer-impacting incident opened", scope: "All deployments", channel: "Email + SMS", enabled: true, lastFired: "42 days ago", contextId: "alert-incident" },
  { id: "al-2", name: "Advisory affecting my regions", scope: "East US, West US 2, North Europe", channel: "Email", enabled: true, lastFired: "Today 08:41 PT", contextId: "alert-advisory" },
  { id: "al-3", name: "Error budget below 25%", scope: "Availability SLO", channel: "Email + Teams", enabled: true, lastFired: "Never", contextId: "alert-error-budget" },
  { id: "al-4", name: "Planned maintenance in my regions", scope: "Provider maintenance", channel: "Email", enabled: false, lastFired: "12 days ago", contextId: "alert-maintenance" },
];

export const reports: ReportItem[] = [
  { id: "rp-1", name: "Monthly service health summary", period: "May 2026", format: "PDF", description: "Availability, incidents, advisories and SLO attainment for your subscribed services.", contextId: "report-monthly" },
  { id: "rp-2", name: "SLO attainment & error budget", period: "Rolling 90 days", format: "PDF + CSV", description: "Attainment per objective with error budget consumption and burn trend.", contextId: "report-slo" },
  { id: "rp-3", name: "Provider dependency exposure", period: "Q2 2026", format: "PDF", description: "Where your deployments depend on cloud provider services and how exposure is mitigated.", contextId: "report-dependency" },
  { id: "rp-4", name: "Incident & advisory register", period: "YTD 2026", format: "CSV", description: "Every event raised against your services with impact classification and resolution.", contextId: "report-events" },
];

/* ------------------------------------------------------------------ */
/* Impact contexts consumed by CustomerImpactDrawer                    */
/* ------------------------------------------------------------------ */

const noAction = "No action required. We will continue to monitor on your behalf and update you if the situation changes.";

export const impactContexts: Record<string, CustomerImpactContext> = {
  "overall-health": {
    id: "overall-health", title: "Overall service health", subtitle: "Rolled up across every service you consume",
    infrastructureStatus: "advisory", infrastructureNote: "One underlying Azure storage dependency in West US 2 is degraded.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "All six services you subscribe to are serving traffic normally. One cloud provider dependency behind a single region is running slower than usual, but your service is absorbing it without a change to your experience.",
    affected: [{ label: "6 subscribed services", detail: "All responding within agreed targets", status: "healthy" }],
    signals: [
      { label: "Successful requests", value: "99.997%", interpretation: "Effectively every request your users made succeeded.", status: "healthy" },
      { label: "Response time (p95)", value: "218 ms", interpretation: "In line with the last 30-day average of 214 ms.", status: "healthy" },
      { label: "Failed customer journeys", value: "0", interpretation: "No end-to-end business flow failed in the last 24 hours.", status: "healthy" },
    ],
    whatIsBeingDone: ["Continuous monitoring of all subscribed services", "Active tracking of the West US 2 storage advisory", "Automated failover paths verified and standing by"],
    customerAction: noAction, noActionRequired: true,
    timeline: [
      { stage: "Detected", at: "08:41 AM PT", note: "Latency deviation observed on a provider dependency." },
      { stage: "Validated", at: "08:47 AM PT", note: "Confirmed no measurable effect on your services." },
      { stage: "Latest observation", at: "12s ago", note: "All customer-facing indicators normal." },
      { stage: "Next update", at: "10:00 AM PT", note: "Or immediately if customer impact begins.", pending: true },
    ],
    technical: [
      { label: "Evaluation window", value: "Rolling 24 hours, 1-minute resolution" },
      { label: "Health model", value: "Composite of availability, latency and journey success" },
      { label: "Regions in scope", value: "East US, West US 2, Central US, North Europe" },
    ],
  },
  services: {
    id: "services", title: "Subscribed services", subtitle: "6 of 6 services healthy",
    infrastructureStatus: "healthy", infrastructureNote: "All service control planes reporting healthy.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Every service included in your subscription is available and meeting its performance targets.",
    affected: [
      { label: "Orchestration API", detail: "Healthy · 99.999% (24h)", status: "healthy" },
      { label: "Event Processing", detail: "Healthy · 99.998% (24h)", status: "healthy" },
      { label: "Document Store", detail: "Healthy · slightly elevated write latency in West US 2", status: "healthy" },
      { label: "Identity Gateway", detail: "Healthy · 99.999% (24h)", status: "healthy" },
      { label: "Reporting", detail: "Healthy · 99.996% (24h)", status: "healthy" },
      { label: "Notification Delivery", detail: "Healthy · 99.997% (24h)", status: "healthy" },
    ],
    signals: [
      { label: "Service checks passing", value: "348 / 348", interpretation: "Every synthetic check we run on your behalf succeeded.", status: "healthy" },
      { label: "Slowest service", value: "Document Store · 264 ms", interpretation: "Within its 400 ms target despite the storage advisory.", status: "healthy" },
    ],
    whatIsBeingDone: ["Synthetic checks run every 60 seconds per service per region", "Document Store write path watched more closely while the advisory is open"],
    customerAction: noAction, noActionRequired: true,
    timeline: [
      { stage: "Latest observation", at: "1m ago", note: "All service checks passing." },
      { stage: "Next update", at: "Continuous", note: "This view refreshes automatically.", pending: true },
    ],
    technical: [{ label: "Check cadence", value: "60s synthetic, 15s passive" }, { label: "Coverage", value: "4 regions × 6 services" }],
  },
  deployments: {
    id: "deployments", title: "Your deployments", subtitle: "8 deployments across 3 regions",
    infrastructureStatus: "advisory", infrastructureNote: "West US 2 hosts run on storage that is currently degraded at the provider.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "You have eight deployments. Seven are fully healthy; one in West US 2 is flagged because of a provider storage advisory, but it is still serving traffic within target.",
    affected: [
      { label: "Production – West US 2", detail: "Advisory · 99.982% availability (24h)", status: "degraded" },
      { label: "7 other deployments", detail: "Healthy across East US, Central US and North Europe", status: "healthy" },
    ],
    signals: [
      { label: "Nodes in service", value: "39 / 39", interpretation: "No capacity has been lost.", status: "healthy" },
      { label: "Failover readiness", value: "Verified", interpretation: "Central US DR can take West US 2 traffic within 4 minutes.", status: "healthy" },
    ],
    whatIsBeingDone: ["Watching the West US 2 write path", "DR capacity pre-warmed in Central US"],
    customerAction: noAction, noActionRequired: true,
    timeline: [
      { stage: "Detected", at: "08:41 AM PT", note: "Advisory raised against West US 2." },
      { stage: "Action initiated", at: "08:52 AM PT", note: "DR capacity pre-warmed as a precaution." },
      { stage: "Next update", at: "10:00 AM PT", note: "Advisory review.", pending: true },
    ],
    technical: [{ label: "Node distribution", value: "12 East US · 8 West US 2 · 6 Central US · 9 North Europe · 4 staging" }],
  },
  "availability-24h": {
    id: "availability-24h", title: "Availability (24 hours)", subtitle: "99.997% against a 99.99% commitment",
    infrastructureStatus: "healthy", infrastructureNote: "No availability-affecting infrastructure condition in the window.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Over the last 24 hours your services were available 99.997% of the time, comfortably above the 99.99% we commit to in your agreement.",
    affected: [{ label: "All production deployments", detail: "Contributing to a single blended availability figure", status: "healthy" }],
    signals: [
      { label: "Unavailable minutes", value: "0.04 min", interpretation: "Roughly two and a half seconds of degraded serving across the day.", status: "healthy" },
      { label: "Headroom to commitment", value: "+0.007%", interpretation: "You are above the contractual floor.", status: "healthy" },
    ],
    whatIsBeingDone: ["Availability measured from the customer edge, not from inside our platform"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "12s ago", note: "Availability steady at 99.997%." }],
    technical: [
      { label: "Measurement point", value: "Customer edge (synthetic + real user)" },
      { label: "Exclusions", value: "Approved maintenance windows are excluded per contract" },
    ],
  },
  "azure-dependencies": {
    id: "azure-dependencies", title: "Azure dependencies", subtitle: "17 of 18 dependencies healthy",
    infrastructureStatus: "degraded", infrastructureNote: "Azure Blob Storage in West US 2 is degraded at the provider.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Your service is built on 18 Azure platform dependencies. One of them — Blob Storage in West US 2 — is currently degraded. Our platform is designed to tolerate this, and your experience is unchanged.",
    affected: [
      { label: "Azure Blob Storage (West US 2)", detail: "Degraded at provider · absorbed by write buffering", status: "degraded" },
      { label: "17 other dependencies", detail: "Healthy", status: "healthy" },
    ],
    signals: [
      { label: "Dependency error rate", value: "0.6%", interpretation: "Failed storage calls are retried transparently; none reached your users.", status: "advisory" },
      { label: "Retry success", value: "100%", interpretation: "Every retried operation eventually succeeded.", status: "healthy" },
    ],
    whatIsBeingDone: ["Microsoft support case AZ-80456 open and being tracked", "Write buffering enabled to shield your workloads"],
    customerAction: noAction, noActionRequired: true,
    timeline: [
      { stage: "Detected", at: "08:41 AM PT", note: "Provider latency deviation detected." },
      { stage: "Provider contacted", at: "08:55 AM PT", note: "Microsoft case AZ-80456 raised at Sev-B." },
      { stage: "Next update", at: "10:00 AM PT", note: "Provider committed update.", pending: true },
    ],
    technical: [
      { label: "Provider reference", value: "AZ-80456" },
      { label: "Mitigation", value: "Client-side write buffering with exponential retry" },
    ],
  },
  "dep-east": {
    id: "dep-east", title: "Production – East US", subtitle: "12 nodes · Customer Production",
    infrastructureStatus: "healthy", infrastructureNote: "All hosts and platform dependencies healthy in East US.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Your primary East US deployment is fully healthy and carrying the majority of your traffic.",
    affected: [{ label: "East US production workloads", detail: "12 nodes, all in service", status: "healthy" }],
    signals: [
      { label: "Availability (24h)", value: "99.999%", interpretation: "Above your commitment.", status: "healthy" },
      { label: "Request latency (p95)", value: "196 ms", interpretation: "Faster than the 30-day average.", status: "healthy" },
      { label: "Saturation", value: "48%", interpretation: "Ample headroom for peak traffic.", status: "healthy" },
    ],
    whatIsBeingDone: ["Routine automated health verification every 60 seconds"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "30s ago", note: "All 12 nodes healthy." }],
    technical: [{ label: "Availability zones", value: "3 (zone-redundant)" }, { label: "Node SKU", value: "Standard_D8s_v5" }],
  },
  "dep-west": {
    id: "dep-west", title: "Production – West US 2", subtitle: "8 nodes · Customer Production",
    infrastructureStatus: "degraded", infrastructureNote: "Underlying Azure Blob Storage in this region is degraded.",
    impact: "POTENTIAL IMPACT",
    whatIsHappening: "The Azure storage that this deployment writes to is responding more slowly than normal. Your deployment is compensating by buffering writes, so users are not currently seeing errors — but if the provider condition worsens, write-heavy operations could slow down.",
    affected: [
      { label: "Production – West US 2", detail: "Serving traffic · elevated write latency", status: "degraded" },
      { label: "Document Store (West US 2)", detail: "Write path buffered", status: "advisory" },
      { label: "Read operations", detail: "Unaffected", status: "healthy" },
    ],
    signals: [
      { label: "Write latency (p95)", value: "612 ms", interpretation: "Around 3× the normal 190 ms, still under the 1s user-visible threshold.", status: "degraded" },
      { label: "Write errors reaching users", value: "0", interpretation: "Every slow write eventually succeeded.", status: "healthy" },
      { label: "Availability (24h)", value: "99.982%", interpretation: "Slightly below the fleet average but above your commitment.", status: "advisory" },
    ],
    whatIsBeingDone: [
      "Write buffering active to shield your users from provider latency",
      "Microsoft case AZ-80456 open at Sev-B",
      "Central US DR pre-warmed and ready to take traffic within 4 minutes",
      "Automatic regional shift armed if write latency exceeds 1 second sustained",
    ],
    customerAction: "No action required. If you run large batch write jobs today, consider scheduling them after the advisory closes.",
    noActionRequired: false,
    timeline: [
      { stage: "Detected", at: "08:41 AM PT", note: "Write latency deviation on the West US 2 storage path." },
      { stage: "Validated", at: "08:47 AM PT", note: "Confirmed provider-side, not caused by your workload." },
      { stage: "Action initiated", at: "08:52 AM PT", note: "Write buffering enabled, DR pre-warmed." },
      { stage: "Provider contacted", at: "08:55 AM PT", note: "Microsoft case AZ-80456 raised." },
      { stage: "Latest observation", at: "5m ago", note: "Latency stable, no user-visible errors." },
      { stage: "Next update", at: "10:00 AM PT", note: "Joint review with Microsoft.", pending: true },
    ],
    technical: [
      { label: "Storage account", value: "nwlprodwestus2 (GPv2, ZRS)" },
      { label: "Buffer depth", value: "2,140 operations (12% of capacity)" },
      { label: "Failover trigger", value: "p95 write latency > 1000 ms for 5 minutes" },
    ],
  },
  "dep-dr": {
    id: "dep-dr", title: "DR – Central US", subtitle: "6 nodes · Customer DR",
    infrastructureStatus: "healthy", infrastructureNote: "Standby capacity healthy and pre-warmed.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Your disaster recovery environment is healthy and has been pre-warmed as a precaution while the West US 2 advisory is open.",
    affected: [{ label: "Central US DR capacity", detail: "6 nodes, warm standby", status: "healthy" }],
    signals: [
      { label: "Replication lag", value: "1.8s", interpretation: "Well inside your 30 second recovery point objective.", status: "healthy" },
      { label: "Failover rehearsal", value: "Passed 6 days ago", interpretation: "Recovery time measured at 3m 42s.", status: "healthy" },
    ],
    whatIsBeingDone: ["DR capacity pre-warmed while the West US 2 advisory is open"],
    customerAction: noAction, noActionRequired: true,
    timeline: [
      { stage: "Action initiated", at: "08:52 AM PT", note: "Pre-warmed as a precaution." },
      { stage: "Latest observation", at: "2m ago", note: "Replication healthy." },
    ],
    technical: [{ label: "RPO / RTO", value: "30s / 15m contractual" }, { label: "Mode", value: "Warm standby, continuous replication" }],
  },
  "dep-eu": {
    id: "dep-eu", title: "Production – North Europe", subtitle: "9 nodes · Customer Production",
    infrastructureStatus: "healthy", infrastructureNote: "All dependencies healthy in North Europe.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Your European production deployment is healthy and unaffected by the North American storage advisory.",
    affected: [{ label: "North Europe workloads", detail: "9 nodes in service", status: "healthy" }],
    signals: [{ label: "Availability (24h)", value: "99.996%", interpretation: "Above commitment.", status: "healthy" }],
    whatIsBeingDone: ["Routine monitoring"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "40s ago", note: "All nodes healthy." }],
    technical: [{ label: "Data residency", value: "EU data stays in North Europe" }],
  },
  "dep-stg": {
    id: "dep-stg", title: "Staging – East US", subtitle: "4 nodes · Non-production",
    infrastructureStatus: "healthy", infrastructureNote: "Non-production environment, healthy.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Your staging environment is healthy. Non-production environments are excluded from your availability commitment.",
    affected: [{ label: "Staging workloads", detail: "4 nodes in service", status: "healthy" }],
    signals: [{ label: "Availability (24h)", value: "99.940%", interpretation: "Normal for a non-production tier.", status: "healthy" }],
    whatIsBeingDone: ["Best-effort monitoring"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "3m ago", note: "Environment healthy." }],
    technical: [{ label: "Tier", value: "Non-production, no SLA" }],
  },
  "layer-your-service": {
    id: "layer-your-service", title: "Your Service", subtitle: "Your deployments and user experience",
    infrastructureStatus: "healthy", infrastructureNote: "This layer represents what your users actually experience.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "This is the layer your users touch. Everything below it exists to support it. Right now it is healthy.",
    affected: [{ label: "All customer-facing endpoints", detail: "Serving normally", status: "healthy" }],
    signals: [
      { label: "User-visible errors", value: "0.003%", interpretation: "Three requests in every hundred thousand failed and were retried.", status: "healthy" },
      { label: "Journey success", value: "100%", interpretation: "Every monitored business flow completed.", status: "healthy" },
    ],
    whatIsBeingDone: ["Real user monitoring plus synthetic journeys across all regions"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "12s ago", note: "No user-visible degradation." }],
    technical: [{ label: "Signals", value: "RUM, synthetic journeys, edge availability" }],
  },
  "layer-service": {
    id: "layer-service", title: "Service Layer", subtitle: "Service control and orchestration",
    infrastructureStatus: "healthy", infrastructureNote: "Control plane healthy in all regions.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "The control layer that schedules and orchestrates your workloads is healthy.",
    affected: [{ label: "Orchestration control plane", detail: "Healthy in 4 regions", status: "healthy" }],
    signals: [{ label: "Scheduling latency", value: "84 ms", interpretation: "Normal.", status: "healthy" }],
    whatIsBeingDone: ["Routine monitoring"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "1m ago", note: "Control plane healthy." }],
    technical: [{ label: "Quorum", value: "5/5 control nodes healthy" }],
  },
  "layer-compute": {
    id: "layer-compute", title: "Compute", subtitle: "Virtual machines and host infrastructure",
    infrastructureStatus: "healthy", infrastructureNote: "All hosts healthy across zones.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "The virtual machines running your workloads are healthy, with no host-level faults.",
    affected: [{ label: "39 production nodes", detail: "All in service", status: "healthy" }],
    signals: [
      { label: "Host faults (24h)", value: "0", interpretation: "No hardware or host restarts affected you.", status: "healthy" },
      { label: "CPU saturation", value: "51%", interpretation: "Healthy headroom for peak load.", status: "healthy" },
    ],
    whatIsBeingDone: ["Predictive host health scoring with pre-emptive workload migration"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "45s ago", note: "No host degradation." }],
    technical: [{ label: "Placement", value: "Zone-redundant across 3 availability zones" }],
  },
  "layer-storage": {
    id: "layer-storage", title: "Storage", subtitle: "Storage accounts and blob services",
    infrastructureStatus: "degraded", infrastructureNote: "Azure Blob Storage in West US 2 is degraded at the provider.",
    impact: "POTENTIAL IMPACT",
    whatIsHappening: "The storage platform behind one of your regions is slower than normal. This is a provider condition. Your service is compensating, and no user-visible failures have occurred.",
    affected: [
      { label: "Production – West US 2", detail: "Write path buffered", status: "degraded" },
      { label: "All other regions", detail: "Storage healthy", status: "healthy" },
    ],
    signals: [
      { label: "Write latency (p95)", value: "612 ms", interpretation: "Around 3× normal in West US 2 only.", status: "degraded" },
      { label: "Data integrity", value: "Verified", interpretation: "No data loss or corruption; durability is unaffected.", status: "healthy" },
    ],
    whatIsBeingDone: ["Write buffering active", "Microsoft case AZ-80456 open", "Automatic regional shift armed"],
    customerAction: "No action required. Consider deferring large batch writes in West US 2 until the advisory closes.",
    noActionRequired: false,
    timeline: [
      { stage: "Detected", at: "08:41 AM PT", note: "Storage latency deviation." },
      { stage: "Provider contacted", at: "08:55 AM PT", note: "Microsoft case AZ-80456." },
      { stage: "Next update", at: "10:00 AM PT", note: "Provider update expected.", pending: true },
    ],
    technical: [{ label: "Redundancy", value: "Zone-redundant storage (ZRS)" }, { label: "Affected scope", value: "West US 2 blob endpoints only" }],
  },
  "layer-network": {
    id: "layer-network", title: "Network", subtitle: "Virtual network and connectivity",
    infrastructureStatus: "healthy", infrastructureNote: "All network paths healthy.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Connectivity between your users, your deployments and their dependencies is healthy.",
    affected: [{ label: "All ingress and inter-region paths", detail: "Healthy", status: "healthy" }],
    signals: [
      { label: "Packet loss", value: "0.00%", interpretation: "No measurable loss on monitored paths.", status: "healthy" },
      { label: "Inter-region latency", value: "58 ms", interpretation: "Normal East US ↔ Central US round trip.", status: "healthy" },
    ],
    whatIsBeingDone: ["Continuous path probing between all regions"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "20s ago", note: "All paths healthy." }],
    technical: [{ label: "Peering", value: "Microsoft backbone, dual-homed" }],
  },
  "layer-azure-services": {
    id: "layer-azure-services", title: "Azure Services", subtitle: "Platform services and dependencies",
    infrastructureStatus: "degraded", infrastructureNote: "One of 18 platform dependencies is degraded.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "One Azure platform service your deployment relies on is degraded. This is an infrastructure condition only — your service is designed to tolerate it and your users are unaffected.",
    affected: [{ label: "Azure Blob Storage – West US 2", detail: "Degraded at provider", status: "degraded" }],
    signals: [{ label: "Dependencies healthy", value: "17 / 18", interpretation: "Only the West US 2 blob endpoint is affected.", status: "advisory" }],
    whatIsBeingDone: ["Provider case open", "Mitigation active in the affected region"],
    customerAction: noAction, noActionRequired: true,
    timeline: [
      { stage: "Detected", at: "08:41 AM PT", note: "Provider service degradation." },
      { stage: "Next update", at: "10:00 AM PT", note: "Provider update.", pending: true },
    ],
    technical: [{ label: "Dependency inventory", value: "18 tracked Azure services across 4 regions" }],
  },
  "layer-azure-region": {
    id: "layer-azure-region", title: "Azure Region – West US 2", subtitle: "Region experiencing issues",
    infrastructureStatus: "at-risk", infrastructureNote: "Microsoft has an active advisory for this region.",
    impact: "POTENTIAL IMPACT",
    whatIsHappening: "Microsoft has an open advisory for the West US 2 region. One of your production deployments runs there. Your service is currently unaffected, but a wider regional issue could change that.",
    affected: [{ label: "Production – West US 2", detail: "8 nodes in the affected region", status: "degraded" }],
    signals: [
      { label: "Regional services affected", value: "1", interpretation: "Only blob storage so far, not compute or network.", status: "advisory" },
      { label: "Your traffic in region", value: "22%", interpretation: "Most of your traffic is served from other regions.", status: "healthy" },
    ],
    whatIsBeingDone: ["Tracking the Microsoft regional advisory", "DR standing by in Central US", "Automatic regional shift armed"],
    customerAction: "No action required. We will shift traffic automatically if the region deteriorates.",
    noActionRequired: false,
    timeline: [
      { stage: "Detected", at: "08:41 AM PT", note: "Regional advisory published by Microsoft." },
      { stage: "Provider contacted", at: "08:55 AM PT", note: "Case AZ-80456 linked to the regional advisory." },
      { stage: "Next update", at: "10:00 AM PT", note: "Regional advisory review.", pending: true },
    ],
    technical: [{ label: "Region", value: "West US 2 (Quincy, WA)" }, { label: "Advisory", value: "AZ-80456" }],
  },
  "evt-blob-latency": {
    id: "evt-blob-latency", title: "Elevated Azure Blob Storage Latency – West US 2", subtitle: "Advisory · started 08:41 AM PT",
    infrastructureStatus: "degraded", infrastructureNote: "Provider storage latency elevated in one region.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Microsoft's blob storage service in West US 2 is responding more slowly than usual. Our platform buffers and retries these operations, so your services remain available and no users have seen errors.",
    affected: [
      { label: "Production – West US 2", detail: "Write path buffered, no user-visible errors", status: "degraded" },
      { label: "Document Store service", detail: "Elevated write latency, within target", status: "advisory" },
    ],
    signals: [
      { label: "Storage p95 latency", value: "612 ms", interpretation: "Elevated from a 190 ms baseline.", status: "degraded" },
      { label: "Requests failed to users", value: "0", interpretation: "Nothing reached your users as an error.", status: "healthy" },
      { label: "Retry volume", value: "2,140", interpretation: "Operations retried transparently in the last hour.", status: "advisory" },
    ],
    whatIsBeingDone: [
      "Microsoft support case AZ-80456 open at Sev-B",
      "Write buffering and transparent retry active",
      "DR capacity pre-warmed in Central US",
      "Engineers monitoring continuously until the advisory closes",
    ],
    customerAction: noAction, noActionRequired: true,
    timeline: [
      { stage: "Detected", at: "08:41 AM PT", note: "Automated detection of storage latency deviation." },
      { stage: "Validated", at: "08:47 AM PT", note: "Confirmed as a provider condition affecting West US 2." },
      { stage: "Action initiated", at: "08:52 AM PT", note: "Buffering enabled and DR pre-warmed." },
      { stage: "Provider contacted", at: "08:55 AM PT", note: "Microsoft case AZ-80456 raised." },
      { stage: "Latest observation", at: "5m ago", note: "Latency stable, no customer impact." },
      { stage: "Next update", at: "10:00 AM PT", note: "Or sooner if impact begins.", pending: true },
    ],
    technical: [
      { label: "Microsoft reference", value: "AZ-80456" },
      { label: "Affected endpoints", value: "*.blob.core.windows.net (West US 2)" },
      { label: "Mitigation", value: "Client-side buffering, exponential retry, armed regional shift" },
    ],
  },
  "evt-net-jitter": {
    id: "evt-net-jitter", title: "Transient network jitter – Central US peering", subtitle: "Information · resolved",
    infrastructureStatus: "healthy", infrastructureNote: "Condition resolved; path restored.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "A brief period of packet re-transmission occurred on one network path serving Central US last night. Traffic was automatically re-routed and the condition resolved in under an hour.",
    affected: [{ label: "DR – Central US", detail: "Replication briefly slower, no data at risk", status: "healthy" }],
    signals: [
      { label: "Peak packet loss", value: "0.4%", interpretation: "Brief and fully absorbed by retransmission.", status: "advisory" },
      { label: "Replication lag peak", value: "9s", interpretation: "Still inside your 30 second recovery objective.", status: "healthy" },
    ],
    whatIsBeingDone: ["Condition resolved; path monitored for recurrence"],
    customerAction: noAction, noActionRequired: true,
    timeline: [
      { stage: "Detected", at: "21:12 PT", note: "Packet loss on a peering path." },
      { stage: "Action initiated", at: "21:14 PT", note: "Automatic traffic steering to an alternate path." },
      { stage: "Latest observation", at: "22:04 PT", note: "Path fully restored, event closed." },
    ],
    technical: [{ label: "Provider reference", value: "AZ-79912" }, { label: "Resolution", value: "Automatic path re-route" }],
  },
  "evt-cert-rotation": {
    id: "evt-cert-rotation", title: "Scheduled certificate rotation", subtitle: "Maintenance · Jun 7, 10:00 PT",
    infrastructureStatus: "healthy", infrastructureNote: "Planned change, staged rollout.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "We rotate the TLS certificates on your orchestration endpoints on a routine schedule. Connections are drained gracefully so no requests are dropped.",
    affected: [{ label: "All production endpoints", detail: "Rolling rotation, one region at a time", status: "healthy" }],
    signals: [{ label: "Expected downtime", value: "None", interpretation: "Graceful connection draining prevents dropped requests.", status: "healthy" }],
    whatIsBeingDone: ["Change approved through governance", "Staged region-by-region rollout with automatic rollback"],
    customerAction: "No action required unless you pin certificates. If you do, refresh your trust store after the window.",
    noActionRequired: false,
    timeline: [
      { stage: "Validated", at: "Jun 3", note: "Change approved by governance board." },
      { stage: "Next update", at: "Jun 7, 11:00 PT", note: "Completion confirmation.", pending: true },
    ],
    technical: [{ label: "Change reference", value: "CHG-24188" }, { label: "Rollback", value: "Automatic on health regression" }],
  },
  "region-east": {
    id: "region-east", title: "East US", subtitle: "Primary production region",
    infrastructureStatus: "healthy", infrastructureNote: "All Azure services healthy in East US.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "East US is healthy and carries the largest share of your traffic.",
    affected: [{ label: "Production – East US, Staging – East US", detail: "16 nodes total", status: "healthy" }],
    signals: [{ label: "Share of your traffic", value: "46%", interpretation: "Your busiest region.", status: "healthy" }],
    whatIsBeingDone: ["Routine monitoring"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "30s ago", note: "Region healthy." }],
    technical: [{ label: "Availability zones", value: "3" }],
  },
  "region-central": {
    id: "region-central", title: "Central US", subtitle: "Disaster recovery region",
    infrastructureStatus: "healthy", infrastructureNote: "Region healthy.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Central US hosts your warm standby environment. It is healthy and pre-warmed.",
    affected: [{ label: "DR – Central US", detail: "6 nodes, warm standby", status: "healthy" }],
    signals: [{ label: "Replication lag", value: "1.8s", interpretation: "Inside your recovery point objective.", status: "healthy" }],
    whatIsBeingDone: ["DR pre-warmed while the West US 2 advisory is open"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "2m ago", note: "Standby healthy." }],
    technical: [{ label: "Mode", value: "Warm standby" }],
  },
  "region-west": {
    id: "region-west", title: "West US 2", subtitle: "Production region with an open advisory",
    infrastructureStatus: "degraded", infrastructureNote: "Provider storage degradation active in this region.",
    impact: "POTENTIAL IMPACT",
    whatIsHappening: "West US 2 has an open provider advisory affecting storage. Your deployment there is still serving traffic normally, but this is the one region we are watching closely.",
    affected: [{ label: "Production – West US 2", detail: "8 nodes · 22% of your traffic", status: "degraded" }],
    signals: [
      { label: "Availability (24h)", value: "99.982%", interpretation: "Above commitment, below fleet average.", status: "advisory" },
      { label: "Write latency (p95)", value: "612 ms", interpretation: "Elevated but under the user-visible threshold.", status: "degraded" },
    ],
    whatIsBeingDone: ["Provider case AZ-80456 open", "Automatic regional shift armed", "DR pre-warmed"],
    customerAction: "No action required. Traffic will shift automatically if the region deteriorates.",
    noActionRequired: false,
    timeline: [
      { stage: "Detected", at: "08:41 AM PT", note: "Regional storage advisory." },
      { stage: "Provider contacted", at: "08:55 AM PT", note: "Case AZ-80456." },
      { stage: "Next update", at: "10:00 AM PT", note: "Regional review.", pending: true },
    ],
    technical: [{ label: "Region", value: "West US 2 (Quincy, WA)" }],
  },
  "region-eu": {
    id: "region-eu", title: "North Europe", subtitle: "European production region",
    infrastructureStatus: "healthy", infrastructureNote: "Region healthy.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "North Europe is healthy and serving your European users with data residency maintained in-region.",
    affected: [{ label: "Production – North Europe", detail: "9 nodes", status: "healthy" }],
    signals: [{ label: "Share of your traffic", value: "26%", interpretation: "Steady week over week.", status: "healthy" }],
    whatIsBeingDone: ["Routine monitoring"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "40s ago", note: "Region healthy." }],
    technical: [{ label: "Data residency", value: "EU only" }],
  },
  "region-sea": {
    id: "region-sea", title: "Southeast Asia", subtitle: "No deployments",
    infrastructureStatus: "healthy", infrastructureNote: "Region healthy; you have no footprint here.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "You have no deployments in this region. It is shown for completeness because a small amount of your read traffic is served from the nearby edge.",
    affected: [{ label: "Edge read traffic", detail: "Cached responses only", status: "healthy" }],
    signals: [{ label: "Edge cache hit rate", value: "94%", interpretation: "Most Asian reads never leave the edge.", status: "healthy" }],
    whatIsBeingDone: ["Edge health monitoring"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "1m ago", note: "Edge healthy." }],
    technical: [{ label: "Footprint", value: "Edge only" }],
  },
  "slo-availability": {
    id: "slo-availability", title: "Availability SLO", subtitle: "Target 99.99% · current 99.997%",
    infrastructureStatus: "healthy", infrastructureNote: "No availability-affecting condition in the measurement window.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Your availability objective is being met with 93.4% of the monthly error budget still unspent.",
    affected: [{ label: "All production deployments", detail: "Blended into one objective", status: "healthy" }],
    signals: [
      { label: "Error budget remaining", value: "93.4%", interpretation: "You could absorb around 40 minutes more downtime this month and still meet the objective.", status: "healthy" },
      { label: "Burn rate", value: "0.4×", interpretation: "Consuming budget slower than the pace that would breach it.", status: "healthy" },
    ],
    whatIsBeingDone: ["Error budget tracked continuously and reported monthly"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "12s ago", note: "Objective met." }],
    technical: [{ label: "Window", value: "Calendar month, rolling display" }, { label: "Measurement", value: "Edge availability, maintenance excluded" }],
  },
  "slo-latency": {
    id: "slo-latency", title: "Latency SLO", subtitle: "Target 99.5% of requests under 500 ms",
    infrastructureStatus: "advisory", infrastructureNote: "West US 2 writes are elevated but within objective.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "99.7% of your requests completed under the 500 ms threshold, above the 99.5% objective — even with the West US 2 storage advisory in play.",
    affected: [{ label: "Write requests in West US 2", detail: "Slower, but still under threshold", status: "advisory" }],
    signals: [
      { label: "Requests under 500 ms", value: "99.7%", interpretation: "Objective met.", status: "healthy" },
      { label: "Error budget remaining", value: "78.2%", interpretation: "Some budget consumed by the advisory.", status: "advisory" },
    ],
    whatIsBeingDone: ["Latency budget monitored while the storage advisory is open"],
    customerAction: noAction, noActionRequired: true,
    timeline: [
      { stage: "Latest observation", at: "1m ago", note: "Objective met at 99.7%." },
      { stage: "Next update", at: "10:00 AM PT", note: "Re-check after advisory review.", pending: true },
    ],
    technical: [{ label: "Threshold", value: "500 ms end-to-end at the edge" }],
  },
  "slo-reliability": {
    id: "slo-reliability", title: "Reliability SLO", subtitle: "Target 99.98% successful operations",
    infrastructureStatus: "healthy", infrastructureNote: "No reliability-affecting condition.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "99.986% of operations succeeded, above your 99.98% objective.",
    affected: [{ label: "All customer operations", detail: "Across every region", status: "healthy" }],
    signals: [{ label: "Error budget remaining", value: "88.1%", interpretation: "Comfortable headroom for the rest of the month.", status: "healthy" }],
    whatIsBeingDone: ["Continuous measurement"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "1m ago", note: "Objective met." }],
    technical: [{ label: "Definition", value: "Non-5xx, non-timeout completions" }],
  },
  "slo-durability": {
    id: "slo-durability", title: "Durability SLO", subtitle: "Target 99.999% durability",
    infrastructureStatus: "healthy", infrastructureNote: "Storage latency does not affect durability.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "No data loss has occurred. The storage advisory affects how quickly writes complete, not whether your data is safe.",
    affected: [{ label: "All stored customer data", detail: "Zone-redundant, integrity verified", status: "healthy" }],
    signals: [
      { label: "Integrity checks", value: "Passed", interpretation: "Every scheduled verification succeeded.", status: "healthy" },
      { label: "Objects lost", value: "0", interpretation: "No data loss since service inception.", status: "healthy" },
    ],
    whatIsBeingDone: ["Continuous checksum verification and cross-zone replication"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "6m ago", note: "Integrity verification passed." }],
    technical: [{ label: "Replication", value: "3 synchronous copies (ZRS) + async DR copy" }],
  },
  "risk-overall": {
    id: "risk-overall", title: "Overall Risk", subtitle: "Predictive risk across your environment",
    infrastructureStatus: "healthy", infrastructureNote: "No compounding conditions detected.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Our predictive model, which looks at historical patterns and current signals, sees a low likelihood of your services being impacted in the next 24 hours.",
    affected: [{ label: "Your environment", detail: "Low composite risk", status: "healthy" }],
    signals: [{ label: "Predicted impact probability", value: "4%", interpretation: "Low chance of customer-visible degradation in the next day.", status: "healthy" }],
    whatIsBeingDone: ["Risk model re-scored every 15 minutes"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "8m ago", note: "Risk score steady at low." }],
    technical: [{ label: "Model inputs", value: "Dependency health, change volume, saturation, historical incident correlation" }],
  },
  "risk-storage": {
    id: "risk-storage", title: "Storage Risk – Elevated", subtitle: "Driven by the open West US 2 advisory",
    infrastructureStatus: "degraded", infrastructureNote: "Provider storage degradation raises the probability of impact.",
    impact: "POTENTIAL IMPACT",
    whatIsHappening: "Because a provider storage dependency is degraded, the model rates the chance of a storage-related customer impact as elevated. Nothing has affected your users so far.",
    affected: [{ label: "Production – West US 2", detail: "The only deployment exposed", status: "degraded" }],
    signals: [
      { label: "Predicted impact probability", value: "23%", interpretation: "Roughly a one-in-four chance of user-visible slowness if the advisory persists into peak hours.", status: "advisory" },
      { label: "Mitigation coverage", value: "High", interpretation: "Buffering plus armed failover reduce the practical risk.", status: "healthy" },
    ],
    whatIsBeingDone: ["Automatic regional shift armed", "DR pre-warmed", "Provider case escalated"],
    customerAction: "No action required. Consider deferring large batch writes in West US 2 until the advisory closes.",
    noActionRequired: false,
    timeline: [
      { stage: "Detected", at: "08:41 AM PT", note: "Risk score moved from low to elevated." },
      { stage: "Action initiated", at: "08:52 AM PT", note: "Mitigations applied, reducing effective risk." },
      { stage: "Next update", at: "10:00 AM PT", note: "Risk re-scored after provider update.", pending: true },
    ],
    technical: [{ label: "Score", value: "68 / 100 (elevated band 60–79)" }],
  },
  "risk-compute": {
    id: "risk-compute", title: "Compute Risk", subtitle: "Low",
    infrastructureStatus: "healthy", infrastructureNote: "No host degradation or capacity pressure.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Compute capacity and host health show no signs of emerging trouble.",
    affected: [{ label: "39 production nodes", detail: "Healthy", status: "healthy" }],
    signals: [{ label: "Capacity headroom", value: "49%", interpretation: "You can absorb a large traffic spike.", status: "healthy" }],
    whatIsBeingDone: ["Predictive host scoring"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "8m ago", note: "Risk low." }],
    technical: [{ label: "Score", value: "18 / 100" }],
  },
  "risk-network": {
    id: "risk-network", title: "Network Risk", subtitle: "Low",
    infrastructureStatus: "healthy", infrastructureNote: "All paths stable.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Network paths serving your deployments are stable with no loss or congestion trend.",
    affected: [{ label: "All monitored paths", detail: "Stable", status: "healthy" }],
    signals: [{ label: "Path stability", value: "100%", interpretation: "No re-routes in the last 24 hours.", status: "healthy" }],
    whatIsBeingDone: ["Continuous path probing"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "8m ago", note: "Risk low." }],
    technical: [{ label: "Score", value: "15 / 100" }],
  },
  "chg-azure-westus2": {
    id: "chg-azure-westus2", title: "Azure Maintenance – West US 2", subtitle: "Jun 6, 02:00 – 06:00 AM PT",
    infrastructureStatus: "info", infrastructureNote: "Provider maintenance on host infrastructure.",
    impact: "POTENTIAL IMPACT",
    whatIsHappening: "Microsoft will perform host maintenance in West US 2. Nodes are updated in waves with live migration, so your deployment stays available — but brief connection resets are possible.",
    affected: [{ label: "Production – West US 2", detail: "8 nodes updated in 2 waves", status: "advisory" }],
    signals: [{ label: "Expected user impact", value: "Low", interpretation: "Possible brief connection resets handled by client retry.", status: "advisory" }],
    whatIsBeingDone: ["Maintenance window reviewed against your traffic profile", "Capacity added in East US for the window"],
    customerAction: "No action required if your clients retry on connection reset, which is our documented default.",
    noActionRequired: false,
    timeline: [
      { stage: "Validated", at: "Jun 1", note: "Maintenance notice received and assessed." },
      { stage: "Action initiated", at: "Jun 5", note: "Extra East US capacity scheduled." },
      { stage: "Next update", at: "Jun 6, 06:00 PT", note: "Completion confirmation.", pending: true },
    ],
    technical: [{ label: "Provider reference", value: "AZ-MT-55210" }, { label: "Method", value: "Live migration, wave-based" }],
  },
  "chg-platform-update": {
    id: "chg-platform-update", title: "Platform Update – Orchestration Service", subtitle: "Jun 7, 10:00 – 11:00 AM PT",
    infrastructureStatus: "info", infrastructureNote: "Rolling platform release.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "We are releasing a routine platform update to the orchestration service. It rolls out region by region with automatic rollback on any health regression.",
    affected: [{ label: "All production deployments", detail: "Rolling, one region at a time", status: "healthy" }],
    signals: [{ label: "Expected downtime", value: "None", interpretation: "Traffic is drained from each node before it updates.", status: "healthy" }],
    whatIsBeingDone: ["Staged rollout with health gates", "Automatic rollback armed"],
    customerAction: noAction, noActionRequired: true,
    timeline: [
      { stage: "Validated", at: "Jun 3", note: "Change approved." },
      { stage: "Next update", at: "Jun 7, 11:00 PT", note: "Completion confirmation.", pending: true },
    ],
    technical: [{ label: "Change reference", value: "CHG-24188" }],
  },
  "chg-dr-verification": {
    id: "chg-dr-verification", title: "DR readiness verification – Central US", subtitle: "Jun 9, 01:00 – 03:00 AM PT",
    infrastructureStatus: "info", infrastructureNote: "Scheduled recovery rehearsal in the standby region.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "We will rehearse recovery into your Central US standby environment. Production traffic is not moved during the rehearsal.",
    affected: [{ label: "DR – Central US", detail: "Standby environment only", status: "healthy" }],
    signals: [{ label: "Production exposure", value: "None", interpretation: "Rehearsal runs against standby capacity only.", status: "healthy" }],
    whatIsBeingDone: ["Rehearsal scheduled outside your business hours", "Results published in your monthly report"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Next update", at: "Jun 9, 03:00 PT", note: "Rehearsal result.", pending: true }],
    technical: [{ label: "Last rehearsal", value: "Passed, recovery time 3m 42s" }],
  },
  "alert-incident": {
    id: "alert-incident", title: "Alert – Customer-impacting incident opened", subtitle: "Email + SMS · all deployments",
    infrastructureStatus: "healthy", infrastructureNote: "Notification rule, not a health condition.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "You are notified immediately whenever an event is classified as affecting your service, on every deployment you own.",
    affected: [{ label: "All deployments", detail: "In scope for this rule", status: "healthy" }],
    signals: [{ label: "Last fired", value: "42 days ago", interpretation: "Your last customer-impacting incident.", status: "healthy" }],
    whatIsBeingDone: ["Rule active and tested monthly"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "42 days ago", note: "Rule last triggered." }],
    technical: [{ label: "Delivery", value: "Email to 4 recipients, SMS to 2" }],
  },
  "alert-advisory": {
    id: "alert-advisory", title: "Alert – Advisory affecting my regions", subtitle: "Email · East US, West US 2, North Europe",
    infrastructureStatus: "advisory", infrastructureNote: "Fired today for the West US 2 storage advisory.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "This rule tells you when an advisory is raised in a region where you run, even if your service is unaffected.",
    affected: [{ label: "Production – West US 2", detail: "Triggered today at 08:41 PT", status: "advisory" }],
    signals: [{ label: "Notifications sent today", value: "1", interpretation: "The West US 2 storage advisory.", status: "advisory" }],
    whatIsBeingDone: ["Rule active"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "08:41 AM PT", note: "Notification delivered." }],
    technical: [{ label: "Delivery", value: "Email to 4 recipients" }],
  },
  "alert-error-budget": {
    id: "alert-error-budget", title: "Alert – Error budget below 25%", subtitle: "Email + Teams · Availability SLO",
    infrastructureStatus: "healthy", infrastructureNote: "Budget at 93.4%; rule not close to firing.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "You will be told if your availability error budget falls below a quarter, giving you time to react before an objective is at risk.",
    affected: [{ label: "Availability SLO", detail: "93.4% budget remaining", status: "healthy" }],
    signals: [{ label: "Distance to threshold", value: "68.4 points", interpretation: "Far from firing.", status: "healthy" }],
    whatIsBeingDone: ["Budget evaluated continuously"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "12s ago", note: "Budget at 93.4%." }],
    technical: [{ label: "Evaluation", value: "Every 5 minutes against the calendar month" }],
  },
  "alert-maintenance": {
    id: "alert-maintenance", title: "Alert – Planned maintenance in my regions", subtitle: "Disabled",
    infrastructureStatus: "info", infrastructureNote: "Rule currently disabled.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "This rule is turned off, so you are not notified about provider maintenance windows in your regions. Upcoming maintenance is still shown on this dashboard.",
    affected: [{ label: "Provider maintenance notices", detail: "Not delivered by email", status: "info" }],
    signals: [{ label: "Suppressed notices (30d)", value: "2", interpretation: "Both were low or no impact.", status: "healthy" }],
    whatIsBeingDone: ["Maintenance still surfaced in the Recent Changes panel"],
    customerAction: "Enable this rule if you want maintenance notices delivered by email.",
    noActionRequired: false,
    timeline: [{ stage: "Latest observation", at: "12 days ago", note: "Last time the rule fired before it was disabled." }],
    technical: [{ label: "State", value: "Disabled" }],
  },
  "report-monthly": {
    id: "report-monthly", title: "Monthly service health summary", subtitle: "May 2026 · PDF",
    infrastructureStatus: "info", infrastructureNote: "Reporting artefact.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "A month-end summary of availability, events and objective attainment for the services you consume.",
    affected: [{ label: "All subscribed services", detail: "Included in the report", status: "healthy" }],
    signals: [{ label: "May availability", value: "99.996%", interpretation: "Above commitment for the full month.", status: "healthy" }],
    whatIsBeingDone: ["Generated automatically on the first business day of each month"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "Jun 1", note: "May report published." }],
    technical: [{ label: "Retention", value: "36 months" }],
  },
  "report-slo": {
    id: "report-slo", title: "SLO attainment & error budget", subtitle: "Rolling 90 days · PDF + CSV",
    infrastructureStatus: "info", infrastructureNote: "Reporting artefact.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Attainment for each objective with error budget consumption and burn trend over the last 90 days.",
    affected: [{ label: "4 objectives", detail: "Availability, latency, reliability, durability", status: "healthy" }],
    signals: [{ label: "Objectives met (90d)", value: "4 / 4", interpretation: "No objective missed this quarter.", status: "healthy" }],
    whatIsBeingDone: ["Refreshed nightly"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "Today 02:00 PT", note: "Nightly refresh completed." }],
    technical: [{ label: "Formats", value: "PDF summary, CSV raw series" }],
  },
  "report-dependency": {
    id: "report-dependency", title: "Provider dependency exposure", subtitle: "Q2 2026 · PDF",
    infrastructureStatus: "info", infrastructureNote: "Reporting artefact.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "Shows where your deployments depend on cloud provider services, and what protects you when one of those dependencies degrades.",
    affected: [{ label: "18 tracked dependencies", detail: "Mapped to your deployments", status: "healthy" }],
    signals: [{ label: "Single points of exposure", value: "0", interpretation: "Every dependency has a documented mitigation.", status: "healthy" }],
    whatIsBeingDone: ["Reviewed quarterly with your service manager"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "Apr 8", note: "Q2 review completed." }],
    technical: [{ label: "Scope", value: "Azure platform services across 4 regions" }],
  },
  "report-events": {
    id: "report-events", title: "Incident & advisory register", subtitle: "YTD 2026 · CSV",
    infrastructureStatus: "info", infrastructureNote: "Reporting artefact.",
    impact: "NO CURRENT IMPACT",
    whatIsHappening: "A complete register of every event raised against your services this year, with impact classification and resolution detail.",
    affected: [{ label: "11 events YTD", detail: "1 incident, 7 advisories, 3 informational", status: "healthy" }],
    signals: [{ label: "Customer-impacting events", value: "1", interpretation: "Resolved in 38 minutes, 42 days ago.", status: "healthy" }],
    whatIsBeingDone: ["Register updated as events close"],
    customerAction: noAction, noActionRequired: true,
    timeline: [{ stage: "Latest observation", at: "Today", note: "Register current." }],
    technical: [{ label: "Format", value: "CSV, one row per event state change" }],
  },
};

export function getImpactContext(id: string): CustomerImpactContext {
  const base = impactContexts[id] ?? kpiContexts[id] ?? impactContexts["overall-health"];
  const overlay = kpiOverlays[base.id];
  const merged = overlay ? { ...base, ...overlay } : base;
  const deployment = deploymentDetails[base.id];
  return deployment ? { ...merged, deployment, title: deployment.headline } : merged;
}
