// Forward-looking risk. Risk is a PREDICTION, deliberately kept separate from
// current health: a service can be Healthy AND carry Elevated Risk at the same
// time. Nothing here asserts that an outage will occur — language stays in the
// space of potential, elevated probability, emerging condition and observed trend.

import type { RiskDetail, RiskSignal } from "./types";

export const riskSignals: RiskSignal[] = [
  {
    id: "risk-overall",
    label: "Overall Risk",
    level: "Low",
    status: "healthy",
    currentHealth: "healthy",
    currentHealthLabel: "Service healthy",
    trend: "Stable",
    trendNote: "Composite score flat over 12h",
    affectedDeployments: ["No deployment exposed"],
    question: "How likely is any part of your environment to be affected in the near term?",
    spark: [30, 28, 32, 29, 27, 31, 28, 26, 29, 27, 25, 28],
    contextId: "risk-overall",
  },
  {
    id: "risk-storage",
    label: "Storage Risk",
    level: "Elevated",
    status: "degraded",
    currentHealth: "healthy",
    currentHealthLabel: "Service healthy",
    trend: "Deteriorating",
    trendNote: "Access latency drifting upward for 3h",
    affectedDeployments: ["Production – West US 2"],
    question: "Could an emerging storage condition reach your users?",
    spark: [34, 40, 52, 47, 61, 58, 70, 64, 72, 68, 74, 71],
    contextId: "risk-storage",
  },
  {
    id: "risk-compute",
    label: "Compute Risk",
    level: "Low",
    status: "healthy",
    currentHealth: "healthy",
    currentHealthLabel: "Service healthy",
    trend: "Stable",
    trendNote: "Headroom steady near 49%",
    affectedDeployments: ["No deployment exposed"],
    question: "Is compute capacity or host health trending toward trouble?",
    spark: [26, 29, 27, 30, 28, 26, 29, 27, 30, 28, 26, 27],
    contextId: "risk-compute",
  },
  {
    id: "risk-network",
    label: "Network Risk",
    level: "Low",
    status: "healthy",
    currentHealth: "healthy",
    currentHealthLabel: "Service healthy",
    trend: "Improving",
    trendNote: "Path variance down 12% over 24h",
    affectedDeployments: ["No deployment exposed"],
    question: "Are network paths showing an emerging instability signal?",
    spark: [32, 30, 31, 29, 30, 28, 27, 28, 26, 27, 25, 24],
    contextId: "risk-network",
  },
  {
    id: "risk-capacity",
    label: "Capacity Risk",
    level: "Moderate",
    status: "advisory",
    currentHealth: "healthy",
    currentHealthLabel: "Service healthy",
    trend: "Deteriorating",
    trendNote: "Request volume up 18% week over week in East US",
    affectedDeployments: ["Production – East US"],
    question: "Could growth in your own traffic outpace the capacity reserved for you?",
    spark: [40, 42, 45, 44, 48, 51, 53, 52, 56, 58, 61, 63],
    contextId: "risk-capacity",
  },
  {
    id: "risk-regional",
    label: "Regional Risk",
    level: "Moderate",
    status: "advisory",
    currentHealth: "healthy",
    currentHealthLabel: "Service healthy",
    trend: "Stable",
    trendNote: "One provider advisory open, no spread observed",
    affectedDeployments: ["Production – West US 2"],
    question: "Could a regional condition concentrate risk in one location?",
    spark: [38, 41, 44, 43, 47, 46, 49, 48, 50, 49, 48, 49],
    contextId: "risk-regional",
  },
];

export const riskDetails: Record<string, RiskDetail> = {
  "risk-overall": {
    headline: "Overall Risk",
    level: "Low",
    levelStatus: "healthy",
    currentImpact: "NO CURRENT IMPACT",
    currentHealthLabel: "Your service is healthy right now",
    currentHealthStatus: "healthy",
    contributingSignals: [
      { label: "Composite risk score", value: "28 / 100 (low band)", status: "healthy", raisesRisk: false },
      { label: "Open provider advisories", value: "1 (West US 2 storage)", status: "advisory", raisesRisk: true },
      { label: "Change volume (24h)", value: "Normal", status: "healthy", raisesRisk: false },
      { label: "Saturation across tiers", value: "Well within headroom", status: "healthy", raisesRisk: false },
      { label: "Customer-facing errors", value: "None detected", status: "healthy", raisesRisk: false },
    ],
    whatCouldHappen:
      "If the open regional storage advisory were to broaden, the Production, West US 2 deployment could see a potential increase in service latency. No other area currently shows an emerging condition.",
    estimatedExposure: "Low",
    trend: "Stable",
    trendNote: "The composite score has moved less than 3 points over the last 12 hours.",
    confidence: 91,
    confidenceNote: "Based on 12 correlated signal families and historical incident patterns for comparable conditions.",
    affectedDeployments: [
      { name: "Production – East US", note: "No risk signal attached", status: "healthy" },
      { name: "Production – West US 2", note: "Carries the single open risk signal", status: "advisory" },
      { name: "Staging – Central US", note: "No risk signal attached", status: "healthy" },
    ],
    preventiveActions: [
      { label: "Risk model re-scored every 15 minutes", done: true },
      { label: "Cross-region comparison running", done: true },
      { label: "Failover readiness validated", done: true },
      { label: "Provider advisory tracking active", done: true },
    ],
    customerAction: "None required",
    spark: [30, 28, 32, 29, 27, 31, 28, 26, 29, 27, 25, 28],
  },

  "risk-storage": {
    headline: "Storage Risk",
    level: "Elevated",
    levelStatus: "degraded",
    currentImpact: "NO CURRENT IMPACT",
    currentHealthLabel: "Your service is healthy right now",
    currentHealthStatus: "healthy",
    contributingSignals: [
      { label: "Storage access latency", value: "+31% above baseline", status: "degraded", raisesRisk: true },
      { label: "Regional storage advisory", value: "Active (West US 2)", status: "advisory", raisesRisk: true },
      { label: "Request success rate", value: "Remains normal", status: "healthy", raisesRisk: false },
      { label: "Throttling", value: "None detected", status: "healthy", raisesRisk: false },
      { label: "Customer-facing errors", value: "None detected", status: "healthy", raisesRisk: false },
    ],
    whatCouldHappen:
      "If the condition continues to deteriorate, the Production, West US 2 deployment could experience increased service latency. This is a potential outcome based on an observed trend, not a predicted certainty.",
    estimatedExposure: "Low",
    trend: "Deteriorating",
    trendNote: "Access latency has drifted upward for roughly three hours while success rates stayed flat.",
    confidence: 87,
    confidenceNote: "Derived from latency trend fit, advisory scope and comparison against three unaffected regions.",
    affectedDeployments: [
      { name: "Production – West US 2", note: "Only deployment exposed to the emerging condition", status: "advisory" },
      { name: "Production – East US", note: "Not exposed — independent storage stamp", status: "healthy" },
      { name: "Staging – Central US", note: "Not exposed", status: "healthy" },
    ],
    preventiveActions: [
      { label: "Enhanced telemetry activated", done: true },
      { label: "Cross-region comparison running", done: true },
      { label: "Cloud provider escalation active", done: true },
      { label: "Failover readiness validated", done: true },
    ],
    customerAction: "None required",
    spark: [34, 40, 52, 47, 61, 58, 70, 64, 72, 68, 74, 71],
  },

  "risk-compute": {
    headline: "Compute Risk",
    level: "Low",
    levelStatus: "healthy",
    currentImpact: "NO CURRENT IMPACT",
    currentHealthLabel: "Your service is healthy right now",
    currentHealthStatus: "healthy",
    contributingSignals: [
      { label: "Capacity headroom", value: "49% available", status: "healthy", raisesRisk: false },
      { label: "Host degradation signals", value: "None observed", status: "healthy", raisesRisk: false },
      { label: "Node restart rate", value: "0 in 24h", status: "healthy", raisesRisk: false },
      { label: "Scale-out latency", value: "Within normal range", status: "healthy", raisesRisk: false },
      { label: "Scheduled maintenance", value: "One low-impact window Jun 6", status: "info", raisesRisk: true },
    ],
    whatCouldHappen:
      "No emerging compute condition is present. If traffic were to rise well beyond forecast during the Jun 6 maintenance window, there is an elevated probability of brief connection resets handled by client retry.",
    estimatedExposure: "None",
    trend: "Stable",
    trendNote: "Headroom and host scores have held steady across the last seven days.",
    confidence: 94,
    confidenceNote: "High signal density: per-node health scoring plus capacity forecasting.",
    affectedDeployments: [
      { name: "All production deployments", note: "No compute risk signal attached", status: "healthy" },
    ],
    preventiveActions: [
      { label: "Predictive host scoring active", done: true },
      { label: "Capacity forecast refreshed hourly", done: true },
      { label: "Maintenance window reviewed against your traffic profile", done: true },
      { label: "Failover readiness validated", done: true },
    ],
    customerAction: "None required",
    spark: [26, 29, 27, 30, 28, 26, 29, 27, 30, 28, 26, 27],
  },

  "risk-network": {
    headline: "Network Risk",
    level: "Low",
    levelStatus: "healthy",
    currentImpact: "NO CURRENT IMPACT",
    currentHealthLabel: "Your service is healthy right now",
    currentHealthStatus: "healthy",
    contributingSignals: [
      { label: "Path stability", value: "100% — no re-routes in 24h", status: "healthy", raisesRisk: false },
      { label: "Packet loss", value: "0.00% on all monitored paths", status: "healthy", raisesRisk: false },
      { label: "Inter-region latency variance", value: "Down 12% over 24h", status: "healthy", raisesRisk: false },
      { label: "Ingress saturation", value: "31% of provisioned capacity", status: "healthy", raisesRisk: false },
      { label: "Peering advisories", value: "None active", status: "healthy", raisesRisk: false },
    ],
    whatCouldHappen:
      "No network risk signal is present. Should an ingress or peering advisory emerge, the earliest customer-visible symptom would be a potential increase in connection setup time.",
    estimatedExposure: "None",
    trend: "Improving",
    trendNote: "Latency variance has narrowed steadily since the last peering optimisation.",
    confidence: 93,
    confidenceNote: "Continuous synthetic probing across all customer-serving paths every 60 seconds.",
    affectedDeployments: [
      { name: "All monitored paths", note: "Stable — no deployment exposed", status: "healthy" },
    ],
    preventiveActions: [
      { label: "Continuous path probing active", done: true },
      { label: "Cross-region comparison running", done: true },
      { label: "Alternate path readiness validated", done: true },
      { label: "Provider peering status monitored", done: true },
    ],
    customerAction: "None required",
    spark: [32, 30, 31, 29, 30, 28, 27, 28, 26, 27, 25, 24],
  },

  "risk-regional": {
    headline: "Regional Risk",
    level: "Moderate",
    levelStatus: "advisory",
    currentImpact: "NO CURRENT IMPACT",
    currentHealthLabel: "Your service is healthy in every region",
    currentHealthStatus: "healthy",
    contributingSignals: [
      { label: "Regions with an open provider advisory", value: "1 of 6 (West US 2)", status: "advisory", raisesRisk: true },
      { label: "Traffic concentration in the affected region", value: "22% of production traffic", status: "advisory", raisesRisk: true },
      { label: "Advisory spread", value: "No expansion observed", status: "healthy", raisesRisk: false },
      { label: "Regional failover readiness", value: "Validated 14m ago", status: "healthy", raisesRisk: false },
      { label: "Customer-facing errors in region", value: "None detected", status: "healthy", raisesRisk: false },
    ],
    whatCouldHappen:
      "If the West US 2 advisory were to broaden across additional services, the Production, West US 2 deployment could see a potential reduction in regional capacity, with traffic shifting to East US. Regions where you run nothing carry no exposure regardless of provider condition.",
    estimatedExposure: "Low",
    trend: "Stable",
    trendNote: "The advisory has remained scoped to a single service family for its full duration.",
    confidence: 89,
    confidenceNote: "Based on advisory scope tracking, regional traffic distribution and failover rehearsal results.",
    affectedDeployments: [
      { name: "Production – West US 2", note: "Located in the region carrying the advisory", status: "advisory" },
      { name: "Production – East US", note: "Standby capacity available for regional shift", status: "healthy" },
      { name: "Staging – Central US", note: "No regional risk signal attached", status: "healthy" },
    ],
    preventiveActions: [
      { label: "Cross-region comparison running", done: true },
      { label: "Cloud provider escalation active", done: true },
      { label: "Failover readiness validated", done: true },
      { label: "Regional traffic rebalancing armed", done: false },
    ],
    customerAction: "None required",
    spark: [38, 41, 44, 43, 47, 46, 49, 48, 50, 49, 48, 49],
  },

  "risk-capacity": {
    headline: "Capacity Risk",
    level: "Moderate",
    levelStatus: "advisory",
    currentImpact: "NO CURRENT IMPACT",
    currentHealthLabel: "Your service is healthy right now",
    currentHealthStatus: "healthy",
    contributingSignals: [
      { label: "Request volume trend", value: "+18% week over week (East US)", status: "advisory", raisesRisk: true },
      { label: "Compute headroom", value: "34% available, down from 49%", status: "advisory", raisesRisk: true },
      { label: "Scale-out response time", value: "New virtual machine nodes ready in ~4 min", status: "healthy", raisesRisk: false },
      { label: "Availability zone balance", value: "Even across three zones", status: "healthy", raisesRisk: false },
      { label: "Customer-facing errors", value: "None detected", status: "healthy", raisesRisk: false },
    ],
    whatCouldHappen:
      "If the observed growth trend continues at the same pace, there is an elevated probability that the Production, East US deployment reaches its current reserved capacity within roughly two weeks. Additional virtual machine capacity would then be added, which is routine and non-disruptive. Nothing here indicates an outage.",
    estimatedExposure: "Low",
    trend: "Deteriorating",
    trendNote: "Headroom has fallen steadily for nine days while error rates stayed flat.",
    confidence: 84,
    confidenceNote: "Forecast from nine days of request-volume and utilisation telemetry, compared with the same period last quarter.",
    affectedDeployments: [
      { name: "Production – East US", note: "Growth trend concentrated here", status: "advisory" },
      { name: "Production – West US 2", note: "Headroom steady at 51%", status: "healthy" },
      { name: "DR – Central US", note: "Standby capacity unchanged", status: "healthy" },
    ],
    preventiveActions: [
      { label: "Capacity forecast refreshed daily", done: true },
      { label: "Scale-out automation verified", done: true },
      { label: "Reserved capacity increase drafted for review", done: false },
      { label: "Growth trend shared with your account team", done: true },
    ],
    customerAction: "None required — we will propose a capacity increase before the trend reaches the reservation.",
    spark: [40, 42, 45, 44, 48, 51, 53, 52, 56, 58, 61, 63],
  },
};
