/**
 * Page 22 · Human Approval and Exception Center
 * Route: /runops/approvals
 *
 * Centralizes operational decisions requiring human authority.
 * Shared state (localStorage):
 *   - runops.approvals.v1   → approval requests (created by Launch/Autonomous)
 *   - runops.executions.v1  → executions resumed/blocked by approval outcome
 *   - runops.exceptions.v1  → time-limited policy exceptions
 *   - runops.breakglass.v1  → break-glass invocations
 *   - runops.reviewtasks.v1 → review tasks generated by break-glass
 *
 * All state changes emit ops.pushNotification (audit + domain events).
 * No fixture arrays imported. No `any`.
 */

import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  AlertTriangle, ArrowRightLeft, Ban, CheckCircle2, ExternalLink, Filter,
  KeyRound, MessageSquareWarning, RefreshCw, Search, ShieldAlert, ShieldCheck,
  Timer, UserCog, XCircle,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import {
  Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { EntityHeader } from "@/runops/components";
import { useOperations } from "@/runops/state/RunOpsProviders";

/* -------------------------------------------------------------------------- */
/* Types                                                                       */
/* -------------------------------------------------------------------------- */

type ApprovalState = "pending" | "approved" | "denied" | "expired" | "changes-requested" | "delegated";
type Risk = "Low" | "Medium" | "High";

interface Decision {
  at: string;
  by: string;
  action: "approved" | "denied" | "changes-requested" | "delegated" | "escalated" | "revoked" | "commented";
  reason: string;
}

interface ApprovalRequest {
  id: string;
  executionId: string;
  runbookId: string;
  role: string;                       // required approver role
  state: ApprovalState;
  requestedAt: string;
  reason: string;
  /* enriched (populated on demand from execution + defaults) */
  requestedByUserId?: string;
  requestedByRole?: string;
  digitalWorker?: string;
  serviceId?: string;
  environment?: string;
  incidentId?: string;
  changeTicket?: string;
  action?: string;                    // e.g. "Approval-gated automation launch"
  risk?: Risk;
  businessImpact?: string;
  aiConfidence?: number;
  policyResult?: "allow" | "deny" | "conditional";
  policyDetail?: string;
  requiresReason?: boolean;
  requiresSeparation?: boolean;
  deadlineAt?: string;
  alternatives?: string[];
  evidenceRefs?: string[];
  blastRadius?: string;
  rollbackReadiness?: "ready" | "partial" | "none";
  requestorHistory?: { approved: number; denied: number; recent: string };
  approverAuthority?: string;
  decisions?: Decision[];
  delegatedTo?: string;
}

interface ExceptionGrant {
  id: string;
  approvalId: string;
  policy: string;
  scope: string;
  issuedAt: string;
  issuedBy: string;
  expiresAt: string;
  reason: string;
  revoked: boolean;
  revokedAt?: string;
  revokedBy?: string;
}

interface BreakGlassEvent {
  id: string;
  approvalId?: string;
  invokedAt: string;
  invokedBy: string;
  targetRef: string;
  reason: string;
  reviewTaskId: string;
}

interface ReviewTask {
  id: string;
  kind: "breakglass-review";
  createdAt: string;
  targetRef: string;
  assignedRole: string;
  status: "open" | "closed";
}

interface ExecutionRecord {
  id: string;
  runbookId: string;
  runbookVersion?: string;
  serviceId?: string;
  environment?: string;
  mode?: string;
  state: string;
  approvals: string[];
  awaitingApproval?: boolean;
  timeline: { at: string; kind: string; detail: string }[];
  changeTicket?: string;
  incidentId?: string;
}

const APPROVALS_KEY   = "runops.approvals.v1";
const EXECUTIONS_KEY  = "runops.executions.v1";
const EXCEPTIONS_KEY  = "runops.exceptions.v1";
const BREAKGLASS_KEY  = "runops.breakglass.v1";
const REVIEWTASKS_KEY = "runops.reviewtasks.v1";

const nowIso = () => new Date().toISOString();
const rid = (p: string) => `${p}-${Math.random().toString(36).slice(2, 8)}`;

function readList<T>(key: string): T[] {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return [];
    const parsed: unknown = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as T[]) : [];
  } catch { return []; }
}
function writeList<T>(key: string, list: T[]) {
  localStorage.setItem(key, JSON.stringify(list));
}

/* Sensitive actions that require a reason for approve/deny. */
function isSensitive(a: ApprovalRequest): boolean {
  return a.environment === "Production" || (a.risk ?? "Low") === "High" || !!a.incidentId;
}

/* Role → authority mapping. Roles that CAN approve when their role matches request role. */
function roleCanApprove(role: string, requestRole: string): boolean {
  if (role === "Read Only User" || role === "Auditor") return false;
  const authoritative: Record<string, string[]> = {
    "Change Manager":       ["Change Manager"],
    "Service Owner":        ["Service Owner"],
    "Incident Commander":   ["Incident Commander", "Service Owner"],
    "SRE Engineer":         ["Service Owner"],
    "Platform Engineer":    ["Service Owner", "Platform Engineer"],
    "Runbook Author":       [],
    "Executive":            ["Change Manager", "Service Owner", "Incident Commander"],
    "Digital Worker Administrator": ["Digital Worker Administrator"],
    "NOC Operator":         [],
    "Demo Controller":      ["Change Manager", "Service Owner", "Incident Commander", "Digital Worker Administrator"],
  };
  return (authoritative[role] ?? []).includes(requestRole);
}

/* -------------------------------------------------------------------------- */
/* Enrichment: augment persisted minimal approval with rich context.           */
/* -------------------------------------------------------------------------- */

function enrichApproval(a: ApprovalRequest, execution: ExecutionRecord | null, incidentId?: string): ApprovalRequest {
  if (a.action && a.risk && a.decisions && a.deadlineAt) return a;
  const risk: Risk = (execution?.environment === "Production" ? "High" : "Medium");
  const deadline = new Date(new Date(a.requestedAt).getTime() + 45 * 60_000).toISOString();
  return {
    ...a,
    action:            a.action ?? `Approval-gated automation · ${a.runbookId}`,
    serviceId:         a.serviceId ?? execution?.serviceId,
    environment:       a.environment ?? execution?.environment ?? "Production",
    incidentId:        a.incidentId ?? execution?.incidentId ?? incidentId ?? "INC-10482",
    changeTicket:      a.changeTicket ?? execution?.changeTicket,
    digitalWorker:     a.digitalWorker ?? "DW-IC-01",
    requestedByRole:   a.requestedByRole ?? "SRE Engineer",
    risk:              a.risk ?? risk,
    businessImpact:    a.businessImpact ?? (execution?.environment === "Production" ? "Checkout revenue at risk · SEV 1" : "Non-production · low"),
    aiConfidence:      a.aiConfidence ?? 78,
    policyResult:      a.policyResult ?? "conditional",
    policyDetail:      a.policyDetail ?? "Requires named approver from Change Manager or Service Owner",
    requiresReason:    a.requiresReason ?? true,
    requiresSeparation:a.requiresSeparation ?? true,
    deadlineAt:        a.deadlineAt ?? deadline,
    alternatives:      a.alternatives ?? ["Transfer to human guided mode", "Increase connection pool cap (fallback)", "Extend maintenance window"],
    evidenceRefs:      a.evidenceRefs ?? ["query-plan-baseline.json", "checkout-p95.png", "pool-utilization.csv"],
    blastRadius:       a.blastRadius ?? `${execution?.serviceId ?? "svc-global-order-processing"} · checkout-api + orders-db`,
    rollbackReadiness: a.rollbackReadiness ?? "ready",
    requestorHistory:  a.requestorHistory ?? { approved: 12, denied: 1, recent: "last 30d" },
    approverAuthority: a.approverAuthority ?? `${a.role} · segregated from requestor`,
    decisions:         a.decisions ?? [{ at: a.requestedAt, by: a.digitalWorker ?? "DW-IC-01", action: "commented", reason: a.reason || "Requested" }],
  };
}

/* -------------------------------------------------------------------------- */
/* Page                                                                        */
/* -------------------------------------------------------------------------- */

export default function ApprovalCenter() {
  const ops = useOperations();
  const navigate = useNavigate();

  const [approvals, setApprovals] = useState<ApprovalRequest[]>([]);
  const [exceptions, setExceptions] = useState<ExceptionGrant[]>([]);
  const [breakglass, setBreakglass] = useState<BreakGlassEvent[]>([]);
  const [tab, setTab] = useState<string>("pending");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [envFilter, setEnvFilter] = useState<string>("all");
  const [riskFilter, setRiskFilter] = useState<string>("all");
  const [sortBy, setSortBy] = useState<"deadline" | "risk" | "requested">("deadline");
  const [dialog, setDialog] = useState<null | "approve" | "deny" | "changes" | "delegate" | "escalate" | "exception" | "revoke" | "breakglass">(null);
  const [reason, setReason] = useState("");
  const [delegateTo, setDelegateTo] = useState("Service Owner");
  const [exceptionMinutes, setExceptionMinutes] = useState<string>("60");
  const [exceptionScope, setExceptionScope] = useState("Approval-gated mitigation window");
  const [now, setNow] = useState(Date.now());
  const [tick, setTick] = useState(0);

  /* Load stores + seed one canonical pending approval if empty. */
  useEffect(() => {
    void tick;
    const execs = readList<ExecutionRecord>(EXECUTIONS_KEY);
    let rawList = readList<ApprovalRequest>(APPROVALS_KEY);
    if (rawList.length === 0) {
      // seed one canonical pending approval tied to EXE-8841 mitigation gate
      const seedExec = execs.find((e) => e.id === "EXE-8841") ?? null;
      const seed: ApprovalRequest = {
        id: "APR-4471",
        executionId: seedExec?.id ?? "EXE-8841",
        runbookId: seedExec?.runbookId ?? "RB-0042",
        role: "Change Manager",
        state: "pending",
        requestedAt: nowIso(),
        reason: "Approval-gated mitigation: revert index CHG-20391 and recycle checkout pods.",
        requestedByRole: "SRE Engineer",
        digitalWorker: "DW-IC-01",
      };
      rawList = [seed];
      writeList(APPROVALS_KEY, rawList);
    }
    const enriched = rawList.map((a) => enrichApproval(a, execs.find((e) => e.id === a.executionId) ?? null));
    writeList(APPROVALS_KEY, enriched);
    setApprovals(enriched);

    // expire approvals past deadline
    const withExpiry = enriched.map((a) => {
      if (a.state === "pending" && a.deadlineAt && new Date(a.deadlineAt).getTime() < Date.now()) {
        return { ...a, state: "expired" as ApprovalState };
      }
      return a;
    });
    if (JSON.stringify(withExpiry) !== JSON.stringify(enriched)) {
      writeList(APPROVALS_KEY, withExpiry);
      setApprovals(withExpiry);
    }

    setExceptions(readList<ExceptionGrant>(EXCEPTIONS_KEY));
    setBreakglass(readList<BreakGlassEvent>(BREAKGLASS_KEY));
    setSelectedId((prev) => prev ?? withExpiry.find((a) => a.state === "pending")?.id ?? withExpiry[0]?.id ?? null);
  }, [tick]);

  /* Live clock for deadlines */
  useEffect(() => {
    const t = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(t);
  }, []);

  const persistApprovals = useCallback((next: ApprovalRequest[]) => {
    writeList(APPROVALS_KEY, next);
    setApprovals(next);
  }, []);

  const audit = useCallback((title: string, detail: string, kind: "info" | "warning" | "critical" = "info", entityRef?: string) => {
    ops.pushNotification({ kind, title, detail, entityRef });
  }, [ops]);

  /* ---- Cross-store: patch execution when approval settles ---- */
  const patchExecution = (executionId: string, patch: (e: ExecutionRecord) => ExecutionRecord) => {
    const execs = readList<ExecutionRecord>(EXECUTIONS_KEY);
    const idx = execs.findIndex((e) => e.id === executionId);
    if (idx < 0) return;
    const updated = { ...patch(execs[idx]) };
    execs[idx] = updated;
    writeList(EXECUTIONS_KEY, execs);
  };

  /* ---- Filtering / sorting ---- */
  const filtered = useMemo(() => {
    let list = approvals.slice();
    // tab
    switch (tab) {
      case "pending":     list = list.filter((a) => a.state === "pending" || a.state === "changes-requested" || a.state === "delegated"); break;
      case "my":          list = list.filter((a) => (a.requestedByRole ?? "SRE Engineer") === ops.role); break;
      case "approved":    list = list.filter((a) => a.state === "approved"); break;
      case "denied":      list = list.filter((a) => a.state === "denied"); break;
      case "expired":     list = list.filter((a) => a.state === "expired"); break;
      case "exceptions":  list = [];  break; // separate view below
      case "breakglass":  list = [];  break;
    }
    const q = search.trim().toLowerCase();
    if (q) list = list.filter((a) =>
      a.id.toLowerCase().includes(q)
      || (a.action ?? "").toLowerCase().includes(q)
      || (a.serviceId ?? "").toLowerCase().includes(q)
      || (a.runbookId ?? "").toLowerCase().includes(q)
      || (a.executionId ?? "").toLowerCase().includes(q)
      || (a.digitalWorker ?? "").toLowerCase().includes(q)
    );
    if (envFilter !== "all") list = list.filter((a) => a.environment === envFilter);
    if (riskFilter !== "all") list = list.filter((a) => a.risk === riskFilter);
    list.sort((a, b) => {
      if (sortBy === "deadline") return new Date(a.deadlineAt ?? 0).getTime() - new Date(b.deadlineAt ?? 0).getTime();
      if (sortBy === "risk") {
        const w: Record<string, number> = { High: 0, Medium: 1, Low: 2 };
        return (w[a.risk ?? "Low"] ?? 3) - (w[b.risk ?? "Low"] ?? 3);
      }
      return new Date(b.requestedAt).getTime() - new Date(a.requestedAt).getTime();
    });
    return list;
  }, [approvals, tab, search, envFilter, riskFilter, sortBy, ops.role]);

  const selected = approvals.find((a) => a.id === selectedId) ?? filtered[0] ?? null;

  /* ---- Authority checks (client mirror; server would re-verify) ---- */
  const authorityStatus = (a: ApprovalRequest | null): "authorized" | "unauthorized" | "conflict" | "no-selection" => {
    if (!a) return "no-selection";
    // separation of duties: requestor cannot approve their own request
    const selfRoleMatch = a.requiresSeparation
      && ((a.requestedByRole ?? "") === ops.role || (a.digitalWorker ?? "") === ops.role);
    if (selfRoleMatch) return "conflict";
    if (!roleCanApprove(ops.role, a.role)) return "unauthorized";
    return "authorized";
  };

  /* ---- Actions ---- */
  const withDecision = (a: ApprovalRequest, d: Decision, state?: ApprovalState): ApprovalRequest => ({
    ...a,
    state: state ?? a.state,
    decisions: [...(a.decisions ?? []), d],
  });

  const doApprove = () => {
    if (!selected) return;
    const auth = authorityStatus(selected);
    if (auth !== "authorized") {
      audit("Approval refused by policy", `${selected.id} · ${auth === "conflict" ? "self-approval blocked" : "unauthorized role"}`, "warning", selected.executionId);
      setDialog(null); return;
    }
    if (isSensitive(selected) && reason.trim().length < 6) {
      audit("Approval requires reason", `${selected.id} · reason ≥ 6 chars`, "warning", selected.executionId);
      return;
    }
    const decision: Decision = { at: nowIso(), by: ops.role, action: "approved", reason: reason.trim() || "Approved" };
    const updated = withDecision(selected, decision, "approved");
    persistApprovals(approvals.map((a) => a.id === selected.id ? updated : a));
    patchExecution(selected.executionId, (e) => ({
      ...e,
      awaitingApproval: false,
      approvals: Array.from(new Set([...(e.approvals ?? []), selected.id])),
      state: e.state === "AwaitingApproval" ? "Running" : e.state,
      timeline: [...(e.timeline ?? []), { at: nowIso(), kind: "approval.granted", detail: `${selected.id} approved by ${ops.role}` }],
    }));
    audit("Approval granted",     `${selected.id} · ${selected.executionId} · ${selected.runbookId}`, "info", selected.executionId);
    audit("Execution resumed",    `${selected.executionId} · autonomous monitor unblocked`, "info", selected.executionId);
    audit("Incident timeline updated", `${selected.incidentId ?? "—"} · approval ${selected.id} granted`, "info", selected.incidentId);
    audit("Worker session updated", `${selected.digitalWorker ?? "DW"} · approval received`, "info", selected.executionId);
    setDialog(null); setReason("");
  };

  const doDeny = () => {
    if (!selected) return;
    const auth = authorityStatus(selected);
    if (auth !== "authorized") { audit("Denial refused", `${selected.id} · ${auth}`, "warning", selected.executionId); setDialog(null); return; }
    if (reason.trim().length < 6) { audit("Denial requires reason", `${selected.id} · reason ≥ 6 chars`, "warning", selected.executionId); return; }
    const decision: Decision = { at: nowIso(), by: ops.role, action: "denied", reason: reason.trim() };
    const updated = withDecision(selected, decision, "denied");
    persistApprovals(approvals.map((a) => a.id === selected.id ? updated : a));
    patchExecution(selected.executionId, (e) => ({
      ...e,
      awaitingApproval: false,
      state: "Cancelled",
      timeline: [...(e.timeline ?? []), { at: nowIso(), kind: "approval.denied", detail: `${selected.id} denied by ${ops.role} · ${reason.trim()}` }],
    }));
    audit("Approval denied",         `${selected.id} · ${selected.executionId} · ${reason.trim()}`, "warning", selected.executionId);
    audit("Execution cancelled",     `${selected.executionId} · denied by ${ops.role}`, "warning", selected.executionId);
    audit("Incident timeline updated", `${selected.incidentId ?? "—"} · approval ${selected.id} denied`, "warning", selected.incidentId);
    audit("Operations queue updated", `${selected.executionId} · removed from active queue`, "info", selected.executionId);
    audit("Worker session updated",   `${selected.digitalWorker ?? "DW"} · approval denied`, "warning", selected.executionId);
    setDialog(null); setReason("");
  };

  const doRequestChanges = () => {
    if (!selected) return;
    if (reason.trim().length < 6) { audit("Change request requires reason", `${selected.id}`, "warning", selected.executionId); return; }
    const decision: Decision = { at: nowIso(), by: ops.role, action: "changes-requested", reason: reason.trim() };
    const updated = withDecision(selected, decision, "changes-requested");
    persistApprovals(approvals.map((a) => a.id === selected.id ? updated : a));
    audit("Changes requested on approval", `${selected.id} · ${reason.trim()}`, "info", selected.executionId);
    setDialog(null); setReason("");
  };

  const doDelegate = () => {
    if (!selected) return;
    const decision: Decision = { at: nowIso(), by: ops.role, action: "delegated", reason: `Delegated to ${delegateTo}` };
    const updated: ApprovalRequest = { ...withDecision(selected, decision, "delegated"), delegatedTo: delegateTo, role: delegateTo };
    persistApprovals(approvals.map((a) => a.id === selected.id ? updated : a));
    audit("Approval delegated", `${selected.id} → ${delegateTo}`, "info", selected.executionId);
    setDialog(null);
  };

  const doEscalate = () => {
    if (!selected) return;
    const decision: Decision = { at: nowIso(), by: ops.role, action: "escalated", reason: reason.trim() || "Escalated to Incident Commander" };
    const updated: ApprovalRequest = withDecision({ ...selected, role: "Incident Commander" }, decision);
    persistApprovals(approvals.map((a) => a.id === selected.id ? updated : a));
    audit("Approval escalated", `${selected.id} → Incident Commander`, "warning", selected.executionId);
    setDialog(null); setReason("");
  };

  const doIssueException = () => {
    if (!selected) return;
    const mins = Math.max(5, Math.min(240, Number(exceptionMinutes) || 60));
    const grant: ExceptionGrant = {
      id: rid("EX"),
      approvalId: selected.id,
      policy: selected.policyDetail ?? "Change Manager required",
      scope: exceptionScope,
      issuedAt: nowIso(),
      issuedBy: ops.role,
      expiresAt: new Date(Date.now() + mins * 60_000).toISOString(),
      reason: reason.trim() || "Time-limited operational exception",
      revoked: false,
    };
    const nextEx = [grant, ...exceptions];
    setExceptions(nextEx);
    writeList(EXCEPTIONS_KEY, nextEx);
    // exception also acts as an approval on the pending request
    const decision: Decision = { at: nowIso(), by: ops.role, action: "approved", reason: `Time-limited exception ${grant.id} for ${mins}m` };
    const updated = withDecision(selected, decision, "approved");
    persistApprovals(approvals.map((a) => a.id === selected.id ? updated : a));
    patchExecution(selected.executionId, (e) => ({
      ...e,
      awaitingApproval: false,
      approvals: Array.from(new Set([...(e.approvals ?? []), selected.id])),
      state: e.state === "AwaitingApproval" ? "Running" : e.state,
      timeline: [...(e.timeline ?? []), { at: nowIso(), kind: "exception.issued", detail: `${grant.id} · ${mins}m by ${ops.role}` }],
    }));
    audit("Policy exception issued", `${grant.id} · ${mins}m · ${selected.executionId}`, "warning", selected.executionId);
    audit("Governance updated", `Exception ${grant.id} logged for review`, "info");
    audit("Audit updated", `Exception ${grant.id} recorded`, "info");
    setDialog(null); setReason(""); setExceptionMinutes("60");
  };

  const doRevokeException = (id: string) => {
    const nextEx = exceptions.map((e) => e.id === id ? { ...e, revoked: true, revokedAt: nowIso(), revokedBy: ops.role } : e);
    setExceptions(nextEx);
    writeList(EXCEPTIONS_KEY, nextEx);
    audit("Policy exception revoked", `${id} · by ${ops.role}`, "warning");
    setDialog(null);
  };

  const doBreakGlass = () => {
    if (!selected) return;
    if (reason.trim().length < 12) { audit("Break glass requires justification", `${selected.id} · reason ≥ 12 chars`, "warning"); return; }
    if (!(ops.role === "Incident Commander" || ops.role === "Service Owner" || ops.role === "Platform Engineer" || ops.role === "Executive" || ops.role === "Demo Controller")) {
      audit("Break glass not authorized", `${ops.role} is not permitted`, "critical", selected.executionId);
      setDialog(null); return;
    }
    const reviewTask: ReviewTask = {
      id: rid("RVW"), kind: "breakglass-review", createdAt: nowIso(),
      targetRef: selected.id, assignedRole: "Auditor", status: "open",
    };
    const tasks = [reviewTask, ...readList<ReviewTask>(REVIEWTASKS_KEY)];
    writeList(REVIEWTASKS_KEY, tasks);
    const ev: BreakGlassEvent = {
      id: rid("BG"), approvalId: selected.id, invokedAt: nowIso(),
      invokedBy: ops.role, targetRef: `${selected.executionId} · ${selected.runbookId}`,
      reason: reason.trim(), reviewTaskId: reviewTask.id,
    };
    const nextBg = [ev, ...breakglass];
    setBreakglass(nextBg);
    writeList(BREAKGLASS_KEY, nextBg);
    const decision: Decision = { at: nowIso(), by: ops.role, action: "approved", reason: `Break glass ${ev.id}` };
    const updated = withDecision(selected, decision, "approved");
    persistApprovals(approvals.map((a) => a.id === selected.id ? updated : a));
    patchExecution(selected.executionId, (e) => ({
      ...e,
      awaitingApproval: false,
      approvals: Array.from(new Set([...(e.approvals ?? []), selected.id])),
      state: e.state === "AwaitingApproval" ? "Running" : e.state,
      timeline: [...(e.timeline ?? []), { at: nowIso(), kind: "breakglass.invoked", detail: `${ev.id} by ${ops.role} · ${reason.trim()}` }],
    }));
    audit("Break glass invoked", `${ev.id} · ${selected.executionId} · ${ops.role}`, "critical", selected.executionId);
    audit("Review task created", `${reviewTask.id} · assigned to Auditor`, "warning");
    audit("Audit updated", `High-severity break-glass event ${ev.id}`, "critical");
    setDialog(null); setReason("");
  };

  /* ---- Add comment (no state change) ---- */
  const [comment, setComment] = useState("");
  const doComment = () => {
    if (!selected || comment.trim().length === 0) return;
    const decision: Decision = { at: nowIso(), by: ops.role, action: "commented", reason: comment.trim() };
    const updated = withDecision(selected, decision);
    persistApprovals(approvals.map((a) => a.id === selected.id ? updated : a));
    audit("Approval comment added", `${selected.id} · ${ops.role}`, "info", selected.executionId);
    setComment("");
  };

  /* ---- Counters ---- */
  const counters = {
    pending:    approvals.filter((a) => a.state === "pending" || a.state === "changes-requested" || a.state === "delegated").length,
    my:         approvals.filter((a) => (a.requestedByRole ?? "SRE Engineer") === ops.role).length,
    approved:   approvals.filter((a) => a.state === "approved").length,
    denied:     approvals.filter((a) => a.state === "denied").length,
    expired:    approvals.filter((a) => a.state === "expired").length,
    exceptions: exceptions.length,
    breakglass: breakglass.length,
  };

  const activeException = exceptions.find((e) => !e.revoked && new Date(e.expiresAt).getTime() > Date.now());

  const stateBadge: Record<ApprovalState, string> = {
    "pending":            "border-amber-300 bg-amber-50 text-amber-900",
    "approved":           "border-emerald-300 bg-emerald-50 text-emerald-900",
    "denied":             "border-rose-300 bg-rose-50 text-rose-900",
    "expired":            "border-slate-300 bg-slate-50 text-slate-700",
    "changes-requested":  "border-sky-300 bg-sky-50 text-sky-900",
    "delegated":          "border-sky-300 bg-sky-50 text-sky-900",
  };

  /* Time-until helper */
  const timeUntil = (iso?: string) => {
    if (!iso) return "—";
    const ms = new Date(iso).getTime() - now;
    if (ms <= 0) return "expired";
    const m = Math.floor(ms / 60_000);
    const s = Math.floor((ms % 60_000) / 1000);
    return `${m}m ${s}s`;
  };
  const nearExpiration = (a: ApprovalRequest) => {
    if (!a.deadlineAt || a.state !== "pending") return false;
    const ms = new Date(a.deadlineAt).getTime() - now;
    return ms > 0 && ms < 10 * 60_000;
  };

  const authForSelected = authorityStatus(selected);

  return (
    <div className="flex flex-col gap-3 p-4 md:p-6" aria-label="Approval and exception center">
      <EntityHeader
        eyebrow="Governance"
        title="Approval and exception center"
        subtitle="Human authority for gated operations, exceptions, and break-glass"
        meta={
          <div className="flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
            <span>Tenant: <span className="text-foreground">{ops.tenant.name}</span></span>
            <span>Role: <span className="text-foreground">{ops.role}</span></span>
            <span>Scenario: <span className="text-foreground">{ops.stages[ops.stageIndex]?.label ?? "—"}</span></span>
            <Badge variant="outline">Pending · {counters.pending}</Badge>
            {activeException && <Badge variant="outline" className="border-amber-300 bg-amber-50 text-amber-900">Exception active · {activeException.id}</Badge>}
            {breakglass.length > 0 && <Badge variant="outline" className="border-rose-300 bg-rose-50 text-rose-900">Break glass · {breakglass.length}</Badge>}
          </div>
        }
        actions={
          <div className="flex flex-wrap gap-2">
            <Button size="sm" variant="outline" onClick={() => setTick((v) => v + 1)} aria-label="Refresh approvals"><RefreshCw className="h-4 w-4" /> Refresh</Button>
            <Button size="sm" variant="outline" onClick={() => navigate("/runops/operations/queue")} aria-label="Open operations queue"><ExternalLink className="h-4 w-4" /> Operations queue</Button>
          </div>
        }
      />

      {/* Filters */}
      <Card>
        <CardContent className="p-3 flex flex-wrap items-center gap-2">
          <div className="relative flex-1 min-w-[220px]">
            <Search className="h-4 w-4 absolute left-2 top-2.5 text-muted-foreground" />
            <Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search approvals…" className="pl-8" aria-label="Search approvals" />
          </div>
          <Select value={envFilter} onValueChange={setEnvFilter}>
            <SelectTrigger className="w-40" aria-label="Environment filter"><SelectValue placeholder="Environment" /></SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All environments</SelectItem>
              <SelectItem value="Production">Production</SelectItem>
              <SelectItem value="Staging">Staging</SelectItem>
              <SelectItem value="Development">Development</SelectItem>
            </SelectContent>
          </Select>
          <Select value={riskFilter} onValueChange={setRiskFilter}>
            <SelectTrigger className="w-32" aria-label="Risk filter"><SelectValue placeholder="Risk" /></SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All risks</SelectItem>
              <SelectItem value="High">High</SelectItem>
              <SelectItem value="Medium">Medium</SelectItem>
              <SelectItem value="Low">Low</SelectItem>
            </SelectContent>
          </Select>
          <Select value={sortBy} onValueChange={(v) => setSortBy(v as typeof sortBy)}>
            <SelectTrigger className="w-40" aria-label="Sort"><SelectValue placeholder="Sort" /></SelectTrigger>
            <SelectContent>
              <SelectItem value="deadline">Sort · deadline</SelectItem>
              <SelectItem value="risk">Sort · risk</SelectItem>
              <SelectItem value="requested">Sort · newest</SelectItem>
            </SelectContent>
          </Select>
          <span className="text-xs text-muted-foreground inline-flex items-center gap-1"><Filter className="h-3 w-3" /> {filtered.length} shown</span>
        </CardContent>
      </Card>

      <Tabs value={tab} onValueChange={(v) => { setTab(v); setSelectedId(null); }}>
        <TabsList className="flex flex-wrap h-auto">
          <TabsTrigger value="pending">Pending <Badge variant="outline" className="ml-2 h-5">{counters.pending}</Badge></TabsTrigger>
          <TabsTrigger value="my">My Requests <Badge variant="outline" className="ml-2 h-5">{counters.my}</Badge></TabsTrigger>
          <TabsTrigger value="approved">Approved <Badge variant="outline" className="ml-2 h-5">{counters.approved}</Badge></TabsTrigger>
          <TabsTrigger value="denied">Denied <Badge variant="outline" className="ml-2 h-5">{counters.denied}</Badge></TabsTrigger>
          <TabsTrigger value="expired">Expired <Badge variant="outline" className="ml-2 h-5">{counters.expired}</Badge></TabsTrigger>
          <TabsTrigger value="exceptions">Policy Exceptions <Badge variant="outline" className="ml-2 h-5">{counters.exceptions}</Badge></TabsTrigger>
          <TabsTrigger value="breakglass">Break Glass <Badge variant="outline" className="ml-2 h-5">{counters.breakglass}</Badge></TabsTrigger>
        </TabsList>

        {/* Approval-list tabs share the same list layout */}
        {["pending", "my", "approved", "denied", "expired"].map((t) => (
          <TabsContent key={t} value={t}>
            <div className="grid grid-cols-1 xl:grid-cols-[minmax(0,1fr)_420px] gap-3">
              <Card>
                <CardContent className="p-0">
                  {filtered.length === 0 ? (
                    <div className="p-8 text-center text-sm text-muted-foreground flex flex-col items-center gap-2">
                      <ShieldCheck className="h-6 w-6" />
                      No approvals in this view.
                    </div>
                  ) : (
                    <Table>
                      <TableHeader>
                        <TableRow>
                          <TableHead>ID</TableHead>
                          <TableHead>Action</TableHead>
                          <TableHead>Service · Env</TableHead>
                          <TableHead>Risk</TableHead>
                          <TableHead>Role</TableHead>
                          <TableHead>Deadline</TableHead>
                          <TableHead>State</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {filtered.map((a) => (
                          <TableRow
                            key={a.id}
                            className={cn("cursor-pointer", selected?.id === a.id && "bg-muted/40")}
                            onClick={() => setSelectedId(a.id)}
                            tabIndex={0}
                            aria-label={`Select approval ${a.id}`}
                            onKeyDown={(e) => (e.key === "Enter" || e.key === " ") && setSelectedId(a.id)}
                          >
                            <TableCell className="font-mono text-xs">{a.id}</TableCell>
                            <TableCell className="text-sm">
                              <div className="truncate max-w-[280px]">{a.action}</div>
                              <div className="text-xs text-muted-foreground">{a.runbookId} · {a.executionId}</div>
                            </TableCell>
                            <TableCell className="text-xs">{a.serviceId ?? "—"}<div className="text-muted-foreground">{a.environment}</div></TableCell>
                            <TableCell><Badge variant="outline">{a.risk ?? "—"}</Badge></TableCell>
                            <TableCell className="text-xs">{a.role}</TableCell>
                            <TableCell className="text-xs">
                              <span className={cn(nearExpiration(a) && "text-amber-700 font-medium")}>
                                {a.state === "pending" ? timeUntil(a.deadlineAt) : "—"}
                              </span>
                            </TableCell>
                            <TableCell>
                              <Badge variant="outline" className={cn("border", stateBadge[a.state])}>{a.state}</Badge>
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  )}
                </CardContent>
              </Card>

              {/* Detail panel */}
              <div className="flex flex-col gap-3">
                {selected ? (
                  <>
                    <Card>
                      <CardContent className="p-4 flex flex-col gap-2">
                        <div className="flex items-start justify-between gap-2">
                          <div>
                            <div className="text-xs uppercase tracking-wide text-muted-foreground">{selected.id}</div>
                            <div className="text-base font-medium">{selected.action}</div>
                            <div className="text-xs text-muted-foreground">{selected.reason}</div>
                          </div>
                          <Badge variant="outline" className={cn("border", stateBadge[selected.state])}>{selected.state}</Badge>
                        </div>

                        {/* Authority band */}
                        <div className={cn("text-xs rounded border px-2 py-1 flex items-center gap-1",
                          authForSelected === "authorized"   ? "border-emerald-300 bg-emerald-50 text-emerald-900"
                          : authForSelected === "conflict"   ? "border-rose-300 bg-rose-50 text-rose-900"
                          : authForSelected === "unauthorized" ? "border-amber-300 bg-amber-50 text-amber-900"
                          :                                    "border-slate-300 bg-slate-50 text-slate-700")}>
                          {authForSelected === "authorized"   && <><ShieldCheck className="h-3 w-3" /> Authority verified — you may approve as {ops.role}.</>}
                          {authForSelected === "conflict"     && <><AlertTriangle className="h-3 w-3" /> Conflict of interest — separation of duties prevents self-approval.</>}
                          {authForSelected === "unauthorized" && <><ShieldAlert className="h-3 w-3" /> Unauthorized — {ops.role} cannot approve requests requiring {selected.role}.</>}
                          {authForSelected === "no-selection" && <>No approval selected.</>}
                        </div>

                        <div className="grid grid-cols-2 gap-2 text-xs mt-1">
                          <div><span className="text-muted-foreground">Service · </span>{selected.serviceId ?? "—"}</div>
                          <div><span className="text-muted-foreground">Env · </span>{selected.environment}</div>
                          <div><span className="text-muted-foreground">Requestor · </span>{selected.requestedByRole}</div>
                          <div><span className="text-muted-foreground">Digital worker · </span>{selected.digitalWorker}</div>
                          <div><span className="text-muted-foreground">Execution · </span>
                            <button className="underline underline-offset-2" onClick={() => navigate(`/runops/executions/${selected.executionId}`)}>{selected.executionId}</button>
                          </div>
                          <div><span className="text-muted-foreground">Incident · </span>
                            {selected.incidentId
                              ? <button className="underline underline-offset-2" onClick={() => navigate(`/runops/incidents/${selected.incidentId}`)}>{selected.incidentId}</button>
                              : "—"}
                          </div>
                          <div><span className="text-muted-foreground">Change · </span>{selected.changeTicket ?? "none"}</div>
                          <div><span className="text-muted-foreground">Risk · </span>{selected.risk}</div>
                          <div className="col-span-2"><span className="text-muted-foreground">Business impact · </span>{selected.businessImpact}</div>
                          <div><span className="text-muted-foreground">AI confidence · </span>{selected.aiConfidence}%</div>
                          <div><span className="text-muted-foreground">Policy · </span>{selected.policyResult}</div>
                          <div className="col-span-2 text-muted-foreground">{selected.policyDetail}</div>
                          <div><span className="text-muted-foreground">Required role · </span>{selected.role}</div>
                          <div><span className="text-muted-foreground">Separation · </span>{selected.requiresSeparation ? "required" : "not required"}</div>
                          <div><span className="text-muted-foreground">Deadline · </span>
                            <span className={cn(nearExpiration(selected) && "text-amber-700 font-medium")}>{timeUntil(selected.deadlineAt)}</span>
                            {nearExpiration(selected) && <Badge variant="outline" className="ml-1 border-amber-300 bg-amber-50 text-amber-900">Near expiration</Badge>}
                          </div>
                          <div><span className="text-muted-foreground">Rollback · </span>{selected.rollbackReadiness}</div>
                          <div className="col-span-2"><span className="text-muted-foreground">Blast radius · </span>{selected.blastRadius}</div>
                        </div>

                        <div className="text-xs uppercase tracking-wide text-muted-foreground mt-2">Alternatives</div>
                        <ul className="text-xs list-disc pl-4">{(selected.alternatives ?? []).map((x, i) => <li key={i}>{x}</li>)}</ul>

                        <div className="text-xs uppercase tracking-wide text-muted-foreground mt-2">Evidence</div>
                        <ul className="text-xs list-disc pl-4">
                          {(selected.evidenceRefs ?? []).map((e, i) => (
                            <li key={i}>
                              <button className="underline underline-offset-2" onClick={() => audit("Evidence opened", `${selected.id} · ${e}`)}>{e}</button>
                            </li>
                          ))}
                        </ul>

                        <div className="text-xs uppercase tracking-wide text-muted-foreground mt-2">Requestor history</div>
                        <div className="text-xs">Approved {selected.requestorHistory?.approved ?? 0} · Denied {selected.requestorHistory?.denied ?? 0} · {selected.requestorHistory?.recent}</div>
                        <div className="text-xs uppercase tracking-wide text-muted-foreground mt-1">Approver authority</div>
                        <div className="text-xs">{selected.approverAuthority}</div>

                        {/* Actions */}
                        <div className="flex flex-wrap gap-2 mt-2">
                          <Button size="sm" onClick={() => { setReason(""); setDialog("approve"); }}
                            disabled={authForSelected !== "authorized" || selected.state !== "pending"}
                            title={authForSelected !== "authorized" ? `Cannot approve — ${authForSelected}` : "Approve"}
                            aria-label="Approve"><CheckCircle2 className="h-4 w-4" /> Approve</Button>
                          <Button size="sm" variant="outline" onClick={() => { setReason(""); setDialog("deny"); }}
                            disabled={authForSelected === "unauthorized" || selected.state !== "pending"}
                            aria-label="Deny"><XCircle className="h-4 w-4" /> Deny</Button>
                          <Button size="sm" variant="outline" onClick={() => { setReason(""); setDialog("changes"); }}
                            disabled={selected.state !== "pending"}
                            aria-label="Request changes"><MessageSquareWarning className="h-4 w-4" /> Request changes</Button>
                          <Button size="sm" variant="outline" onClick={() => setDialog("delegate")}
                            disabled={selected.state !== "pending"}
                            aria-label="Delegate"><ArrowRightLeft className="h-4 w-4" /> Delegate</Button>
                          <Button size="sm" variant="outline" onClick={() => { setReason(""); setDialog("escalate"); }}
                            disabled={selected.state !== "pending"}
                            aria-label="Escalate"><UserCog className="h-4 w-4" /> Escalate</Button>
                          <Button size="sm" variant="outline" onClick={() => { setReason(""); setDialog("exception"); }}
                            disabled={selected.state !== "pending" || authForSelected === "unauthorized"}
                            aria-label="Issue time-limited exception"><Timer className="h-4 w-4" /> Time-limited exception</Button>
                          <Button size="sm" variant="outline" onClick={() => { setReason(""); setDialog("breakglass"); }}
                            disabled={selected.state !== "pending"}
                            aria-label="Invoke break glass"><KeyRound className="h-4 w-4" /> Break glass</Button>
                          <Button size="sm" variant="ghost" onClick={() => navigate(`/runops/executions/${selected.executionId}`)} aria-label="Open execution"><ExternalLink className="h-4 w-4" /> Execution</Button>
                          {selected.incidentId && <Button size="sm" variant="ghost" onClick={() => navigate(`/runops/incidents/${selected.incidentId}`)} aria-label="Open incident"><ExternalLink className="h-4 w-4" /> Incident</Button>}
                        </div>
                      </CardContent>
                    </Card>

                    {/* Comments / decision history */}
                    <Card>
                      <CardContent className="p-4">
                        <div className="text-xs uppercase tracking-wide text-muted-foreground mb-2">Comments & decision history (immutable)</div>
                        <ul className="text-xs space-y-1 max-h-56 overflow-auto">
                          {(selected.decisions ?? []).slice().reverse().map((d, i) => (
                            <li key={i} className="border rounded px-2 py-1"><span className="text-muted-foreground">{new Date(d.at).toLocaleTimeString()} · {d.by} · {d.action}:</span> {d.reason}</li>
                          ))}
                        </ul>
                        <div className="flex gap-2 mt-2">
                          <Input value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Add comment (audited)…" aria-label="Comment" />
                          <Button size="sm" variant="outline" onClick={doComment} disabled={!comment.trim()}>Post</Button>
                        </div>
                      </CardContent>
                    </Card>
                  </>
                ) : (
                  <Card><CardContent className="p-8 text-center text-sm text-muted-foreground">Select an approval to see details.</CardContent></Card>
                )}
              </div>
            </div>
          </TabsContent>
        ))}

        {/* Policy exceptions tab */}
        <TabsContent value="exceptions">
          <Card>
            <CardContent className="p-0">
              {exceptions.length === 0 ? (
                <div className="p-8 text-center text-sm text-muted-foreground">No policy exceptions issued.</div>
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>ID</TableHead>
                      <TableHead>Approval</TableHead>
                      <TableHead>Policy</TableHead>
                      <TableHead>Scope</TableHead>
                      <TableHead>Issued</TableHead>
                      <TableHead>Expires</TableHead>
                      <TableHead>State</TableHead>
                      <TableHead></TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {exceptions.map((e) => {
                      const active = !e.revoked && new Date(e.expiresAt).getTime() > now;
                      return (
                        <TableRow key={e.id}>
                          <TableCell className="font-mono text-xs">{e.id}</TableCell>
                          <TableCell className="text-xs">{e.approvalId}</TableCell>
                          <TableCell className="text-xs">{e.policy}</TableCell>
                          <TableCell className="text-xs">{e.scope}</TableCell>
                          <TableCell className="text-xs">{new Date(e.issuedAt).toLocaleTimeString()} · {e.issuedBy}</TableCell>
                          <TableCell className="text-xs">{active ? timeUntil(e.expiresAt) : "—"}</TableCell>
                          <TableCell>
                            <Badge variant="outline" className={cn("border",
                              e.revoked ? "border-rose-300 bg-rose-50 text-rose-900"
                              : active ? "border-amber-300 bg-amber-50 text-amber-900"
                              : "border-slate-300 bg-slate-50 text-slate-700")}>
                              {e.revoked ? "revoked" : active ? "active" : "expired"}
                            </Badge>
                          </TableCell>
                          <TableCell>
                            <Button size="sm" variant="outline" onClick={() => doRevokeException(e.id)} disabled={e.revoked || !active} aria-label={`Revoke ${e.id}`}>
                              <Ban className="h-4 w-4" /> Revoke
                            </Button>
                          </TableCell>
                        </TableRow>
                      );
                    })}
                  </TableBody>
                </Table>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Break glass tab */}
        <TabsContent value="breakglass">
          <Card>
            <CardContent className="p-0">
              {breakglass.length === 0 ? (
                <div className="p-8 text-center text-sm text-muted-foreground">No break-glass invocations recorded.</div>
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>ID</TableHead>
                      <TableHead>Approval</TableHead>
                      <TableHead>Target</TableHead>
                      <TableHead>Invoked</TableHead>
                      <TableHead>Reason</TableHead>
                      <TableHead>Review task</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {breakglass.map((b) => (
                      <TableRow key={b.id}>
                        <TableCell className="font-mono text-xs">{b.id}</TableCell>
                        <TableCell className="text-xs">{b.approvalId}</TableCell>
                        <TableCell className="text-xs">{b.targetRef}</TableCell>
                        <TableCell className="text-xs">{new Date(b.invokedAt).toLocaleTimeString()} · {b.invokedBy}</TableCell>
                        <TableCell className="text-xs max-w-[320px] truncate">{b.reason}</TableCell>
                        <TableCell className="text-xs">{b.reviewTaskId}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Dialogs */}
      <Dialog open={dialog === "approve"} onOpenChange={(o) => !o && setDialog(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Approve {selected?.id}</DialogTitle></DialogHeader>
          <div className="text-sm">{selected && isSensitive(selected) ? "This is a sensitive action — reason is required." : "Optional reason for the record."}</div>
          <Label htmlFor="ap-reason">Reason</Label>
          <Textarea id="ap-reason" value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Why is this safe to approve?" />
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialog(null)}>Cancel</Button>
            <Button onClick={doApprove} disabled={authForSelected !== "authorized" || (selected ? (isSensitive(selected) && reason.trim().length < 6) : true)}>Approve</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={dialog === "deny"} onOpenChange={(o) => !o && setDialog(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Deny {selected?.id}</DialogTitle></DialogHeader>
          <div className="text-sm">Reason is required and will cancel the linked execution.</div>
          <Label htmlFor="dn-reason">Reason</Label>
          <Textarea id="dn-reason" value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Reason for denial" />
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialog(null)}>Keep pending</Button>
            <Button onClick={doDeny} disabled={reason.trim().length < 6 || authForSelected === "unauthorized"}>Deny</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={dialog === "changes"} onOpenChange={(o) => !o && setDialog(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Request changes on {selected?.id}</DialogTitle></DialogHeader>
          <Textarea value={reason} onChange={(e) => setReason(e.target.value)} placeholder="What needs to change before you can approve?" />
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialog(null)}>Cancel</Button>
            <Button onClick={doRequestChanges} disabled={reason.trim().length < 6}>Request changes</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={dialog === "delegate"} onOpenChange={(o) => !o && setDialog(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Delegate approval {selected?.id}</DialogTitle></DialogHeader>
          <Label>Delegate to</Label>
          <Select value={delegateTo} onValueChange={setDelegateTo}>
            <SelectTrigger><SelectValue /></SelectTrigger>
            <SelectContent>
              <SelectItem value="Service Owner">Service Owner</SelectItem>
              <SelectItem value="Change Manager">Change Manager</SelectItem>
              <SelectItem value="Incident Commander">Incident Commander</SelectItem>
              <SelectItem value="Platform Engineer">Platform Engineer</SelectItem>
            </SelectContent>
          </Select>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialog(null)}>Cancel</Button>
            <Button onClick={doDelegate}>Delegate</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={dialog === "escalate"} onOpenChange={(o) => !o && setDialog(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Escalate {selected?.id}</DialogTitle></DialogHeader>
          <div className="text-sm">Reassigns the request to Incident Commander and pages them.</div>
          <Textarea value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Why escalate?" />
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialog(null)}>Cancel</Button>
            <Button onClick={doEscalate}>Escalate</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={dialog === "exception"} onOpenChange={(o) => !o && setDialog(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Issue time-limited exception for {selected?.id}</DialogTitle></DialogHeader>
          <div className="grid grid-cols-2 gap-2">
            <div>
              <Label>Duration (minutes, 5–240)</Label>
              <Input inputMode="numeric" value={exceptionMinutes} onChange={(e) => setExceptionMinutes(e.target.value.replace(/[^0-9]/g, ""))} />
            </div>
            <div>
              <Label>Scope</Label>
              <Input value={exceptionScope} onChange={(e) => setExceptionScope(e.target.value)} />
            </div>
          </div>
          <Label>Reason</Label>
          <Textarea value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Operational justification" />
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialog(null)}>Cancel</Button>
            <Button onClick={doIssueException} disabled={reason.trim().length < 6}>Issue exception</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={dialog === "breakglass"} onOpenChange={(o) => !o && setDialog(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Invoke break glass on {selected?.id}</DialogTitle></DialogHeader>
          <div className="text-sm text-rose-900 bg-rose-50 border border-rose-200 rounded p-2">
            High-severity emergency approval. Creates an audit event and a mandatory review task assigned to the Auditor role. Only Incident Commander, Service Owner, Platform Engineer, Executive, or Demo Controller may invoke.
          </div>
          <Label>Justification (min 12 characters)</Label>
          <Textarea value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Explain the emergency" />
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialog(null)}>Cancel</Button>
            <Button onClick={doBreakGlass} disabled={reason.trim().length < 12}>Invoke break glass</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
