import type { CommercialGuideContent } from "../../types";

/**
 * CDT-COMMERCIAL-GUIDE-STAFFING
 *
 * Authored strictly from what `CommercialStaffingResources.tsx`, the components in
 * `src/commercial/staffing/*` and `src/data/staffingResourcesMockData.ts` actually
 * render. No staffing calculation, scenario, table or resource value is changed.
 */
export const commercialStaffingGuide: CommercialGuideContent = {
  pageId: "commercial-staffing-resources",
  route: "/commercial/staffing-resources",
  match: "exact",
  pageTitle: "Staffing & Resources",
  guideTitle: "Staffing & Resources — People, Capacity and Feasibility Behind the Plan",
  audiences: ["Delivery", "Operations", "Commercial Lead", "Finance", "Executive", "Administrator"],
  modes: ["executive", "practitioner", "administrator"],
  estimatedReadingMinutes: 13,
  trainingLevel: "Intermediate",
  lastUpdated: "2026-07-31",

  /* ---------------- Overview ---------------- */
  purpose:
    "Staffing & Resources determines the people, roles, skills, timing, capacity, location model and operating structures Neurealm needs to support Day 0, Day 1 and Day 2. It converts scope and activation into demand, compares that demand against real supply, and shows whether the commercial plan can actually be staffed.",
  represents:
    "A prototype internal staffing plan for the Citrix Healthcare Operating Model Engagement, last updated June 17, 2026. It renders peak demand of 48.5 FTEs, 54.5 total planned FTEs, 48.0 filled, 6 open positions, 93% coverage, 10 planned roles, 12 critical roles, 6 pipeline candidates, 4 operating structures, 6 capacity gaps, 5 resource risks and 6 executive attention items, under Conservative, Base and Upside scenarios.",
  whyItMatters:
    "Revenue is only deliverable if the capacity behind it exists on the date it is needed. Peak simultaneous demand of 48.5 FTEs falls between August 16 and October 15, 2026, while SRE Lead, Transition Lead and Automation Lead are still open and two functions sit at or above the 95% utilization threshold. If those gaps are not closed, staffing cost, cash timing, the schedule and the go-live commitment are all wrong at once.",
  moduleConnection:
    "Program, Portfolio, Scenarios, Program & Timeline and Timelines set scope, activation and dates. This page converts them into FTE demand, role coverage, utilization and hiring pipeline. Its outputs feed P&L as staffing cost, Cash as start-date and payment timing, Timelines and Governance as readiness and escalation, Scenarios as feasibility, and Overview as confidence.",
  questionsAnswered: [
    "How many resources are needed, and at what peak?",
    "When are they needed across Day 0, Day 1 and Day 2?",
    "Which roles are critical to service continuity?",
    "Which positions are open and by when must they be filled?",
    "Is capacity sufficient against forecast demand?",
    "Where are resources overallocated above the utilization threshold?",
    "What is the staffing-cost impact of the plan?",
    "Can the activation plan actually be delivered with this capacity?",
  ],
  expectedOutcome:
    "You can state peak FTE demand, distinguish it from named headcount, name every open critical role and its required-by date, quantify each capacity gap and its sourcing strategy, and say whether the selected scenario is deliverable or must be re-planned before approval.",
  lifecycleStages: [
    "Commercial Structuring",
    "Financial Modeling",
    "Delivery Planning",
    "Mobilization",
    "Execution",
    "Operations",
    "Continuous Improvement",
  ],
  prerequisites: [
    { id: "pre-1", label: "Account scope", route: "/commercial/portfolio", detail: "Accounts and segments that generate service demand." },
    { id: "pre-2", label: "Activation plan", route: "/commercial/program", detail: "How many accounts activate, and when — the primary driver of demand." },
    { id: "pre-3", label: "Program schedule", route: "/commercial/program-timeline", detail: "Phase dates that set when each role is required." },
    { id: "pre-4", label: "Services scope", detail: "Delivery, migration, modernization and transition work behind Delivery demand." },
    { id: "pre-5", label: "Support scope", detail: "RunOps, SRE, service management and support-function coverage commitments." },
    { id: "pre-6", label: "Role model", detail: "The 10 planned roles and the 4 operating structures they sit in." },
    { id: "pre-7", label: "Skills requirements", detail: "Critical skills per function, such as SRE, observability, automation and migration engineering." },
    { id: "pre-8", label: "Loaded cost", route: "/commercial/model/pnl", detail: "Employee and contractor loaded rates used to price the plan." },
    { id: "pre-9", label: "Location assumptions", detail: "Onshore, nearshore, offshore and hybrid mix per role." },
    { id: "pre-10", label: "Availability and hiring lead time", detail: "Recruitment lead time of 8 to 10 weeks and pipeline conversion of 60%." },
  ],
  ownership: {
    businessOwner: "Delivery Executive",
    commercialOwner: "Commercial Lead",
    technicalOwner: "RunOps Lead",
    executiveApprover: "Executive Sponsor",
    primaryUsers: [
      "Staffing Lead",
      "Delivery Lead",
      "RunOps Lead",
      "SRE Lead",
      "Program Director",
      "Finance",
      "Commercial Lead",
      "Customer Success Lead",
      "Executive Sponsor",
      "Functional Managers",
    ],
    consumersOfOutput: [
      "P&L (Cost & EBITDA)",
      "Cash & Sustainability",
      "Timelines",
      "Program",
      "Governance",
      "Overview",
    ],
  },

  /* ---------------- How it works ---------------- */
  sections: [
    {
      id: "sec-scenario",
      title: "Scenario selector and page controls",
      explanation:
        "The header carries the scenario selector — Conservative (0.88 factor, slower ramp), Base (1.0, expected plan) and Upside (1.15, accelerated activation) — plus Export, Filters, Reset Mock Data and a notification badge covering 6 executive items. The scenario factor scales demand and planned values everywhere on the page. An 'Unsaved local changes' badge appears once you edit anything.",
      targetId: "staffing-scenario",
    },
    {
      id: "sec-summary",
      title: "Staffing summary",
      explanation:
        "Five cards: Total Planned FTEs, Peak (48.5), Resource Coverage (93%), Critical Roles Filled (42 of 45), Open Positions (3) and Peak Staffing Window (August 16 to October 15, 2026). Selecting a card reveals its definition, calculation, related roles and phases, capacity implications, risks and assumptions — so each headline number can be traced rather than assumed.",
      targetId: "staffing-summary",
    },
    {
      id: "sec-filters",
      title: "Filters and active filter chips",
      explanation:
        "Filter by search, phase, function, operating structure, status, resource type, location model and minimum utilization, plus open-only, gaps-only, at-risk-only and critical-only toggles. Active filters appear as removable chips. Filters change the totals you are reading, never the underlying plan.",
      targetId: "staffing-filters",
    },
    {
      id: "sec-role-plan",
      title: "Role staffing plan",
      explanation:
        "The 10 planned roles with Day 0, Day 1 and Day 2 demand, total planned, filled, open, shared, contractor, utilization, status, location model, resource type, owner, skills, start and end dates, dependencies, risks and notes. Baseline totals are 18.5 Day 0, 48.5 Day 1, 32.0 Day 2, 54.5 planned, 48.0 filled, 6 open and 93% utilization.",
      targetId: "staffing-role-plan",
    },
    {
      id: "sec-function-allocation",
      title: "FTE allocation by function, peak",
      explanation:
        "A donut of peak allocation: Delivery 24.0 FTEs (49%), RunOps and SRE 12.0 (25%), Customer Success 7.0 (14%) and Support Functions 5.5 (11%). Selecting a slice opens purpose, filled count, open roles, peak utilization, critical skills, phase demand, sharing model and risks, and can filter the role plan to that function.",
      targetId: "staffing-function-allocation",
    },
    {
      id: "sec-resource-health",
      title: "Resource health",
      explanation:
        "Eight health metrics: capacity versus demand 93%, 2 overallocated resources above the 95% threshold, skill coverage 88%, attrition risk Low, contractor dependency 12% (5.5 of 48.0 filled FTEs), bench availability 4.5 FTEs, offshore coverage 68% and onshore leadership coverage 100%. A View Risks action jumps to the resource risk register.",
      targetId: "staffing-resource-health",
    },
    {
      id: "sec-phase-cards",
      title: "Day 0, Day 1 and Day 2 phase cards",
      explanation:
        "Day 0, Build and Transition (June to August 15, 2026, peak 24.5 FTEs), Day 1, Operate and Stabilize (August 16 to November 15, peak 48.5) and Day 2, Optimize and Evolve (November 16 to December 31, peak 32.0). Each lists staffing focus and target outcome, and selecting a card filters the page to that phase.",
      targetId: "staffing-phase-cards",
    },
    {
      id: "sec-forecast",
      title: "Staffing forecast",
      explanation:
        "Monthly demand from June to December 2026 by function, switchable between FTE and percentage and between month and phase grouping. Demand rises from 18.5 in June to a September peak, then declines through Day 2. Selecting a segment filters the plan to that function and phase.",
      targetId: "staffing-forecast",
    },
    {
      id: "sec-critical-roles",
      title: "Critical-role coverage",
      explanation:
        "Twelve critical roles with status, owner, required-by date, phase and notes. Nine are Filled; SRE Lead is Open by August 15, Transition Lead is Open by July 15, Automation Lead is Open by November 1, and Problem Manager needs a backfill by September 1 as the incumbent rotates off. Interim coverage is not counted as filled.",
      targetId: "staffing-critical-roles",
    },
    {
      id: "sec-pipeline",
      title: "Resource pipeline",
      explanation:
        "Six named candidates moving through eight stages from Identified to Ready, with source and expected start date, alongside pipeline summary counts: 3 backfills, 2 new hires, 4 planned contractors, 3 internal transfers, 6 CoE shared assignments and 2 pending approvals. Advancing a stage is a local prototype action only.",
      targetId: "staffing-pipeline",
    },
    {
      id: "sec-operating-structures",
      title: "Operating structures",
      explanation:
        "Four structures with model, peak allocation, open roles, utilization and phase demand: Account Pods (dedicated and semi-dedicated, 12.0, 88%), Delivery Pods (phase-based, 18.0, 92%), RunOps and SRE CoE (shared and pooled, 12.0, 3 open, 95%) and Enterprise Shared Services (on demand, 6.5, 78%). The model determines whether capacity is truly dedicated.",
      targetId: "staffing-operating-structures",
    },
    {
      id: "sec-capacity-gaps",
      title: "Capacity gaps",
      explanation:
        "Six gaps with demand, available, gap, severity, required-by date, sourcing strategy, owner and status: SRE Leadership 1.0 by August 15, Automation Engineering 1.0 by November 1, Customer Success 0.5 by August 16, Support Functions 1.5 by July 31, Transition Leadership 1.0 by July 15 and Solution Delivery 2.0 by August 16. Every gap carries a strategy.",
      targetId: "staffing-capacity-gaps",
    },
    {
      id: "sec-risks",
      title: "Resource risks",
      explanation:
        "Five risks with severity, owner, impact, mitigation and status: peak utilization above threshold for RunOps and SRE, unfilled Transition Lead, automation capability below the Day 2 requirement, Customer Success below peak demand and limited buffer in shared support functions. Three are High severity and Open.",
      targetId: "staffing-risks",
    },
    {
      id: "sec-executive-attention",
      title: "Executive attention",
      explanation:
        "Six items requiring leadership action: SRE Lead open before Day 1 stabilization, Transition Lead needed before July 15, projected Day 2 automation gap, two resources above the preferred utilization threshold, limited support-function buffer and contractor onboarding that must start before peak demand. Shortcut actions jump to gaps, open positions and risks.",
      targetId: "staffing-executive-attention",
    },
  ],

  inputs: [
    { id: "in-1", label: "Account activation", description: "Number and timing of activating accounts; the primary driver of FTE demand.", owner: "Commercial Lead", source: "Program", required: true },
    { id: "in-2", label: "Service scope", description: "Delivery, migration, modernization and transition work behind Delivery demand of 24.0 peak FTEs.", owner: "Delivery Lead", required: true },
    { id: "in-3", label: "Support scope", description: "RunOps, SRE, service management and support coverage commitments.", owner: "RunOps Lead", required: true },
    { id: "in-4", label: "Program timing", description: "Phase dates that determine when each role is required, June to December 2026.", owner: "Program Director", source: "Timelines", required: true },
    { id: "in-5", label: "Role ratios", description: "Function mix behind the 49 / 25 / 14 / 11 percent peak allocation split.", owner: "Staffing Lead", required: true },
    { id: "in-6", label: "Skill requirements", description: "Critical skills per role, such as SRE, observability, automation, migration and HIPAA controls.", owner: "Functional Managers", required: true },
    { id: "in-7", label: "Loaded cost", description: "Fully loaded employee and contractor rates used to convert FTEs into cost.", owner: "Finance", source: "P&L", required: true },
    { id: "in-8", label: "Employee and contractor mix", description: "Resource types across Employee, Contractor, Shared CoE, Internal Transfer, New Hire and Backfill.", owner: "Staffing Lead", required: true },
    { id: "in-9", label: "Shared CoE assumptions", description: "Shared assignments counted at 50% availability, not as dedicated capacity.", owner: "Staffing Lead", required: true },
    { id: "in-10", label: "Location mix", description: "Onshore, nearshore, offshore and hybrid model per role; offshore coverage currently 68%.", owner: "Delivery Executive" },
    { id: "in-11", label: "Utilization threshold", description: "The 95% sustainable utilization ceiling used to flag overallocation.", owner: "Staffing Lead", required: true },
    { id: "in-12", label: "Hiring lead time", description: "Recruitment lead time of 8 to 10 weeks with 60% pipeline conversion.", owner: "Staffing Lead", required: true },
    { id: "in-13", label: "Attrition risk", description: "Attrition exposure among critical-role holders; currently assessed Low.", owner: "Functional Managers" },
    { id: "in-14", label: "Training and certification", description: "Enablement and certification required before a filled role is operationally available.", owner: "Neurealm CoE" },
    { id: "in-15", label: "Scenario", description: "Conservative, Base or Upside factor applied to demand and planned values.", owner: "Commercial Lead", source: "Scenarios", required: true },
  ],
  outputs: [
    { id: "out-1", label: "Peak FTE demand", description: "Highest simultaneous demand in any month: 48.5 FTEs under Base, in the Day 1 window.", consumedBy: ["P&L (Cost & EBITDA)", "Overview"] },
    { id: "out-2", label: "Planned resources", description: "Total planned FTEs across all phases: 54.5 under Base.", consumedBy: ["P&L (Cost & EBITDA)"] },
    { id: "out-3", label: "Filled positions", description: "Named coverage of 48.0 FTEs against the plan.", consumedBy: ["Governance", "Timelines"] },
    { id: "out-4", label: "Open positions", description: "6 open positions in the role plan and 3 open critical roles, each with a required-by date.", consumedBy: ["Governance", "Timelines"] },
    { id: "out-5", label: "Capacity gap", description: "Six quantified gaps totalling 7.0 FTEs with severity, required-by date, owner and sourcing strategy.", consumedBy: ["Governance", "Scenarios"] },
    { id: "out-6", label: "Utilization", description: "Role and structure utilization against the 95% sustainable threshold; 2 resources currently exceed it.", consumedBy: ["Governance", "Overview"] },
    { id: "out-7", label: "Critical-role status", description: "42 of 45 critical roles filled; SRE Lead, Transition Lead and Automation Lead outstanding.", consumedBy: ["Governance", "Timelines"] },
    { id: "out-8", label: "Hiring pipeline", description: "Six candidates by stage and source with expected start dates.", consumedBy: ["Cash & Sustainability", "Timelines"] },
    { id: "out-9", label: "Staffing cost", description: "The cost consequence of FTE volume, mix and location; must reconcile to P&L cost lines.", consumedBy: ["P&L (Cost & EBITDA)", "Cash & Sustainability"] },
    { id: "out-10", label: "Readiness", description: "Whether Day 0, Day 1 and Day 2 coverage will exist on the dates required.", consumedBy: ["Timelines", "Governance"] },
    { id: "out-11", label: "Resource risk", description: "Five registered staffing risks with severity, owner, impact and mitigation.", consumedBy: ["Governance", "Overview"] },
    { id: "out-12", label: "Scenario feasibility", description: "Whether the selected scenario can be staffed; Upside reduces coverage by 6 points.", consumedBy: ["Scenarios", "Executive Sponsor"] },
  ],
  businessRules: [
    { id: "br-1", rule: "Peak FTE demand is not the same as total named headcount.", explanation: "Peak is the highest simultaneous demand in a single month — 48.5 FTEs here. Total planned is 54.5 across all phases, because roles start and end at different times. Quoting one number for the other either overstates the team or understates the crunch." },
    { id: "br-2", rule: "Filled does not mean available on the required date.", explanation: "A named resource still needs onboarding, tooling access and certification. The plan notes onboarding must complete two weeks before the August 16 peak window opens. Treat availability, not naming, as the readiness test." },
    { id: "br-3", rule: "Shared resources must not be counted as fully dedicated across multiple functions.", explanation: "Shared CoE assignments are counted at 50% availability. Solution Architecture, Security and Compliance and Corporate Shared Services are shared across engagements; claiming their full FTE in each place double counts capacity that does not exist." },
    { id: "br-4", rule: "Contractor and employee costs must use the correct assumptions.", explanation: "Contractor FTEs are 12% of filled capacity. Contractor loaded rates differ from employee rates and often carry different payment terms, so applying a single blended rate misstates both cost on P&L and outflow timing on Cash." },
    { id: "br-5", rule: "Staffing demand must align with activation and schedule.", explanation: "Demand is driven by account activation and the program schedule. If activation moves, the monthly curve, the peak window and the hiring start dates all move with it — the plan is not a fixed team, it is a dated ramp." },
    { id: "br-6", rule: "Revenue growth cannot be considered feasible without capacity.", explanation: "The Upside scenario raises demand by 15% and reduces coverage by 6 points. Revenue that depends on activation Neurealm cannot staff is not upside; it is unfunded delivery risk carried in the model." },
    { id: "br-7", rule: "Critical roles may gate Day 0 or Day 1 readiness.", explanation: "SRE Lead is required before the Day 1 stabilization window and Transition Lead before Day 0 coordination completes. An open critical role is a gate on readiness, not a line item to be backfilled later." },
    { id: "br-8", rule: "Utilization above the defined threshold requires review.", explanation: "The sustainable threshold is 95%. RunOps and SRE sits at 95% and Automation and AI Operations at 96%, with two named resources flagged as overallocated. Sustained overallocation converts into attrition, service instability and hidden cost." },
    { id: "br-9", rule: "Open positions must include required-by dates.", explanation: "Every open critical role and capacity gap carries a date: July 15, July 31, August 15, August 16, September 1 and November 1. Without a required-by date, an open position cannot be tested against hiring lead time." },
    { id: "br-10", rule: "Role coverage must include skills, not only headcount.", explanation: "Skill coverage is 88% even though headcount coverage is 93%, because SRE leadership and automation engineering skills are short. Counting bodies without checking critical skills produces a plan that is numerically complete and operationally unable." },
    { id: "br-11", rule: "Staffing cost must reconcile to P&L.", explanation: "FTE volume, mix and location drive the cost lines on P&L. If the staffing plan changes and the cost model does not, EBITDA is reported against a team that is not the team being planned." },
    { id: "br-12", rule: "Start dates and payment timing must reconcile to Cash.", explanation: "Start dates from the pipeline determine when payroll and contractor invoices begin. A candidate expected in September does not create August outflow, and a contractor with different payment terms does not phase like an employee." },
    { id: "br-13", rule: "Day 2 automation assumptions must not reduce Day 1 staffing before the capability exists.", explanation: "Automation and AI Operations is currently At Risk with capability below the Day 2 requirement and an open Automation Lead. Booking the efficiency before the automation is built removes people who are still needed." },
    { id: "br-14", rule: "Location mix must reflect trust, customer, time-zone and operational requirements.", explanation: "Offshore coverage is 68% while onshore leadership coverage is 100%. Location is not a pure cost lever: leadership, customer-facing and compliance-sensitive roles carry onshore or hybrid requirements that constrain the mix." },
    { id: "br-15", rule: "Every capacity gap must have a sourcing strategy.", explanation: "Each of the six gaps names one — external hire with interim CoE cover, contractor capacity plus CoE support, pooled coverage, a shared-services commitment, internal transfer with accelerated recruitment, or contractor augmentation. A gap without a strategy is an unmanaged risk." },
  ],
  calculationLogic: [
    "Peak FTE demand = MAX over months of (Delivery + RunOps and SRE + Customer Success + Support Functions).",
    "Resource coverage = Filled FTEs / Total planned FTEs; 48.0 / 54.5 gives 93% at Base.",
    "Critical roles filled = Filled critical roles / Total critical roles, with interim cover excluded from Filled.",
    "Open positions = SUM of open positions across the role plan; critical open roles are reported separately.",
    "Peak staffing window = the months where total demand is at or above 90% of peak demand.",
    "Capacity gap = Demand minus Available, evaluated per area and reported with a required-by date.",
    "Scenario scaling multiplies demand and planned FTE values by the scenario factor: 0.88 Conservative, 1.00 Base, 1.15 Upside.",
    "Scenario coverage delta adjusts coverage by +4 points under Conservative and −6 points under Upside.",
    "Shared CoE assignments are counted at 50% availability rather than as dedicated FTEs.",
    "Filtered totals recompute Day 0, Day 1, Day 2, planned, filled, open and utilization from the visible rows only.",
    "Displayed FTE values are rounded to one decimal place.",
  ],
  relationship: {
    receivesFrom: [
      "Program",
      "Portfolio",
      "Activation plan",
      "Scenarios",
      "Program & Timeline",
      "Timelines",
      "Services scope",
      "Support scope",
      "Operating model",
      "Assumptions",
    ],
    models: [
      "FTE demand",
      "Role demand",
      "Capacity",
      "Utilization",
      "Role coverage",
      "Hiring pipeline",
      "Shared and dedicated allocation",
      "Day 0 staffing",
      "Day 1 staffing",
      "Day 2 staffing",
      "Resource risk",
    ],
    feeds: [
      "P&L",
      "Cash",
      "Program schedule",
      "Operational readiness",
      "Governance",
      "Scenario feasibility",
      "Overview",
    ],
  },
  downstreamImpacts: [
    { area: "Costs", effect: "FTE volume, employee and contractor mix and location model drive the staffing cost lines on P&L." },
    { area: "EBITDA", effect: "Overstated capacity or understated contractor cost inflates margin that delivery cannot reproduce." },
    { area: "Cash", effect: "Start dates and contractor payment terms set when payroll and invoice outflows actually begin." },
    { area: "Staffing", effect: "Open critical roles and hiring lead time set the earliest credible ramp." },
    { area: "Capacity", effect: "Utilization above 95% and shared-resource conflicts reduce the capacity the plan assumes." },
    { area: "Timeline", effect: "Unfilled critical roles push readiness activities and can move operational acceptance." },
    { area: "Activation", effect: "Activation cannot exceed the capacity available to deliver and support it." },
    { area: "Governance", effect: "Open critical roles, high-severity gaps and threshold breaches become forum and escalation items." },
    { area: "Risk", effect: "Five registered resource risks convert directly into program risk exposure." },
    { area: "Customer outcomes", effect: "Thin Day 1 coverage produces slower incident response and weaker adoption." },
  ],
  dataQuality: {
    dataSources: [
      "staffingResourcesMockData.ts — 5 summary cards, 3 phases, 7 monthly demand points, 4 functions, 8 health metrics, 10 roles, 12 critical roles, 6 pipeline items, 4 operating structures, 6 capacity gaps, 5 risks, 6 executive attention items",
      "Scenario factors: Conservative 0.88, Base 1.00, Upside 1.15",
      "Last updated: June 17, 2026 at 10:30 AM",
    ],
    updateFrequency: "Static prototype data; all edits live in React state and reset on reload or via Reset Mock Data.",
    knownGaps: [
      "No loaded cost rates, salary bands or staffing cost values are rendered on this page; cost lives on P&L.",
      "No automatic reconciliation exists between this plan and P&L or Cash — the link is described, not computed.",
      "No named individuals are modelled; pipeline candidates are anonymised as Candidate A through F.",
      "No time-zone coverage, shift rota or follow-the-sun model is represented behind the location mix.",
      "No certification completion percentage or training status is tracked per named resource.",
      "No attrition modelling, notice periods or ramp-down curves are calculated; attrition risk is a single Low rating.",
      "No cost of contractor versus employee is compared numerically, despite the 12% dependency being flagged.",
      "Utilization is a static per-role value, not a computed function of assigned work.",
      "Export, notification and pipeline-advance actions are simulated; no backend is called and nothing persists.",
    ],
    changeControl:
      "Read-only against any system of record. Filters, edits, added roles, added risks and pipeline advances mutate local React state only.",
    lineage: "Static module import; no query, no run manifest, no persistence layer.",
  },
  modelConfidence: "Medium",
  confidenceBasis: ["Staffing assumptions", "Cost assumptions", "Timing", "Source completeness"],
  confidenceGuidance:
    "Structure is reliable: the function split, phase shape, operating structures and gap list reflect how the engagement is intended to be staffed. Values are illustrative — FTE counts, utilization and coverage are prototype assumptions with no cost model behind them. Trust the shape of the demand curve and the identified gaps; confirm every number and date with the named owner before committing capacity or cost.",
  commercialReadiness: "Review Required",
  readinessCriteria: [
    "Peak demand is covered by available capacity in the peak window, not merely by total planned headcount.",
    "Every critical role is filled, or has a named interim plus a dated recruitment plan.",
    "No role or structure sits above the 95% sustainable utilization threshold without an agreed mitigation.",
    "Shared CoE capacity is confirmed at its stated availability by the owning function.",
    "Hiring start dates precede each required-by date by at least the 8 to 10 week lead time.",
    "Staffing cost is reconciled to P&L and start-date timing to Cash.",
    "Every capacity gap has a sourcing strategy, an owner and an accepted or resolved status.",
  ],

  /* ---------------- How to use it ---------------- */
  workflow: [
    { id: "wf-1", step: 1, title: "Confirm the scenario", description: "Select Conservative, Base or Upside and note the factor applied; every FTE value on the page scales with it.", role: "Commercial Lead" },
    { id: "wf-2", step: 2, title: "Confirm account and activation plan", description: "Check the activation assumptions driving demand before reading any capacity number.", role: "Commercial Lead" },
    { id: "wf-3", step: 3, title: "Review monthly and phase demand", description: "Read the forecast and phase cards to locate peak demand and the August 16 to October 15 peak window.", role: "Staffing Lead" },
    { id: "wf-4", step: 4, title: "Review functional allocation", description: "Open each donut segment to check filled, open roles, peak utilization and critical skills per function.", role: "Staffing Lead" },
    { id: "wf-5", step: 5, title: "Review filled and open roles", description: "Use the role plan with open-only filtering to list every unfilled position and its owner.", role: "Delivery Lead" },
    { id: "wf-6", step: 6, title: "Review critical-role coverage", description: "Check the 12 critical roles and the required-by dates on SRE Lead, Transition Lead, Automation Lead and Problem Manager.", role: "RunOps Lead" },
    { id: "wf-7", step: 7, title: "Review utilization", description: "Filter to 95% and above to find overallocated roles, then confirm whether the load is sustainable.", role: "Functional Managers" },
    { id: "wf-8", step: 8, title: "Review shared and contractor dependency", description: "Check shared CoE allocations and the 12% contractor dependency against the operating structure models.", role: "Staffing Lead" },
    { id: "wf-9", step: 9, title: "Review hiring lead time", description: "Test each required-by date against the 8 to 10 week lead time and 60% pipeline conversion.", role: "Staffing Lead" },
    { id: "wf-10", step: 10, title: "Reconcile staffing cost to P&L", description: "Confirm FTE volume, mix and location assumptions match the cost lines carried in the P&L model.", role: "Finance" },
    { id: "wf-11", step: 11, title: "Reconcile timing to Cash and Timelines", description: "Confirm start dates and payment terms match cash phasing, and ramp dates match the readiness schedule.", role: "Finance" },
    { id: "wf-12", step: 12, title: "Resolve or escalate capacity gaps", description: "For each of the six gaps, confirm the sourcing strategy is live, or escalate it with a dated recovery plan.", role: "Program Director" },
    { id: "wf-13", step: 13, title: "Confirm scenario feasibility", description: "State plainly whether the selected scenario can be staffed on the dates it assumes, and record the answer.", role: "Executive Sponsor" },
  ],
  actionsAvailable: [
    "Switch scenario between Conservative, Base and Upside.",
    "Open filters and filter by search, phase, function, structure, status, resource type, location model or minimum utilization.",
    "Toggle open-positions-only, capacity-gaps-only, at-risk-only and critical-only, and clear filters from the chips.",
    "Select a summary card to read its definition, calculation, capacity implications, risks and assumptions.",
    "Select a phase card to filter the page to Day 0, Day 1 or Day 2.",
    "Switch the forecast between FTE and percentage and between month and phase grouping.",
    "Select a forecast segment or donut slice to filter the role plan to that function and phase.",
    "Edit a role locally, or add a planned role placeholder (prototype only).",
    "Update critical-role status locally and advance or add pipeline candidates (prototype only).",
    "Record a capacity-gap action and add or update a resource risk (prototype only).",
    "Jump from resource health or executive attention to gaps, open positions and risks.",
    "Export staffing summary, role plan, capacity forecast, open positions or the executive update (prototype only).",
    "Reset all mock data to the prototype baseline.",
  ],
  teamActivities: [
    { id: "ta-1", activity: "Maintain staffing demand and supply, pipeline and open positions", role: "Staffing Lead", cadence: "Weekly" },
    { id: "ta-2", activity: "Validate delivery roles, skills and phase-based pod sizing", role: "Delivery Lead", cadence: "Weekly" },
    { id: "ta-3", activity: "Validate operational coverage, escalation and on-call adequacy", role: "RunOps Lead", cadence: "Weekly" },
    { id: "ta-4", activity: "Validate reliability and automation coverage against Day 2 requirements", role: "SRE Lead", cadence: "Weekly" },
    { id: "ta-5", activity: "Validate account coverage and adoption capacity", role: "Customer Success Lead", cadence: "Biweekly" },
    { id: "ta-6", activity: "Validate loaded cost, contractor rates and reconciliation to P&L and Cash", role: "Finance", cadence: "Monthly" },
    { id: "ta-7", activity: "Validate staffing timing against the program schedule and readiness path", role: "Program Director", cadence: "Weekly" },
    { id: "ta-8", activity: "Validate demand against commercial assumptions and activation", role: "Commercial Lead", cadence: "Monthly" },
    { id: "ta-9", activity: "Approve material staffing changes and threshold breaches", role: "Governance Lead", cadence: "Monthly" },
    { id: "ta-10", activity: "Approve staffing funding, contractor spend and accepted resource risk", role: "Executive Sponsor", cadence: "Monthly" },
  ],
  roles: [
    { role: "Delivery Executive", responsibility: "Business owner for the staffing plan and accountable for delivery capacity overall." },
    { role: "Staffing Lead", responsibility: "Owns demand and supply, role coverage, pipeline, utilization and capacity gaps." },
    { role: "Delivery Lead", responsibility: "Validates delivery roles, skills and pod structure against the delivery scope." },
    { role: "RunOps Lead", responsibility: "Owns operational coverage, incident and problem capacity and Day 1 readiness." },
    { role: "SRE Lead", responsibility: "Owns reliability and automation capacity, including the Day 2 automation capability." },
    { role: "Customer Success Lead", responsibility: "Owns account coverage, adoption capacity and pooled coverage decisions." },
    { role: "Finance", responsibility: "Owns loaded cost, contractor rates and reconciliation to P&L and Cash." },
    { role: "Commercial Lead", responsibility: "Owns the link between commercial assumptions, activation and staffing demand." },
    { role: "Program Director", responsibility: "Owns staffing timing against the schedule and escalation of blocking gaps." },
    { role: "Governance Lead", responsibility: "Owns approval routing for material staffing changes and threshold breaches." },
    { role: "Executive Sponsor", responsibility: "Approves funding, contractor dependency and any accepted resource risk." },
    { role: "Functional Managers", responsibility: "Own named-resource availability, skills, utilization and attrition exposure." },
  ],
  raci: [
    {
      activity: "Maintain the staffing demand and supply plan",
      assignments: [
        { role: "Staffing Lead", raci: "R" },
        { role: "Delivery Executive", raci: "A" },
        { role: "Delivery Lead", raci: "C" },
        { role: "Executive Sponsor", raci: "I" },
      ],
    },
    {
      activity: "Validate operational and reliability coverage",
      assignments: [
        { role: "RunOps Lead", raci: "R" },
        { role: "SRE Lead", raci: "R" },
        { role: "Delivery Executive", raci: "A" },
        { role: "Program Director", raci: "C" },
      ],
    },
    {
      activity: "Reconcile staffing cost and timing to P&L and Cash",
      assignments: [
        { role: "Finance", raci: "R" },
        { role: "Commercial Lead", raci: "A" },
        { role: "Staffing Lead", raci: "C" },
        { role: "Executive Sponsor", raci: "I" },
      ],
    },
    {
      activity: "Resolve or escalate capacity gaps",
      assignments: [
        { role: "Staffing Lead", raci: "R" },
        { role: "Program Director", raci: "A" },
        { role: "Governance Lead", raci: "C" },
        { role: "Executive Sponsor", raci: "I" },
      ],
    },
    {
      activity: "Approve scenario feasibility and staffing funding",
      assignments: [
        { role: "Executive Sponsor", raci: "A" },
        { role: "Commercial Lead", raci: "R" },
        { role: "Finance", raci: "C" },
        { role: "Delivery Executive", raci: "C" },
      ],
    },
  ],
  reviewRequirements: [
    "Weekly review of open positions, pipeline stage movement and required-by dates.",
    "Weekly review of critical-role coverage before the Day 1 stabilization window.",
    "Review of any role or structure above the 95% utilization threshold.",
    "Monthly reconciliation of staffing cost and start-date timing with Finance.",
    "Review of shared CoE availability with each owning function before it is counted as capacity.",
    "Review of contractor dependency whenever it moves materially from the current 12%.",
    "Scenario feasibility review before any activation or revenue change is accepted.",
  ],
  approvalRequirements: [
    "Executive Sponsor approves staffing funding and accepted resource risk.",
    "Governance approves material staffing changes and sustained threshold breaches.",
    "Finance approves loaded-cost and contractor-rate assumptions used for reconciliation.",
    "Delivery Executive approves role plan changes affecting delivery commitments.",
    "RunOps and SRE Leads approve any reduction in operational or reliability coverage.",
    "Commercial Lead approves demand changes arising from activation or scope movement.",
  ],
  decisions: [
    { id: "dec-1", decision: "Fill SRE Lead externally or extend interim CoE cover", decidedBy: "RunOps Executive", evidence: "Open critical role required by August 15, 2026, with a 1.0 FTE High-severity gap." },
    { id: "dec-2", decision: "Accelerate Transition Lead via internal transfer", decidedBy: "Delivery Executive", evidence: "Open critical role required by July 15, 2026; candidate C accepted with a July 10 expected start." },
    { id: "dec-3", decision: "Add contractor automation capacity before peak demand", decidedBy: "SRE Lead", evidence: "Automation and AI Operations at 96% utilization, At Risk, with a 1.0 FTE gap by November 1." },
    { id: "dec-4", decision: "Use pooled coverage for Customer Success during stabilization", decidedBy: "Customer Success Lead", evidence: "0.5 FTE gap against 7.0 peak demand, required by August 16." },
    { id: "dec-5", decision: "Agree service-level commitments for shared support functions", decidedBy: "PMO", evidence: "1.5 FTE gap required by July 31 with limited buffer flagged in resource health." },
    { id: "dec-6", decision: "Accept or re-plan the Upside scenario", decidedBy: "Executive Sponsor", evidence: "Upside raises demand 15% and reduces coverage by 6 points against existing open critical roles." },
  ],
  whatToDoNext: [
    "List every open critical role with its required-by date and confirm recruitment has already started.",
    "Test each required-by date against the 8 to 10 week hiring lead time and flag any date that is already unreachable.",
    "Confirm shared CoE availability with each owning function before counting it toward coverage.",
    "Take the two overallocated resources to their functional managers with a mitigation option.",
    "Reconcile the staffing plan to P&L cost lines and to Cash start-date phasing.",
    "Escalate the three High-severity capacity gaps with owners and dated recovery plans.",
    "State scenario feasibility explicitly before any activation increase is approved.",
  ],
  relatedPages: [
    { pageId: "commercial-program", label: "Program", route: "/commercial/program", relationship: "Upstream" },
    { pageId: "commercial-portfolio", label: "Portfolio", route: "/commercial/portfolio", relationship: "Upstream" },
    { pageId: "commercial-scenarios", label: "Scenarios", route: "/commercial/scenarios", relationship: "Companion" },
    { pageId: "commercial-program-timeline", label: "Timelines", route: "/commercial/program-timeline", relationship: "Companion" },
    { pageId: "commercial-governance", label: "Governance", route: "/commercial/neurealm-governance", relationship: "Companion" },
    { pageId: "commercial-pnl", label: "P&L (Cost & EBITDA)", route: "/commercial/model/pnl", relationship: "Downstream" },
    { pageId: "commercial-cash", label: "Cash & Sustainability", route: "/commercial/model/cash", relationship: "Downstream" },
    { pageId: "commercial-overview", label: "Overview", route: "/commercial", relationship: "Downstream" },
  ],

  /* ---------------- Interpretation & training ---------------- */
  interpretation: [
    {
      band: "healthy",
      label: "Staffable plan",
      criteria: [
        "Peak demand is covered by available capacity in the peak window.",
        "Critical roles are filled by their required-by dates.",
        "Utilization is sustainable and below the 95% threshold.",
        "Staffing cost reconciles to P&L and start-date timing reconciles to Cash.",
        "Staffing timing aligns with the activation plan and program schedule.",
        "Shared capacity is realistic and confirmed by the owning functions.",
        "The selected scenario is deliverable with the capacity planned.",
      ],
      action: "Hold the plan, keep pipeline and required-by dates current, and continue weekly demand and supply review.",
    },
    {
      band: "warning",
      label: "Capacity under pressure",
      criteria: [
        "Critical roles remain open with dates approaching.",
        "Utilization is at or near the 95% sustainable threshold.",
        "Contractor dependency is increasing beyond the planned mix.",
        "Shared resources are in conflict across functions or engagements.",
        "Hiring lead time is approaching the required-by date.",
        "Staffing cost or cash timing has not been updated for recent changes.",
      ],
      action: "Assign an owner and date to each gap, start sourcing now rather than at the required-by date, and update cost and cash timing before the next review.",
    },
    {
      band: "critical",
      label: "Not staffable as planned",
      criteria: [
        "Activation exceeds delivery capacity.",
        "Day 1 begins without required operations leadership in place.",
        "Staffing cost is materially understated in the financial model.",
        "The same shared FTE is counted in more than one place.",
        "Required skills are unavailable regardless of headcount.",
        "The model recommends a scenario that cannot be staffed.",
      ],
      action: "Escalate to the Executive Sponsor, pause approval of the affected scenario or activation increase, and re-plan capacity, cost and dates before proceeding.",
    },
  ],
  commonMistakes: [
    { id: "cm-1", description: "Confusing peak FTE with named headcount. Peak is 48.5 simultaneous FTEs; total planned across all phases is 54.5. They answer different questions.", correction: "Quote peak for capacity crunch and total planned for the full-plan headcount, and label which you mean." },
    { id: "cm-2", description: "Treating planned roles as filled. Coverage of 93% still leaves 6 open positions and 3 open critical roles.", correction: "Read filled and open separately, and treat open critical roles as readiness gates." },
    { id: "cm-3", description: "Ignoring start dates. A resource named in September does not cover an August peak.", correction: "Test every required-by date against the expected start date and the 8 to 10 week hiring lead time." },
    { id: "cm-4", description: "Double counting shared resources. Shared CoE assignments count at 50% availability, not as dedicated FTEs.", correction: "Confirm shared allocation with the owning function before counting it in any function's coverage." },
    { id: "cm-5", description: "Ignoring contractor cost. Contractors are 12% of filled capacity and are priced differently from employees.", correction: "Apply contractor loaded rates and payment terms separately in both P&L and Cash." },
    { id: "cm-6", description: "Reducing staffing before automation exists. Automation and AI Operations is At Risk with an open Automation Lead.", correction: "Only take the Day 2 efficiency once the automation capability is delivered and proven." },
    { id: "cm-7", description: "Increasing activation without a capacity review. Upside raises demand 15% and drops coverage 6 points.", correction: "Run the feasibility check before accepting any activation or revenue increase." },
    { id: "cm-8", description: "Failing to update P&L and Cash after a staffing change.", correction: "Re-phase cost on P&L and outflow timing on Cash whenever the ramp, mix or start dates move." },
    { id: "cm-9", description: "Measuring role coverage only by quantity. Headcount coverage is 93% but skill coverage is 88%.", correction: "Check critical skills per function, not just filled counts." },
    { id: "cm-10", description: "Ignoring critical-role dependencies. SRE Lead gates Day 1 stabilization and Transition Lead gates Day 0 coordination.", correction: "Track critical roles against the readiness path on Timelines, not just the staffing table." },
  ],
  bestPractices: [
    "Read the peak window before the totals; the crunch, not the average, is what breaks a plan.",
    "Always state whether a number is peak, planned, filled or available.",
    "Give every open position a required-by date and work backwards through hiring lead time.",
    "Confirm shared CoE capacity with the owning function in writing before counting it.",
    "Pair every capacity gap with a named sourcing strategy and an owner before the next forum.",
    "Check skill coverage alongside headcount coverage whenever you report readiness.",
    "Re-run feasibility on every scenario change rather than assuming the Base plan scales.",
    "Reconcile to P&L and Cash in the same session in which you change the staffing plan.",
  ],
  workedExamples: [
    {
      id: "we-1",
      title: "Activation increases under the Upside scenario",
      narrative:
        "Switch the scenario selector from Base to Upside. The 1.15 factor raises demand everywhere: peak simultaneous demand moves above 48.5 FTEs, Delivery rises from 24.0 peak FTEs, RunOps and SRE from 12.0, and Customer Success from 7.0. Supply does not move with it — coverage drops by 6 points from 93%, so the plan is now short in exactly the functions already flagged. RunOps and SRE is already at 95% utilization and Automation and AI Operations at 96%, so the additional demand lands on the two functions with no headroom. The six capacity gaps widen: SRE Leadership required by August 15, Transition Leadership by July 15, Solution Delivery by August 16. With an 8 to 10 week hiring lead time and 60% pipeline conversion, recruitment for the August dates must already be running in June, not started when the scenario is approved. Cost rises with the extra FTEs and the contractor augmentation used to close the gaps, and cash rises earlier because contractor onboarding must precede peak demand. Schedule risk increases because unfilled critical roles gate Day 0 and Day 1 readiness. The extra revenue is only real if that capacity is actually delivered.",
      steps: [
        "Select Upside and record the new peak demand and coverage position.",
        "Compare the widened gaps against each required-by date and the hiring lead time.",
        "Check utilization on RunOps and SRE and Automation before adding any more demand.",
        "Price the additional FTEs and contractor augmentation into P&L.",
        "Move the earlier onboarding outflow into Cash timing.",
        "Test whether Day 0 and Day 1 readiness dates still hold on Timelines.",
        "Take the residual gaps to Governance with owners and dated sourcing plans.",
      ],
      result:
        "Delivery, RunOps, SRE and Customer Success demand all rise, hiring must start earlier, cost and cash rise, and schedule risk increases. The revenue upside is conditional on capacity being delivered, so the scenario should not be approved until each gap is either resolved with a dated plan or explicitly accepted by the Executive Sponsor.",
    },
  ],
  faqs: [
    { id: "faq-1", question: "What is peak FTE demand?", answer: "The highest simultaneous FTE demand across all functions in any single month — 48.5 FTEs under the Base scenario, occurring in the Day 1 window. It is calculated as the maximum monthly sum of Delivery, RunOps and SRE, Customer Success and Support Functions. It is not the total number of people involved in the engagement, because roles start and finish at different times." },
    { id: "faq-2", question: "What is the difference between filled and available?", answer: "Filled means a named resource is assigned to the position. Available means that person can actually do the work on the date required — onboarded, tooled, access-provisioned and certified. The plan notes onboarding must complete two weeks before the August 16 peak window opens. A filled role that is not yet available still leaves a capacity gap on the day it is needed." },
    { id: "faq-3", question: "How are shared resources counted?", answer: "Shared CoE assignments count at 50% availability, not as dedicated FTEs. Solution Architecture, Security and Compliance, Support Functions and Corporate Shared Services are shared across engagements or functions. Counting the same shared FTE fully in two places is double counting and produces capacity that does not exist when the crunch arrives." },
    { id: "faq-4", question: "Why does activation affect staffing?", answer: "Activation determines how much service is live and when. More activating accounts means more delivery work, more operational load on RunOps and SRE, and more account coverage from Customer Success. That is why the Upside scenario raises demand by 15% while coverage falls by 6 points — activation changes demand immediately, but supply only changes at the speed of hiring." },
    { id: "faq-5", question: "How does staffing affect EBITDA?", answer: "Staffing is the dominant cost in a services engagement. FTE volume, employee versus contractor mix and onshore, nearshore or offshore location all drive the cost lines that flow into P&L. Understated staffing or a wrong contractor assumption inflates EBITDA on paper while delivery carries the real cost." },
    { id: "faq-6", question: "How does staffing affect cash?", answer: "Start dates set when payroll and contractor invoices begin, and contractor payment terms often differ from employee payroll timing. A candidate expected in September creates no August outflow. If contractor onboarding is pulled forward to cover peak demand, cash outflow moves earlier even when total cost is unchanged." },
    { id: "faq-7", question: "What is a critical role?", answer: "A role designated critical to service continuity, where absence creates a single point of failure or gates a readiness phase. There are 12 on this page. SRE Lead is required before the Day 1 stabilization window, Transition Lead before Day 0 coordination completes, and Automation Lead before Day 2 optimization. Interim coverage is not counted as filled." },
    { id: "faq-8", question: "When should a contractor be used?", answer: "For short-duration peaks, specialist skills not held internally, or capacity needed faster than the 8 to 10 week hiring lead time allows — such as the contractor augmentation planned for automation engineering and the migration workstream. Contractor dependency is currently 12% of filled capacity and should be reviewed if it rises materially." },
    { id: "faq-9", question: "What is a CoE allocation?", answer: "Capacity drawn from a Centre of Excellence — a shared, pooled capability such as the RunOps and SRE CoE, Architecture CoE or Security CoE — rather than a dedicated team member. There are 6 CoE shared assignments in the pipeline. CoE capacity is real but partial, counted at 50% availability and subject to competing demand." },
    { id: "faq-10", question: "Where should staffing assumptions be changed?", answer: "Not here. This page is a prototype and all edits reset on reload. Demand assumptions belong with activation and scope on Program and Portfolio, financial assumptions belong in Assumptions & Change Sets, and scenario factors belong in Scenarios. Change them at source, then read the staffing consequence here." },
  ],
  glossary: [
    { term: "FTE", definition: "Full-time equivalent — one unit of full-time capacity. Two people at 50% allocation equal 1.0 FTE." },
    { term: "Peak FTE", definition: "The highest simultaneous FTE demand in any single month; 48.5 under the Base scenario." },
    { term: "Named Resource", definition: "A specific individual assigned to a position, as distinct from an approved but unassigned position." },
    { term: "Filled Position", definition: "A position with a named resource assigned; not the same as being available on the required date." },
    { term: "Open Position", definition: "An approved position with no named resource assigned; 6 across the role plan, 3 of them critical." },
    { term: "Shared Resource", definition: "Capacity split across functions or engagements, counted at 50% availability rather than as dedicated FTE." },
    { term: "Dedicated Resource", definition: "Capacity assigned exclusively to this engagement, such as the phase-based Delivery Pods." },
    { term: "Contractor", definition: "Externally engaged capacity with distinct loaded cost and payment terms; currently 12% of filled FTEs." },
    { term: "Utilization", definition: "The proportion of a resource's capacity consumed by assigned work; the sustainable threshold here is 95%." },
    { term: "Capacity Gap", definition: "Demand minus available capacity for an area, with severity, required-by date, owner and sourcing strategy." },
    { term: "CoE", definition: "Centre of Excellence — a shared, pooled capability such as the RunOps and SRE, Architecture or Security CoE." },
    { term: "Loaded Cost", definition: "The fully burdened cost of a resource, including benefits, overhead and delivery costs, used to convert FTEs into P&L cost." },
  ],
  executiveTakeaway:
    "Staffing & Resources answers whether the commercial plan can actually be delivered by people. Coverage is 93% against a Base peak of 48.5 simultaneous FTEs, which sounds adequate until you read the composition: SRE Lead, Transition Lead and Automation Lead are open, two functions sit at or above the 95% utilization threshold, skill coverage is 88%, and six capacity gaps totalling 7.0 FTEs carry dates between July 15 and November 1. Peak demand is not headcount, and filled is not available. Treat critical-role dates and hiring lead time as the binding constraint on activation, and do not approve an Upside scenario until each gap has a dated plan or explicit acceptance.",
  keyRisks: [
    "SRE Lead remains open before the Day 1 stabilization window (High) — single point of failure at go-live.",
    "Transition Lead is unfilled (High) — Day 0 coordination and readiness may be delayed.",
    "Automation capability is below the Day 2 requirement (High) — higher manual effort and lower operating leverage.",
    "Peak-period utilization exceeds the sustainable threshold for RunOps and SRE — service instability and burnout risk.",
    "Customer Success coverage is below peak demand — reduced engagement and renewal readiness.",
    "Shared support functions have limited buffer — decision and approval delays.",
    "Contractor dependency rising above the planned 12% without cost and cash being updated.",
    "Shared CoE capacity counted as dedicated in more than one place, overstating available capacity.",
    "Upside activation approved without the capacity to deliver it, converting revenue upside into delivery risk.",
    "Prototype FTE, utilization and coverage values mistaken for a validated staffing commitment.",
  ],

  /* ---------------- Show on page ---------------- */
  showOnPageTargets: [
    { targetId: "staffing-scenario", label: "Scenario selector", description: "Conservative, Base and Upside factors applied to all demand values." },
    { targetId: "staffing-summary", label: "Staffing summary", description: "Peak FTEs, coverage, critical roles, open positions and the peak window." },
    { targetId: "staffing-filters", label: "Active filters", description: "Removable chips for every applied filter." },
    { targetId: "staffing-role-plan", label: "Role staffing plan", description: "Ten roles with phase demand, filled, open, shared, contractor and utilization." },
    { targetId: "staffing-function-allocation", label: "FTE allocation by function", description: "Peak allocation split across the four functions." },
    { targetId: "staffing-resource-health", label: "Resource health", description: "Coverage, overallocation, skills, attrition, contractor dependency and bench." },
    { targetId: "staffing-phase-cards", label: "Day 0, Day 1 and Day 2 cards", description: "Phase periods, peak FTEs, staffing focus and outcomes." },
    { targetId: "staffing-forecast", label: "Staffing forecast", description: "Monthly and phase demand by function in FTE or percentage." },
    { targetId: "staffing-critical-roles", label: "Critical-role coverage", description: "Twelve critical roles with status, owner and required-by date." },
    { targetId: "staffing-pipeline", label: "Resource pipeline", description: "Candidates by stage, source and expected start date." },
    { targetId: "staffing-operating-structures", label: "Operating structures", description: "Account Pods, Delivery Pods, RunOps and SRE CoE and Enterprise Shared Services." },
    { targetId: "staffing-capacity-gaps", label: "Capacity gaps", description: "Six gaps with severity, required-by date, sourcing strategy and owner." },
    { targetId: "staffing-risks", label: "Resource risks", description: "Five registered staffing risks with owner, impact and mitigation." },
    { targetId: "staffing-executive-attention", label: "Executive attention", description: "Six items requiring leadership action." },
  ],
};
