import type { CommercialGuideContent } from "../../types";

/**
 * Page-specific Commercial Guide content — Program (`/commercial/program`).
 *
 * Authored strictly against what renders in
 * `src/commercial/pages/CommercialProgram.tsx`: the directional banner, the
 * program summary card (name, code, status, current gate, partner, segment,
 * description, gate-count note) and the Operating Gates list (gate code, name,
 * status, account scope label, operating objective, economic objective, unlock
 * conditions).
 *
 * Concepts requested but NOT rendered on this page (parties table, account
 * universe, operating-model split, commercial mechanics, responsibility split,
 * funding, services rights, support scope, governance authority, open
 * decisions, source register, related documents) are described only as
 * context/known gaps — never as if the page displayed them.
 *
 * All commercial mechanics below are described as PROPOSED / directional. No
 * contract term is presented as executed or approved.
 */
export const commercialProgramGuide: CommercialGuideContent = {
  pageId: "commercial-program",
  route: "/commercial/program",
  match: "exact",
  pageTitle: "Program",
  guideTitle: "Program — Deal Definition and Gate Model",
  audiences: ["Executive", "Commercial Lead", "Finance", "Delivery", "Sales", "Operations", "Administrator"],
  modes: ["executive", "practitioner", "administrator"],
  estimatedReadingMinutes: 11,
  trainingLevel: "Foundation",
  lastUpdated: "2026-07-29",

  /* ---------------- Overview ---------------- */
  purpose:
    "Program defines the deal being modeled. It names the program record, the partner, the market segment, the current operating gate and the staged gate model (one readiness gate plus four decision gates). Everything the Commercial Module calculates — revenue, cost, EBITDA, cash, staffing, activation — is only meaningful inside the boundary this page states. It is a definition surface, not a calculation surface.",
  represents:
    "The stored program record for Project Momentous and its ordered gate register: for each gate a code, name, status, account scope label, operating objective, economic objective and unlock conditions. The directional banner records that the whole definition is still a proposed, directional model pending account-level validation and contractual confirmation.",
  whyItMatters:
    "A financial model without an agreed program basis is arithmetic, not a deal. Program is where the strategic intent of the Citrix and Neurealm healthcare operating model, the parties, the account and service scope, and the staged operator progression are stated once. If this page is wrong or out of date, every downstream page is confidently wrong. The banner is deliberate: proposed terms must never be read as approved terms.",
  moduleConnection:
    "Program sits directly beneath Overview and above every model page. Sources supplies the evidence behind the definition; deal documents and MOU or term-sheet assumptions supply the commercial mechanics. Program then constrains Portfolio (which accounts may be modeled), Timelines and Program & Timeline (when phases occur), Revenue, P&L and Cash (what may be earned, spent and funded), Staffing & Resources (what must be operated), Release & Activation (what may be activated) and Governance (who may approve a change).",
  questionsAnswered: [
    "What commercial and operating model is being evaluated?",
    "Which accounts and services are in scope for this gate?",
    "What must Citrix provide — authority, data, funding, control and governance?",
    "What must Neurealm build, staff, operate or assume as shared risk?",
    "What conditions must be met before each phase begins?",
    "Which terms are proposed versus agreed, approved or activated?",
    "How does the program progress from controlled operator pilot to scale, segment and mature operator?",
    "What would stop or delay the program?",
  ],
  expectedOutcome:
    "A shared, evidenced understanding of the deal boundary: the program in force, the current gate, the unlock conditions still outstanding, and an explicit statement of which elements are proposed rather than approved — plus a routing decision for anything unresolved.",
  lifecycleStages: [
    "Opportunity Qualification",
    "Commercial Structuring",
    "Negotiation",
    "Executive Review",
    "Delivery Planning",
    "Mobilization",
  ],
  prerequisites: [
    { id: "pre-deal-docs", label: "Current deal documents", detail: "Latest circulated deal pack for the Citrix healthcare operator model." },
    { id: "pre-mou", label: "Current MOU or term-sheet assumptions", detail: "Proposed commercial mechanics; treat as proposed until legally confirmed." },
    { id: "pre-accounts", label: "Named account scope", route: "/commercial/portfolio", detail: "The named healthcare account list and its segmentation." },
    { id: "pre-support", label: "Defined support scope", detail: "What support Neurealm would operate, at what tier and hours." },
    { id: "pre-services", label: "Defined services rights", detail: "Whether professional and managed services may be sold and by whom." },
    { id: "pre-terms", label: "Commercial-term assumptions", route: "/commercial/model/assumptions", detail: "Rebate, funding, MBG and pricing assumptions in the governed assumption set." },
    { id: "pre-authority", label: "Governance and authority assumptions", route: "/commercial/neurealm-governance", detail: "Who decides, who approves, and what operating authority is granted." },
    { id: "pre-sources", label: "Current source references", route: "/commercial/sources", detail: "Registered evidence behind every stated term." },
  ],
  ownership: {
    businessOwner: "Deal Lead",
    commercialOwner: "Commercial Lead",
    technicalOwner: "Program Director",
    executiveApprover: "Executive Sponsor",
    primaryUsers: ["Deal team", "Program leadership", "Commercial Lead", "Finance", "Legal", "Delivery Leadership", "RunOps Leadership", "Customer Success Leadership"],
    consumersOfOutput: [
      "Portfolio",
      "Program & Timeline",
      "Timelines",
      "Revenue",
      "P&L (Cost & EBITDA)",
      "Cash & Sustainability",
      "Assumptions & Change Sets",
      "Release & Activation",
      "Staffing & Resources",
      "Governance",
      "Overview",
    ],
  },

  /* ---------------- How it works ---------------- */
  sections: [
    {
      id: "sec-context",
      title: "Directional model banner",
      targetId: "program-context",
      explanation:
        "The banner states that this is a directional portfolio model and that account-level validation and contractual confirmation are pending. Read it as the status of the whole page: everything below is a proposed operating and commercial construct, not an executed agreement. Nothing here should be quoted externally, and no downstream page should present the program as agreed while this banner stands.",
    },
    {
      id: "sec-purpose",
      title: "Program summary card",
      targetId: "program-purpose",
      explanation:
        "The summary card carries the program name and code, its lifecycle status, the current gate code, the partner, the market segment and a description of strategic intent. This is the authoritative identity of the deal being modeled. Every other Commercial page resolves its data against this program record, so the code shown here is the join key for the entire module.",
    },
    {
      id: "sec-approval-status",
      title: "Status and current-gate badges",
      targetId: "program-approval-status",
      explanation:
        "The badge row shows the program code, the program status and the current gate. Status describes the state of the program record, not legal execution of any term. Current gate is the boundary condition for downstream modeling: accounts, revenue, staffing and activation should be modeled for the current gate and the gates already passed, not for later gates whose unlock conditions remain open.",
    },
    {
      id: "sec-scope",
      title: "Partner, segment and strategic intent",
      targetId: "program-scope",
      explanation:
        "Partner and market segment define the parties and the market boundary — the Citrix and Neurealm healthcare operating model. The description beneath states the strategic intent of that model. Together they set the scope test for every later question: if an account, service or cost sits outside this partner and segment boundary, it does not belong in this program's economics.",
    },
    {
      id: "sec-phases",
      title: "Operating Gates section",
      targetId: "program-phases",
      explanation:
        "The gate model is stated on the card above as one readiness gate (G0) plus four formal decision gates (G1–G4). This is the staged operator progression: pre-kickoff readiness, controlled operator pilot, scale, segment expansion and mature operator. A phase is the period of work; a gate is the decision that opens it. Phases are not shown as dates here — sequencing lives on Timelines.",
    },
    {
      id: "sec-gates",
      title: "Gate cards — objectives, scope and unlock conditions",
      targetId: "program-gates",
      explanation:
        "Each gate card shows its code and name, its status, an account scope label, an operating objective, an economic objective and the unlock conditions that must be satisfied before the gate is passed. The operating objective is what must be run; the economic objective is what must be proven commercially. Unlock conditions are the evidence test — treat them as the entry criteria for the next phase, not as aspirations.",
    },
  ],
  inputs: [
    { id: "in-accounts", label: "Named account list", description: "The named healthcare accounts considered in scope. Owner: Deal Lead. Approver: Executive Sponsor. Source: deal documents. Status: proposed. Confidence: medium. Impact: Portfolio, Revenue, Release & Activation.", owner: "Deal Lead", source: "Deal documents / account data", required: true },
    { id: "in-segmentation", label: "Account segmentation", description: "How accounts are grouped for phasing — pilot, scale, segment. Owner: Commercial Lead. Approver: Program Director. Source: account data. Status: proposed. Confidence: medium. Impact: gate scope labels, activation sequencing.", owner: "Commercial Lead", source: "Account data" },
    { id: "in-terms", label: "Commercial terms", description: "Pricing, discount and margin mechanics under discussion. Owner: Commercial Lead. Approver: Executive Sponsor with Legal. Source: MOU or term sheet. Status: proposed. Confidence: low to medium. Impact: Revenue, P&L.", owner: "Commercial Lead", source: "MOU / term sheet", required: true },
    { id: "in-rebate", label: "Rebate structure", description: "Proposed rebate mechanics payable on qualifying activity. Owner: Finance. Approver: Executive Sponsor. Source: term-sheet assumptions. Status: proposed. Confidence: low. Impact: Revenue, Cash.", owner: "Finance", source: "Term-sheet assumptions" },
    { id: "in-services", label: "Services rights", description: "Whether Neurealm may sell professional and managed services into in-scope accounts, and on what basis. Owner: Commercial Lead. Approver: Legal. Source: deal documents. Status: proposed. Confidence: low. Impact: Revenue eligibility.", owner: "Commercial Lead", source: "Deal documents", required: true },
    { id: "in-support", label: "Support scope", description: "Tiers, hours, channels and entitlement boundaries for support Neurealm would operate. Owner: RunOps Lead. Approver: Delivery Leadership. Source: support scope definition. Status: unresolved in places. Confidence: low. Impact: Staffing, P&L.", owner: "RunOps Lead", source: "Support scope definition", required: true },
    { id: "in-activation-fund", label: "Activation funding", description: "Proposed Citrix funding to stand up the operator capability. Owner: Finance. Approver: Executive Sponsor. Source: term-sheet assumptions. Status: proposed, not approved. Confidence: low. Impact: Cash & Sustainability.", owner: "Finance", source: "Term-sheet assumptions" },
    { id: "in-sm-baseline", label: "Sales and marketing baseline", description: "Baseline sales and marketing effort assumed to be carried by Neurealm. Owner: Commercial Lead. Approver: Finance. Source: assumption set. Status: proposed. Confidence: medium. Impact: P&L.", owner: "Commercial Lead", source: "Assumptions & Change Sets" },
    { id: "in-support-funding", label: "Support-services funding", description: "Any funding or reimbursement proposed against support delivery. Owner: Finance. Approver: Executive Sponsor. Source: term-sheet assumptions. Status: proposed. Confidence: low. Impact: P&L, Cash.", owner: "Finance", source: "Term-sheet assumptions" },
    { id: "in-mbg", label: "Risk-sharing or MBG conditions", description: "Minimum business guarantee and other shared-risk conditions, including which accounts qualify. Owner: Commercial Lead. Approver: Executive Sponsor with Legal. Source: MOU. Status: proposed. Confidence: low. Impact: Revenue, Cash, Risk.", owner: "Commercial Lead", source: "MOU" },
    { id: "in-gates", label: "Program gates", description: "Gate codes, objectives, account scope labels and unlock conditions rendered on this page. Owner: Program Director. Approver: Executive Sponsor. Source: program record. Status: recorded. Confidence: medium. Impact: all phasing.", owner: "Program Director", source: "Program record", required: true },
    { id: "in-authority", label: "Operator authority", description: "The decision rights Neurealm would hold over in-scope accounts. Owner: Program Director. Approver: Legal. Source: governance assumptions. Status: proposed. Confidence: low. Impact: Governance, Risk.", owner: "Program Director", source: "Governance assumptions" },
    { id: "in-tooling", label: "Tooling and data access", description: "Citrix systems, telemetry and account data Neurealm would need to operate. Owner: Delivery Lead. Approver: Citrix. Source: deal documents. Status: proposed. Confidence: low. Impact: feasibility of assumed risk.", owner: "Delivery Lead", source: "Deal documents" },
    { id: "in-incumbent", label: "Incumbent-partner rules", description: "How accounts already served by an incumbent partner are treated versus no-partner accounts. Owner: Commercial Lead. Approver: Legal. Source: deal documents. Status: proposed. Confidence: low. Impact: account eligibility.", owner: "Commercial Lead", source: "Deal documents" },
    { id: "in-exclusions", label: "Legal exclusions", description: "Accounts, geographies, products or activities explicitly excluded. Owner: Legal. Approver: Legal. Source: deal documents. Status: proposed. Confidence: low. Impact: scope, Portfolio.", owner: "Legal Lead", source: "Deal documents" },
    { id: "in-liability", label: "Liability framework", description: "Caps, indemnities and service-level exposure attaching to operator responsibilities. Owner: Legal. Approver: Executive Sponsor. Source: deal documents. Status: proposed. Confidence: low. Impact: Risk, Cash.", owner: "Legal Lead", source: "Deal documents" },
  ],
  outputs: [
    { id: "out-context", label: "Authoritative program context", description: "The program record, code, partner, segment and status that every other Commercial page resolves against.", consumedBy: ["Overview", "Portfolio", "Revenue", "P&L (Cost & EBITDA)", "Cash & Sustainability"] },
    { id: "out-scope", label: "Scope definition", description: "The partner, market segment and account scope boundary for the deal.", consumedBy: ["Portfolio", "Release & Activation"] },
    { id: "out-gates", label: "Phase and gate definitions", description: "Gate codes, sequence, objectives, account scope labels and unlock conditions.", consumedBy: ["Timelines", "Program & Timeline", "Release & Activation", "Governance"] },
    { id: "out-responsibility", label: "Responsibility boundaries", description: "The proposed split of Citrix and Neurealm obligations across Day 0, Day 1 and Day 2.", consumedBy: ["Staffing & Resources", "Governance"] },
    { id: "out-mechanics", label: "Commercial-mechanics context", description: "Proposed rebate, services, funding and MBG mechanics as modeling context.", consumedBy: ["Revenue", "Cash & Sustainability", "Assumptions & Change Sets"] },
    { id: "out-operating", label: "Operating-model context", description: "The staged operator progression from controlled pilot to mature operator.", consumedBy: ["Staffing & Resources", "Timelines"] },
    { id: "out-constraints", label: "Model constraints", description: "What may not yet be modeled because its gate has not opened.", consumedBy: ["Revenue", "Release & Activation"] },
    { id: "out-assumptions", label: "Downstream assumptions", description: "Program-level assumptions that the governed assumption set must reflect.", consumedBy: ["Assumptions & Change Sets"] },
    { id: "out-decisions", label: "Required decisions", description: "Unresolved terms that must be routed for decision before the next gate.", consumedBy: ["Governance"] },
    { id: "out-readiness", label: "Program-readiness status", description: "Whether the current gate's unlock conditions are satisfied.", consumedBy: ["Overview", "Governance"] },
  ],
  businessRules: [
    { id: "br-kickoff", rule: "No account transfer or activation is modeled before required kickoff conditions are met", explanation: "Pre-kickoff work is preparation only. Until kickoff conditions — data access, authority, agreed exclusions and named eligible accounts — are satisfied, activation and transfer must not appear in Portfolio, Revenue or Release & Activation." },
    { id: "br-gate", rule: "Each phase begins only after its prior gate conditions are satisfied", explanation: "Gate unlock conditions are entry criteria, not milestones to be assumed. Modeling a scale-phase account population while the pilot gate is still open overstates revenue and understates the risk of delay." },
    { id: "br-risk", rule: "Commercial risk is not assumed without matching data, authority, access and agreed exclusions", explanation: "Shared-risk and MBG mechanics only make sense where Neurealm can actually influence the outcome. Without telemetry, decision rights and system access, assumed risk is unmanaged exposure and should be flagged, not modeled as neutral." },
    { id: "br-proposed", rule: "Proposed terms must remain distinguishable from approved terms", explanation: "Every mechanic on this page is currently proposed. The directional banner, program status and source register carry that distinction. Guides, exports and executive summaries must repeat it rather than smoothing it away." },
    { id: "br-reconcile", rule: "Account scope must reconcile with Portfolio and Release & Activation", explanation: "The gate account scope labels here are the control total. If Portfolio holds accounts that no open gate covers, or Release & Activation activates accounts outside the current gate, one of the three is wrong and must be corrected at source." },
    { id: "br-services", rule: "Services rights must align with the revenue model", explanation: "Professional and managed services revenue may only be modeled where the right to sell and deliver those services into the account is stated. Unconfirmed rights should be modeled as a scenario variant, not in the baseline." },
    { id: "br-support", rule: "Support scope must align with staffing, costs and funding", explanation: "Support tiers, hours and entitlements drive headcount on Staffing & Resources and cost on P&L. A support scope that is broader than the staffed plan is a cost understatement; narrower is a service risk." },
    { id: "br-funding", rule: "Funding assumptions must align with Cash & Sustainability", explanation: "Activation funding and support-services funding are proposed, may be milestone-based, and are not cash at kickoff. Cash timing must reflect the actual proposed trigger and not an assumed lump sum." },
    { id: "br-authority", rule: "Governance authority must align with actual decision rights", explanation: "Operator authority stated here must match what Governance records as the real decision rights. Where they diverge, the weaker of the two governs the model until the difference is resolved." },
    { id: "br-version", rule: "The program definition is versioned through approved source documentation, not changed silently", explanation: "Any change to scope, phases, mechanics or authority must be traceable to a registered source and routed through Assumptions & Change Sets or Governance so downstream pages can be re-reconciled." },
  ],
  calculationLogic: [
    "Program performs no financial calculation. It defines the boundary within which every other page calculates.",
    "Gate sequence is ordered by the gate's sequence number; the current gate on the summary card is the program's stated position in that sequence.",
    "Gate status is a recorded state (not started, in progress, in review, ready, passed) and is not derived from downstream model results.",
    "Account scope labels on gate cards are descriptive scope statements; the authoritative account population lives on Portfolio.",
  ],
  relationship: {
    receivesFrom: ["Sources", "Deal documents", "MOU or term-sheet content", "Account data", "Stakeholder decisions"],
    models: [
      "Program purpose and strategic intent",
      "In-scope parties",
      "Account scope",
      "Services scope",
      "Phase structure",
      "Gate structure",
      "Responsibility boundaries",
      "Commercial mechanics (proposed)",
      "Operating authority (proposed)",
      "Risk-sharing conditions (proposed)",
    ],
    feeds: [
      "Program & Timeline",
      "Portfolio",
      "Assumptions & Change Sets",
      "Release & Activation",
      "Revenue",
      "P&L (Cost & EBITDA)",
      "Cash & Sustainability",
      "Governance",
      "Timelines",
      "Staffing & Resources",
      "Overview",
    ],
  },
  downstreamImpacts: [
    { area: "Accounts", effect: "Gate account scope constrains which accounts Portfolio may treat as in play." },
    { area: "Revenue", effect: "Services rights and account eligibility determine which revenue streams may be modeled." },
    { area: "Costs", effect: "Support scope and operator responsibilities drive cost lines on P&L." },
    { area: "EBITDA", effect: "Rebate, funding and MBG mechanics change the margin picture materially." },
    { area: "Cash", effect: "Activation and support funding timing drives working-capital need." },
    { area: "Staffing", effect: "Day 0, Day 1 and Day 2 obligations set the staffing shape by phase." },
    { area: "Timeline", effect: "Gate unlock conditions set the earliest credible phase start dates." },
    { area: "Activation", effect: "No activation may be released ahead of its gate." },
    { area: "Governance", effect: "Unresolved terms become governance decisions with named approvers." },
    { area: "Risk", effect: "Assumed risk without data, authority or access is a top-tier program risk." },
  ],
  dataQuality: {
    dataSources: [
      "commercial_programs — program identity, partner, segment, status, current gate",
      "commercial_stage_gates — gate code, sequence, name, account scope label, objectives, unlock conditions, status",
      "Registered source references on the Sources page",
    ],
    updateFrequency: "On change to the deal definition, and at each gate review.",
    knownGaps: [
      "No parties and stakeholders table on the Program page.",
      "No account universe or named account list rendered here — Portfolio is the only account surface.",
      "No explicit operating-model split of Day 0, Day 1 and Day 2 responsibilities on the page.",
      "No commercial-model section — rebate, services, funding and MBG mechanics are not displayed.",
      "No responsibility split between Citrix and Neurealm displayed.",
      "No funding or reimbursement section.",
      "No services-rights or support-scope section.",
      "No governance and authority section on this page.",
      "No program-assumptions panel; assumptions live on Assumptions & Change Sets.",
      "No open-decisions list on this page.",
      "No source status or related-documents panel on this page; the source register is on Sources.",
      "Program source_status is loaded but not rendered.",
    ],
    changeControl: "Changes to program scope, phases or mechanics must be evidenced by a registered source document and routed through Governance or Assumptions & Change Sets.",
    lineage: "Program record and gates are tenant-scoped and seeded from the Project Momentous source pack.",
  },
  modelConfidence: "Medium",
  confidenceBasis: ["Commercial terms", "Governance approvals", "Source completeness", "Account data"],
  confidenceGuidance:
    "Confidence in the gate structure is reasonable because it is recorded and sequenced. Confidence in the commercial mechanics is low because rebate, services rights, funding and MBG conditions remain proposed. Treat the gate model as the stable part of this page and the commercial mechanics as the volatile part.",
  commercialReadiness: "Review Required",
  readinessCriteria: [
    "Program record, partner and segment confirmed against the current deal documents.",
    "Current gate correct and its unlock conditions individually evidenced.",
    "Account scope reconciled with Portfolio.",
    "Services rights and support scope confirmed or explicitly flagged as unresolved.",
    "Funding and MBG mechanics labelled as proposed wherever used downstream.",
    "Operator authority matched against Governance decision rights.",
  ],

  /* ---------------- How to use it ---------------- */
  workflow: [
    { id: "wf-1", step: 1, title: "Confirm the program version and source", description: "Check the program code, status and current gate against the latest registered source document before reading anything else.", role: "Deal Lead" },
    { id: "wf-2", step: 2, title: "Confirm parties and strategic intent", description: "Read partner, market segment and the description. Confirm they still describe the Citrix and Neurealm healthcare operating model being pursued.", role: "Commercial Lead" },
    { id: "wf-3", step: 3, title: "Confirm account scope and segmentation", description: "Compare each gate's account scope label with the account population on Portfolio, including no-partner and incumbent-partner treatment.", role: "Commercial Lead" },
    { id: "wf-4", step: 4, title: "Confirm phase and gate structure", description: "Walk G0 through G4 and check the operating and economic objectives still match the intended pilot, scale, segment and mature operator progression.", role: "Program Director" },
    { id: "wf-5", step: 5, title: "Confirm Neurealm responsibilities", description: "Test that the staffing, services and accountability implied by each gate objective is deliverable and reflected on Staffing & Resources.", role: "Delivery Lead" },
    { id: "wf-6", step: 6, title: "Confirm Citrix responsibilities", description: "Test that authority, data, funding, control and governance needed to meet each gate objective are stated and evidenced.", role: "Program Director" },
    { id: "wf-7", step: 7, title: "Confirm service and support scope", description: "Confirm services rights and support scope are defined; flag anything assumed but unconfirmed rather than modeling it as baseline.", role: "RunOps Lead" },
    { id: "wf-8", step: 8, title: "Confirm commercial mechanics and funding", description: "Check rebate, professional services, managed services, activation funding and MBG assumptions are labelled proposed and match Assumptions & Change Sets.", role: "Finance" },
    { id: "wf-9", step: 9, title: "Identify unresolved terms", description: "List every gate unlock condition without evidence and every mechanic without a registered source.", role: "Deal Lead" },
    { id: "wf-10", step: 10, title: "Check downstream alignment", description: "Confirm Portfolio, Revenue, P&L, Cash, Timelines, Staffing and Release & Activation all reflect the same program definition and gate position.", role: "Commercial Lead" },
    { id: "wf-11", step: 11, title: "Route unresolved items", description: "Send open terms to Governance for decision, or to Assumptions & Change Sets where they are modeling assumptions.", role: "Program Director" },
    { id: "wf-12", step: 12, title: "Obtain the required approval", description: "Secure Executive Sponsor approval for any change to strategic boundaries, scope, phases or risk-sharing before downstream pages are updated.", role: "Executive Sponsor" },
  ],
  actionsAvailable: [
    "Read the program identity, status and current gate",
    "Read each gate's objectives, account scope label and unlock conditions",
    "Seed the Project Momentous program bundle when no program exists in the workspace",
    "Navigate to Portfolio, Sources, Timelines, Governance and the model pages for the detail behind the definition",
  ],
  teamActivities: [
    { id: "ta-deal", activity: "Own the integrated deal definition and keep the program record current", role: "Deal Lead", cadence: "Continuous, reviewed at each gate" },
    { id: "ta-comm", activity: "Validate commercial mechanics — rebate, services, funding, MBG — and their proposed status", role: "Commercial Lead", cadence: "Weekly" },
    { id: "ta-prog", activity: "Validate phase and gate structure and the evidence behind unlock conditions", role: "Program Director", cadence: "Weekly and at gate review" },
    { id: "ta-fin", activity: "Validate funding and economic treatment against Cash & Sustainability and P&L", role: "Finance", cadence: "Per model run cycle" },
    { id: "ta-legal", activity: "Validate authority, liability, exclusions and obligations; confirm nothing proposed is stated as executed", role: "Legal Lead", cadence: "On each change to terms" },
    { id: "ta-del", activity: "Validate delivery scope against Day 0, Day 1 and Day 2 obligations", role: "Delivery Lead", cadence: "Per gate" },
    { id: "ta-runops", activity: "Validate support and operational scope, tiers, hours and entitlements", role: "RunOps Lead", cadence: "Per gate" },
    { id: "ta-cs", activity: "Validate account-engagement responsibilities and incumbent-partner treatment", role: "Customer Success Lead", cadence: "Per gate" },
    { id: "ta-exec", activity: "Approve strategic boundaries, scope changes and risk-sharing exposure", role: "Executive Sponsor", cadence: "At gate review" },
  ],
  roles: [
    { role: "Deal Lead", responsibility: "Owns the integrated deal definition and the accuracy of the program record." },
    { role: "Commercial Lead", responsibility: "Owns commercial mechanics, account segmentation and services-rights assumptions." },
    { role: "Program Director", responsibility: "Owns the phase and gate model and the evidence behind unlock conditions." },
    { role: "Finance", responsibility: "Owns funding, rebate and economic treatment and their reflection in Cash and P&L." },
    { role: "Legal Lead", responsibility: "Owns authority, liability, exclusions and the proposed-versus-approved distinction." },
    { role: "Delivery Lead", responsibility: "Owns delivery scope and feasibility of the operator obligations." },
    { role: "RunOps Lead", responsibility: "Owns support scope, operating model and run-state accountability." },
    { role: "Customer Success Lead", responsibility: "Owns account engagement responsibilities and partner-conflict handling." },
    { role: "Executive Sponsor", responsibility: "Approves strategic boundaries, scope and risk-sharing exposure." },
  ],
  raci: [
    { activity: "Define and maintain the program record", assignments: [{ role: "Deal Lead", raci: "R" }, { role: "Executive Sponsor", raci: "A" }, { role: "Commercial Lead", raci: "C" }, { role: "Program Director", raci: "I" }] },
    { activity: "Define account scope and segmentation", assignments: [{ role: "Commercial Lead", raci: "R" }, { role: "Deal Lead", raci: "A" }, { role: "Customer Success Lead", raci: "C" }, { role: "Finance", raci: "I" }] },
    { activity: "Define phase and gate structure", assignments: [{ role: "Program Director", raci: "R" }, { role: "Executive Sponsor", raci: "A" }, { role: "Delivery Lead", raci: "C" }, { role: "RunOps Lead", raci: "C" }] },
    { activity: "Validate commercial mechanics and funding", assignments: [{ role: "Commercial Lead", raci: "R" }, { role: "Finance", raci: "A" }, { role: "Legal Lead", raci: "C" }, { role: "Deal Lead", raci: "I" }] },
    { activity: "Validate authority, liability and exclusions", assignments: [{ role: "Legal Lead", raci: "R" }, { role: "Executive Sponsor", raci: "A" }, { role: "Program Director", raci: "C" }, { role: "Deal Lead", raci: "I" }] },
    { activity: "Validate support and delivery scope", assignments: [{ role: "RunOps Lead", raci: "R" }, { role: "Delivery Lead", raci: "A" }, { role: "Finance", raci: "C" }, { role: "Commercial Lead", raci: "I" }] },
    { activity: "Approve a change to program scope or risk-sharing", assignments: [{ role: "Executive Sponsor", raci: "A" }, { role: "Deal Lead", raci: "R" }, { role: "Legal Lead", raci: "C" }, { role: "Finance", raci: "C" }] },
  ],
  reviewRequirements: [
    "Program identity and current gate reviewed against the latest registered source.",
    "Every unlock condition on the current gate reviewed for evidence.",
    "Account scope reviewed against Portfolio before each gate review.",
    "Commercial mechanics reviewed by Finance and Legal for proposed-versus-approved accuracy.",
  ],
  approvalRequirements: [
    "Executive Sponsor approval for changes to strategic boundaries, partner or segment.",
    "Executive Sponsor approval for changes to phase or gate structure.",
    "Executive Sponsor with Legal approval for risk-sharing, MBG or liability changes.",
    "Finance approval for funding treatment used in Cash & Sustainability.",
  ],
  decisions: [
    { id: "dec-scope", decision: "Which accounts are in scope for the controlled operator pilot", decidedBy: "Deal Lead with Executive Sponsor", evidence: "Named account list and eligibility check" },
    { id: "dec-services", decision: "Whether professional and managed services rights may be modeled as baseline", decidedBy: "Commercial Lead with Legal", evidence: "Deal documents confirming services rights" },
    { id: "dec-support", decision: "The support scope Neurealm will operate at each phase", decidedBy: "RunOps Lead with Delivery Leadership", evidence: "Support scope definition" },
    { id: "dec-funding", decision: "Whether activation funding may be modeled and on what timing", decidedBy: "Finance with Executive Sponsor", evidence: "Term-sheet assumptions" },
    { id: "dec-mbg", decision: "Whether MBG or other shared-risk conditions apply and to which accounts", decidedBy: "Executive Sponsor with Legal", evidence: "MOU content" },
    { id: "dec-gate", decision: "Whether the current gate is passed", decidedBy: "Executive Sponsor at gate review", evidence: "Unlock-condition evidence pack" },
  ],
  whatToDoNext: [
    "Reconcile gate account scope with Portfolio.",
    "Confirm services rights and support scope, or record them as unresolved.",
    "Check that Assumptions & Change Sets reflects the proposed commercial mechanics.",
    "Review gate sequencing and dates on Timelines.",
    "Route unresolved terms to Governance.",
    "Confirm Release & Activation activates nothing beyond the current gate.",
  ],
  relatedPages: [
    { pageId: "commercial-overview", label: "Overview", route: "/commercial", relationship: "Downstream" },
    { pageId: "commercial-portfolio", label: "Portfolio", route: "/commercial/portfolio", relationship: "Downstream" },
    { pageId: "commercial-sources", label: "Sources", route: "/commercial/sources", relationship: "Prerequisite" },
    { pageId: "commercial-program-timeline", label: "Timelines", route: "/commercial/program-timeline", relationship: "Downstream" },
    { pageId: "commercial-assumptions", label: "Assumptions & Change Sets", route: "/commercial/model/assumptions", relationship: "Companion" },
    { pageId: "commercial-release", label: "Release & Activation", route: "/commercial/model/release", relationship: "Downstream" },
    { pageId: "commercial-revenue", label: "Revenue", route: "/commercial/model/revenue", relationship: "Downstream" },
    { pageId: "commercial-pnl", label: "P&L (Cost & EBITDA)", route: "/commercial/model/pnl", relationship: "Downstream" },
    { pageId: "commercial-cash", label: "Cash & Sustainability", route: "/commercial/model/cash", relationship: "Downstream" },
    { pageId: "commercial-staffing-resources", label: "Staffing & Resources", route: "/commercial/staffing-resources", relationship: "Downstream" },
    { pageId: "commercial-governance", label: "Governance", route: "/commercial/neurealm-governance", relationship: "Companion" },
  ],

  /* ---------------- Interpretation & training ---------------- */
  interpretation: [
    {
      band: "healthy",
      label: "Program basis is agreed and consistent",
      criteria: [
        "Scope is explicit — accounts, services and support boundaries are stated.",
        "Roles are clear across Citrix and Neurealm for Day 0, Day 1 and Day 2.",
        "Proposed and approved terms are distinguishable everywhere they are used.",
        "Gate criteria are measurable and evidenced.",
        "Account, financial, staffing and timeline pages align to the same definition.",
        "Source documents are current and registered.",
      ],
      action: "Proceed to gate review and allow downstream modeling to be treated as decision-grade for the current gate.",
    },
    {
      band: "warning",
      label: "Definition is incomplete or partly assumed",
      criteria: [
        "Named accounts are available but control rights are unclear.",
        "Services rights are assumed but not confirmed.",
        "Funding is described but not approved.",
        "Support scope is unresolved.",
        "Phase gates are subjective rather than measurable.",
        "Program definitions differ across pages.",
      ],
      action: "Keep modeling directional, label the affected outputs, and route each open item to Governance or Assumptions & Change Sets with a named owner and date.",
    },
    {
      band: "critical",
      label: "Modeling is running ahead of the deal",
      criteria: [
        "Financial modeling proceeds without an agreed program basis.",
        "Risk is assumed without data, access or control.",
        "Account activation is modeled before eligibility.",
        "Contractual obligations are represented as approved without evidence.",
        "The current program version cannot be identified.",
      ],
      action: "Stop presenting the model externally, freeze activation modeling, and escalate to the Executive Sponsor to re-establish the program basis before any further work.",
    },
  ],
  commonMistakes: [
    { id: "cm-draft", description: "Treating a draft framework, MOU or term sheet as an executed agreement.", correction: "Read the directional banner as binding on interpretation; label every mechanic as proposed until Legal confirms execution." },
    { id: "cm-accounts", description: "Assuming every named account is immediately available to operate.", correction: "Model only accounts whose gate has opened and whose eligibility, access and exclusions are confirmed." },
    { id: "cm-partner", description: "Mixing no-partner and incumbent-partner operating assumptions in the same account population.", correction: "Segment the two treatments explicitly; incumbent-partner accounts carry different rights, engagement and economics." },
    { id: "cm-services", description: "Modeling professional or managed services revenue without confirmed rights to sell and deliver.", correction: "Move unconfirmed services revenue into a scenario variant until the right is evidenced." },
    { id: "cm-support", description: "Modeling support cost without confirming tiers, hours and entitlement scope.", correction: "Fix support scope with RunOps first, then derive staffing and cost from it." },
    { id: "cm-funding", description: "Assuming activation funding is cash received at kickoff.", correction: "Model funding on its proposed trigger and timing, and reflect the working-capital gap in Cash & Sustainability." },
    { id: "cm-mbg", description: "Applying MBG assumptions to accounts that do not qualify under the proposed conditions.", correction: "Apply MBG only to the qualifying population and show the qualification test alongside the number." },
    { id: "cm-downstream", description: "Changing scope here and failing to update the downstream pages that depend on it.", correction: "Run the reconciliation checklist across Portfolio, Revenue, P&L, Cash, Staffing, Timelines and Release & Activation after every scope change." },
  ],
  bestPractices: [
    "State the program version and source at the start of every review.",
    "Keep proposed and approved language separate in every artefact, including slides.",
    "Make every gate unlock condition testable with named evidence.",
    "Reconcile account scope to Portfolio before modeling anything new.",
    "Record unresolved terms as governance decisions with owners and dates rather than as silent assumptions.",
    "Re-check Day 0, Day 1 and Day 2 responsibilities whenever support or services scope moves.",
  ],
  workedExamples: [
    {
      id: "we-pilot-scope",
      title: "The controlled operator pilot account scope changes",
      narrative:
        "During pre-kickoff the deal team expected the controlled operator pilot to cover a set of no-partner healthcare accounts. Legal review then excludes two of them, and one further account is found to have an incumbent partner engagement that cannot be displaced at this phase. The pilot population shrinks and its mix changes. The correct response is not to adjust the revenue number in isolation — the program definition has moved, so every dependent page must be reconciled before the case is presented again.",
      steps: [
        "Portfolio scope changes: the pilot account population and its segmentation are updated, with exclusions recorded and evidenced.",
        "Activation sequencing changes: Release & Activation re-sequences which accounts may be activated at the pilot gate.",
        "Revenue eligibility changes: services and managed-services revenue for the excluded accounts is removed from the baseline; incumbent-partner treatment is applied to the third account.",
        "Staffing and delivery demand change: Staffing & Resources reduces or reshapes the Day 1 operator team for the smaller pilot.",
        "Funding needs may change: a smaller pilot may change the activation funding required and its timing in Cash & Sustainability.",
        "Gate evidence changes: the pilot gate unlock conditions referencing the original account list must be restated and re-evidenced.",
        "Governance approval is required: the Executive Sponsor approves the revised pilot scope, with Legal confirming the exclusions.",
      ],
      result:
        "Overview must not present the revised case until Portfolio, Revenue, P&L, Cash, Staffing, Timelines and Release & Activation are reconciled to the new program definition and the approval is recorded.",
    },
  ],
  faqs: [
    { id: "faq-auth", question: "What is the authoritative program definition?", answer: "The program record shown on this page — code, partner, segment, status and current gate — together with its ordered gate register, read against the registered source documents on Sources. Where a slide, spreadsheet or email disagrees with this page and its sources, this page and its sources govern the model." },
    { id: "faq-phase-gate", question: "What is the difference between a phase and a gate?", answer: "A phase is a period of work — pre-kickoff, controlled operator pilot, scale, segment expansion, mature operator. A gate is the decision point that opens the next phase. G0 is a readiness gate; G1 to G4 are formal decision gates. Gates have unlock conditions; phases have objectives and delivery." },
    { id: "faq-named", question: "Does an account name mean the account is activated?", answer: "No. A named account is a candidate. Activation requires the account's gate to be open, eligibility and exclusions confirmed, data and access available, and a release recorded on Release & Activation. Names in a deal document are not entitlements." },
    { id: "faq-authority", question: "What does operating authority mean?", answer: "It is the set of decision rights Neurealm would hold over an in-scope account — what it can decide, change or commit without Citrix approval, and what data and tooling it can use. Authority is currently proposed; it must match what Governance records before shared-risk economics are treated as credible." },
    { id: "faq-support", question: "How is support scope reflected financially?", answer: "Support tiers, hours and entitlements drive the operator headcount on Staffing & Resources, which drives cost on P&L, which flows to EBITDA and to Cash & Sustainability. Any proposed support-services funding offsets that cost on its own timing. Unresolved support scope therefore leaves cost and cash both uncertain." },
    { id: "faq-risk", question: "When can risk-sharing be modeled?", answer: "Only when Neurealm has the data, access, authority and agreed exclusions needed to influence the outcome, and the qualifying account population is defined. Until then, MBG and shared-risk mechanics should be shown as a scenario variant with the qualification test stated, not embedded in the baseline." },
    { id: "faq-approval", question: "What changes require executive approval?", answer: "Changes to strategic boundaries, partner or segment; changes to phase or gate structure; changes to account scope at a gate; and any change to risk-sharing, liability or funding treatment. Legal is consulted on authority, exclusions and liability; Finance on funding and economic treatment." },
    { id: "faq-where", question: "Which page should be updated when the program structure changes?", answer: "Start here — the program record and gates. Then update Portfolio for accounts, Assumptions & Change Sets for modeling assumptions, Timelines for sequencing, Staffing & Resources for the operating team, and Release & Activation for what may be activated. Record the decision on Governance." },
    { id: "faq-directional", question: "Why does the page carry a directional banner?", answer: "Because account-level validation and contractual confirmation are still pending. The banner is the page's honest status: the structure is usable for planning and gate preparation, but no term on it should be quoted as agreed or approved." },
  ],
  glossary: [
    { term: "Day 0", definition: "Pre-kickoff preparation: definition, readiness, access, authority and evidence gathering before any account is operated." },
    { term: "Day 1", definition: "Stand-up and transition: the operator capability is established and the first accounts are taken on under the opened gate." },
    { term: "Day 2", definition: "Steady-state run: ongoing operation, support, optimisation and account growth under the operator model." },
    { term: "Controlled Operator Pilot", definition: "The first live phase, run on a deliberately limited account population to prove the operating and economic model before scale." },
    { term: "Gate", definition: "A decision point with unlock conditions that must be evidenced before the next phase begins. G0 is a readiness gate; G1 to G4 are formal decision gates." },
    { term: "No-Partner Account", definition: "An in-scope account with no incumbent partner engagement, and therefore the simplest operator treatment." },
    { term: "Incumbent Partner", definition: "An existing partner already engaged in an account, whose presence changes engagement rights, economics and sequencing." },
    { term: "Activation Fund", definition: "Proposed funding to stand up the operator capability. Proposed only — not confirmed, and not assumed to be cash at kickoff." },
    { term: "Managed Services", definition: "Ongoing operated services delivered under the operator model, subject to confirmed services rights." },
    { term: "Professional Services", definition: "Project-based delivery services, subject to confirmed rights to sell and deliver into the account." },
    { term: "MBG", definition: "Minimum Business Guarantee — a proposed shared-risk mechanic setting a floor on business volume or value for qualifying accounts." },
    { term: "Operator Authority", definition: "The decision rights, data access and control granted to Neurealm to run in-scope accounts." },
  ],
  executiveTakeaway:
    "Program states the deal being modeled: the Citrix and Neurealm healthcare operator construct, the partner and segment, the current gate, and a staged progression of one readiness gate and four decision gates from controlled pilot to mature operator. Every term on the page is proposed and directional — account-level validation and contractual confirmation are pending. Use it to test whether the model has an agreed basis, whether the current gate's unlock conditions are genuinely evidenced, and whether downstream pages describe the same deal.",
  keyRisks: [
    "Proposed commercial mechanics being read as approved.",
    "Shared risk assumed without data, access or authority.",
    "Account scope drifting between Program, Portfolio and Release & Activation.",
    "Unconfirmed services rights carried in the baseline revenue model.",
    "Unresolved support scope leaving cost and staffing understated.",
    "Funding modeled as cash at kickoff rather than on its proposed trigger.",
  ],

  /* ---------------- Show on page ---------------- */
  showOnPageTargets: [
    { targetId: "program-context", label: "Directional model banner", description: "Status of the whole program definition — proposed and pending validation." },
    { targetId: "program-purpose", label: "Program summary card", description: "Program identity, status, current gate, partner, segment and strategic intent." },
    { targetId: "program-approval-status", label: "Status and current-gate badges", description: "Program code, program status and the gate currently in force." },
    { targetId: "program-scope", label: "Partner and segment scope", description: "The parties and market boundary for the deal." },
    { targetId: "program-phases", label: "Operating Gates section", description: "The staged gate model — one readiness gate plus four decision gates." },
    { targetId: "program-gates", label: "Gate cards", description: "Per-gate objectives, account scope label and unlock conditions." },
  ],
};
