import type { CommercialGuideContent } from "../../types";

/**
 * Page-specific Commercial Guide content — Sources (`/commercial/sources`).
 *
 * Authored strictly against what renders in
 * `src/commercial/pages/CommercialSources.tsx`: the directional banner, the
 * metadata-only confidentiality notice, and a two-column registry of source
 * cards. Each card shows a source code, a title, and three badges (source
 * type, confidentiality, status) plus optional notes. When no program exists
 * the page shows an empty state and a seed action for SRC-001 to SRC-006.
 *
 * Concepts requested but NOT rendered on this page (owner, date, version,
 * authority level, confidence rating, conflict status, supersession status,
 * related-page mapping, lineage view, search, filters, detail view, document
 * or file storage) are described only as practice or known gaps. No source is
 * invented here, and no upload, repository or connector exists.
 */
export const commercialSourcesGuide: CommercialGuideContent = {
  pageId: "commercial-sources",
  route: "/commercial/sources",
  match: "exact",
  pageTitle: "Sources",
  guideTitle: "Sources — Evidence, Provenance and Confidence",
  audiences: ["Executive", "Commercial Lead", "Finance", "Delivery", "Operations", "Administrator", "Sales"],
  modes: ["executive", "practitioner", "administrator"],
  estimatedReadingMinutes: 10,
  trainingLevel: "Foundation",
  lastUpdated: "2026-07-29",

  /* ---------------- Overview ---------------- */
  purpose:
    "Sources is the evidence, provenance and confidence foundation of the Commercial Digital Twin. It registers, as metadata only, the documents and data behind the model so any number in Revenue, P&L, Cash, Portfolio or Overview can be traced to something outside the model. Its job is to let the team separate source facts, estimates, assumptions and calculated outputs, and to tell draft material apart from approved material.",
  represents:
    "A confidential source register for Project Momentous: one card per registered reference, each with a source code, a title, a source type, a confidentiality classification, a status and optional notes. It represents what evidence exists and how it is classified — never the evidence itself. Raw content, transcripts, spreadsheets, contact information and credentials are deliberately not stored.",
  whyItMatters:
    "A model is only as strong as the evidence behind it. Without a register, an executive cannot tell whether a figure came from an agreement, a draft term sheet, a meeting or an analyst's judgement — and cannot reproduce the basis of a recommendation later. Sources makes provenance explicit, keeps draft and approved material distinct, and makes missing evidence visible instead of invisible.",
  moduleConnection:
    "Sources sits behind every other Commercial page. Program takes its deal definition from registered documents; Portfolio cannot import accounts without a registered account source; Assumptions & Change Sets, Revenue, P&L, Cash, Scenarios, Sensitivity and Release & Activation all rest on assumptions that should each point back to a source code here. Governance uses the register to judge whether a decision is decision-grade or still evidence-limited.",
  questionsAnswered: [
    "Where did this information come from?",
    "Who owns the source and is that ownership recorded anywhere?",
    "Is the source current, or has it been superseded?",
    "Is it approved, or is it still draft?",
    "Is the figure actual, estimated, assumed or calculated?",
    "Do two sources disagree, and has that conflict been disclosed?",
    "Is the evidence strong enough to support a decision?",
    "Which pages depend on this source?",
  ],
  expectedOutcome:
    "A shared, honest view of the evidence base: which references exist, how each is classified, what is still draft or confidential, and where evidence is missing — so downstream statements can be qualified correctly rather than presented with unearned certainty.",
  lifecycleStages: [
    "Opportunity Qualification",
    "Commercial Structuring",
    "Financial Modeling",
    "Executive Review",
    "Negotiation",
    "Delivery Planning",
    "Mobilization",
    "Execution",
    "Operations",
    "Continuous Improvement",
  ],
  prerequisites: [
    { id: "pre-source", label: "A known source", detail: "An identified document, data file, decision record or dataset that supports a model input." },
    { id: "pre-owner", label: "Source owner", detail: "A named person accountable for the source's accuracy. Tracked off-page today." },
    { id: "pre-date", label: "Source date", detail: "When the source was issued or last refreshed. Tracked off-page today." },
    { id: "pre-version", label: "Source version", detail: "The specific version relied upon, so the basis can be reproduced later." },
    { id: "pre-field", label: "Relevant page or model field", route: "/commercial/model/assumptions", detail: "The page, assumption or field the source supports." },
    { id: "pre-status", label: "Status", detail: "Draft, in review, approved or superseded — reflected in the status badge on the card." },
    { id: "pre-confidence", label: "Confidence", detail: "How strongly the source supports the input it underwrites." },
    { id: "pre-authority", label: "Approval or authority level", detail: "Whether the source carries contractual, financial or advisory authority." },
  ],
  ownership: {
    businessOwner: "Deal Lead",
    commercialOwner: "Commercial Lead",
    technicalOwner: "Designated model or source administrator (data steward)",
    executiveApprover: "Relevant governance body",
    primaryUsers: ["Deal Lead", "Commercial Lead", "Finance", "PMO", "Legal Lead", "Data owners", "Model administrators", "Governance reviewers", "Page owners"],
    consumersOfOutput: [
      "Program",
      "Portfolio",
      "Scenarios",
      "Assumptions & Change Sets",
      "Revenue",
      "P&L (Cost & EBITDA)",
      "Cash & Sustainability",
      "Scenario Comparison",
      "Sensitivity Analysis",
      "Release & Activation",
      "Governance",
      "Overview",
    ],
  },

  /* ---------------- How it works ---------------- */
  sections: [
    {
      id: "sec-context",
      title: "Directional model banner",
      targetId: "sources-context",
      explanation:
        "The banner states that the model is directional pending account-level validation and contractual confirmation. On Sources it sets the reading rule for the whole register: the presence of a reference proves that a document exists and has been classified, not that its terms are agreed. Draft and approved material must stay distinguishable everywhere the register is quoted.",
    },
    {
      id: "sec-confidentiality",
      title: "Metadata-only notice",
      targetId: "sources-confidentiality",
      explanation:
        "The lock notice states that only metadata is held: raw content, transcripts, spreadsheets, contact information and credentials are never stored here. This is a deliberate control, not a gap in the build. Sources is a register of references, not a document repository — the underlying material stays in its own system of record under existing handling rules.",
    },
    {
      id: "sec-registry",
      title: "Source registry",
      targetId: "sources-registry",
      explanation:
        "The registry is the two-column grid of registered source references for the program, ordered by source code. It is the page's principal output: the definitive list of what evidence the model claims to rest on. If a material input cannot be tied to a code shown here, it is an assumption and must be labelled as one on the page that uses it.",
    },
    {
      id: "sec-record",
      title: "Source card",
      targetId: "sources-record",
      explanation:
        "Each card is one registered reference. It carries the code, the title, its classification badges and optional notes — nothing more. There is no detail view, no attachment and no per-source page. Read a card as an index entry: it tells you a source exists and how it is classified, then points you to the owning system for the content itself.",
    },
    {
      id: "sec-identity",
      title: "Source code and title",
      targetId: "sources-identity",
      explanation:
        "The monospaced code (SRC-001 onward for the seeded Project Momentous pack) is the stable identifier used to cite the source elsewhere. The title describes what the source is. Cite the code, not the title, when linking an assumption to its evidence — titles change wording over time while the code remains the durable reference.",
    },
    {
      id: "sec-status",
      title: "Type, confidentiality and status badges",
      targetId: "sources-status",
      explanation:
        "Three badges per card. Source type says what kind of evidence it is. Confidentiality says how the material must be handled. Status says where the source stands in its own lifecycle — the field that determines whether it may be relied on. A source that is not approved cannot make a term approved, however precise the number derived from it looks.",
    },
    {
      id: "sec-notes",
      title: "Source notes",
      targetId: "sources-notes",
      explanation:
        "Optional notes give scope or handling context for the reference — what it covers and any caveat on its use. Notes are free text and are not a substitute for a recorded owner, date, version or confidence rating, none of which the page currently displays. Treat notes as guidance, not as an authority statement.",
    },
  ],
  inputs: [
    { id: "in-name", label: "Source name", description: "The title shown on the card. Owner: source owner. Approver: Deal Lead. Source: registered reference. Status: displayed. Confidence: high for the reference itself. Impact: identification of evidence.", owner: "Source owner", source: "Source register", required: true },
    { id: "in-code", label: "Source code", description: "Stable identifier (SRC-001 onward) used to cite the source from assumptions and pages. Owner: model administrator. Approver: Deal Lead. Source: source register. Status: displayed. Impact: citation and lineage.", owner: "Model administrator", source: "Source register", required: true },
    { id: "in-type", label: "Source type", description: "The kind of evidence — agreement, term sheet, account file, model, decision record, program documentation. Owner: model administrator. Approver: Commercial Lead. Status: displayed. Impact: how much weight the source may carry.", owner: "Model administrator", source: "Source register", required: true },
    { id: "in-confidentiality", label: "Confidentiality classification", description: "Handling classification for the underlying material. Owner: Legal. Approver: Legal. Status: displayed. Impact: who may see the underlying content and how it may be shared.", owner: "Legal Lead", source: "Source register", required: true },
    { id: "in-status", label: "Approval status", description: "Where the source stands — draft, in review, approved, superseded. Owner: source owner. Approver: relevant governance body. Status: displayed. Impact: whether the source may support a decision.", owner: "Source owner", source: "Source register", required: true },
    { id: "in-owner", label: "Owner", description: "The named person accountable for the source. Owner: Deal Lead to assign. Approver: Deal Lead. Source: off-page register. Status: not displayed on this page. Confidence: low. Impact: accountability for accuracy.", owner: "Deal Lead", source: "Off-page (not rendered)" },
    { id: "in-date", label: "Source date", description: "Issue or last-refresh date. Owner: source owner. Approver: Deal Lead. Source: the document itself. Status: not displayed. Confidence: low. Impact: recency and staleness assessment.", owner: "Source owner", source: "Off-page (not rendered)" },
    { id: "in-version", label: "Version", description: "The exact version relied upon. Owner: model administrator. Approver: Deal Lead. Source: the document itself. Status: not displayed. Impact: reproducibility of the model basis.", owner: "Model administrator", source: "Off-page (not rendered)" },
    { id: "in-authority", label: "Authority", description: "Whether the source carries contractual, financial or advisory authority. Owner: Legal for contractual, Finance for financial. Approver: Legal. Status: not displayed. Impact: how far a term may be stated as binding.", owner: "Legal Lead", source: "Off-page (not rendered)" },
    { id: "in-related-page", label: "Related page", description: "The Commercial page the source underwrites. Owner: page owner. Approver: Commercial Lead. Status: not displayed; maintained by convention. Impact: knowing what breaks when the source changes.", owner: "Page owner", source: "Off-page (not rendered)" },
    { id: "in-related-field", label: "Related field or assumption", description: "The specific assumption the source supports. Owner: Commercial Lead. Approver: Finance. Source: Assumptions & Change Sets. Status: maintained on the assumption record, not here. Impact: lineage from number to evidence.", owner: "Commercial Lead", source: "Assumptions & Change Sets" },
    { id: "in-confidence", label: "Confidence", description: "How strongly the source supports the input. Owner: Commercial Lead with Finance. Approver: governance body. Status: not displayed on this page. Impact: how strongly downstream results may be stated.", owner: "Commercial Lead", source: "Off-page (not rendered)" },
    { id: "in-gaps", label: "Known gaps", description: "Inputs with no source at all. Owner: page owner. Approver: Deal Lead. Source: page-level review. Status: recorded in each page's guide. Impact: readiness for decision.", owner: "Page owner", source: "Page-level review" },
    { id: "in-conflict", label: "Conflict status", description: "Whether two sources disagree on the same fact. Owner: Deal Lead. Approver: governance body. Status: not displayed on this page. Impact: blocks decision-ready status until resolved or accepted.", owner: "Deal Lead", source: "Off-page (not rendered)" },
    { id: "in-supersession", label: "Supersession status", description: "Whether a newer source replaces this one, and which. Owner: model administrator. Approver: Deal Lead. Status: expressible through the status badge only. Impact: traceability of the historic basis.", owner: "Model administrator", source: "Source status badge" },
    { id: "in-handling", label: "Handling requirements", description: "How the underlying material may be stored and shared, per existing application controls. Owner: Legal. Approver: Legal. Status: displayed via the confidentiality badge. Impact: compliance.", owner: "Legal Lead", source: "Source register", required: true },
  ],
  outputs: [
    { id: "out-register", label: "Source register", description: "The definitive list of registered references, by code, type, confidentiality and status.", consumedBy: ["Program", "Portfolio", "Assumptions & Change Sets", "Governance"] },
    { id: "out-status", label: "Evidence status", description: "Whether the evidence behind an input is draft, in review, approved or superseded.", consumedBy: ["Governance", "Release & Activation", "Overview"] },
    { id: "out-confidence", label: "Confidence guidance", description: "How strongly downstream outputs may be stated given the evidence available.", consumedBy: ["Overview", "Scenarios", "Sensitivity Analysis"] },
    { id: "out-gaps", label: "Known gaps", description: "Material inputs with no registered source, which must be labelled as assumptions.", consumedBy: ["Assumptions & Change Sets", "Governance"] },
    { id: "out-conflicts", label: "Source conflicts", description: "Disagreements between sources on the same fact, disclosed rather than averaged away.", consumedBy: ["Portfolio", "Revenue", "Governance"] },
    { id: "out-lineage", label: "Data lineage", description: "The chain from a displayed number back through its assumption to a source code.", consumedBy: ["Revenue", "P&L (Cost & EBITDA)", "Cash & Sustainability"] },
    { id: "out-affected", label: "Pages affected", description: "Which Commercial pages depend on a given source and must be re-checked when it changes.", consumedBy: ["All Commercial Module pages"] },
    { id: "out-readiness", label: "Readiness for decision", description: "Whether the evidence base is strong enough to support an executive decision.", consumedBy: ["Governance", "Overview"] },
  ],
  businessRules: [
    { id: "br-identify", rule: "Every material model input has an identifiable source or is explicitly labelled an assumption", explanation: "There is no third category. If an input cannot be tied to a source code in this register, it must be shown as an assumption on the page that uses it, with an owner. Unlabelled judgement is the most common way a model loses credibility." },
    { id: "br-draft", rule: "Draft documents must not be represented as executed agreements", explanation: "The status badge is the control. A draft term sheet supports planning; it does not make a term binding. Guides, exports and executive summaries must repeat the draft status rather than smoothing it into settled language." },
    { id: "br-newer", rule: "Newer does not automatically mean more authoritative", explanation: "A recent working spreadsheet does not outrank an approved agreement. Weigh authority first — contractual, then financial system of record, then analytical — and use date only to choose between sources of equal authority." },
    { id: "br-superseded", rule: "Superseded sources remain traceable", explanation: "Mark a source superseded and record what replaced it; never delete it. Past recommendations were made on the old basis, and reproducing them later is only possible if the superseded reference still exists." },
    { id: "br-conflict", rule: "Conflicting sources must be resolved or disclosed", explanation: "Where two sources disagree on the same fact, either resolve the conflict on authority and date with a named owner, or disclose it alongside the number. Silently choosing the convenient figure is the failure mode this rule exists to prevent." },
    { id: "br-calculated", rule: "Calculated outputs must identify their upstream inputs", explanation: "A calculated figure is evidence only to the extent its inputs are. Model results should trace to assumptions, and assumptions to source codes, so a reviewer can walk from an EBITDA line back to a document." },
    { id: "br-desirability", rule: "Source confidence is not the same as commercial desirability", explanation: "Confidence measures how well evidence supports a value, not how much the team likes the value. A well-evidenced disappointing number is high confidence; an attractive number with thin evidence is not." },
    { id: "br-silent", rule: "A source must not be silently changed to fit a desired model outcome", explanation: "Changing the evidence to match the answer inverts the process. Any change of source must be recorded as a supersession with a reason, and every dependent page re-checked afterwards." },
    { id: "br-sensitive", rule: "Sensitive information is handled under existing application controls", explanation: "This page holds metadata only — no raw content, transcripts, spreadsheets, contact details or credentials. The confidentiality badge states the handling class; the underlying material stays in its own controlled system." },
    { id: "br-missing", rule: "Missing evidence lowers confidence and may block approval", explanation: "An evidence gap is a finding, not a formatting problem. Record it, lower stated confidence accordingly, and expect governance to withhold decision-ready status where a material input is unsupported." },
  ],
  calculationLogic: [
    "Sources performs no calculation. It registers references and their classification only.",
    "Cards are ordered by source code; the code is the stable citation key used elsewhere in the module.",
    "Type, confidentiality and status are recorded classifications, not derived values.",
    "When no program exists in the workspace, the page shows an empty state and offers to seed the Project Momentous references SRC-001 to SRC-006.",
  ],
  relationship: {
    receivesFrom: [
      "Agreements",
      "Draft term sheets",
      "Account files",
      "Financial models",
      "Meeting decisions",
      "Customer data",
      "Program documentation",
      "Governance records",
    ],
    models: [
      "Source registry",
      "Provenance",
      "Recency",
      "Authority",
      "Confidence",
      "Conflicts",
      "Data lineage",
      "Evidence gaps",
    ],
    feeds: [
      "Program",
      "Portfolio",
      "Scenarios",
      "Assumptions & Change Sets",
      "Revenue",
      "P&L (Cost & EBITDA)",
      "Cash & Sustainability",
      "Scenario Comparison",
      "Sensitivity Analysis",
      "Release & Activation",
      "Timelines",
      "Staffing & Resources",
      "Governance",
      "Overview",
    ],
  },
  downstreamImpacts: [
    { area: "Accounts", effect: "Account import cannot proceed without a registered, current account source." },
    { area: "Revenue", effect: "Revenue mechanics may only be stated as firmly as the source behind them." },
    { area: "Costs", effect: "Cost assumptions without a source must be labelled and owned." },
    { area: "Cash", effect: "Funding timing rests on term-sheet material that remains draft." },
    { area: "Governance", effect: "Evidence status determines whether a decision may be taken or must be deferred." },
    { area: "Risk", effect: "Undisclosed conflicts and evidence gaps are top-tier model risks." },
    { area: "Activation", effect: "Release decisions require approved evidence, not draft references." },
    { area: "Timeline", effect: "Waiting on evidence is a legitimate and common cause of gate delay." },
  ],
  dataQuality: {
    dataSources: [
      "commercial_source_references — source code, title, type, confidentiality, status, notes (metadata only)",
      "Seeded Project Momentous source pack (SRC-001 to SRC-006)",
    ],
    updateFrequency: "On registration of a new reference, on supersession, and at each gate review.",
    knownGaps: [
      "No owner displayed per source.",
      "No source date or last-updated field displayed.",
      "No version field displayed.",
      "No authority level displayed.",
      "No confidence rating displayed per source.",
      "No conflict status field or conflict view.",
      "No supersession pointer showing which source replaced which.",
      "No related-pages or related-field mapping shown on this page.",
      "No lineage view from a source to the numbers it supports.",
      "No search or filters over the register.",
      "No per-source detail view; each card is the full record.",
      "No document storage, upload, repository or external connector — metadata only, by design.",
    ],
    changeControl: "New references and supersessions are registered through the seeded source pack and governance; sources are never edited to fit a desired outcome and are never deleted.",
    lineage: "Source references are tenant-scoped and joined to the program record; lineage to individual assumptions is maintained on Assumptions & Change Sets rather than here.",
  },
  modelConfidence: "Medium",
  confidenceBasis: ["Source completeness", "Commercial terms", "Governance approvals"],
  confidenceGuidance:
    "Confidence in the existence and classification of the registered references is reasonable — they are recorded and coded. Confidence in the evidence base as a whole is limited by what the page does not carry: no owner, date, version, authority or confidence rating is displayed, and conflicts are not tracked here. Treat the register as an index, and hold the qualitative judgement in governance until those attributes are recorded.",
  commercialReadiness: "Review Required",
  readinessCriteria: [
    "Every material model input traces to a source code or is labelled an assumption.",
    "Draft and approved material are distinguishable in every downstream statement.",
    "Each registered source has a named owner and a known date, recorded somewhere authoritative.",
    "Known conflicts are either resolved on authority or explicitly disclosed.",
    "Superseded references are retained and marked, not deleted.",
    "Evidence gaps are recorded with owners and reflected in stated confidence.",
  ],

  /* ---------------- How to use it ---------------- */
  workflow: [
    { id: "wf-1", step: 1, title: "Identify the information requiring support", description: "Start from the number or term under review and state precisely what fact needs evidence.", role: "Page Owner" },
    { id: "wf-2", step: 2, title: "Find the authoritative source", description: "Locate the highest-authority material covering that fact — agreement first, then system of record, then analytical material.", role: "Data Owner" },
    { id: "wf-3", step: 3, title: "Record owner, date, version and status", description: "Capture accountability and recency. The page shows status only, so owner, date and version must be held in the governance record.", role: "Model administrator" },
    { id: "wf-4", step: 4, title: "Classify the value", description: "Mark the supported value as actual, estimated, assumed or calculated, and carry that label wherever the value appears.", role: "Commercial Lead" },
    { id: "wf-5", step: 5, title: "Link the source to the page or assumption", description: "Cite the source code on the assumption record so the number can be traced back to its evidence.", role: "Page Owner" },
    { id: "wf-6", step: 6, title: "Check for conflicts", description: "Compare against other sources covering the same fact and note any disagreement before using the value.", role: "Deal Lead" },
    { id: "wf-7", step: 7, title: "Record confidence and known gaps", description: "State how strongly the evidence supports the value and what is still missing.", role: "Commercial Lead" },
    { id: "wf-8", step: 8, title: "Route contractual interpretation to Legal", description: "Any reading of a term, obligation, exclusion or liability goes to Legal rather than being interpreted in the model.", role: "Legal Lead" },
    { id: "wf-9", step: 9, title: "Replace superseded sources without deleting lineage", description: "Mark the old reference superseded, register the replacement, and keep both so past decisions remain reproducible.", role: "Model administrator" },
    { id: "wf-10", step: 10, title: "Confirm the dependent page reflects the current source", description: "Re-open each page that relied on the old source and confirm its values and labels now match the new one.", role: "Page Owner" },
    { id: "wf-11", step: 11, title: "Disclose unresolved conflicts", description: "Where a conflict cannot be resolved, disclose it next to the number and record it for governance rather than choosing quietly.", role: "Deal Lead" },
    { id: "wf-12", step: 12, title: "Take the evidence position to governance", description: "Present the evidence status, gaps and conflicts so the approver can accept the uncertainty or defer the decision.", role: "Governance reviewer" },
  ],
  actionsAvailable: [
    "Read the registered source references — code, title, type, confidentiality, status and notes",
    "Read the metadata-only handling notice",
    "Seed the Project Momentous source pack (SRC-001 to SRC-006) when no program exists in the workspace",
  ],
  teamActivities: [
    { id: "ta-page", activity: "Identify the evidence required for each material input on the owned page", role: "Page Owner", cadence: "Per model run cycle" },
    { id: "ta-data", activity: "Validate source accuracy, recency and completeness", role: "Data Owner", cadence: "On registration and refresh" },
    { id: "ta-comm", activity: "Validate commercial relevance and the actual/estimated/assumed classification", role: "Commercial Lead", cadence: "Weekly" },
    { id: "ta-fin", activity: "Validate financial sources and their treatment in the model", role: "Finance", cadence: "Per model run cycle" },
    { id: "ta-legal", activity: "Validate contractual authority, confidentiality handling and draft-versus-executed status", role: "Legal Lead", cadence: "On each new contractual reference" },
    { id: "ta-pmo", activity: "Maintain decision and meeting sources and keep governance records aligned", role: "PMO", cadence: "Weekly" },
    { id: "ta-admin", activity: "Maintain source references, codes, supersessions and lineage", role: "Model administrator", cadence: "On change" },
    { id: "ta-exec", activity: "Accept material uncertainty explicitly where a decision must proceed without complete evidence", role: "Executive Approver", cadence: "At gate review" },
    { id: "ta-gov", activity: "Review evidence status, conflicts and gaps before granting decision-ready status", role: "Governance reviewer", cadence: "At gate review" },
  ],
  roles: [
    { role: "Deal Lead", responsibility: "Owns the evidence position of the deal and the resolution of source conflicts." },
    { role: "Model administrator (Data Steward)", responsibility: "Owns the register itself — codes, classifications, supersessions and lineage." },
    { role: "Commercial Lead", responsibility: "Owns commercial relevance and the classification of supported values." },
    { role: "Finance", responsibility: "Owns financial sources and their consistent treatment in the model." },
    { role: "Legal Lead", responsibility: "Owns contractual authority, confidentiality classification and the draft-versus-executed distinction." },
    { role: "PMO", responsibility: "Owns decision and meeting records used as sources." },
    { role: "Page Owner", responsibility: "Owns identifying what evidence their page requires and confirming it is current." },
    { role: "Governance reviewer", responsibility: "Owns the judgement on whether the evidence base supports a decision." },
  ],
  raci: [
    { activity: "Register a new source reference", assignments: [{ role: "Model administrator", raci: "R" }, { role: "Deal Lead", raci: "A" }, { role: "Commercial Lead", raci: "C" }, { role: "PMO", raci: "I" }] },
    { activity: "Classify confidentiality and authority", assignments: [{ role: "Legal Lead", raci: "R" }, { role: "Deal Lead", raci: "A" }, { role: "Model administrator", raci: "C" }, { role: "Finance", raci: "I" }] },
    { activity: "Resolve a source conflict", assignments: [{ role: "Deal Lead", raci: "R" }, { role: "Governance reviewer", raci: "A" }, { role: "Finance", raci: "C" }, { role: "Page Owner", raci: "I" }] },
    { activity: "Supersede a source and preserve lineage", assignments: [{ role: "Model administrator", raci: "R" }, { role: "Deal Lead", raci: "A" }, { role: "PMO", raci: "C" }, { role: "Page Owner", raci: "I" }] },
    { activity: "Record confidence and evidence gaps", assignments: [{ role: "Commercial Lead", raci: "R" }, { role: "Finance", raci: "A" }, { role: "Page Owner", raci: "C" }, { role: "Governance reviewer", raci: "I" }] },
    { activity: "Accept material uncertainty for a decision", assignments: [{ role: "Executive Approver", raci: "A" }, { role: "Deal Lead", raci: "R" }, { role: "Legal Lead", raci: "C" }, { role: "Finance", raci: "C" }] },
  ],
  reviewRequirements: [
    "Register reviewed before each gate review for staleness and supersession.",
    "Every material input checked for a source citation or an explicit assumption label.",
    "Contractual references reviewed by Legal for draft-versus-executed accuracy.",
    "Known conflicts reviewed and either resolved or formally disclosed.",
  ],
  approvalRequirements: [
    "Legal approval for confidentiality classification and any contractual interpretation.",
    "Finance approval for financial sources relied on in Revenue, P&L and Cash.",
    "Deal Lead approval to supersede a source used by a downstream page.",
    "Governance approval to proceed on a decision where a material evidence gap remains.",
  ],
  decisions: [
    { id: "dec-authoritative", decision: "Which source is authoritative for a contested fact", decidedBy: "Deal Lead with Legal or Finance", evidence: "Authority level and source date" },
    { id: "dec-classify", decision: "Whether a value is actual, estimated, assumed or calculated", decidedBy: "Commercial Lead with Finance", evidence: "Source type and status" },
    { id: "dec-supersede", decision: "Whether a source is superseded and by what", decidedBy: "Model administrator with Deal Lead", evidence: "Replacement reference and reason" },
    { id: "dec-accept", decision: "Whether to accept an evidence gap and proceed", decidedBy: "Executive Approver at gate review", evidence: "Recorded gap, owner and impact" },
  ],
  whatToDoNext: [
    "Check that every material input on your page cites a source code or is labelled an assumption.",
    "Record owner, date and version for each reference in the governance record, since the page does not display them.",
    "Raise any two sources that disagree on the same fact as a conflict with a named owner.",
    "Confirm draft references are not being quoted as approved anywhere downstream.",
    "Review Assumptions & Change Sets for assumptions with no supporting source.",
    "Take unresolved evidence gaps to Governance before the next gate review.",
  ],
  relatedPages: [
    { pageId: "commercial-program", label: "Program", route: "/commercial/program", relationship: "Downstream" },
    { pageId: "commercial-portfolio", label: "Portfolio", route: "/commercial/portfolio", relationship: "Downstream" },
    { pageId: "commercial-assumptions", label: "Assumptions & Change Sets", route: "/commercial/model/assumptions", relationship: "Companion" },
    { pageId: "commercial-scenarios", label: "Scenarios", route: "/commercial/scenarios", relationship: "Downstream" },
    { pageId: "commercial-revenue", label: "Revenue", route: "/commercial/model/revenue", relationship: "Downstream" },
    { pageId: "commercial-pnl", label: "P&L (Cost & EBITDA)", route: "/commercial/model/pnl", relationship: "Downstream" },
    { pageId: "commercial-cash", label: "Cash & Sustainability", route: "/commercial/model/cash", relationship: "Downstream" },
    { pageId: "commercial-release", label: "Release & Activation", route: "/commercial/model/release", relationship: "Downstream" },
    { pageId: "commercial-governance", label: "Governance", route: "/commercial/neurealm-governance", relationship: "Companion" },
    { pageId: "commercial-overview", label: "Overview", route: "/commercial", relationship: "Downstream" },
  ],

  /* ---------------- Interpretation & training ---------------- */
  interpretation: [
    {
      band: "healthy",
      label: "Evidence base is current and traceable",
      criteria: [
        "Material inputs have current, registered sources.",
        "Ownership of each source is clear.",
        "Draft and approved materials are distinct everywhere they are used.",
        "Known conflicts are resolved on authority and date.",
        "Confidence is explained rather than asserted.",
        "Dependent pages for each source are identifiable.",
      ],
      action: "Allow decision-ready status: the model basis can be reproduced and defended.",
    },
    {
      band: "warning",
      label: "Evidence is partial or ageing",
      criteria: [
        "A material input relies on a portfolio average rather than an actual.",
        "A source is stale relative to the decision being taken.",
        "The owner of a source is unknown.",
        "Multiple sources conflict on the same fact.",
        "An assumption has limited supporting evidence.",
        "Contractual terms remain in draft.",
      ],
      action: "Keep the affected outputs labelled, assign each gap and conflict an owner and date, and disclose the evidence position in any executive material.",
    },
    {
      band: "critical",
      label: "The model basis cannot be defended",
      criteria: [
        "A binding recommendation relies on an unsupported value.",
        "Draft terms are being presented as approved.",
        "Source lineage is missing for a material number.",
        "A material conflict is hidden rather than disclosed.",
        "The team cannot reproduce the model basis.",
      ],
      action: "Withdraw the recommendation, stop external use of the model, and escalate to the Deal Lead, Legal and the Executive Approver to re-establish the evidence base.",
    },
  ],
  commonMistakes: [
    { id: "cm-unlinked", description: "Registering a document without linking it to the model fields it supports.", correction: "Cite the source code on the assumption record so the number and the evidence stay connected." },
    { id: "cm-meeting", description: "Treating meeting discussion as formal approval.", correction: "A decision record can evidence intent; only an approved document evidences approval. Keep the two apart." },
    { id: "cm-oldbook", description: "Using an older workbook because it supports the preferred scenario.", correction: "Choose the source by authority and date, not by outcome, and record the reason for the choice." },
    { id: "cm-confidence", description: "Confusing source confidence with confidence in the result.", correction: "A strong source can still feed a volatile calculation. State evidence confidence and result confidence separately." },
    { id: "cm-delete", description: "Deleting superseded evidence once a newer version arrives.", correction: "Mark it superseded and keep it, so earlier recommendations remain reproducible." },
    { id: "cm-label", description: "Failing to label assumptions, so judgement reads as fact.", correction: "Anything without a source code is an assumption and must say so on the page that uses it." },
    { id: "cm-transcript", description: "Treating a transcript or summary as a contract.", correction: "Route any contractual reading to Legal; a transcript records what was said, not what was agreed." },
    { id: "cm-stale-pages", description: "Correcting a source and leaving the dependent pages unchanged.", correction: "Walk the dependency list after every supersession and confirm each page now reflects the current source." },
  ],
  bestPractices: [
    "Cite source codes, not document titles, when linking evidence to assumptions.",
    "Record owner, date and version in the governance record because the page does not display them.",
    "Weigh authority before recency when two sources disagree.",
    "Disclose conflicts next to the number rather than resolving them silently.",
    "Keep superseded references in the register permanently.",
    "Re-check dependent pages after every source change.",
  ],
  workedExamples: [
    {
      id: "we-arr-conflict",
      title: "Two sources disagree on account ARR and renewal date",
      narrative:
        "A registered account file gives an account's ARR and a renewal date in one quarter. A more recent working spreadsheet circulated after a customer meeting gives a higher ARR and a renewal date a quarter later. Both are registered references. The temptation is to take the more recent figure, or to average the two so the model still runs. Both responses destroy the evidence trail: one substitutes recency for authority, the other invents a value that neither source supports.",
      steps: [
        "Do not average the two values, and do not quietly adopt either one.",
        "Identify authority and date: the contract or billing system of record outranks a working spreadsheet regardless of which is newer.",
        "Assign an owner — here Finance for the ARR value and the Account Lead for the renewal date — with a date to resolve.",
        "Record the conflict against the affected input so any reader of the number sees the disagreement.",
        "Withhold decision-ready status for anything that depends on the value until the conflict is resolved or the Executive Approver explicitly accepts the uncertainty.",
        "On resolution, register the losing source as superseded rather than deleting it, and keep both traceable.",
      ],
      result:
        "After resolution, Portfolio is updated with the authoritative ARR and renewal date, and Revenue, Cash, Timelines and Scenario Comparison are re-run so every downstream output reflects the same evidence basis before any executive material is reissued.",
    },
  ],
  faqs: [
    { id: "faq-authoritative", question: "What counts as an authoritative source?", answer: "The material with the strongest standing for that fact: an executed agreement for contractual terms, the contract or billing system of record for financial values, the account system for account data, and an approved governance record for decisions. Working spreadsheets, drafts, transcripts and analyses are supporting material, not authority — however recent they are." },
    { id: "faq-transcript", question: "Can a meeting transcript support an assumption?", answer: "It can support an assumption, but it cannot make a term approved. Register it as a decision or meeting source, label the value it supports as assumed, and route any contractual reading to Legal. This page holds metadata only; the transcript itself is never stored here." },
    { id: "faq-conflict", question: "How do I handle conflicting values?", answer: "Never average them silently. Compare authority first and date second, assign an owner, record the conflict against the affected input, and withhold decision-ready status until it is resolved or the uncertainty is formally accepted. Once resolved, mark the losing source superseded and update the dependent pages." },
    { id: "faq-actual", question: "What is the difference between actual and assumed?", answer: "An actual is a value taken from an authoritative record of what is true today. An estimate is derived from actuals with a stated method. An assumption is a chosen input with no source behind it. A calculated output is produced by the model from the others. Every material value should sit in exactly one of those four categories and say so." },
    { id: "faq-delete", question: "Should superseded sources be deleted?", answer: "No. Mark them superseded and keep them. Decisions were taken on the earlier basis, and the ability to reproduce those decisions later depends on the superseded reference still existing. Deletion breaks lineage and is treated as a governance failure." },
    { id: "faq-confidence", question: "Who sets confidence?", answer: "The Commercial Lead with Finance, based on the source's authority, recency, completeness and any conflicts — not on how attractive the resulting number is. Governance reviews the stated confidence before granting decision-ready status. The page does not display a confidence rating today, so it is held in the governance record." },
    { id: "faq-whole-model", question: "Why does source status affect the whole model?", answer: "Because every page resolves back to evidence. Program takes its deal definition from documents, Portfolio needs a registered account source, and Revenue, P&L and Cash rest on assumptions that should each cite a code here. A draft or superseded source therefore limits how strongly every dependent output may be stated." },
    { id: "faq-which-page", question: "Which page should be changed after a source is corrected?", answer: "Not this one — the register records the reference, not the values. Update the assumption on Assumptions & Change Sets, then re-check Program, Portfolio, Revenue, P&L, Cash, Timelines, Staffing & Resources and Release & Activation, re-run the affected scenarios, and record the change on Governance." },
  ],
  glossary: [
    { term: "Provenance", definition: "Where a value came from — the document, dataset or decision that produced it, and the path it took into the model." },
    { term: "Source Authority", definition: "The standing a source carries for a given fact: contractual, financial system of record, operational or advisory." },
    { term: "Actual", definition: "A value taken directly from an authoritative record of what is true today." },
    { term: "Estimate", definition: "A value derived from actuals by a stated method, labelled as estimated wherever it appears." },
    { term: "Assumption", definition: "A chosen input with no supporting source, owned by a named person and visible as an assumption." },
    { term: "Calculated", definition: "A value produced by the model from other inputs; only as strong as the inputs behind it." },
    { term: "Superseded", definition: "A source replaced by a newer reference, retained in the register so earlier decisions remain reproducible." },
    { term: "Lineage", definition: "The traceable chain from a displayed number, through its assumption, to a registered source code." },
    { term: "Confidence", definition: "How strongly the available evidence supports a value — independent of whether the value is commercially welcome." },
    { term: "Evidence Gap", definition: "A material input with no registered source, which lowers confidence and may block approval." },
    { term: "Confidentiality Classification", definition: "The handling class shown on each card, governing how the underlying material may be stored and shared." },
    { term: "Source Code", definition: "The stable identifier (SRC-001 onward) used to cite a reference from assumptions and pages." },
  ],
  executiveTakeaway:
    "Sources is the register that makes the model defensible: it records, as metadata only, what evidence exists behind the deal and how each reference is classified. It deliberately stores no documents, transcripts or credentials. Its current limits matter — no owner, date, version, authority or confidence is displayed, and conflicts are not tracked here — so those judgements sit with governance. Treat unsourced material as an assumption and say so.",
  keyRisks: [
    "Draft term-sheet material being read as executed agreement.",
    "Material inputs with no registered source and no assumption label.",
    "Conflicting sources resolved silently in favour of the preferred outcome.",
    "Superseded evidence deleted, making earlier recommendations irreproducible.",
    "Owner, date and version held informally because the page does not display them.",
    "Dependent pages left stale after a source is corrected or replaced.",
  ],

  /* ---------------- Show on page ---------------- */
  showOnPageTargets: [
    { targetId: "sources-context", label: "Directional model banner", description: "Sets the reading rule: a registered reference is not an agreed term." },
    { targetId: "sources-confidentiality", label: "Metadata-only notice", description: "Raw content, transcripts, spreadsheets, contact info and credentials are never stored here." },
    { targetId: "sources-registry", label: "Source registry", description: "The grid of registered source references for the program, ordered by code." },
    { targetId: "sources-record", label: "Source card", description: "One registered reference — code, title, classification badges and optional notes." },
    { targetId: "sources-identity", label: "Source code and title", description: "The stable citation key and the description of the reference." },
    { targetId: "sources-status", label: "Type, confidentiality and status badges", description: "What kind of evidence it is, how it must be handled, and whether it may be relied on." },
    { targetId: "sources-notes", label: "Source notes", description: "Optional scope or handling context; not a substitute for owner, date or confidence." },
  ],
};
