import type { CommercialGuideContent } from "../../types";

/**
 * Page-specific Commercial Guide content — Assumptions & Change Sets
 * (`/commercial/model/assumptions`, prefix-matched so the change-set detail
 * route `/commercial/model/assumptions/change-sets/:id` shares this guide).
 *
 * Authored strictly against what renders in
 * `src/commercial/pages/CommercialAssumptions.tsx` (page heading "Governed
 * Assumption Editing", staleness alert, change-set panel, effective-assumption
 * register with search / scenario / impact filters and a proposed-value entry
 * column) and `src/commercial/pages/CommercialAssumptionChangeSet.tsx`
 * (change-set header, status badge, timestamps, validation and impact alerts,
 * Validate / Apply / Cancel actions, and the current-vs-proposed item table).
 *
 * The real lifecycle is Draft → Validated → Applied, with Cancelled as a
 * terminal branch from Draft or Validated. Item-level validation states are
 * unvalidated, valid, warning and error. There is no separate approval status,
 * no history timeline, no owner, source or confidence field on the page —
 * those are recorded as known gaps and as governance practice, never invented
 * as page behaviour.
 */
export const commercialAssumptionsGuide: CommercialGuideContent = {
  pageId: "commercial-assumptions",
  route: "/commercial/model/assumptions",
  match: "prefix",
  pageTitle: "Assumptions & Change Sets",
  guideTitle: "Assumptions & Change Sets — Governed Assumption Editing",
  audiences: ["Executive", "Commercial Lead", "Finance", "Delivery", "Operations", "Administrator", "Sales"],
  modes: ["executive", "practitioner", "administrator"],
  estimatedReadingMinutes: 12,
  trainingLevel: "Intermediate",
  lastUpdated: "2026-07-29",

  /* ---------------- Overview ---------------- */
  purpose:
    "This page is where the controlled inputs of the Commercial Digital Twin are read and changed. The register shows the effective assumption values the calculation runtime consumes; change sets provide the governed route to propose a new value, validate it, apply it to the Draft model version, or cancel it. Nothing on this page edits a calculated output, and nothing takes effect until a change set is applied.",
  represents:
    "Two linked surfaces. The register lists effective assumptions resolved from the scenario assumption store — code, scenario, effective value, unit and impact scope. The change-set surface lists change sets for the program and, on the detail route, one change set with its status, timestamps, validation state, impacted scopes, controlled actions and a current-versus-proposed item table. It represents controlled inputs and proposals, not results.",
  whyItMatters:
    "Every figure in Revenue, P&L, Cash, Scenario Comparison, Sensitivity and Overview traces back to an assumption. If assumptions can be changed informally, results become unreproducible and no executive can tell what a number was based on. Change sets make each proposal explicit — what changed, from what, to what, why, in which scenario, validated by whom, applied when — so the model stays defensible under challenge.",
  moduleConnection:
    "Assumptions sits between evidence and results. It receives context from Program, Portfolio, Sources, commercial terms, staffing and timeline plans, and governance decisions. It controls the values that Scenarios, Revenue, P&L, Cash, Scenario Comparison, Sensitivity Analysis, Release & Activation, Staffing & Resources and Overview consume. An apply changes future runs only — completed runs stay immutable, so affected scopes must be re-executed on their own pages before any output is quoted.",
  questionsAnswered: [
    "What assumptions drive the model, and what is each one's effective value?",
    "Which scenario does a value belong to?",
    "What evidence supports it and how confident are we?",
    "Who owns the assumption being changed?",
    "What is being proposed to change, from what value to what value?",
    "Which pages and outcomes will move if it is applied?",
    "Has the change been validated, and who must review and approve it?",
    "Has the change been applied, and are the model runs now stale?",
  ],
  expectedOutcome:
    "A controlled assumption register whose effective values reconcile to model outputs, plus a traceable set of proposals — each with rationale, current and proposed values, impact scope, validation result and a recorded apply or cancel — so a change can be explained and reproduced long after it was made.",
  lifecycleStages: [
    "Commercial Structuring",
    "Financial Modeling",
    "Executive Review",
    "Negotiation",
    "Delivery Planning",
    "Operations",
    "Continuous Improvement",
  ],
  prerequisites: [
    { id: "pre-baseline", label: "Current active model or baseline", route: "/commercial/model/release", detail: "A Draft model version must exist — change sets are created against it. Applied changes affect future runs only." },
    { id: "pre-evidence", label: "Current source evidence", route: "/commercial/sources", detail: "A registered source code supporting the proposed value. Held off-page; the register shows no source field today." },
    { id: "pre-owner", label: "Defined assumption owner", detail: "A named person accountable for the value. Tracked in governance records, not on this page." },
    { id: "pre-scenario", label: "Defined scenario", route: "/commercial/scenarios", detail: "Every change set item is scenario-specific. Values must not be carried between Base, Downside and Upside." },
    { id: "pre-rationale", label: "Change rationale", detail: "Entered on the change-set description and, per item, in the rationale field on the register row." },
    { id: "pre-impact", label: "Impact assessment", detail: "The impact scopes (revenue, pnl, cash) shown per assumption, plus the downstream reading the team performs before applying." },
    { id: "pre-reviewer", label: "Reviewer and approver", detail: "Validate and apply are separate permissions. Executive approval for material changes is a governance control outside the page." },
  ],
  ownership: {
    businessOwner: "Owner of the underlying assumption (Revenue Owner, Cost Owner, Staffing Lead or Deal Lead as applicable)",
    commercialOwner: "Commercial Lead",
    technicalOwner: "Finance or Model Administrator",
    executiveApprover: "Designated approval body, by materiality",
    primaryUsers: ["Commercial Lead", "Finance", "Deal Lead", "Model Administrator", "Program Director", "Staffing Lead", "Revenue Owner", "Cost Owner", "Governance reviewers", "Executive approvers"],
    consumersOfOutput: [
      "Scenarios",
      "Sensitivity Analysis",
      "Revenue",
      "P&L (Cost & EBITDA)",
      "Cash & Sustainability",
      "Scenario Comparison",
      "Release & Activation",
      "Staffing & Resources",
      "Governance",
      "Overview",
    ],
  },

  /* ---------------- How it works ---------------- */
  sections: [
    {
      id: "sec-summary",
      title: "Assumption summary header",
      targetId: "assumptions-summary",
      explanation:
        "The heading reads Governed Assumption Editing and, when a Draft model version exists, shows its version code as a badge. The supporting line states the operating rule for the whole page: changes are proposed, validated and applied against the Draft model version, and applying updates future runs only — historical Revenue, P&L and Cash runs remain immutable. Read the badge first; without a Draft version no change set can be created.",
    },
    {
      id: "sec-staleness",
      title: "Stale model run alert",
      targetId: "assumptions-staleness",
      explanation:
        "This alert appears when assumptions changed after the last completed run for one or more scopes, and it names the affected scopes. It is the page's warning that outputs elsewhere no longer reflect the current inputs. An applied change is not visible in Revenue, P&L or Cash until those scopes are re-executed on their own pages, so treat a stale scope as a reason not to quote its numbers.",
    },
    {
      id: "sec-changesets",
      title: "Change sets panel",
      targetId: "change-sets-list",
      explanation:
        "Lists the program's change sets and lets you select an active one or create a new Draft. Each option shows title, status and item count; the selected set shows its status, item count and content hash, with a link to its detail route. Only a Draft set accepts new items — selecting a Validated, Applied or Cancelled set locks the entry fields on the register below.",
    },
    {
      id: "sec-register",
      title: "Effective assumption register",
      targetId: "assumptions-register",
      explanation:
        "The register lists effective assumptions with code, scenario, effective value, unit and impact scope. Effective values resolve from the same scenario assumption store the calculation runtime reads, so what is shown here is what the model will use. This is the controlled input layer: if a figure is not listed here, it is a calculated output and must be changed at its driver, not at the result.",
    },
    {
      id: "sec-filters",
      title: "Search, scenario and impact filters",
      targetId: "assumptions-filters",
      explanation:
        "Search matches assumption code or label. The scenario filter narrows to a single scenario or shows all. The impact filter narrows to assumptions that move Revenue, P&L or Cash, or whose impact is unknown. The counter shows how many of the total are displayed. Filter by scenario before proposing anything — the register shows all scenarios by default, which is how values get mixed by accident.",
    },
    {
      id: "sec-entry",
      title: "Current value and proposed value entry",
      targetId: "assumptions-proposed-entry",
      explanation:
        "Each row shows the current effective value and, when a Draft change set is selected and you hold the create permission, a proposed-value field, an optional rationale field and an Add action that stages the item. The proposed value must be numeric and must differ from the current effective value. Staging an item does not change the model — it only records the proposal inside the change set.",
    },
    {
      id: "sec-permissions",
      title: "Validation and application permissions",
      targetId: "assumptions-permissions",
      explanation:
        "The footer states whether you hold the validate and apply permissions, and repeats that historical model runs are never mutated by an apply. Create, validate, apply and cancel are separate permissions deliberately, so proposing, checking and committing a change can sit with different people. Holding apply is not the same as holding governance authority for a material change.",
    },
    {
      id: "sec-detail",
      title: "Change-set detail header",
      targetId: "change-set-detail",
      explanation:
        "On the detail route the header shows the change set's title and description — the rationale of record for the proposal as a whole. If no description was entered the page says so explicitly. Read this before the item table: it states why the group of changes was proposed, which the individual item rationales rarely repeat.",
    },
    {
      id: "sec-status",
      title: "Change-set status",
      targetId: "change-set-status",
      explanation:
        "A single status badge shows draft, validated, applied or cancelled, alongside the item count and the content hash. This is the authoritative lifecycle state. Draft means proposed and editable; validated means internally checked and ready to apply; applied means the values are in the Draft model version; cancelled means permanently closed. There is no separate approved status here — approval is a governance control outside the page.",
    },
    {
      id: "sec-audit",
      title: "Audit timestamps",
      targetId: "change-set-audit",
      explanation:
        "Created and updated timestamps always show; validated, applied and cancelled timestamps appear once those transitions occur. Together with the content hash this is the page's audit trail. It answers when a proposal was made, when it was checked and when it took effect — which is what reconciles a model output back to the decision that produced it.",
    },
    {
      id: "sec-validation",
      title: "Validation result",
      targetId: "change-set-validation",
      explanation:
        "For a Draft set with failing items an alert reports the error count and blocks validation until the flagged items are fixed. Each item also carries its own validation state — unvalidated, valid, warning or error. Validation is a consistency check on the proposal itself. It confirms the change is internally coherent; it says nothing about whether the change is commercially right or authorised.",
    },
    {
      id: "sec-impact",
      title: "Impact summary",
      targetId: "change-set-impact",
      explanation:
        "Once validated, an alert states how many assumptions will be updated and lists the downstream scopes affected, or shows unknown where the scope cannot be classified. It repeats that historical runs are not mutated. Read the scope list as the minimum re-run list: every scope named here must be re-executed before its page can be quoted, and unknown means the impact must be assessed manually.",
    },
    {
      id: "sec-actions",
      title: "Apply, validate and cancel actions",
      targetId: "change-set-actions",
      explanation:
        "The available action follows the status. A Draft set offers Validate. A Validated set offers Apply, behind a confirmation naming the item count, the model version and the impacted scopes. Draft and Validated sets both offer Cancel, which is permanent. Applied and Cancelled sets offer nothing — they are terminal. If assumptions moved since validation the apply reports a conflict and the set must be revalidated.",
    },
    {
      id: "sec-items",
      title: "Proposed versus current items",
      targetId: "change-set-current-proposed",
      explanation:
        "The item table is the substance of the proposal: assumption code, scenario, from value, to value, delta, unit, impact scope, validation state and rationale, with an ok / warn / error tally in the heading. Draft items can be removed; items in Validated, Applied or Cancelled sets are immutable. Read from and to together — a delta without its base rarely conveys materiality.",
    },
  ],
  inputs: [
    { id: "in-account-scope", label: "Account scope", description: "Which accounts are in commercial scope. Owner: Deal Lead. Drives every volume-derived figure downstream.", owner: "Deal Lead", source: "Portfolio / registered account source", required: true },
    { id: "in-activation", label: "Activation", description: "The share of in-scope accounts that become active. Owner: Commercial Lead. Highest-leverage driver on the page.", owner: "Commercial Lead", source: "Commercial plan", required: true },
    { id: "in-renewal", label: "Renewal influence", description: "Assumed influence over renewal outcomes. Owner: Commercial Lead. Feeds retained revenue.", owner: "Commercial Lead", source: "Account evidence" },
    { id: "in-pricing", label: "Pricing", description: "Price points and uplift assumptions. Owner: Commercial Lead with Finance. Requires commercial authority to change.", owner: "Commercial Lead", source: "Commercial terms", required: true },
    { id: "in-rebate", label: "Rebate", description: "Rebate rates and thresholds. Owner: Commercial Lead. Contractually sensitive — never changed unilaterally.", owner: "Commercial Lead", source: "Commercial terms" },
    { id: "in-growth-share", label: "Growth share", description: "Assumed share of account growth attributable to the program. Owner: Revenue Owner.", owner: "Revenue Owner", source: "Commercial plan" },
    { id: "in-services-attach", label: "Services attach", description: "Attach rate of services to activated accounts. Owner: Revenue Owner. Drives services revenue and delivery demand.", owner: "Revenue Owner", source: "Commercial plan" },
    { id: "in-professional-services", label: "Professional services", description: "Professional services volumes and rates. Owner: Delivery Lead with Finance.", owner: "Delivery Lead", source: "Delivery plan" },
    { id: "in-managed-services", label: "Managed services", description: "Managed services scope and run-rate assumptions. Owner: Operations Lead.", owner: "Operations Lead", source: "Delivery plan" },
    { id: "in-support-scope", label: "Support scope", description: "Support coverage assumed within the commercial envelope. Owner: Operations Lead.", owner: "Operations Lead", source: "Delivery plan" },
    { id: "in-staffing", label: "Staffing", description: "FTE counts and ramp by function. Owner: Staffing Lead. Changing activation without revisiting this is the most common error.", owner: "Staffing Lead", source: "Staffing plan", required: true },
    { id: "in-loaded-cost", label: "Loaded cost", description: "Fully loaded cost per role. Owner: Finance. Drives P&L and EBITDA directly.", owner: "Finance", source: "Finance rate card", required: true },
    { id: "in-funding", label: "Funding", description: "Funding contributions and offsets assumed in the deal. Owner: Finance with Deal Lead.", owner: "Finance", source: "Commercial terms" },
    { id: "in-payment-lag", label: "Payment lag", description: "Days between invoicing and receipt. Owner: Finance. Moves Cash without moving P&L.", owner: "Finance", source: "Commercial terms" },
    { id: "in-timeline", label: "Timeline", description: "Start dates, ramp periods and phase boundaries. Owner: Program Director.", owner: "Program Director", source: "Timelines" },
    { id: "in-growth", label: "Growth", description: "Period-on-period growth rates applied to volumes or values. Owner: Revenue Owner.", owner: "Revenue Owner", source: "Commercial plan" },
    { id: "in-risk", label: "Risk", description: "Risk loadings and contingency assumptions. Owner: Program Director with Finance.", owner: "Program Director", source: "Governance record" },
    { id: "in-collections", label: "Collections", description: "Collection performance assumptions. Owner: Finance. Affects working capital and cash sustainability.", owner: "Finance", source: "Finance record" },
    { id: "in-utilization", label: "Utilization", description: "Assumed productive utilisation of staffed capacity. Owner: Delivery Lead.", owner: "Delivery Lead", source: "Delivery plan" },
    { id: "in-exclusions", label: "Commercial exclusions", description: "What is explicitly outside the commercial envelope. Owner: Deal Lead with Legal. Silence here is read as inclusion.", owner: "Deal Lead", source: "Commercial terms" },
  ],
  outputs: [
    { id: "out-register", label: "Controlled assumption register", description: "The effective value, unit, scenario and impact scope of every assumption the runtime consumes.", consumedBy: ["Revenue", "P&L (Cost & EBITDA)", "Cash & Sustainability", "Scenarios", "Sensitivity Analysis"] },
    { id: "out-changeset", label: "Proposed change set", description: "A titled, described group of scenario-specific proposals with per-item current and proposed values and rationale.", consumedBy: ["Governance", "Release & Activation"] },
    { id: "out-impact", label: "Impact analysis", description: "The impact scopes classified per assumption and summarised per change set before apply.", consumedBy: ["Revenue", "P&L (Cost & EBITDA)", "Cash & Sustainability", "Governance"] },
    { id: "out-validation", label: "Validation result", description: "Per-item valid, warning or error states with an aggregate tally, gating the transition to Validated.", consumedBy: ["Governance"] },
    { id: "out-approval", label: "Approval requirement", description: "The governance judgement on whether a change is material enough to need executive approval before apply. Held off-page.", consumedBy: ["Governance", "Executive review"] },
    { id: "out-applied", label: "Applied model input", description: "The new effective value inside the Draft model version, used by all future runs.", consumedBy: ["Revenue", "P&L (Cost & EBITDA)", "Cash & Sustainability", "Overview"] },
    { id: "out-history", label: "Change history", description: "Status, content hash and created, updated, validated, applied and cancelled timestamps retained per change set.", consumedBy: ["Governance", "Audit"] },
    { id: "out-notification", label: "Downstream notification", description: "The stale-run signal telling owners which scopes must be re-executed after an apply.", consumedBy: ["Revenue", "P&L (Cost & EBITDA)", "Cash & Sustainability", "Scenario Comparison"] },
  ],
  businessRules: [
    { id: "rule-outputs", rule: "Calculated outputs must not be edited as assumptions.", explanation: "Only values in the register are inputs. A revenue, margin, EBITDA or cash figure is produced by the model and must be changed at its driver. Overwriting a result breaks the link between inputs and outputs and makes the whole model unreproducible." },
    { id: "rule-owner", rule: "Every material assumption must have an owner.", explanation: "A named person accountable for the value and its evidence. The page does not display an owner field, so ownership is held in governance records — an unowned material assumption should not survive review." },
    { id: "rule-rationale", rule: "Every proposed change needs a rationale.", explanation: "The change set carries a description and each item carries an optional rationale field. Use both: the description explains why the group exists, the item rationale explains why that value moved. A change with no stated reason cannot be defended later." },
    { id: "rule-material-impact", rule: "Material changes require impact analysis.", explanation: "Read the impact scopes on the assumption and the summary on the validated change set, then check the affected pages before applying. Impact scope shown as unknown means the analysis must be done manually rather than skipped." },
    { id: "rule-scenario-specific", rule: "Changes must remain scenario-specific where applicable.", explanation: "Every change-set item is bound to one scenario. A value proposed for Upside applies only to Upside. Apply the same logic deliberately to each scenario rather than assuming a change propagates." },
    { id: "rule-no-mixing", rule: "Values from different scenarios must not be mixed.", explanation: "The register shows all scenarios by default. Filter to a single scenario before comparing or proposing, otherwise a Downside value can be read as the Base position and carried into an executive statement." },
    { id: "rule-not-active", rule: "A change should not be represented as active before it is applied.", explanation: "Draft and Validated change sets are proposals. Only an Applied set has changed the model, and even then the outputs do not move until the affected scopes are re-executed. Quoting a proposal as a model position is a governance failure." },
    { id: "rule-traceable", rule: "Applied change history should remain traceable.", explanation: "Status, content hash and lifecycle timestamps are retained, and items in Validated, Applied and Cancelled sets are immutable. That record is how a past decision is reconstructed — it must never be worked around by editing values outside a change set." },
    { id: "rule-evidence", rule: "Source evidence and confidence should be retained.", explanation: "Every material value should cite a source code from Sources and carry a stated confidence. Neither is displayed on this page today, so both are held in the governance record and must be produced on request." },
    { id: "rule-approval", rule: "Approval requirements should reflect materiality and existing governance.", explanation: "The page enforces separate create, validate, apply and cancel permissions. It does not enforce executive approval — that threshold is set by governance, and holding the apply permission does not itself constitute approval of a material change." },
    { id: "rule-downstream", rule: "A change affecting account scope, commercial terms, staffing or risk must identify downstream pages.", explanation: "These drivers move several surfaces at once. Name the affected pages — Revenue, P&L, Cash, Staffing & Resources, Timelines, Scenario Comparison, Overview — in the rationale so reviewers know what to re-check after the apply." },
    { id: "rule-cancel", rule: "Cancellation should preserve history rather than silently erase the proposal.", explanation: "Cancelling is permanent and the cancelled set stays visible with its items, its rationale and a cancellation timestamp. A rejected proposal is evidence that an option was considered and declined — deleting that record loses the reasoning." },
    { id: "rule-real-lifecycle", rule: "Only the real change-set lifecycle may be relied upon.", explanation: "The implemented statuses are draft, validated, applied and cancelled, with item states unvalidated, valid, warning and error. There is no submitted, rejected, approved or reverted status in the product. Do not describe or report states that the page cannot show." },
  ],
  calculationLogic: [
    "The register reads effective assumptions from the scenario assumption store — the same source the calculation runtime consumes — so displayed values equal the values a run will use.",
    "Impact scope per assumption is classified from the assumption code into revenue, pnl, cash or unknown, and the badges on each row reflect that classification.",
    "A staged item records the current effective value as the previous value and the entered number as the proposed value; the detail table derives the delta from the two.",
    "A proposed value must be numeric and must differ from the current effective value, otherwise the item is rejected at entry.",
    "Validation evaluates items into valid, warning or error states and aggregates them; outstanding errors prevent the set from becoming Validated.",
    "Apply writes proposed values into the Draft model version and is refused as a conflict if the underlying assumptions moved since validation.",
    "Applying affects future runs only — completed Revenue, P&L and Cash runs are immutable and are never recalculated retrospectively.",
    "Run staleness is derived by comparing assumption change times against the last completed run per scope, which drives the stale-run alert.",
    "This page performs no financial calculation of its own; all monetary effects are produced by re-executing the model on the Revenue, P&L and Cash pages.",
  ],
  relationship: {
    receivesFrom: [
      "Program",
      "Portfolio",
      "Sources",
      "Commercial terms",
      "Staffing plans",
      "Timeline plans",
      "Governance decisions",
    ],
    models: [
      "Assumption values",
      "Scenario drivers",
      "Change proposals",
      "Validation",
      "Impact",
      "Approval routing",
      "Application to the model",
    ],
    feeds: [
      "Scenarios",
      "Sensitivity Analysis",
      "Revenue",
      "P&L (Cost & EBITDA)",
      "Cash & Sustainability",
      "Release & Activation",
      "Staffing & Resources",
      "Overview",
      "Governance",
    ],
  },
  downstreamImpacts: [
    { area: "Revenue", effect: "Volume, pricing, attach and growth assumptions change modelled revenue as soon as the revenue scope is re-run." },
    { area: "Costs", effect: "Staffing, loaded cost and utilisation assumptions change modelled cost once the P&L scope is re-run." },
    { area: "EBITDA", effect: "Any revenue or cost movement changes margin and EBITDA, often more than proportionally." },
    { area: "Cash", effect: "Payment lag, collections and funding assumptions move cash and working capital independently of P&L." },
    { area: "Staffing", effect: "Activation and volume changes alter delivery, RunOps and customer-success demand in the staffing plan." },
    { area: "Capacity", effect: "Utilisation and ramp assumptions change whether the plan is deliverable with the staffed capacity." },
    { area: "Timeline", effect: "Ramp and phase assumptions shift when revenue and cost land across periods." },
    { area: "Activation", effect: "Activation is the highest-leverage driver: it propagates to volume, revenue, staffing, cost and cash simultaneously." },
    { area: "Risk", effect: "Risk and contingency assumptions change the defensibility of the committed position." },
    { area: "Governance", effect: "Material applied changes reset what has been reviewed and may invalidate a prior executive endorsement." },
  ],
  dataQuality: {
    dataSources: [
      "Effective scenario assumptions consumed by the calculation runtime",
      "Change sets and change-set items for the program",
      "Draft model version status and version code",
      "Run staleness derived from completed model runs per scope",
      "Commercial permission grants for create, validate, apply and cancel",
    ],
    updateFrequency:
      "The register reflects the current effective values continuously. Change-set state updates on each create, stage, validate, apply or cancel action. Downstream outputs update only when the affected scopes are re-executed.",
    knownGaps: [
      "No owner field is displayed against an assumption — ownership is held off-page in governance records.",
      "No source or evidence link is shown per assumption, so provenance must be traced manually through Sources.",
      "No confidence rating is displayed for any assumption value.",
      "No approval status exists in the change-set lifecycle — approval is governance practice, enforced only through the separate apply permission.",
      "No history timeline or per-item audit log is rendered; history is limited to status, content hash and lifecycle timestamps.",
      "Assumption category grouping is not shown; categories such as activation, rebate or staffing must be inferred from the assumption code.",
      "Impact classification can return unknown, in which case downstream effect must be assessed manually.",
      "Text-valued assumptions can be displayed but only numeric proposed values can be staged.",
      "There is no reversal action — an applied change is undone only by proposing a further change set.",
      "No materiality threshold is calculated, so what counts as a material change is a governance judgement.",
    ],
    changeControl:
      "All value changes flow through a change set: create a Draft, stage items with rationale, validate, then apply. Create, validate, apply and cancel are separate permissions. Applied and cancelled sets are immutable, and applying never mutates completed model runs.",
    lineage:
      "Displayed output → model run → effective assumption in the register → applied change set item (previous and proposed value, rationale, timestamps) → source evidence recorded in Sources.",
  },
  modelConfidence: "Medium",
  confidenceBasis: ["Commercial terms", "Staffing assumptions", "Revenue assumptions", "Cost assumptions", "Governance approvals", "Source completeness"],
  confidenceGuidance:
    "Confidence in the register is procedural rather than evidential: the lifecycle, permissions, immutability and staleness signals are strong, but the page shows no owner, source or confidence per assumption. Treat a value as decision-grade only when its owner and source evidence can be produced from governance records, and downgrade any statement resting on an assumption with unknown impact scope.",
  commercialReadiness: "Review Required",
  readinessCriteria: [
    "Every material assumption in scope has a named owner recorded in governance.",
    "Each proposed change cites the source evidence supporting the new value.",
    "Each change set has a description and each item a rationale.",
    "Impact scopes are known — no material item left classified as unknown.",
    "Validation shows zero errors before apply.",
    "Executive approval is obtained where materiality requires it, before apply.",
    "Affected scopes are re-executed and no stale-run alert remains.",
    "Scenario boundaries are intact: no value carried between Base, Downside and Upside.",
  ],

  /* ---------------- How to use it ---------------- */
  workflow: [
    { id: "wf-1", step: 1, title: "Confirm baseline and scenario", description: "Check the Draft model version badge and filter the register to the scenario you intend to change.", role: "Model Administrator" },
    { id: "wf-2", step: 2, title: "Identify the assumption", description: "Search by code or label and confirm the current effective value and unit before proposing anything.", role: "Assumption Owner" },
    { id: "wf-3", step: 3, title: "Confirm owner and source", description: "Establish who owns the value and which registered source supports the new one. Both are held off-page.", role: "Commercial Lead" },
    { id: "wf-4", step: 4, title: "Create or select a Draft change set", description: "Group related changes under one titled Draft set. Only Draft sets accept new items.", role: "Assumption Owner" },
    { id: "wf-5", step: 5, title: "Enter the proposed value", description: "Type the numeric proposed value on the row and add the item to the change set.", role: "Assumption Owner" },
    { id: "wf-6", step: 6, title: "Record rationale", description: "Fill the item rationale and the change-set description so the reason survives the proposal.", role: "Assumption Owner" },
    { id: "wf-7", step: 7, title: "Review direct and downstream impact", description: "Read the impact scopes and identify every affected page before going further.", role: "Finance" },
    { id: "wf-8", step: 8, title: "Validate internal consistency", description: "Run Validate on the detail route and clear every error; treat warnings as questions to answer.", role: "Finance" },
    { id: "wf-9", step: 9, title: "Route for review", description: "Share the change set with the Commercial Lead and the relevant functional lead for feasibility.", role: "Commercial Lead" },
    { id: "wf-10", step: 10, title: "Obtain approval", description: "Where materiality requires it, secure executive approval before apply. The page will not ask for it.", role: "Executive Approver" },
    { id: "wf-11", step: 11, title: "Apply the change set", description: "Use the Apply action, confirming the item count, model version and impacted scopes in the dialog.", role: "Model Administrator" },
    { id: "wf-12", step: 12, title: "Re-run the affected scopes", description: "Execute new runs on Revenue, P&L and Cash until no stale-run alert remains.", role: "Finance" },
    { id: "wf-13", step: 13, title: "Review the outputs", description: "Check Revenue, P&L, Cash, Scenario Comparison and Overview for the effect and any surprise.", role: "Commercial Lead" },
    { id: "wf-14", step: 14, title: "Preserve evidence and history", description: "Record the source, owner and approval against the change set in the governance record.", role: "Governance" },
  ],
  actionsAvailable: [
    "Filter the register by scenario, impact scope or search text",
    "Create a new Draft change set with a title and description",
    "Select an active change set",
    "Stage a proposed numeric value with an optional rationale",
    "Open the change-set detail route",
    "Remove an item from a Draft change set",
    "Validate a Draft change set",
    "Apply a Validated change set",
    "Cancel a Draft or Validated change set",
    "Read run staleness and impacted scopes",
  ],
  teamActivities: [
    { id: "ta-owner", activity: "Proposes the value and supplies its evidence", role: "Assumption Owner", cadence: "As required" },
    { id: "ta-finance", activity: "Validates the modelling effect and the arithmetic consequence", role: "Finance or Model Owner", cadence: "Per change set" },
    { id: "ta-commercial", activity: "Validates the commercial meaning and deal consistency", role: "Commercial Lead", cadence: "Per change set" },
    { id: "ta-functional", activity: "Validates operational feasibility of the implied delivery or staffing", role: "Relevant functional lead", cadence: "Per material change" },
    { id: "ta-governance", activity: "Confirms the approval path and materiality threshold", role: "Governance", cadence: "Per material change" },
    { id: "ta-exec", activity: "Approves material changes before they are applied", role: "Executive Approver", cadence: "By materiality" },
    { id: "ta-admin", activity: "Ensures controlled application, conflict handling and traceability", role: "Administrator", cadence: "Per apply" },
    { id: "ta-rerun", activity: "Re-executes affected scopes and clears stale-run alerts", role: "Finance", cadence: "After each apply" },
    { id: "ta-review", activity: "Reviews the applied register against outputs for reconciliation", role: "Commercial Lead", cadence: "Weekly" },
  ],
  roles: [
    { role: "Assumption Owner", responsibility: "Owns the value, its evidence and its rationale; proposes changes through a change set." },
    { role: "Commercial Lead", responsibility: "Owns commercial meaning; confirms a change is consistent with the deal being pursued." },
    { role: "Finance / Model Owner", responsibility: "Owns modelling integrity; validates effect, clears errors and re-runs affected scopes." },
    { role: "Deal Lead", responsibility: "Owns account scope and commercial terms feeding the register." },
    { role: "Model Administrator", responsibility: "Owns the Draft model version, controlled application and traceability." },
    { role: "Program Director", responsibility: "Owns timeline and risk assumptions and their delivery consequences." },
    { role: "Staffing Lead", responsibility: "Owns staffing and utilisation assumptions and confirms feasibility." },
    { role: "Revenue Owner", responsibility: "Owns growth, attach and revenue-side drivers." },
    { role: "Cost Owner", responsibility: "Owns loaded cost and cost-side drivers." },
    { role: "Governance reviewers", responsibility: "Confirm the approval path, materiality and evidence completeness." },
    { role: "Executive Approver", responsibility: "Approves material changes before application and owns the resulting position." },
  ],
  raci: [
    { activity: "Propose an assumption change", assignments: [{ role: "Assumption Owner", raci: "R" }, { role: "Commercial Lead", raci: "A" }, { role: "Finance", raci: "C" }, { role: "Governance", raci: "I" }] },
    { activity: "Record rationale and evidence", assignments: [{ role: "Assumption Owner", raci: "R" }, { role: "Commercial Lead", raci: "A" }, { role: "Governance", raci: "C" }] },
    { activity: "Assess downstream impact", assignments: [{ role: "Finance", raci: "R" }, { role: "Commercial Lead", raci: "A" }, { role: "Staffing Lead", raci: "C" }, { role: "Program Director", raci: "C" }] },
    { activity: "Validate the change set", assignments: [{ role: "Finance", raci: "R" }, { role: "Model Administrator", raci: "A" }, { role: "Commercial Lead", raci: "C" }] },
    { activity: "Confirm operational feasibility", assignments: [{ role: "Staffing Lead", raci: "R" }, { role: "Program Director", raci: "A" }, { role: "Finance", raci: "C" }] },
    { activity: "Approve a material change", assignments: [{ role: "Executive Approver", raci: "A" }, { role: "Governance", raci: "R" }, { role: "Commercial Lead", raci: "C" }, { role: "Finance", raci: "I" }] },
    { activity: "Apply the change set", assignments: [{ role: "Model Administrator", raci: "R" }, { role: "Finance", raci: "A" }, { role: "Governance", raci: "I" }] },
    { activity: "Re-run affected scopes and reconcile", assignments: [{ role: "Finance", raci: "R" }, { role: "Model Administrator", raci: "A" }, { role: "Commercial Lead", raci: "I" }] },
    { activity: "Cancel a proposal", assignments: [{ role: "Assumption Owner", raci: "R" }, { role: "Commercial Lead", raci: "A" }, { role: "Governance", raci: "I" }] },
  ],
  reviewRequirements: [
    "Every change set carries a description before validation.",
    "Every item has a rationale where the change is material.",
    "Impact scopes are read and the affected pages named.",
    "Validation completes with zero errors and warnings explained.",
    "Functional feasibility confirmed for staffing, delivery and timeline effects.",
    "Scenario integrity checked — the change is bound to the intended scenario only.",
  ],
  approvalRequirements: [
    "Create, validate, apply and cancel are separate permissions and should not all rest with one person for material changes.",
    "Validation is not approval; a validated set may still be commercially wrong.",
    "Material changes to account scope, pricing, rebate, funding or risk require executive approval before apply, per governance.",
    "Approval is not recorded on the page — it must be captured in the governance record and referenced by change-set title.",
    "Apply must not proceed while an unresolved conflict or outstanding error exists.",
  ],
  decisions: [
    { id: "dec-propose", decision: "Whether a value should change at all", decidedBy: "Assumption Owner with Commercial Lead", evidence: "Current effective value, new source evidence, rationale" },
    { id: "dec-material", decision: "Whether the change is material", decidedBy: "Governance", evidence: "Impact scopes, delta size relative to base, affected pages" },
    { id: "dec-validate", decision: "Whether the proposal is internally consistent", decidedBy: "Finance or Model Owner", evidence: "Item validation states and error tally" },
    { id: "dec-feasible", decision: "Whether the implied delivery or staffing is feasible", decidedBy: "Relevant functional lead", evidence: "Staffing plan, utilisation, ramp" },
    { id: "dec-approve", decision: "Whether to approve a material change", decidedBy: "Executive Approver", evidence: "Impact analysis, rationale, evidence pack" },
    { id: "dec-apply", decision: "Whether to apply now or hold", decidedBy: "Model Administrator with Finance", evidence: "Validated status, impacted scopes, run schedule" },
    { id: "dec-cancel", decision: "Whether to cancel a proposal", decidedBy: "Commercial Lead", evidence: "Review outcome, superseded rationale" },
  ],
  whatToDoNext: [
    "Filter the register to your scenario and confirm the current effective value.",
    "Create a Draft change set before entering any proposed value.",
    "Open the detail route to see current versus proposed and the validation tally.",
    "Clear validation errors, then route for commercial and functional review.",
    "Secure approval where materiality requires it, then apply.",
    "Re-run Revenue, P&L and Cash until no stale-run alert remains.",
    "Compare scenarios on Scenario Comparison and re-read Overview before reissuing any executive material.",
  ],
  relatedPages: [
    { pageId: "commercial-sources", label: "Sources", route: "/commercial/sources", relationship: "Prerequisite" },
    { pageId: "commercial-scenarios", label: "Scenarios", route: "/commercial/scenarios", relationship: "Prerequisite" },
    { pageId: "commercial-program", label: "Program", route: "/commercial/program", relationship: "Upstream" },
    { pageId: "commercial-portfolio", label: "Portfolio", route: "/commercial/portfolio", relationship: "Upstream" },
    { pageId: "commercial-revenue", label: "Revenue", route: "/commercial/model/revenue", relationship: "Downstream" },
    { pageId: "commercial-pnl", label: "P&L (Cost & EBITDA)", route: "/commercial/model/pnl", relationship: "Downstream" },
    { pageId: "commercial-cash", label: "Cash & Sustainability", route: "/commercial/model/cash", relationship: "Downstream" },
    { pageId: "commercial-compare", label: "Scenario Comparison", route: "/commercial/model/compare", relationship: "Downstream" },
    { pageId: "commercial-sensitivity", label: "Sensitivity Analysis", route: "/commercial/model/sensitivity", relationship: "Downstream" },
    { pageId: "commercial-release", label: "Release & Activation", route: "/commercial/model/release", relationship: "Downstream" },
    { pageId: "commercial-staffing-resources", label: "Staffing & Resources", route: "/commercial/staffing-resources", relationship: "Companion" },
    { pageId: "commercial-governance", label: "Governance", route: "/commercial/neurealm-governance", relationship: "Companion" },
    { pageId: "commercial-overview", label: "Overview", route: "/commercial", relationship: "Downstream" },
  ],

  /* ---------------- Interpretation & training ---------------- */
  interpretation: [
    {
      band: "healthy",
      label: "Controlled and reconciled",
      criteria: [
        "Assumptions have named owners and cited evidence.",
        "Confidence in each material value is explicit.",
        "Change sets show current and proposed values with rationale.",
        "Impact scopes are known and the affected pages identified.",
        "Approval is complete before apply where materiality requires it.",
        "No stale-run alert: applied values reconcile to model outputs.",
      ],
      action: "Proceed. Quote the model with its stated confidence and keep the evidence pack attached to the change set.",
    },
    {
      band: "warning",
      label: "Proceed with qualification",
      criteria: [
        "Evidence behind a proposed value is incomplete.",
        "Confidence in a material assumption is low.",
        "Downstream impact has not been assessed or is classified unknown.",
        "The change rationale is thin or missing.",
        "Functional feasibility of the implied staffing or delivery is unconfirmed.",
        "A change set is validated but not approved.",
      ],
      action: "Hold the apply. Assign owners to the gaps with dates, complete the impact read, and label any dependent output as provisional.",
    },
    {
      band: "critical",
      label: "Not decision-grade",
      criteria: [
        "A calculated output has been overwritten instead of its driver.",
        "A change was applied without the approval its materiality required.",
        "Values from different scenarios have been mixed.",
        "Historical values or rationale have been lost.",
        "A binding decision rests on an unvalidated assumption.",
        "A material applied change is not reflected downstream — stale runs remain.",
      ],
      action: "Stop external use of the affected numbers. Reconstruct the change history, re-run every affected scope, and refer the breach to governance before any further commitment.",
    },
  ],
  commonMistakes: [
    { id: "mis-output", description: "Trying to change a revenue, margin or cash figure directly because the result looks wrong.", correction: "Results are not editable. Find the driver in the register and propose a change to it through a change set." },
    { id: "mis-activation-staffing", description: "Raising activation without revisiting staffing, so more accounts are modelled as active than the plan can serve.", correction: "Pair every activation change with a staffing and utilisation review before validating the change set." },
    { id: "mis-staffing-cost", description: "Changing staffing without checking the cost and cash consequence, then presenting an unchanged margin.", correction: "Re-run P&L and Cash after any staffing change and read the EBITDA and working-capital effect before quoting." },
    { id: "mis-rebate", description: "Adjusting rebate or pricing without confirming who holds commercial authority for the term.", correction: "Route pricing and rebate changes through the Commercial Lead and Deal Lead before staging them." },
    { id: "mis-scenario", description: "Entering an upside value while the register is unfiltered, so it lands in the Base scenario.", correction: "Filter to a single scenario first and confirm the scenario column on the item before validating." },
    { id: "mis-rationale", description: "Staging items with no rationale because the reason feels obvious at the time.", correction: "Write the rationale at entry. Six weeks later the reason is unrecoverable and the change looks arbitrary." },
    { id: "mis-validation-approval", description: "Treating a Validated status as sign-off and applying immediately.", correction: "Validation is an internal consistency check only. Obtain the governance approval that materiality requires before apply." },
    { id: "mis-applied-approved", description: "Assuming an Applied change was executive-approved because the system permitted it.", correction: "Apply is a permission, not an endorsement. Check the governance record for the approval." },
    { id: "mis-stale", description: "Quoting Revenue, P&L or Cash while a stale-run alert is showing.", correction: "Re-execute the named scopes first; until then the outputs predate the applied change." },
    { id: "mis-cancel", description: "Cancelling a change set to make an unwanted proposal disappear from view.", correction: "Cancellation is permanent and preserved on purpose. Record why it was declined — the record is the point." },
  ],
  bestPractices: [
    "Group related changes into one change set so their combined impact can be judged together.",
    "Write the change-set description as the decision memo: what, why, and what it should move.",
    "Filter the register by scenario before every editing session.",
    "Read the impact badges before entering a value, not after validating.",
    "Keep create, validate and apply with different people for material changes.",
    "Record owner, source and approval against the change-set title in the governance record.",
    "Re-run every named scope immediately after an apply and confirm the alert clears.",
    "Re-read Scenario Comparison after any driver change — relative scenario positions can invert.",
    "Never edit values outside a change set, even where permissions would allow it.",
  ],
  workedExamples: [
    {
      id: "we-activation",
      title: "Illustrative: raising activation from 35 percent to 50 percent",
      narrative:
        "Illustrative example — these values are used to show the mechanics and are not a stated position of the model. A Commercial Lead believes activation across in-scope accounts should move from 35 percent to 50 percent in the Base scenario following stronger early adoption signals. Because activation is a driver rather than a result, the change belongs in the register, staged through a change set. The temptation is to make the change and quote the improved revenue in the next review. That would be wrong on two counts: the revenue figure does not exist until the affected scopes are re-run, and the higher activation implies delivery, RunOps and customer-success demand that nobody has yet confirmed is feasible. The proposal is therefore staged with a rationale, validated, reviewed by Finance for modelling effect and by the Staffing Lead for feasibility, and put to governance for approval on materiality — before anything is applied.",
      steps: [
        "Filter the register to the Base scenario and confirm the current effective activation value.",
        "Create a Draft change set titled for the adoption evidence and describe the reasoning.",
        "Stage the proposed value with a rationale citing the source evidence.",
        "Read the impact badges — activation propagates to revenue, P&L and cash.",
        "Validate the change set and clear any errors.",
        "Have the Staffing Lead confirm whether the implied delivery and customer-success demand is deliverable.",
        "Have Finance state the expected cost and cash consequence, including funding and payment lag effects.",
        "Route to governance; obtain executive approval because the change is material.",
        "Apply the change set only after approval, confirming the impacted scopes in the dialog.",
        "Re-run Revenue, P&L and Cash until the stale-run alert clears, then re-read Scenario Comparison and Overview.",
      ],
      result:
        "More accounts model as active, revenue may rise, and delivery, RunOps and customer-success demand, cost and cash requirements may rise with it; timeline and risk may also shift. None of that is real until the scenarios are rerun, and the change should not be applied until those impacts have been reviewed and approved.",
    },
  ],
  faqs: [
    { id: "faq-what-assumption", question: "What is an assumption?", answer: "A controlled input the model consumes — an activation rate, a price, a loaded cost, a payment lag. It is chosen rather than calculated, belongs to a named owner, should cite source evidence, and is bound to a scenario. If a value appears in the register, it is an input. If it appears only on Revenue, P&L or Cash, it is a result." },
    { id: "faq-what-changeset", question: "What is a change set?", answer: "A titled, described group of proposed assumption changes handled as one unit. It moves through draft, validated and applied, or is cancelled. Each item records the assumption code, scenario, previous value, proposed value, impact scope and rationale, so the whole proposal can be reviewed, applied or declined together." },
    { id: "faq-validate-vs-approve", question: "What is the difference between validation and approval?", answer: "Validation is a system check that the proposal is internally consistent — it clears errors and flags warnings. Approval is a human governance decision that the change is commercially right and authorised. The page enforces validation; it does not enforce approval. A validated change set can still be wrong and must not be applied on validation alone." },
    { id: "faq-edit-output", question: "Can I edit an output here?", answer: "No, and that is deliberate. Only assumptions in the register can be changed. Revenue, margin, EBITDA and cash figures are produced by the model from those inputs. If a result looks wrong, the driver behind it is wrong — change the driver and re-run, never the result." },
    { id: "faq-exec-approval", question: "Which changes require executive approval?", answer: "Governance sets the threshold, not the page. In practice, changes to account scope, pricing, rebate, funding, risk or anything that moves the committed position materially require executive approval before apply. The system will let a permission holder apply without it, so the discipline sits with the team." },
    { id: "faq-scenario", question: "How do scenario-specific assumptions work?", answer: "Every change-set item is bound to one scenario, and the register shows the scenario per row. A value changed for Base does not affect Downside or Upside. To move all three you stage three items deliberately. Because the register shows all scenarios by default, always filter before proposing." },
    { id: "faq-after-apply", question: "What happens after a change is applied?", answer: "The proposed values are written into the Draft model version and used by future runs. Completed Revenue, P&L and Cash runs are immutable and are not recalculated, so the stale-run alert appears for affected scopes. Nothing downstream is true until those scopes are re-executed on their own pages." },
    { id: "faq-reverse", question: "How do I reverse or replace an assumption safely?", answer: "There is no undo. Create a new change set proposing the prior value, state in the rationale that it reverses the earlier set, validate, obtain approval and apply, then re-run the affected scopes. The original applied set stays in history — that is what makes the reversal auditable rather than invisible." },
    { id: "faq-conflict", question: "Why did my apply report a conflict?", answer: "The underlying assumptions moved between validation and apply, so the previous values recorded in the items no longer match reality. Nothing is written. Re-open the change set, revalidate against the current effective values, and confirm the deltas still say what you intended before applying again." },
    { id: "faq-cancel", question: "What does cancelling do?", answer: "It closes the change set permanently. The set, its items and its rationale remain visible with a cancellation timestamp, and nothing is written to the model. Cancel is the correct way to decline a proposal — it preserves the evidence that an option was considered and rejected." },
  ],
  glossary: [
    { term: "Baseline", definition: "The current agreed model position — the Draft model version against which change sets are created and applied." },
    { term: "Assumption", definition: "A controlled input the model consumes, chosen rather than calculated, owned by a named person and bound to a scenario." },
    { term: "Driver", definition: "An assumption that materially moves outputs; changing a driver is the only legitimate way to change a result." },
    { term: "Change Set", definition: "A titled group of proposed assumption changes handled as one unit through draft, validated and applied, or cancelled." },
    { term: "Validation", definition: "The system check that a change set is internally consistent, producing valid, warning or error states per item." },
    { term: "Approval", definition: "The human governance decision that a change is commercially right and authorised. Not a status on this page." },
    { term: "Applied", definition: "The state in which proposed values have been written into the Draft model version and will be used by future runs." },
    { term: "Cancelled", definition: "The terminal state of a declined proposal, retained with its items and rationale so the decision stays traceable." },
    { term: "Materiality", definition: "The governance judgement of how significantly a change moves the commercial position, which sets the approval path." },
    { term: "Downstream Impact", definition: "The pages and outcomes a change affects — revenue, P&L and cash scopes, plus staffing, timeline and risk consequences." },
    { term: "Confidence", definition: "How strongly the evidence supports an assumption's value. Held in governance records; not displayed on this page." },
    { term: "Stale Run", definition: "A completed model run whose inputs changed afterwards, so its outputs no longer reflect the current assumptions." },
    { term: "Effective Value", definition: "The value the calculation runtime will actually use for an assumption in a given scenario." },
    { term: "Content Hash", definition: "The fingerprint of a change set's contents, used to detect whether the proposal changed between validation and apply." },
  ],
  executiveTakeaway:
    "Assumptions & Change Sets is the control point of the Commercial Digital Twin: the register holds the inputs the model actually uses, and every change must pass through a change set — draft, validated, applied, or cancelled. Validation is a consistency check, not approval, and applying changes future runs only, so outputs are not true until the affected scopes are re-run. The page shows no owner, source, confidence or approval field, so those judgements sit with governance and must be produced on request.",
  keyRisks: [
    "A validated change applied without the executive approval its materiality required.",
    "An upside value staged into the Base scenario because the register was unfiltered.",
    "Activation or volume raised without confirming delivery and staffing feasibility.",
    "Outputs quoted while a stale-run alert is outstanding.",
    "Assumptions with no recorded owner, source or confidence because the page does not display those fields.",
    "Impact classified as unknown and therefore never assessed.",
    "An applied change reversed informally instead of through a further change set, losing the audit trail.",
  ],

  /* ---------------- Show on page ---------------- */
  showOnPageTargets: [
    { targetId: "assumptions-summary", label: "Assumption summary header", description: "Governed Assumption Editing, the Draft model version badge and the immutability rule." },
    { targetId: "assumptions-staleness", label: "Stale model run alert", description: "Names the scopes whose completed runs no longer reflect current assumptions." },
    { targetId: "change-sets-list", label: "Change sets panel", description: "Select or create a change set; shows status, item count and content hash." },
    { targetId: "assumptions-register", label: "Effective assumption register", description: "Code, scenario, effective value, unit and impact scope for every controlled input." },
    { targetId: "assumptions-filters", label: "Search, scenario and impact filters", description: "Narrow the register before proposing — always filter by scenario first." },
    { targetId: "assumptions-proposed-entry", label: "Current and proposed value entry", description: "Row-level proposed value, rationale and Add action, enabled only for a Draft set." },
    { targetId: "assumptions-permissions", label: "Validation and application permissions", description: "Whether you hold validate and apply, and the historical-run immutability rule." },
    { targetId: "change-set-detail", label: "Change-set detail header", description: "Title and description — the rationale of record for the whole proposal." },
    { targetId: "change-set-status", label: "Change-set status", description: "Draft, validated, applied or cancelled, with item count and content hash." },
    { targetId: "change-set-audit", label: "Audit timestamps", description: "Created, updated, validated, applied and cancelled times forming the audit trail." },
    { targetId: "change-set-validation", label: "Validation result", description: "Outstanding validation errors that block the transition to Validated." },
    { targetId: "change-set-impact", label: "Impact summary", description: "Item count and downstream scopes affected once the set is validated." },
    { targetId: "change-set-actions", label: "Validate, apply and cancel actions", description: "The controlled transitions available for the current status." },
    { targetId: "change-set-current-proposed", label: "Proposed versus current items", description: "From, to, delta, impact, validation state and rationale per assumption." },
  ],
};
