import type { CommercialGuideContent } from "../../types";

/**
 * Page-specific Commercial Guide content — Portfolio (`/commercial/portfolio`).
 *
 * Authored strictly against what renders in
 * `src/commercial/pages/CommercialPortfolio.tsx`: the directional banner, the
 * "No account records imported" card (aggregate 104-account no-partner
 * statement plus navigation actions to Sources, Program and Overview) and the
 * "Data readiness" card listing eight known/pending readiness rows.
 *
 * Concepts requested but NOT rendered on this page (account table, filters,
 * search, selected-account drawer, ARR summary, segmentation view, partner
 * status view, renewal calendar, ICP fit, risk view, source metadata panel)
 * are described only as context or known gaps — never as if the page showed
 * them. No account-level value is invented here.
 */
export const commercialPortfolioGuide: CommercialGuideContent = {
  pageId: "commercial-portfolio",
  route: "/commercial/portfolio",
  match: "exact",
  pageTitle: "Portfolio",
  guideTitle: "Portfolio — Account Universe and Data Readiness",
  audiences: ["Executive", "Commercial Lead", "Finance", "Delivery", "Sales", "Operations", "Administrator"],
  modes: ["executive", "practitioner", "administrator"],
  estimatedReadingMinutes: 11,
  trainingLevel: "Foundation",
  lastUpdated: "2026-07-29",

  /* ---------------- Overview ---------------- */
  purpose:
    "Portfolio is the account-level commercial foundation of the deal: the surface where the account universe is defined, segmented, validated, prioritised and connected to activation, revenue, services, staffing, renewal readiness, risk and customer outcomes. Today it deliberately holds no account records. It states the aggregate position — a 104-account no-partner portfolio — and reports, row by row, which account-level facts are known and which are still pending validation.",
  represents:
    "The current state of account data for Project Momentous. It represents an aggregate-only portfolio: the account universe and aggregate ARR are known, while account-level ARR, renewal dates, product mix, partner status and opportunity enrichment are pending validation. It represents readiness to import accounts, not a validated account register.",
  whyItMatters:
    "Every revenue, staffing, activation and cash number ultimately resolves to accounts. While the portfolio is aggregate-only, all downstream modelling rests on portfolio-level averages rather than account facts, so no account-level commitment, activation sequence or executive decision can be evidenced from here. The readiness list is the honest gate: it tells reviewers exactly how far the account foundation can currently carry a decision.",
  moduleConnection:
    "Portfolio sits between Program and every account-dependent page. Program sets the scope boundary — partner, segment and gate account scope — and Sources registers the evidence that would allow account records to be imported. Portfolio then feeds Revenue (which accounts may earn), Release & Activation (which may be activated), Staffing & Resources (what must be operated), Assumptions & Change Sets and Scenarios (what may be varied), Timelines, Governance and Overview.",
  questionsAnswered: [
    "Which accounts are in scope, and are they recorded individually or only in aggregate?",
    "Which accounts qualify for the pilot or a later phase?",
    "What is each account's commercial value?",
    "When are renewals expected?",
    "Which accounts carry partner constraints — no-partner or incumbent partner?",
    "Which accounts have sufficient data and customer access to be operated?",
    "Which accounts present the greatest opportunity or risk?",
    "Which accounts should be activated first?",
  ],
  expectedOutcome:
    "A clear, evidenced answer to how far the account foundation can be trusted: what is known at aggregate level, what is pending at account level, what must be sourced before import, and which downstream statements must therefore stay directional.",
  lifecycleStages: [
    "Opportunity Qualification",
    "Commercial Structuring",
    "Financial Modeling",
    "Negotiation",
    "Delivery Planning",
    "Execution",
    "Continuous Improvement",
  ],
  prerequisites: [
    { id: "pre-source", label: "Named account source", route: "/commercial/sources", detail: "A registered, current source for the named account list." },
    { id: "pre-ids", label: "Account identifiers", detail: "A stable unique identifier per account so records cannot be duplicated or merged by name." },
    { id: "pre-partner", label: "Partner status", detail: "No-partner or incumbent-partner classification per account." },
    { id: "pre-arr", label: "ARR or contract-value source", detail: "Authoritative account-level value; aggregate ARR alone cannot support account decisions." },
    { id: "pre-renewal", label: "Renewal dates", detail: "Authoritative renewal timing on a consistent fiscal-period basis." },
    { id: "pre-mix", label: "Product mix", detail: "Products held per account, which drives services and support potential." },
    { id: "pre-usage", label: "Usage or adoption data", detail: "Telemetry or adoption signals indicating account health." },
    { id: "pre-support", label: "Support history", detail: "Historic support volume and complexity per account." },
    { id: "pre-access", label: "Customer access status", detail: "Whether Neurealm may engage the account directly at this phase." },
    { id: "pre-confidence", label: "Source confidence", route: "/commercial/sources", detail: "Confidence rating for each contributing source." },
  ],
  ownership: {
    businessOwner: "Account or Portfolio Lead",
    commercialOwner: "Commercial Lead",
    technicalOwner: "Designated account-data owner",
    executiveApprover: "Deal Lead or Executive Sponsor",
    primaryUsers: ["Account Leads", "Finance", "Customer Success", "Program team", "Commercial Lead", "Delivery Leadership"],
    consumersOfOutput: [
      "Revenue",
      "Release & Activation",
      "Staffing & Resources",
      "Program",
      "Scenarios",
      "Assumptions & Change Sets",
      "Governance",
      "Overview",
    ],
  },

  /* ---------------- How it works ---------------- */
  sections: [
    {
      id: "sec-context",
      title: "Directional model banner",
      targetId: "portfolio-context",
      explanation:
        "The banner states that this is a directional model pending account-level validation and contractual confirmation. On Portfolio it is literal rather than cautionary: the page holds no validated account records at all. Read every account statement made elsewhere in the module as resting on aggregate assumptions until this banner can be retired for the account layer.",
    },
    {
      id: "sec-summary",
      title: "Portfolio status card — no account records imported",
      targetId: "portfolio-summary",
      explanation:
        "The card title is the portfolio summary: no account records have been imported. This is the authoritative account status for the workspace. It means there is no account table, no filters, no search and no per-account drawer to interrogate — and that any account-level figure quoted elsewhere is derived from aggregate assumptions rather than from a validated register.",
    },
    {
      id: "sec-account-count",
      title: "Aggregate portfolio statement",
      targetId: "portfolio-account-count",
      explanation:
        "The statement records that the current model represents a 104-account no-partner portfolio at an aggregate level, and that account-level records have not yet been validated or imported. The count and the no-partner treatment are the two facts available today. Any per-account value implied downstream is a portfolio average applied uniformly, which must be labelled as estimated wherever it is used.",
    },
    {
      id: "sec-next-actions",
      title: "Navigation actions",
      targetId: "portfolio-next-actions",
      explanation:
        "Three links: Review source requirements (Sources), Review program metrics (Program) and Return to Commercial Overview. They exist because the work needed to populate this page is not done here — it is done by registering account sources and reconciling scope with the program definition. These are navigation only; they do not import, edit or validate any account.",
    },
    {
      id: "sec-data-quality",
      title: "Data readiness card",
      targetId: "portfolio-data-quality",
      explanation:
        "The Data readiness card is the page's data-quality instrument. It replaces the account table with an explicit statement of what the account foundation can and cannot support. Treat it as the entry test for account-level modelling: while pending rows remain, account-level revenue, activation sequencing and staffing demand are assumptions, not evidence.",
    },
    {
      id: "sec-readiness",
      title: "Readiness rows — Known and Pending",
      targetId: "portfolio-readiness",
      explanation:
        "Eight rows, each badged Known or Pending. Known: broader account universe, aggregate ARR and the no-partner aggregate model. Pending: account-level ARR, account-level renewal dates, product mix, partner status, and opportunity and sentiment enrichment. Known means recorded at aggregate level only; Pending means the fact is not yet validated and must not be presented as an account-level result.",
    },
  ],
  inputs: [
    { id: "in-id", label: "Account ID", description: "Stable unique identifier per account. Owner: account-data owner. Approver: Portfolio Lead. Source: account system of record. Status: pending. Confidence: not assessed. Impact: prevents duplicate counting across the whole model.", owner: "Account-data owner", source: "Account system of record", required: true },
    { id: "in-name", label: "Account name", description: "Legal or trading name used for reconciliation with deal documents. Owner: Account Lead. Approver: Portfolio Lead. Source: named account list. Status: aggregate only. Confidence: medium. Impact: scope reconciliation with Program.", owner: "Account Lead", source: "Named account list", required: true },
    { id: "in-segment", label: "Segment", description: "Commercial segmentation used for phasing — pilot, scale, segment expansion. Owner: Commercial Lead. Approver: Program Director. Source: account data. Status: pending. Confidence: low. Impact: activation sequencing.", owner: "Commercial Lead", source: "Account data" },
    { id: "in-partner", label: "Partner status", description: "No-partner or incumbent partner. Owner: Commercial Lead. Approver: Deal Lead. Source: Citrix account information. Status: pending validation (aggregate no-partner model only). Confidence: low. Impact: account-entry strategy and eligibility.", owner: "Commercial Lead", source: "Citrix account information", required: true },
    { id: "in-arr", label: "ARR", description: "Annual recurring value held by the customer with Citrix. Owner: Finance. Approver: Finance. Source: contract or billing data. Status: known in aggregate, pending per account. Confidence: low at account level. Impact: Revenue sizing.", owner: "Finance", source: "Contract / billing data", required: true },
    { id: "in-renewal", label: "Renewal date", description: "Authoritative renewal timing on a consistent fiscal-period basis. Owner: Finance with Account Lead. Approver: Finance. Source: contract data. Status: pending validation. Confidence: low. Impact: revenue phasing and renewal coverage.", owner: "Finance", source: "Contract data", required: true },
    { id: "in-mix", label: "Product mix", description: "Products and editions held per account. Owner: Account Lead. Approver: Commercial Lead. Source: entitlement data. Status: pending validation. Confidence: low. Impact: services opportunity and support complexity.", owner: "Account Lead", source: "Entitlement data" },
    { id: "in-usage", label: "License or usage profile", description: "Deployed versus entitled usage and adoption trend. Owner: Customer Success. Approver: Delivery Lead. Source: telemetry or adoption reporting. Status: pending. Confidence: low. Impact: renewal risk and expansion potential.", owner: "Customer Success Lead", source: "Telemetry / adoption reporting" },
    { id: "in-support", label: "Support history", description: "Historic ticket volume, severity mix and escalation history. Owner: RunOps Lead. Approver: Delivery Lead. Source: support system. Status: pending. Confidence: low. Impact: Staffing & Resources and P&L cost.", owner: "RunOps Lead", source: "Support system" },
    { id: "in-access", label: "Customer access", description: "Whether Neurealm may engage the account directly at the current phase. Owner: Customer Success Lead. Approver: Deal Lead. Source: program and partner rules. Status: pending. Confidence: low. Impact: activation eligibility.", owner: "Customer Success Lead", source: "Program and partner rules" },
    { id: "in-services", label: "Services opportunity", description: "Indicative professional and managed services potential. Owner: Delivery Lead. Approver: Commercial Lead. Source: account assessment. Status: not captured. Confidence: not assessed. Impact: Revenue upside only — never committed revenue.", owner: "Delivery Lead", source: "Account assessment" },
    { id: "in-readiness", label: "Readiness", description: "Whether the account has the data, access and partner clearance to be operated. Owner: Portfolio Lead. Approver: Program Director. Source: this page's readiness rows at aggregate level. Status: aggregate only. Confidence: low. Impact: release candidacy.", owner: "Portfolio Lead", source: "Data readiness card" },
    { id: "in-risk", label: "Risk", description: "Account-level commercial, delivery or relationship risk. Owner: Account Lead. Approver: Program Director. Source: account review. Status: not captured. Confidence: not assessed. Impact: risk concentration and scenario selection.", owner: "Account Lead", source: "Account review" },
    { id: "in-owner", label: "Account owner", description: "The named individual accountable for the account relationship and its facts. Owner: Portfolio Lead. Approver: Deal Lead. Source: account assignment. Status: pending. Confidence: low. Impact: data accountability.", owner: "Portfolio Lead", source: "Account assignment" },
    { id: "in-source", label: "Source", description: "The registered source document behind each account fact. Owner: Commercial Lead. Approver: Deal Lead. Source: Sources register. Status: partially registered. Confidence: medium. Impact: evidence for every account claim.", owner: "Commercial Lead", source: "Sources register", required: true },
    { id: "in-confidence", label: "Confidence", description: "Confidence rating attached to each contributing source. Owner: Commercial Lead. Approver: Finance. Source: Sources register. Status: recorded at source level. Confidence: medium. Impact: how strongly downstream outputs may be stated.", owner: "Commercial Lead", source: "Sources register" },
  ],
  outputs: [
    { id: "out-universe", label: "Validated account universe", description: "Currently an aggregate 104-account no-partner universe; a validated per-account register is pending import.", consumedBy: ["Program", "Revenue", "Release & Activation", "Overview"] },
    { id: "out-segmentation", label: "Account segmentation", description: "Phase-based grouping of accounts. Not yet available at account level.", consumedBy: ["Release & Activation", "Timelines"] },
    { id: "out-arr", label: "Portfolio ARR", description: "Aggregate ARR is known; account-level ARR is pending and must be labelled estimated when apportioned.", consumedBy: ["Revenue", "Overview"] },
    { id: "out-renewal", label: "Renewal distribution", description: "Renewal timing across the portfolio. Pending validation of account-level renewal dates.", consumedBy: ["Revenue", "Timelines"] },
    { id: "out-readiness", label: "Readiness classification", description: "The Known/Pending readiness rows that state how far the account foundation can support decisions.", consumedBy: ["Governance", "Release & Activation", "Overview"] },
    { id: "out-partner", label: "Partner treatment", description: "No-partner versus incumbent-partner treatment. Modelled in aggregate as no-partner; per-account status pending.", consumedBy: ["Revenue", "Program"] },
    { id: "out-candidates", label: "Activation candidates", description: "Accounts eligible for release at the current gate. Cannot be produced until accounts are imported and validated.", consumedBy: ["Release & Activation"] },
    { id: "out-risk", label: "Account risk", description: "Account-level risk and concentration signals. Not currently captured.", consumedBy: ["Governance", "Scenarios"] },
    { id: "out-services", label: "Services opportunity", description: "Indicative services potential per account — opportunity, never contracted revenue.", consumedBy: ["Revenue", "Staffing & Resources"] },
    { id: "out-gaps", label: "Data-quality gaps", description: "The explicit list of pending account facts, which is this page's principal output today.", consumedBy: ["Sources", "Governance", "Overview"] },
  ],
  businessRules: [
    { id: "br-id", rule: "Each account must have a stable unique identifier", explanation: "Names change, merge and duplicate. A stable identifier is the only safe join key between the account register, Release & Activation and Revenue, and is the precondition for importing records onto this page." },
    { id: "br-dupe", rule: "Duplicate accounts must not be counted twice", explanation: "Duplicates inflate portfolio ARR, activation candidates and staffing demand simultaneously. De-duplicate on identifier before import, and reconcile the resulting count against the aggregate universe stated on this page." },
    { id: "br-actuals", rule: "Account-level values must not be replaced by portfolio averages where actual data exists", explanation: "Averages are a stopgap for the current aggregate model. As soon as an account's actual ARR, renewal date or product mix is validated, the actual must replace the average for that account rather than being blended away." },
    { id: "br-estimated", rule: "Estimated values must be labelled as estimated", explanation: "Everything derived from the 104-account aggregate is an estimate. Any downstream figure resting on it must carry that label so an executive reader can distinguish a validated account fact from an apportioned average." },
    { id: "br-partner", rule: "Partner status must influence account-entry strategy", explanation: "No-partner accounts and incumbent-partner accounts have different rights, engagement models and economics. Partner status is currently pending validation, so any per-account entry strategy is provisional." },
    { id: "br-not-active", rule: "An account appearing in the portfolio does not mean it is released or activated", explanation: "Portfolio inclusion is candidacy. Release requires the gate to be open and eligibility confirmed; activation requires a recorded release on Release & Activation. The three states must never be reported as one." },
    { id: "br-revenue", rule: "Revenue may only include accounts meeting the relevant eligibility and activation rules", explanation: "Eligibility comes from Program's gate scope and partner rules; activation comes from Release & Activation. Accounts that satisfy neither must not contribute revenue, even where their ARR is known." },
    { id: "br-renewal", rule: "Renewal timing must use the authoritative source and a consistent fiscal-period treatment", explanation: "Mixed calendar and fiscal treatment silently shifts revenue between periods. Fix one convention, source renewal dates from contract data, and reconcile against Revenue phasing." },
    { id: "br-services", rule: "Services potential is not committed services revenue", explanation: "Services opportunity is an unqualified indication of demand. It may inform upside scenarios and staffing sensitivity, but it must never enter baseline revenue without confirmed rights and a signed engagement." },
    { id: "br-reconcile", rule: "Portfolio totals must reconcile to account-level records", explanation: "When accounts are imported, the sum of account records must equal the stated portfolio totals — count and ARR. An unexplained difference means either the aggregate figure or the register is wrong; neither may be used until resolved." },
    { id: "br-exclusion", rule: "Excluded accounts must retain a documented exclusion reason", explanation: "Silent removal destroys the audit trail and invites the account's quiet return. Record why an account was excluded, who decided, and the evidence, so the exclusion can be reviewed at the next gate." },
    { id: "br-flow", rule: "Scope changes must flow through Assumptions, Scenarios, Release, Revenue, Staffing and Governance", explanation: "A change to the account universe changes eligibility, activation sequencing, revenue, delivery demand and risk concentration. Reconcile every dependent page before the revised case is presented." },
  ],
  calculationLogic: [
    "Portfolio performs no financial calculation on this page. It states account status and data readiness only.",
    "The 104-account no-partner portfolio is an aggregate statement carried from the program source pack, not a computed total from account records.",
    "Readiness rows are recorded states (Known or Pending), not derived from model results.",
    "Any per-account value used elsewhere in the module is currently an apportionment of aggregate figures and must be treated as estimated.",
  ],
  relationship: {
    receivesFrom: [
      "Sources",
      "Named account data",
      "Citrix account information",
      "ICP or fit data",
      "Partner status",
      "Renewal and usage data",
      "Customer engagement information",
    ],
    models: [
      "Account universe",
      "Account segmentation",
      "Commercial value",
      "Renewal timing",
      "Partner treatment",
      "Readiness",
      "Risk",
      "Opportunity",
      "Account prioritisation",
    ],
    feeds: [
      "Program",
      "Assumptions & Change Sets",
      "Scenarios",
      "Release & Activation",
      "Revenue",
      "Staffing & Resources",
      "Program & Timeline",
      "Governance",
      "Overview",
    ],
  },
  downstreamImpacts: [
    { area: "Accounts", effect: "Defines which accounts may be considered at all; today only in aggregate." },
    { area: "Revenue", effect: "Account eligibility and renewal timing determine what revenue may be recognised and when." },
    { area: "Costs", effect: "Product mix and support history drive support cost per account." },
    { area: "Staffing", effect: "Account count and complexity set the operator team shape on Staffing & Resources." },
    { area: "Capacity", effect: "Activation sequencing determines the peak onboarding load." },
    { area: "Activation", effect: "Release candidates are drawn only from validated, eligible accounts." },
    { area: "Timeline", effect: "Renewal distribution shapes phase sequencing on Timelines." },
    { area: "Risk", effect: "Concentration in a small number of high-value accounts is a portfolio-level risk." },
    { area: "Governance", effect: "Material scope changes and strategic exclusions require recorded approval." },
    { area: "Customer outcomes", effect: "Access and adoption data determine whether outcomes can actually be influenced." },
  ],
  dataQuality: {
    dataSources: [
      "Program source pack — aggregate 104-account no-partner portfolio statement",
      "Data readiness rows rendered on this page (Known / Pending)",
      "Registered source references on the Sources page",
    ],
    updateFrequency: "On account-data import or validation, and at each gate review.",
    knownGaps: [
      "No account records imported — there is no account table, so no per-account inspection is possible.",
      "No filters, search or selected-account drawer on this page.",
      "No ARR or value summary rendered; aggregate ARR is described as known but is not displayed here.",
      "No segmentation view.",
      "No partner-status view; the model is aggregate no-partner only.",
      "No renewal calendar or renewal distribution view.",
      "No ICP fit view.",
      "No account risk view or risk concentration measure.",
      "No services-opportunity view.",
      "No source metadata panel on this page; source detail lives on Sources.",
      "Account-level ARR, renewal dates, product mix and partner status remain pending validation.",
      "Opportunity and sentiment enrichment remains pending validation.",
    ],
    changeControl: "Account records may only be imported from a registered source; material scope additions or exclusions require Governance approval and a documented reason.",
    lineage: "Aggregate portfolio position is carried from the Project Momentous source pack; no account-level lineage exists until records are imported.",
  },
  modelConfidence: "Low",
  confidenceBasis: ["Account data", "Source completeness", "Revenue assumptions", "Timing"],
  confidenceGuidance:
    "Confidence in the aggregate universe and aggregate ARR is reasonable; confidence in anything stated per account is low because no account records exist. Treat aggregate statements as planning-grade and every account-level implication as an assumption to be evidenced before an executive decision is taken.",
  commercialReadiness: "Not Ready",
  readinessCriteria: [
    "A registered, current source exists for the named account list.",
    "Every account carries a stable unique identifier and a named owner.",
    "Account-level ARR and renewal dates are validated against contract data.",
    "Partner status is confirmed per account.",
    "Portfolio totals reconcile to the sum of account records.",
    "Activation candidates are distinguishable from the total portfolio.",
  ],

  /* ---------------- How to use it ---------------- */
  workflow: [
    { id: "wf-1", step: 1, title: "Confirm the portfolio source and update date", description: "Check the registered account source on Sources and when it was last refreshed before treating any portfolio figure as current.", role: "Portfolio Lead" },
    { id: "wf-2", step: 2, title: "Validate identifiers and remove duplicates", description: "Confirm every candidate account has a stable unique identifier and that no account appears twice under different names.", role: "Account-data owner" },
    { id: "wf-3", step: 3, title: "Confirm partner status", description: "Classify each account as no-partner or incumbent partner. The current model assumes no-partner in aggregate; per-account status is pending.", role: "Commercial Lead" },
    { id: "wf-4", step: 4, title: "Validate ARR and renewal timing", description: "Source account-level ARR and renewal dates from contract data on a single consistent fiscal-period basis.", role: "Finance" },
    { id: "wf-5", step: 5, title: "Review product mix, usage and support history", description: "Assess entitlement, adoption and historic support load to understand service potential and operating complexity.", role: "Account Lead" },
    { id: "wf-6", step: 6, title: "Assess readiness and customer access", description: "Test whether data, tooling and direct customer access exist for the account at the current phase.", role: "Customer Success Lead" },
    { id: "wf-7", step: 7, title: "Review commercial opportunity and risk", description: "Record services opportunity as indicative only, and flag relationship, renewal or concentration risk.", role: "Commercial Lead" },
    { id: "wf-8", step: 8, title: "Apply the appropriate segment", description: "Assign each account to pilot, scale or segment-expansion grouping consistent with Program's gate account scope.", role: "Commercial Lead" },
    { id: "wf-9", step: 9, title: "Identify release candidates and exclusions", description: "Separate eligible activation candidates from the wider universe and record a documented reason for each exclusion.", role: "Program Director" },
    { id: "wf-10", step: 10, title: "Reconcile totals", description: "Confirm the account count and summed ARR match the stated aggregate portfolio position; investigate any difference before use.", role: "Finance" },
    { id: "wf-11", step: 11, title: "Escalate missing or conflicting data", description: "Route every pending readiness row to a named owner with a date, and raise conflicts to Governance.", role: "Portfolio Lead" },
    { id: "wf-12", step: 12, title: "Continue to Release & Activation or Assumptions", description: "Take validated candidates to Release & Activation, and take unresolved modelling positions to Assumptions & Change Sets.", role: "Commercial Lead" },
  ],
  actionsAvailable: [
    "Read the aggregate portfolio position and the no-account-records status",
    "Read the eight Known/Pending data readiness rows",
    "Navigate to Sources to review source requirements",
    "Navigate to Program to review program metrics",
    "Return to Commercial Overview",
  ],
  teamActivities: [
    { id: "ta-portfolio", activity: "Maintain account scope and the register of pending account facts", role: "Portfolio Lead", cadence: "Weekly" },
    { id: "ta-account", activity: "Validate account facts — identifier, owner, product mix, access", role: "Account Leads", cadence: "Per account, before import" },
    { id: "ta-finance", activity: "Validate ARR and renewal treatment on a consistent fiscal basis", role: "Finance", cadence: "Per model run cycle" },
    { id: "ta-commercial", activity: "Validate commercial eligibility, segmentation and partner treatment", role: "Commercial Lead", cadence: "Weekly" },
    { id: "ta-cs", activity: "Validate customer engagement, adoption and access status", role: "Customer Success Lead", cadence: "Per gate" },
    { id: "ta-delivery", activity: "Validate service potential and delivery complexity per account", role: "Delivery Lead", cadence: "Per gate" },
    { id: "ta-gov", activity: "Approve material scope changes and record exclusion reasons", role: "Governance", cadence: "On change" },
    { id: "ta-exec", activity: "Approve strategic exclusions or additions to the account universe", role: "Executive Sponsor", cadence: "At gate review" },
    { id: "ta-program", activity: "Reconcile account scope against the program gate account scope labels", role: "Program Director", cadence: "Per gate" },
  ],
  roles: [
    { role: "Portfolio Lead", responsibility: "Owns the account universe, its scope and its data-quality register." },
    { role: "Account Lead", responsibility: "Owns the accuracy of individual account facts and the customer relationship." },
    { role: "Commercial Lead", responsibility: "Owns eligibility, segmentation and partner treatment." },
    { role: "Finance", responsibility: "Owns value and renewal treatment and portfolio reconciliation." },
    { role: "Customer Success Lead", responsibility: "Owns engagement, adoption and access assessment." },
    { role: "Delivery Lead", responsibility: "Owns service potential and complexity assessment." },
    { role: "Program Director", responsibility: "Owns reconciliation with the program gate scope and release candidacy." },
    { role: "Executive Sponsor", responsibility: "Approves strategic exclusions and additions." },
  ],
  raci: [
    { activity: "Maintain the account universe", assignments: [{ role: "Portfolio Lead", raci: "R" }, { role: "Deal Lead", raci: "A" }, { role: "Commercial Lead", raci: "C" }, { role: "Finance", raci: "I" }] },
    { activity: "Validate account-level ARR and renewal dates", assignments: [{ role: "Finance", raci: "R" }, { role: "Portfolio Lead", raci: "A" }, { role: "Account Lead", raci: "C" }, { role: "Commercial Lead", raci: "I" }] },
    { activity: "Confirm partner status per account", assignments: [{ role: "Commercial Lead", raci: "R" }, { role: "Deal Lead", raci: "A" }, { role: "Account Lead", raci: "C" }, { role: "Program Director", raci: "I" }] },
    { activity: "Assess readiness and customer access", assignments: [{ role: "Customer Success Lead", raci: "R" }, { role: "Program Director", raci: "A" }, { role: "Delivery Lead", raci: "C" }, { role: "Portfolio Lead", raci: "I" }] },
    { activity: "Identify release candidates", assignments: [{ role: "Program Director", raci: "R" }, { role: "Commercial Lead", raci: "A" }, { role: "Finance", raci: "C" }, { role: "Delivery Lead", raci: "C" }] },
    { activity: "Approve a material scope change or exclusion", assignments: [{ role: "Executive Sponsor", raci: "A" }, { role: "Portfolio Lead", raci: "R" }, { role: "Commercial Lead", raci: "C" }, { role: "Finance", raci: "C" }] },
  ],
  reviewRequirements: [
    "Portfolio source and refresh date reviewed before each gate review.",
    "Every Pending readiness row reviewed with a named owner and target date.",
    "Account count and ARR reconciled to account records once imported.",
    "Account scope reviewed against the Program gate account scope labels.",
  ],
  approvalRequirements: [
    "Executive Sponsor approval for strategic additions to, or exclusions from, the account universe.",
    "Deal Lead approval for changes to the in-scope account population.",
    "Finance approval for ARR and renewal treatment used downstream.",
    "Governance approval and a recorded reason for any account removal.",
  ],
  decisions: [
    { id: "dec-source", decision: "Which source becomes the authoritative account register", decidedBy: "Deal Lead with Commercial Lead", evidence: "Registered source on Sources" },
    { id: "dec-import", decision: "Whether account records are ready to import", decidedBy: "Portfolio Lead with Finance", evidence: "Identifier, ARR and renewal validation" },
    { id: "dec-partner", decision: "How incumbent-partner accounts are treated in this phase", decidedBy: "Commercial Lead with Legal", evidence: "Partner rules in deal documents" },
    { id: "dec-candidates", decision: "Which accounts are release candidates at the current gate", decidedBy: "Program Director with Commercial Lead", evidence: "Eligibility and access assessment" },
    { id: "dec-exclusion", decision: "Which accounts are excluded and why", decidedBy: "Executive Sponsor", evidence: "Documented exclusion reason" },
  ],
  whatToDoNext: [
    "Register the authoritative account source on Sources.",
    "Close the pending readiness rows one at a time with named owners.",
    "Reconcile the aggregate 104-account position with the Program gate account scope.",
    "Label every account-level figure used elsewhere as estimated until import completes.",
    "Take validated candidates to Release & Activation.",
    "Record unresolved modelling positions on Assumptions & Change Sets.",
  ],
  relatedPages: [
    { pageId: "commercial-program", label: "Program", route: "/commercial/program", relationship: "Prerequisite" },
    { pageId: "commercial-sources", label: "Sources", route: "/commercial/sources", relationship: "Prerequisite" },
    { pageId: "commercial-overview", label: "Overview", route: "/commercial", relationship: "Downstream" },
    { pageId: "commercial-scenarios", label: "Scenarios", route: "/commercial/scenarios", relationship: "Companion" },
    { pageId: "commercial-assumptions", label: "Assumptions & Change Sets", route: "/commercial/model/assumptions", relationship: "Companion" },
    { pageId: "commercial-release", label: "Release & Activation", route: "/commercial/model/release", relationship: "Downstream" },
    { pageId: "commercial-revenue", label: "Revenue", route: "/commercial/model/revenue", relationship: "Downstream" },
    { pageId: "commercial-staffing-resources", label: "Staffing & Resources", route: "/commercial/staffing-resources", relationship: "Downstream" },
    { pageId: "commercial-program-timeline", label: "Timelines", route: "/commercial/program-timeline", relationship: "Downstream" },
    { pageId: "commercial-governance", label: "Governance", route: "/commercial/neurealm-governance", relationship: "Companion" },
  ],

  /* ---------------- Interpretation & training ---------------- */
  interpretation: [
    {
      band: "healthy",
      label: "Account foundation is evidenced and reconciled",
      criteria: [
        "Account-level source data is complete.",
        "Partner status is known for every account.",
        "ARR and renewal dates are reconciled to contract data.",
        "Readiness is evidence-based rather than assumed.",
        "Portfolio totals reconcile to the sum of account records.",
        "Activation candidates are clearly distinct from the total portfolio.",
      ],
      action: "Proceed to Release & Activation and allow account-level revenue and staffing modelling to be treated as decision-grade.",
    },
    {
      band: "warning",
      label: "Account data is partial or assumed",
      criteria: [
        "Portfolio averages substitute for missing account data.",
        "Partner status is unknown for part of the universe.",
        "Renewal dates conflict between sources.",
        "Readiness is based on assumptions rather than evidence.",
        "High-value accounts carry low data confidence.",
        "Account scope differs from the Program page.",
      ],
      action: "Keep account-level outputs labelled as estimated, assign each gap an owner and date, and reconcile scope with Program before the next gate review.",
    },
    {
      band: "critical",
      label: "Account basis cannot support a decision",
      criteria: [
        "Revenue is modelled from unvalidated accounts.",
        "Duplicate accounts are affecting totals.",
        "Excluded accounts remain in activation.",
        "Partner restrictions are being ignored.",
        "Account-level data cannot support an executive decision.",
      ],
      action: "Stop presenting account-level results, freeze activation modelling, and escalate to the Deal Lead and Executive Sponsor to establish a validated account register.",
    },
  ],
  commonMistakes: [
    { id: "cm-equal", description: "Treating every account as equally activatable.", correction: "Test each account for gate eligibility, partner status, data availability and customer access before treating it as a candidate." },
    { id: "cm-arr", description: "Treating customer ARR as revenue immediately available to Neurealm.", correction: "ARR is the customer's spend with Citrix. Neurealm revenue follows the modelled commercial mechanics on eligible, activated accounts only." },
    { id: "cm-release", description: "Confusing portfolio inclusion with release.", correction: "Keep in scope, eligible, released and activated as four distinct states and report them separately." },
    { id: "cm-incumbent", description: "Ignoring incumbent partners when planning account entry.", correction: "Confirm partner status per account and apply the incumbent-partner treatment rules before assuming direct entry." },
    { id: "cm-average", description: "Applying a single customer-level average to every account.", correction: "Use averages only where no actual exists, label them estimated, and replace them as soon as account data is validated." },
    { id: "cm-renewal", description: "Failing to reconcile renewal timing across sources and fiscal conventions.", correction: "Adopt one fiscal convention, source renewal dates from contract data, and reconcile against Revenue phasing." },
    { id: "cm-services", description: "Treating services opportunity as contracted services revenue.", correction: "Keep opportunity in upside scenarios until rights are confirmed and an engagement is signed." },
    { id: "cm-remove", description: "Removing accounts without documenting the reason or the downstream effects.", correction: "Record the exclusion reason and approver, then reconcile Revenue, Staffing, Release & Activation and Scenarios." },
  ],
  bestPractices: [
    "State the portfolio source and refresh date at the start of every review.",
    "Never present an apportioned average without the word estimated next to it.",
    "Close pending readiness rows one at a time with a named owner and a date.",
    "Reconcile the account count and ARR to account records at every import.",
    "Keep exclusion reasons with the account record, not in meeting notes.",
    "Re-run the downstream reconciliation checklist after every scope change.",
  ],
  workedExamples: [
    {
      id: "we-account-removed",
      title: "A major account is removed from the pilot scope",
      narrative:
        "A high-value account expected to anchor the controlled operator pilot is found to have an incumbent partner engagement that cannot be displaced this phase, so it is delayed rather than removed permanently. Because it represents a disproportionate share of the aggregate value, the effect is not a small trim — it changes the shape of the case. The correct response is to reconcile every dependent page before any revised number is shown to an executive audience.",
      steps: [
        "Portfolio ARR falls, and because the account was disproportionately large the average per remaining account also changes.",
        "Renewal coverage changes: the renewal event that anchored the early period moves out, thinning early-period coverage.",
        "Activation timing changes: Release & Activation re-sequences the pilot cohort and the pilot gate evidence is restated.",
        "Revenue changes: eligible revenue for the delayed account is removed from the baseline and, if retained at all, moves to an upside scenario.",
        "Staffing changes: Staffing & Resources reduces or reshapes the Day 1 operator team for a smaller pilot cohort.",
        "Service opportunity changes: indicative professional and managed services potential attached to that account leaves the pilot view.",
        "Risk concentration changes: the remaining cohort may be more or less concentrated; record the new concentration explicitly.",
        "Scenario performance changes: Conservative, Base and Upside cases must be re-run so comparison stays valid.",
      ],
      result:
        "Governance approval is required for the revised scope, and Overview must not present the revised executive recommendation until Portfolio, Revenue, Staffing, Release & Activation and Scenarios are reconciled to the same account basis.",
    },
  ],
  faqs: [
    { id: "faq-scope", question: "What makes an account in scope?", answer: "The account falls inside the program's partner and market-segment boundary, appears in the registered named account source, and is not subject to a documented legal or partner exclusion. In scope means it may be considered — nothing more. Today the workspace holds this at aggregate level only: 104 no-partner accounts, with no individual records imported." },
    { id: "faq-states", question: "What is the difference between in scope, eligible, released and activated?", answer: "In scope means the account is inside the deal boundary. Eligible means its gate is open and its partner, data, access and exclusion tests pass. Released means it has been approved for activation on Release & Activation. Activated means it is being operated and may contribute revenue. Only activated accounts belong in baseline revenue." },
    { id: "faq-partner", question: "Why does partner status matter?", answer: "No-partner accounts can be approached directly under the proposed operator model. Incumbent-partner accounts carry an existing relationship with different rights, engagement rules and economics. Mixing the two produces an entry strategy that cannot be executed and revenue that cannot be earned. Partner status is currently pending validation per account." },
    { id: "faq-arr", question: "Is ARR the same as Neurealm revenue?", answer: "No. ARR is the customer's recurring spend with Citrix. Neurealm revenue is what the proposed commercial mechanics yield on eligible, activated accounts — rebate, professional services and managed services as modelled on Revenue. Treating ARR as revenue overstates the case by a wide margin." },
    { id: "faq-renewal", question: "How should missing renewal dates be handled?", answer: "Flag the account as pending rather than assuming a date. Where a placeholder is unavoidable for phasing, label it estimated, keep it out of any committed statement, and record the gap as a data-quality item with a named owner. Never let an assumed date drive an activation commitment." },
    { id: "faq-readiness", question: "What does readiness mean?", answer: "Readiness is whether the account can actually be operated: validated data, confirmed partner status, available tooling and telemetry, and direct customer access at this phase. On this page readiness is reported at aggregate level through the Known and Pending rows, not per account." },
    { id: "faq-priority", question: "Why can a high-value account have low commercial priority?", answer: "Value is only one input. A large account with an incumbent partner, no direct access, unvalidated data or a distant renewal cannot be activated early regardless of its ARR. Priority combines value with eligibility, readiness, timing and risk." },
    { id: "faq-change", question: "Where do I change account scope?", answer: "Not on this page — it is read-only. Scope changes originate from a registered source on Sources and the program definition on Program, then flow through Assumptions & Change Sets, Scenarios, Release & Activation, Revenue, Staffing & Resources and Governance. Record the approval before any revised case is presented." },
  ],
  glossary: [
    { term: "Account Universe", definition: "The full set of accounts inside the deal boundary that may be considered for the operator model — currently stated as 104 no-partner accounts in aggregate." },
    { term: "ARR", definition: "Annual recurring revenue the customer spends with Citrix. An input to sizing, not Neurealm revenue." },
    { term: "Renewal Pool", definition: "The set of account renewals falling within a given period. Used for phasing; only meaningful once account-level renewal dates are validated." },
    { term: "ICP Fit", definition: "How closely an account matches the ideal customer profile for the operator model. Not currently captured on this page." },
    { term: "No-Partner", definition: "An account with no incumbent partner engagement, which the operator model assumes may be approached directly." },
    { term: "Incumbent Partner", definition: "An existing partner already serving the account, whose presence changes entry rights, engagement model and economics." },
    { term: "Readiness", definition: "Whether validated data, partner clearance, tooling and customer access exist to operate the account at the current phase." },
    { term: "Release Candidate", definition: "An eligible account proposed for activation at the current gate, ahead of a recorded release decision." },
    { term: "Activation", definition: "The point at which a released account is operated under the model and may contribute revenue." },
    { term: "Services Opportunity", definition: "Indicative professional or managed services potential in an account. An opportunity signal, never contracted revenue." },
    { term: "Data Readiness", definition: "The Known versus Pending classification of account facts shown on this page." },
    { term: "Reconciliation", definition: "Confirming that portfolio totals equal the sum of account records, and that account scope matches the Program gate scope." },
  ],
  executiveTakeaway:
    "Portfolio is the account foundation of the deal, and today it is deliberately empty. The workspace holds an aggregate 104-account no-partner position with aggregate ARR known, while account-level ARR, renewal dates, product mix, partner status and enrichment remain pending validation. Every account-level figure elsewhere in the module is therefore an apportioned estimate. Treat the model as planning-grade until a validated account register is imported and reconciled.",
  keyRisks: [
    "Account-level revenue and staffing conclusions drawn from portfolio averages.",
    "Duplicate or unstable account identifiers distorting totals once records are imported.",
    "Partner status unknown, producing an entry strategy that cannot be executed.",
    "Renewal timing conflicts shifting revenue between periods undetected.",
    "Portfolio inclusion being read as release or activation.",
    "Scope changes made without reconciling Revenue, Staffing, Release & Activation and Scenarios.",
  ],

  /* ---------------- Show on page ---------------- */
  showOnPageTargets: [
    { targetId: "portfolio-context", label: "Directional model banner", description: "States that account-level validation and contractual confirmation are pending." },
    { targetId: "portfolio-summary", label: "Portfolio status card", description: "No account records imported — the authoritative account status for the workspace." },
    { targetId: "portfolio-account-count", label: "Aggregate portfolio statement", description: "104-account no-partner portfolio held at aggregate level only." },
    { targetId: "portfolio-next-actions", label: "Navigation actions", description: "Links to Sources, Program and Overview. Navigation only — no account is imported or edited." },
    { targetId: "portfolio-data-quality", label: "Data readiness card", description: "The page's data-quality instrument in place of an account table." },
    { targetId: "portfolio-readiness", label: "Readiness rows", description: "Eight Known/Pending rows covering universe, aggregate ARR, no-partner model, account ARR, renewals, product mix, partner status and enrichment." },
  ],
};
