import { X } from "lucide-react";
import { PACKAGE_ARTIFACTS } from "./data";

export function PackageContentsDrawer({ open, onClose }: { open: boolean; onClose: () => void }) {
  if (!open) return null;
  return (
    <div className="fixed inset-0 z-50 flex justify-end">
      <button type="button" aria-label="Close" className="flex-1 bg-slate-900/30" onClick={onClose} />
      <aside className="flex h-full w-full max-w-[720px] flex-col border-l border-[#E2E8F0] bg-white shadow-xl">
        <header className="flex items-center gap-3 border-b border-[#E2E8F0] px-4 py-3">
          <div>
            <h2 className="text-[13px] font-semibold text-slate-900">Change Package Contents</h2>
            <p className="text-[11.5px] text-slate-500">CP-2026-01842 · {PACKAGE_ARTIFACTS.length} artifacts</p>
          </div>
          <button type="button" onClick={onClose} className="ml-auto grid h-7 w-7 place-items-center rounded-md text-slate-500 hover:bg-slate-100">
            <X className="h-4 w-4" />
          </button>
        </header>
        <div className="flex-1 overflow-auto p-4">
          <div className="overflow-x-auto rounded-md border border-[#E2E8F0]">
            <table className="w-full min-w-[820px] text-left text-[11.5px]">
              <thead className="bg-slate-50 text-[10.5px] uppercase tracking-wide text-slate-500">
                <tr>
                  <th className="px-3 py-1.5 font-medium">Artifact</th>
                  <th className="px-3 py-1.5 font-medium">Type</th>
                  <th className="px-3 py-1.5 font-medium">Technology</th>
                  <th className="px-3 py-1.5 font-medium">Generated By</th>
                  <th className="px-3 py-1.5 font-medium">Version</th>
                  <th className="px-3 py-1.5 font-medium">Validation</th>
                  <th className="px-3 py-1.5 font-medium">Checksum</th>
                  <th className="px-3 py-1.5 font-medium">Last Generated</th>
                </tr>
              </thead>
              <tbody>
                {PACKAGE_ARTIFACTS.map((a) => (
                  <tr key={a.name} className="border-t border-[#E2E8F0]">
                    <td className="px-3 py-1.5 font-mono text-slate-800">{a.name}</td>
                    <td className="px-3 py-1.5 text-slate-600">{a.type}</td>
                    <td className="px-3 py-1.5 text-slate-600">{a.technology}</td>
                    <td className="px-3 py-1.5 text-slate-600">{a.generatedBy}</td>
                    <td className="px-3 py-1.5 text-slate-600">{a.version}</td>
                    <td className={a.validation === "Validated" ? "px-3 py-1.5 text-emerald-700" : "px-3 py-1.5 text-amber-700"}>{a.validation}</td>
                    <td className="px-3 py-1.5 font-mono text-slate-500">{a.checksum}</td>
                    <td className="px-3 py-1.5 text-slate-600">{a.lastGenerated}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="mt-3 text-[11px] text-slate-500">
            Artifacts are engineered previews. Nothing in this package has been executed against production.
          </p>
        </div>
      </aside>
    </div>
  );
}
