/**
 * Stage 3 — SRE capability hierarchy.
 *
 * Stage 1 registered eight flat capabilities for the SRE module. Several of
 * them bundle materially different screens under one label, which will make
 * Module Capability Intelligence answer coarsely. This file decomposes them
 * into a four-level hierarchy (domain → capability → sub-capability → feature)
 * without changing the Stage 1 manifest: every node that derives from a Stage 1
 * capability records `supersedesCapabilityId` so the lineage is traceable.
 *
 * Two classifications are recorded separately and deliberately:
 *  - `declaredMaturity` — what the manifest says the implementation is.
 *  - `implementationClassification` — whether a node is product representation,
 *    an interactive prototype, or an operating capability. No SRE node is an
 *    operational implementation today; the module has no database usage.
 */

import type { CapabilityHierarchy, CapabilityNode } from "../classificationTypes";

const P = "src/pages/prod-twin";

const node = (n: CapabilityNode): CapabilityNode => n;

export const SRE_CAPABILITY_HIERARCHY: CapabilityHierarchy = {
  moduleId: "sre",
  nodes: [
    /* ---------------------------------------------------------------- domain */
    node({
      capabilityId: "sre",
      parentCapabilityId: null,
      level: "domain",
      name: "Site Reliability Engineering",
      description:
        "Neurealm's SRE practice surface: operating model, reliability enablement, assessment, digital twins, modernization, automation catalogue and the value narrative.",
      relatedRoutes: [],
      relatedPages: [],
      relatedComponents: [],
      relatedActions: [],
      evidenceStrength: "client-side-functional",
      declaredMaturity: "mock",
      implementationClassification: "product-representation",
      knownLimitations: [
        "No database, edge function or agent runtime is used anywhere in the module",
        "Every screen renders in-repo fixture or editorial content",
      ],
    }),

    /* ------------------------------------------------- operating model */
    node({
      capabilityId: "sre.operating-model",
      parentCapabilityId: "sre",
      level: "capability",
      name: "Operating Model",
      description: "Target reliability operating model: teams, responsibilities and rhythms.",
      relatedRoutes: ["/sre-operating-model"],
      relatedPages: [`${P}/SreOperatingModel.tsx`],
      relatedComponents: [],
      relatedActions: ["Review operating model sections"],
      evidenceStrength: "static-only",
      declaredMaturity: "static",
      implementationClassification: "product-representation",
      knownLimitations: ["Content is authored in the component; no tenant variation"],
      supersedesCapabilityId: "sre.operating-model-cockpit",
    }),

    /* ---------------------------------------------------- enablement */
    node({
      capabilityId: "sre.enablement",
      parentCapabilityId: "sre",
      level: "capability",
      name: "Reliability Enablement",
      description:
        "Reference library establishing shared vocabulary and target state across SRE, team topologies, platform engineering and FinOps.",
      relatedRoutes: ["/reliability-foundations"],
      relatedPages: [`${P}/ReliabilityFoundations.tsx`],
      relatedComponents: [],
      relatedActions: ["Browse foundation topics"],
      evidenceStrength: "static-only",
      declaredMaturity: "static",
      implementationClassification: "product-representation",
      knownLimitations: ["Editorial content only"],
      supersedesCapabilityId: "sre.reliability-foundations",
    }),
    node({
      capabilityId: "sre.enablement.google-sre",
      parentCapabilityId: "sre.enablement",
      level: "sub-capability",
      name: "Google SRE Model",
      description: "Google SRE principles and an adoption path.",
      relatedRoutes: [
        "/reliability-foundations/google-sre",
        "/reliability-foundations/google-sre/how-to-achieve",
      ],
      relatedPages: [`${P}/GoogleSre.tsx`, `${P}/HowToAchieveGoogleSre.tsx`],
      relatedComponents: [],
      relatedActions: ["Read principles", "Read adoption path"],
      evidenceStrength: "static-only",
      declaredMaturity: "static",
      implementationClassification: "product-representation",
      knownLimitations: [],
      supersedesCapabilityId: "sre.reliability-foundations",
    }),
    node({
      capabilityId: "sre.enablement.team-topologies",
      parentCapabilityId: "sre.enablement",
      level: "sub-capability",
      name: "Team Topologies",
      description: "Team topology patterns, future-state organisation and functional org chart.",
      relatedRoutes: [
        "/reliability-foundations/team-topologies",
        "/reliability-foundations/team-topologies/future-state-org",
        "/reliability-foundations/team-topologies/functional-org-chart",
      ],
      relatedPages: [
        `${P}/TeamTopologies.tsx`,
        `${P}/FutureStateReliabilityOrg.tsx`,
        `${P}/FunctionalOrgChart.tsx`,
      ],
      relatedComponents: [],
      relatedActions: ["Explore org structures"],
      evidenceStrength: "static-only",
      declaredMaturity: "static",
      implementationClassification: "product-representation",
      knownLimitations: [],
      supersedesCapabilityId: "sre.reliability-foundations",
    }),
    node({
      capabilityId: "sre.enablement.platform-engineering",
      parentCapabilityId: "sre.enablement",
      level: "sub-capability",
      name: "Platform Engineering Foundations",
      description: "Design principles, build path and platform-as-a-product capability model.",
      relatedRoutes: [
        "/reliability-foundations/platform-engineering/design-principles",
        "/reliability-foundations/platform-engineering/how-to-build",
        "/reliability-foundations/platform-engineering/capability-model",
      ],
      relatedPages: [
        `${P}/PlatformEngineeringDesignPrinciples.tsx`,
        `${P}/HowToBuildPlatformEngineering.tsx`,
        `${P}/PlatformAsAProduct.tsx`,
      ],
      relatedComponents: [],
      relatedActions: ["Read design principles", "Review capability model"],
      evidenceStrength: "static-only",
      declaredMaturity: "static",
      implementationClassification: "product-representation",
      knownLimitations: [],
      supersedesCapabilityId: "sre.reliability-foundations",
    }),
    node({
      capabilityId: "sre.enablement.finops",
      parentCapabilityId: "sre.enablement",
      level: "sub-capability",
      name: "FinOps Operations",
      description: "FinOps operations console framing cost accountability alongside reliability.",
      relatedRoutes: ["/reliability-foundations/finops/operations-console"],
      relatedPages: [`${P}/FinOpsOperationsConsole.tsx`],
      relatedComponents: [],
      relatedActions: ["Review cost posture panels"],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: ["No cloud billing integration"],
      supersedesCapabilityId: "sre.reliability-foundations",
    }),

    /* ---------------------------------------------------- assessment */
    node({
      capabilityId: "sre.assessment",
      parentCapabilityId: "sre",
      level: "capability",
      name: "Reliability Assessment",
      description: "Scored assessment of operational friction across an enterprise estate.",
      relatedRoutes: ["/operational-friction-index", "/product-reliability-transformation-index"],
      relatedPages: [`${P}/OperationalFrictionIndex.tsx`],
      relatedComponents: [],
      relatedActions: ["Review friction domains", "Compare scores"],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: [
        "Scores are hard-coded in frictionPanelData.ts",
        "The same component is exposed under two routes",
      ],
      supersedesCapabilityId: "sre.friction-index",
    }),

    /* --------------------------------------------------- digital twin */
    node({
      capabilityId: "sre.digital-twin",
      parentCapabilityId: "sre",
      level: "capability",
      name: "Estate Digital Twin",
      description:
        "Twin views of a client estate spanning production services, cloud architecture and resilience posture.",
      relatedRoutes: [],
      relatedPages: [],
      relatedComponents: [],
      relatedActions: [],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: ["No live telemetry anywhere in the twin"],
    }),
    node({
      capabilityId: "sre.digital-twin.production",
      parentCapabilityId: "sre.digital-twin",
      level: "sub-capability",
      name: "Production Resilience Twin",
      description: "Command centre for production services and their resilience posture.",
      relatedRoutes: ["/prod-resilience-twin"],
      relatedPages: [`${P}/ProdResilienceTwin.tsx`],
      relatedComponents: ["src/components/eoc/ServiceMap.tsx"],
      relatedActions: ["Open service rows", "Navigate to a RunOps service twin"],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: ["Rows link out to RunOps, crossing the module boundary"],
      supersedesCapabilityId: "sre.production-digital-twin",
    }),
    node({
      capabilityId: "sre.digital-twin.production.topology",
      parentCapabilityId: "sre.digital-twin.production",
      level: "feature",
      name: "Production Topology",
      description: "Dependency topology of production services.",
      relatedRoutes: ["/production-topology"],
      relatedPages: [`${P}/ProductionTopology.tsx`],
      relatedComponents: [],
      relatedActions: ["Inspect dependencies"],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: ["Fixture topology"],
      supersedesCapabilityId: "sre.production-digital-twin",
    }),
    node({
      capabilityId: "sre.digital-twin.production.product-lines",
      parentCapabilityId: "sre.digital-twin.production",
      level: "feature",
      name: "Product Line Map",
      description: "Mapping of services to product lines.",
      relatedRoutes: ["/product-line-map"],
      relatedPages: [`${P}/ProductLineMap.tsx`],
      relatedComponents: [],
      relatedActions: ["Browse product lines"],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: ["Fixture data"],
      supersedesCapabilityId: "sre.production-digital-twin",
    }),
    node({
      capabilityId: "sre.digital-twin.production.golden-workflows",
      parentCapabilityId: "sre.digital-twin.production",
      level: "feature",
      name: "Golden Workflow Map",
      description: "Business-critical workflows traced across services.",
      relatedRoutes: ["/golden-workflow-map"],
      relatedPages: [`${P}/GoldenWorkflowMap.tsx`],
      relatedComponents: [],
      relatedActions: ["Trace a workflow"],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: ["Workflows are not linked to any executable definition"],
      supersedesCapabilityId: "sre.production-digital-twin",
    }),
    node({
      capabilityId: "sre.digital-twin.production.signals",
      parentCapabilityId: "sre.digital-twin.production",
      level: "feature",
      name: "Signal Intelligence",
      description: "Aggregated reliability signals for the production estate.",
      relatedRoutes: ["/signal-intelligence"],
      relatedPages: [`${P}/SignalIntelligence.tsx`],
      relatedComponents: [],
      relatedActions: ["Review signal panels"],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: ["No monitoring integration"],
      supersedesCapabilityId: "sre.production-digital-twin",
    }),
    node({
      capabilityId: "sre.digital-twin.cloud",
      parentCapabilityId: "sre.digital-twin",
      level: "sub-capability",
      name: "Cloud Architecture Twin",
      description: "Enterprise cloud application twin driven by shared scenario state.",
      relatedRoutes: ["/enterprise-cloud-twin"],
      relatedPages: [`${P}/EnterpriseCloudTwin.tsx`],
      relatedComponents: ["src/components/sre-twin/SRETwinSections.tsx"],
      relatedActions: ["Switch scenario", "Explore architecture layers"],
      evidenceStrength: "client-side-functional",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: ["Depends on shared.scenario-state, which has no agreed owner"],
      supersedesCapabilityId: "sre.cloud-architecture-twins",
    }),
    node({
      capabilityId: "sre.digital-twin.aws-resilience",
      parentCapabilityId: "sre.digital-twin",
      level: "sub-capability",
      name: "AWS Resilience Architecture Twin",
      description: "AWS-specific resilience patterns and failure-domain view.",
      relatedRoutes: ["/aws-resilience-architecture-twin"],
      relatedPages: [`${P}/AWSResilienceArchitectureTwin.tsx`],
      relatedComponents: [],
      relatedActions: ["Explore resilience patterns"],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: ["src/data/sreTwinData.ts is a static fixture"],
      supersedesCapabilityId: "sre.cloud-architecture-twins",
    }),

    /* -------------------------------------------------- modernization */
    node({
      capabilityId: "sre.modernization",
      parentCapabilityId: "sre",
      level: "capability",
      name: "Modernization Delivery",
      description: "Delivery model for platform engineering and application modernization work.",
      relatedRoutes: [],
      relatedPages: [],
      relatedComponents: [],
      relatedActions: [],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "product-representation",
      knownLimitations: [],
      supersedesCapabilityId: "sre.platform-and-modernization-factories",
    }),
    node({
      capabilityId: "sre.modernization.platform-factory",
      parentCapabilityId: "sre.modernization",
      level: "sub-capability",
      name: "Platform Engineering Factory",
      description: "Factory model for building and running internal platforms.",
      relatedRoutes: ["/platform-engineering-factory", "/hybrid-cloud-workbench"],
      relatedPages: [`${P}/PlatformEngineeringFactory.tsx`, `${P}/HybridCloudWorkbench.tsx`],
      relatedComponents: [],
      relatedActions: ["Review factory stages"],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: [],
      supersedesCapabilityId: "sre.platform-and-modernization-factories",
    }),
    node({
      capabilityId: "sre.modernization.app-factory",
      parentCapabilityId: "sre.modernization",
      level: "sub-capability",
      name: "Application Modernization Factory",
      description: "Modernization factory and roadmap screens.",
      relatedRoutes: ["/modernization-factory", "/modernization-roadmap", "/modernization-roadmap-v2"],
      relatedPages: [
        `${P}/ModernizationFactory.tsx`,
        `${P}/ModernizationRoadmap.tsx`,
        `${P}/ModernizationRoadmapV2.tsx`,
      ],
      relatedComponents: [],
      relatedActions: ["Review roadmap waves"],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: [
        "Two competing roadmap implementations are both live and both in navigation",
      ],
      supersedesCapabilityId: "sre.platform-and-modernization-factories",
    }),

    /* ----------------------------------------------------- automation */
    node({
      capabilityId: "sre.automation",
      parentCapabilityId: "sre",
      level: "capability",
      name: "Reliability Automation Catalogue",
      description: "Catalogue of reliability automations and the AI coworker control room.",
      relatedRoutes: ["/automation-marketplace", "/ai-coworker-control-room"],
      relatedPages: [`${P}/AutomationMarketplace.tsx`, `${P}/AiCoworkerControlRoom.tsx`],
      relatedComponents: [],
      relatedActions: ["Browse automations", "Review coworker roster"],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "product-representation",
      knownLimitations: [
        "Catalogue entries are not executable and are not linked to RunOps automation",
        "Overlaps the Digital Coworkers candidate module",
      ],
      supersedesCapabilityId: "sre.automation-marketplace",
    }),

    /* ------------------------------------------------- value narrative */
    node({
      capabilityId: "sre.value-narrative",
      parentCapabilityId: "sre",
      level: "capability",
      name: "Transformation and Value Narrative",
      description:
        "Narrative screens supporting reliability transformation conversations with clients.",
      relatedRoutes: [],
      relatedPages: [],
      relatedComponents: [],
      relatedActions: [],
      evidenceStrength: "static-only",
      declaredMaturity: "static",
      implementationClassification: "product-representation",
      knownLimitations: [],
      supersedesCapabilityId: "sre.transformation-narrative",
    }),
    node({
      capabilityId: "sre.value-narrative.journey",
      parentCapabilityId: "sre.value-narrative",
      level: "sub-capability",
      name: "Transformation Journey",
      description: "Journey, success measurement and reliability anatomy narrative.",
      relatedRoutes: [
        "/transformation-journey",
        "/measuring-success",
        "/product-reliability-anatomy",
      ],
      relatedPages: [
        `${P}/TransformationJourney.tsx`,
        `${P}/MeasuringSuccess.tsx`,
        `${P}/ProductReliabilityAnatomy.tsx`,
      ],
      relatedComponents: [],
      relatedActions: ["Walk the journey stages"],
      evidenceStrength: "static-only",
      declaredMaturity: "static",
      implementationClassification: "product-representation",
      knownLimitations: [],
      supersedesCapabilityId: "sre.transformation-narrative",
    }),
    node({
      capabilityId: "sre.value-narrative.transition",
      parentCapabilityId: "sre.value-narrative",
      level: "sub-capability",
      name: "Transition and Onboarding",
      description: "Transition/dual-run model and acquisition onboarding factory.",
      relatedRoutes: ["/transition-dual-run", "/acquisition-onboarding-factory"],
      relatedPages: [`${P}/TransitionDualRun.tsx`, `${P}/AcquisitionOnboardingFactory.tsx`],
      relatedComponents: [],
      relatedActions: ["Review transition phases"],
      evidenceStrength: "static-only",
      declaredMaturity: "static",
      implementationClassification: "product-representation",
      knownLimitations: ["Conceptually adjacent to the carve-out candidate module"],
      supersedesCapabilityId: "sre.transformation-narrative",
    }),
    node({
      capabilityId: "sre.value-narrative.value-board",
      parentCapabilityId: "sre.value-narrative",
      level: "sub-capability",
      name: "Value and Risk Overlays",
      description: "Value creation board, cyber resilience overlay and the interactive demo centre.",
      relatedRoutes: ["/value-creation-board", "/cyber-resilience-overlay", "/interactive-demo-center"],
      relatedPages: [
        `${P}/ValueCreationBoard.tsx`,
        `${P}/CyberResilienceOverlay.tsx`,
        `${P}/InteractiveDemoCenter.tsx`,
      ],
      relatedComponents: [],
      relatedActions: ["Review value levers", "Launch a demo scenario"],
      evidenceStrength: "static-data",
      declaredMaturity: "mock",
      implementationClassification: "interactive-prototype",
      knownLimitations: ["The demo centre is presentation tooling, not a product capability"],
      supersedesCapabilityId: "sre.transformation-narrative",
    }),
  ],
};

export const sreCapabilityById = (id: string) =>
  SRE_CAPABILITY_HIERARCHY.nodes.find((n) => n.capabilityId === id);

export const sreCapabilityChildren = (parentId: string | null) =>
  SRE_CAPABILITY_HIERARCHY.nodes.filter((n) => n.parentCapabilityId === parentId);
