/**
 * SRE Practice module manifest.
 *
 * Scope: the "Site Resilience Engineering" navigation group in
 * `src/components/eoc/Sidebar.tsx`, implemented under `src/pages/prod-twin/`.
 *
 * Evidence discipline: nothing in this manifest is inferred from a menu label
 * alone. No file under `src/pages/prod-twin/` imports the Supabase client, so
 * the module declares NO database entities, services, APIs, workflows,
 * integrations, AI agents or automation actions, and no capability is marked
 * "implemented".
 */

import { MODULE_MANIFEST_SCHEMA_VERSION, type ModuleManifest } from "../types";

const P = "src/pages/prod-twin";

export const manifest: ModuleManifest = {
  schemaVersion: MODULE_MANIFEST_SCHEMA_VERSION,
  identity: {
    moduleId: "sre",
    name: "SRE Practice",
    description:
      "Site Resilience Engineering practice surface: operating-model, reliability-foundations, production digital-twin and modernization narrative screens used in client-facing engagements.",
    moduleVersion: "0.1.0",
    status: "prototype",
    businessDomain: "Site Reliability Engineering",
    productOwner: "unassigned",
    technicalOwner: "unassigned",
    identificationConfidence: "medium",
  },

  boundaries: {
    sourcePaths: [
      "src/pages/prod-twin",
      "src/components/sre-twin",
      "src/data/sreTwinData.ts",
      "src/pages/prod-twin/frictionPanelData.ts",
    ],
    // The module has no route namespace: every route is registered flat at the
    // application root. This is recorded as an architectural issue, not fixed here.
    routePrefixes: ["/reliability-foundations"],
    routes: [
      "/operational-friction-index",
      "/product-reliability-transformation-index",
      "/reliability-foundations",
      "/reliability-foundations/google-sre",
      "/reliability-foundations/google-sre/how-to-achieve",
      "/reliability-foundations/team-topologies",
      "/reliability-foundations/team-topologies/future-state-org",
      "/reliability-foundations/team-topologies/functional-org-chart",
      "/reliability-foundations/platform-engineering/design-principles",
      "/reliability-foundations/platform-engineering/how-to-build",
      "/reliability-foundations/platform-engineering/capability-model",
      "/reliability-foundations/finops/operations-console",
      "/product-reliability-anatomy",
      "/transformation-journey",
      "/measuring-success",
      "/prod-resilience-twin",
      "/product-line-map",
      "/golden-workflow-map",
      "/production-topology",
      "/sre-operating-model",
      "/signal-intelligence",
      "/enterprise-cloud-twin",
      "/aws-resilience-architecture-twin",
      "/platform-engineering-factory",
      "/hybrid-cloud-workbench",
      "/automation-marketplace",
      "/modernization-factory",
      "/cyber-resilience-overlay",
      "/ai-coworker-control-room",
      "/transition-dual-run",
      "/acquisition-onboarding-factory",
      "/value-creation-board",
      "/modernization-roadmap",
      "/modernization-roadmap-v2",
      "/interactive-demo-center",
    ],
    navigationIds: [
      "sre-ofi",
      "sre-fnd",
      "sre-anat",
      "sre-tj",
      "sre-ms",
      "sre-cmd",
      "sre-plm",
      "sre-gwm",
      "sre-topo",
      "sre-opmodel",
      "sre-signal",
      "sre-ecdt",
      "sre-awsrat",
      "sre-pef",
      "sre-hcw",
      "sre-amp",
      "sre-admf",
      "sre-cyber",
      "sre-aicr",
      "sre-tdr",
      "sre-aof",
      "sre-vcb",
      "sre-mrm",
      "sre-idc",
      "sre-mrm2",
    ],
    pageIds: [
      `${P}/OperationalFrictionIndex.tsx`,
      `${P}/ReliabilityFoundations.tsx`,
      `${P}/GoogleSre.tsx`,
      `${P}/HowToAchieveGoogleSre.tsx`,
      `${P}/TeamTopologies.tsx`,
      `${P}/FutureStateReliabilityOrg.tsx`,
      `${P}/FunctionalOrgChart.tsx`,
      `${P}/PlatformEngineeringDesignPrinciples.tsx`,
      `${P}/HowToBuildPlatformEngineering.tsx`,
      `${P}/PlatformAsAProduct.tsx`,
      `${P}/FinOpsOperationsConsole.tsx`,
      `${P}/ProductReliabilityAnatomy.tsx`,
      `${P}/TransformationJourney.tsx`,
      `${P}/MeasuringSuccess.tsx`,
      `${P}/ProdResilienceTwin.tsx`,
      `${P}/ProductLineMap.tsx`,
      `${P}/GoldenWorkflowMap.tsx`,
      `${P}/ProductionTopology.tsx`,
      `${P}/SreOperatingModel.tsx`,
      `${P}/SignalIntelligence.tsx`,
      `${P}/EnterpriseCloudTwin.tsx`,
      `${P}/AWSResilienceArchitectureTwin.tsx`,
      `${P}/PlatformEngineeringFactory.tsx`,
      `${P}/HybridCloudWorkbench.tsx`,
      `${P}/AutomationMarketplace.tsx`,
      `${P}/ModernizationFactory.tsx`,
      `${P}/CyberResilienceOverlay.tsx`,
      `${P}/AiCoworkerControlRoom.tsx`,
      `${P}/TransitionDualRun.tsx`,
      `${P}/AcquisitionOnboardingFactory.tsx`,
      `${P}/ValueCreationBoard.tsx`,
      `${P}/ModernizationRoadmap.tsx`,
      `${P}/ModernizationRoadmapV2.tsx`,
      `${P}/InteractiveDemoCenter.tsx`,
    ],
    componentRefs: [
      "src/components/sre-twin/SRETwinSections.tsx",
    ],
    // Verified: no file under src/pages/prod-twin imports the Supabase client.
    serviceRefs: [],
    apiPrefixes: [],
    databaseEntities: [],
    workflowIds: [],
    integrationIds: [],
    aiAgentIds: [],
    automationActionIds: [],
    // Dashboard-style screens are declared as pages; no separate dashboard or
    // report registry exists in the codebase today.
    dashboardIds: [],
    reportIds: [],
    // Verified: no `sre.*` permission code exists and no SRE route is wrapped
    // in PermissionRoute.
    permissionIds: [],
  },

  capabilities: [
    {
      capabilityId: "sre.operating-model-cockpit",
      name: "SRE Operating Model Cockpit",
      description:
        "Client-facing view of the target SRE operating model: teams, responsibilities and operating rhythms.",
      domain: "Site Reliability Engineering",
      subdomain: "Operating Model",
      businessPurpose:
        "Communicate the proposed reliability operating model during transformation engagements.",
      primaryPersona: "SRE Practice Lead",
      secondaryPersonas: ["Engagement Manager", "Client Executive"],
      implementationStatus: "static",
      relatedPages: [`${P}/SreOperatingModel.tsx`],
      relatedRoutes: ["/sre-operating-model"],
      relatedComponents: [],
      relatedServices: [],
      relatedWorkflows: [],
      relatedEntities: [],
      relatedApis: [],
      relatedIntegrations: [],
      relatedAgents: [],
      relatedAutomationActions: [],
      evidenceHints: [
        "src/App.tsx route /sre-operating-model",
        "Sidebar nav key sre-opmodel",
      ],
      dependencies: [],
      knownLimitations: ["No persistence; content is authored in the component."],
    },
    {
      capabilityId: "sre.reliability-foundations",
      name: "Reliability Foundations Library",
      description:
        "Reference content set covering Google SRE, Team Topologies, Platform Engineering and FinOps operating shifts.",
      domain: "Site Reliability Engineering",
      subdomain: "Enablement",
      businessPurpose: "Provide a shared vocabulary and target-state reference for reliability transformation.",
      primaryPersona: "SRE Practice Lead",
      secondaryPersonas: ["Client Engineering Leader"],
      implementationStatus: "static",
      relatedPages: [
        `${P}/ReliabilityFoundations.tsx`,
        `${P}/GoogleSre.tsx`,
        `${P}/HowToAchieveGoogleSre.tsx`,
        `${P}/TeamTopologies.tsx`,
        `${P}/FutureStateReliabilityOrg.tsx`,
        `${P}/FunctionalOrgChart.tsx`,
        `${P}/PlatformEngineeringDesignPrinciples.tsx`,
        `${P}/HowToBuildPlatformEngineering.tsx`,
        `${P}/PlatformAsAProduct.tsx`,
        `${P}/FinOpsOperationsConsole.tsx`,
      ],
      relatedRoutes: [
        "/reliability-foundations",
        "/reliability-foundations/google-sre",
        "/reliability-foundations/google-sre/how-to-achieve",
        "/reliability-foundations/team-topologies",
        "/reliability-foundations/team-topologies/future-state-org",
        "/reliability-foundations/team-topologies/functional-org-chart",
        "/reliability-foundations/platform-engineering/design-principles",
        "/reliability-foundations/platform-engineering/how-to-build",
        "/reliability-foundations/platform-engineering/capability-model",
        "/reliability-foundations/finops/operations-console",
      ],
      relatedComponents: [],
      relatedServices: [],
      relatedWorkflows: [],
      relatedEntities: [],
      relatedApis: [],
      relatedIntegrations: [],
      relatedAgents: [],
      relatedAutomationActions: [],
      evidenceHints: ["src/App.tsx routes under /reliability-foundations"],
      dependencies: [],
      knownLimitations: ["Editorial content only; no tenant-specific data."],
    },
    {
      capabilityId: "sre.friction-index",
      name: "Enterprise Friction Index",
      description:
        "Scored view of operational friction across an enterprise, rendered from in-repo panel data.",
      domain: "Site Reliability Engineering",
      subdomain: "Assessment",
      businessPurpose: "Quantify and prioritise operational friction for a client engagement.",
      primaryPersona: "SRE Practice Lead",
      secondaryPersonas: ["Client Executive"],
      implementationStatus: "mock",
      relatedPages: [`${P}/OperationalFrictionIndex.tsx`],
      relatedRoutes: ["/operational-friction-index", "/product-reliability-transformation-index"],
      relatedComponents: [],
      relatedServices: [],
      relatedWorkflows: [],
      relatedEntities: [],
      relatedApis: [],
      relatedIntegrations: [],
      relatedAgents: [],
      relatedAutomationActions: [],
      evidenceHints: [
        `${P}/frictionPanelData.ts`,
        "Two routes render the same component (duplicate capability surface).",
      ],
      dependencies: [],
      knownLimitations: [
        "Scores are hard-coded in frictionPanelData.ts.",
        "Exposed twice under two different routes.",
      ],
    },
    {
      capabilityId: "sre.production-digital-twin",
      name: "Production Resilience Digital Twin",
      description:
        "Command-centre, topology, product line and golden-workflow views of a client production estate.",
      domain: "Site Reliability Engineering",
      subdomain: "Digital Twin",
      businessPurpose: "Visualise production services, dependencies and resilience posture.",
      primaryPersona: "Service Owner",
      secondaryPersonas: ["SRE Engineer", "Client Executive"],
      implementationStatus: "mock",
      relatedPages: [
        `${P}/ProdResilienceTwin.tsx`,
        `${P}/ProductionTopology.tsx`,
        `${P}/ProductLineMap.tsx`,
        `${P}/GoldenWorkflowMap.tsx`,
        `${P}/SignalIntelligence.tsx`,
      ],
      relatedRoutes: [
        "/prod-resilience-twin",
        "/production-topology",
        "/product-line-map",
        "/golden-workflow-map",
        "/signal-intelligence",
      ],
      relatedComponents: [],
      relatedServices: [],
      relatedWorkflows: [],
      relatedEntities: [],
      relatedApis: [],
      relatedIntegrations: [],
      relatedAgents: [],
      relatedAutomationActions: [],
      evidenceHints: [
        "No Supabase import anywhere under src/pages/prod-twin.",
        "ProdResilienceTwin links out to the RunOps clinical-integration service route.",
      ],
      dependencies: ["shared.scenario-state"],
      knownLimitations: [
        "All topology and signal data is fixture data.",
        "No live telemetry integration.",
      ],
    },
    {
      capabilityId: "sre.cloud-architecture-twins",
      name: "Cloud & Resilience Architecture Twins",
      description:
        "Enterprise cloud application twin and AWS resilience architecture twin views.",
      domain: "Site Reliability Engineering",
      subdomain: "Digital Twin",
      businessPurpose: "Show cloud architecture and resilience patterns for a client estate.",
      primaryPersona: "Cloud Architect",
      secondaryPersonas: ["SRE Engineer"],
      implementationStatus: "mock",
      relatedPages: [
        `${P}/EnterpriseCloudTwin.tsx`,
        `${P}/AWSResilienceArchitectureTwin.tsx`,
      ],
      relatedRoutes: ["/enterprise-cloud-twin", "/aws-resilience-architecture-twin"],
      relatedComponents: ["src/components/sre-twin/SRETwinSections.tsx"],
      relatedServices: [],
      relatedWorkflows: [],
      relatedEntities: [],
      relatedApis: [],
      relatedIntegrations: [],
      relatedAgents: [],
      relatedAutomationActions: [],
      evidenceHints: [
        "src/data/sreTwinData.ts is imported only by AWSResilienceArchitectureTwin.tsx.",
        "/enterprise-cloud-twin is wrapped in ScenarioStateProvider in src/App.tsx.",
      ],
      dependencies: ["shared.scenario-state"],
      knownLimitations: ["Architecture data is a static fixture."],
    },
    {
      capabilityId: "sre.platform-and-modernization-factories",
      name: "Platform & Modernization Factories",
      description:
        "Platform engineering factory, hybrid cloud workbench, modernization factory and modernization roadmap screens.",
      domain: "Site Reliability Engineering",
      subdomain: "Modernization",
      businessPurpose: "Present the delivery model for platform engineering and modernization work.",
      primaryPersona: "Platform Engineering Lead",
      secondaryPersonas: ["Engagement Manager"],
      implementationStatus: "mock",
      relatedPages: [
        `${P}/PlatformEngineeringFactory.tsx`,
        `${P}/HybridCloudWorkbench.tsx`,
        `${P}/ModernizationFactory.tsx`,
        `${P}/ModernizationRoadmap.tsx`,
        `${P}/ModernizationRoadmapV2.tsx`,
      ],
      relatedRoutes: [
        "/platform-engineering-factory",
        "/hybrid-cloud-workbench",
        "/modernization-factory",
        "/modernization-roadmap",
        "/modernization-roadmap-v2",
      ],
      relatedComponents: [],
      relatedServices: [],
      relatedWorkflows: [],
      relatedEntities: [],
      relatedApis: [],
      relatedIntegrations: [],
      relatedAgents: [],
      relatedAutomationActions: [],
      evidenceHints: [
        "Sidebar declares two entries both labelled 'Modernization Roadmap' (sre-mrm, sre-mrm2).",
      ],
      dependencies: [],
      knownLimitations: ["Two competing roadmap implementations are both live."],
    },
    {
      capabilityId: "sre.automation-marketplace",
      name: "Reliability Automation Marketplace",
      description: "Catalogue view of reliability automations and the AI coworker control room.",
      domain: "Site Reliability Engineering",
      subdomain: "Automation",
      businessPurpose: "Show the automation catalogue available to a reliability programme.",
      primaryPersona: "SRE Engineer",
      secondaryPersonas: ["Automation Engineer"],
      implementationStatus: "mock",
      relatedPages: [`${P}/AutomationMarketplace.tsx`, `${P}/AiCoworkerControlRoom.tsx`],
      relatedRoutes: ["/automation-marketplace", "/ai-coworker-control-room"],
      relatedComponents: [],
      relatedServices: [],
      relatedWorkflows: [],
      relatedEntities: [],
      relatedApis: [],
      relatedIntegrations: [],
      relatedAgents: [],
      relatedAutomationActions: [],
      evidenceHints: [
        "No automation action registry or execution path exists for these screens; RunOps owns real automation.",
      ],
      dependencies: [],
      knownLimitations: [
        "Catalogue entries are not executable and are not linked to RunOps automation.",
      ],
    },
    {
      capabilityId: "sre.transformation-narrative",
      name: "Transformation & Value Narrative",
      description:
        "Transformation journey, measuring success, product reliability anatomy, transition/dual-run, acquisition onboarding, value creation board and demo centre screens.",
      domain: "Site Reliability Engineering",
      subdomain: "Value Story",
      businessPurpose: "Support the reliability transformation and value narrative in client conversations.",
      primaryPersona: "Engagement Manager",
      secondaryPersonas: ["Client Executive", "SRE Practice Lead"],
      implementationStatus: "static",
      relatedPages: [
        `${P}/TransformationJourney.tsx`,
        `${P}/MeasuringSuccess.tsx`,
        `${P}/ProductReliabilityAnatomy.tsx`,
        `${P}/TransitionDualRun.tsx`,
        `${P}/AcquisitionOnboardingFactory.tsx`,
        `${P}/ValueCreationBoard.tsx`,
        `${P}/CyberResilienceOverlay.tsx`,
        `${P}/InteractiveDemoCenter.tsx`,
      ],
      relatedRoutes: [
        "/transformation-journey",
        "/measuring-success",
        "/product-reliability-anatomy",
        "/transition-dual-run",
        "/acquisition-onboarding-factory",
        "/value-creation-board",
        "/cyber-resilience-overlay",
        "/interactive-demo-center",
      ],
      relatedComponents: [],
      relatedServices: [],
      relatedWorkflows: [],
      relatedEntities: [],
      relatedApis: [],
      relatedIntegrations: [],
      relatedAgents: [],
      relatedAutomationActions: [],
      evidenceHints: ["Sidebar nav keys sre-tj, sre-ms, sre-anat, sre-tdr, sre-aof, sre-vcb, sre-cyber, sre-idc"],
      dependencies: [],
      knownLimitations: ["Narrative content only; no tenant data or persistence."],
    },
  ],

  sharedOwnership: [
    {
      ref: "src/components/sre-twin/SRETwinSections.tsx",
      ownership: "module-owned",
      primaryOwner: "sre",
      consumingModules: [],
      relationship: "consumes",
      implementationRefs: ["src/components/sre-twin/SRETwinSections.tsx", "src/data/sreTwinData.ts"],
      notes:
        "Lives outside src/pages/prod-twin but is imported only by AWSResilienceArchitectureTwin.tsx.",
    },
  ],

  sharedDependencies: [
    {
      owner: "unassigned",
      ref: "src/components/eoc/*",
      relationship: "consumes",
      notes:
        "33 imports from SRE pages; also used by other page areas. Ownership undeclared — see docs/modules/ownership-conflicts.md.",
    },
    {
      owner: "unassigned",
      ref: "shared.scenario-state",
      relationship: "consumes",
      notes: "src/context/ScenarioStateContext + src/components/scenario.",
    },
    {
      owner: "unassigned",
      ref: "shared.guided-investigation",
      relationship: "consumes",
      notes: "src/context/GuidedInvestigationContext + src/components/investigation.",
    },
    {
      owner: "unassigned",
      ref: "shared.evidence-graph",
      relationship: "consumes",
      notes: "src/context/EvidenceGraphContext + src/components/evidence.",
    },
  ],

  platformDependencies: [
    { owner: "platform", ref: "src/components/ui/*", relationship: "consumes", notes: "172 imports from SRE pages." },
    { owner: "platform", ref: "src/components/auth/ProtectedRoute.tsx", relationship: "consumes", notes: "Applied at the application shell level, not per SRE route." },
    { owner: "platform", ref: "src/platform/access/AccessContext.tsx", relationship: "consumes" },
    { owner: "platform", ref: "src/components/eoc/Sidebar.tsx", relationship: "consumes", notes: "Hosts the sre-practice navigation group." },
  ],

  exclusions: {
    sourcePaths: ["src/runops", "src/pages/coworkers/sre", "src/pages/practice-library"],
    routes: [
      "/runops",
      "/coworkers/site-reliability-engineering",
      "/coworkers/site-reliability-engineering/release-deployment-rollout",
      "/coworkers/site-reliability-engineering/slo-sla-sli-monitoring",
      "/practice-library/observability-resilience-sre",
      "/data-orchestration-twin",
      "/executive-service-owner-twin",
      "/delivery-org-twin",
      "/engagement-manager-twin",
    ],
    components: [],
    capabilities: [],
    databaseEntities: [],
    workflows: [],
    integrations: [],
    agents: [],
    permissions: [],
    reason:
      "RunOps owns operational execution (incidents, runbooks, SLOs). The SRE digital-coworker pages and the Practice Library SRE dashboard belong to their own modules. The three *-twin routes are registered but absent from the SRE navigation group and remain unassigned.",
  },

  unableToVerify: [
    "Ownership of /data-orchestration-twin (labelled 'SRE Data Orchestration' in navigation but implemented as a separate route tree).",
    "Ownership of routed-but-unnavigated pages: /executive-service-owner-twin, /delivery-org-twin, /engagement-manager-twin.",
    "Product and technical owner for the module (no owner metadata exists anywhere in the repository).",
    "Whether ModernizationRoadmap or ModernizationRoadmapV2 is the intended survivor.",
  ],
};

export default manifest;
