/**
 * Stage 3 — platform capability registry.
 *
 * Platform capabilities are owned by the platform and consumed by every module.
 * They must never be counted as a unique capability of a consuming module: an
 * SRE page that renders inside the app shell and authenticates a user has not
 * thereby implemented authentication.
 *
 * Only capabilities with observed implementation appear here.
 */

import type { PlatformCapability } from "../classificationTypes";

const ALL_MODULES = ["sre", "commercial", "runops", "avep", "cae", "coworkers", "practice-library"];

export const PLATFORM_CAPABILITIES: readonly PlatformCapability[] = [
  {
    platformCapabilityId: "platform.authentication",
    name: "Authentication",
    description:
      "Supabase-backed sign-in, sign-up, invitation acceptance, password reset and session handling.",
    owner: "platform",
    consumingModules: ALL_MODULES,
    frequentlyMiscounted: true,
    sourcePaths: [
      "src/context/AuthContext.tsx",
      "src/components/auth/",
      "src/lib/authErrors.ts",
      "src/integrations/supabase/",
    ],
    routes: ["/login", "/signup", "/reset-password", "/accept-invitation"],
    components: ["src/components/auth/ProtectedRoute.tsx"],
    services: ["supabase.auth"],
    apis: ["forgot-password", "tenant-signup", "record-login", "auth-email-hook"],
    databaseEntities: ["profiles", "user_login_events"],
    workflows: [],
    integrations: [],
    agents: [],
    permissions: [],
    evidence: [
      "AuthContext wraps the whole application in src/App.tsx",
      "Edge functions: forgot-password, tenant-signup, record-login, auth-email-hook",
      "33 of 37 SRE pages reach Supabase only through this chrome",
    ],
    evidenceStrength: "database-backed",
    status: "active",
    maturity: "hardened",
    knownLimitations: [
      "src/components/auth/AuthVerificationOverlay.tsx and TenantAccessGuard.tsx have no import sites — unapplied controls pending review",
    ],
  },
  {
    platformCapabilityId: "platform.tenant-isolation",
    name: "Tenant Isolation",
    description:
      "Tenant resolution, active-tenant scope, membership checks and row-level-security enforcement across all tenant data.",
    owner: "platform",
    consumingModules: ALL_MODULES,
    frequentlyMiscounted: true,
    sourcePaths: [
      "src/platform/access/AccessContext.tsx",
      "src/hooks/useTenantScope.ts",
      "src/platform/data/tenantOptions.ts",
    ],
    routes: ["/platform/tenant-settings"],
    components: [],
    services: ["has_role", "is_platform_admin", "is_user_approved"],
    apis: ["admin-set-tenant-membership", "tenant-invite", "tenant-data-import"],
    databaseEntities: ["tenants", "tenant_memberships", "tenant_tool_assignments"],
    workflows: [],
    integrations: [],
    agents: [],
    permissions: [],
    evidence: [
      "tenants / tenant_memberships referenced by 12 and 13 call sites",
      "RLS matrix documented in docs/bp1-1-rls-matrix.md",
      "Security-definer helpers hardened against arbitrary-uid queries",
    ],
    evidenceStrength: "database-backed",
    status: "active",
    maturity: "hardened",
    knownLimitations: [],
  },
  {
    platformCapabilityId: "platform.rbac",
    name: "Role-Based Access Control",
    description:
      "Platform and tenant roles, permission codes, permission-gated routes and role administration.",
    owner: "platform",
    consumingModules: ALL_MODULES,
    frequentlyMiscounted: true,
    sourcePaths: ["src/platform/access/", "src/platform/pages/RoleAdmin.tsx"],
    routes: ["/platform/roles", "/platform/members"],
    components: ["src/components/auth/PermissionRoute.tsx"],
    services: ["has_role"],
    apis: ["admin-set-platform-role"],
    databaseEntities: ["user_roles", "permissions"],
    workflows: [],
    integrations: [],
    agents: [],
    permissions: ["commercial.*", "audio.*"],
    evidence: [
      "user_roles referenced by 20 call sites; permissions table read by the access layer",
      "PermissionRoute guards Commercial and CAE routes",
    ],
    evidenceStrength: "database-backed",
    status: "active",
    maturity: "hardened",
    knownLimitations: ["No SRE route is permission-gated; the SRE surface has no permission codes"],
  },
  {
    platformCapabilityId: "platform.application-shell-and-navigation",
    name: "Application Shell and Navigation",
    description:
      "Router composition, module layouts, sidebars and the navigation registry that makes a route reachable.",
    owner: "platform",
    consumingModules: ALL_MODULES,
    frequentlyMiscounted: true,
    sourcePaths: [
      "src/App.tsx",
      "src/main.tsx",
      "src/platform/shell/",
      "src/components/routing/",
      "src/components/NavLink.tsx",
    ],
    routes: [],
    components: ["src/platform/shell/PlatformLayout.tsx"],
    services: [],
    apis: [],
    databaseEntities: [],
    workflows: [],
    integrations: [],
    agents: [],
    permissions: [],
    evidence: [
      "436 route entries registered from a single router file",
      "Every module layout mounts inside this shell",
    ],
    evidenceStrength: "client-side-functional",
    status: "active",
    maturity: "established",
    knownLimitations: [
      "src/App.tsx is a single ~900-line route registry with no module segmentation",
      "Two route families are generated at runtime and cannot be statically resolved",
    ],
  },
  {
    platformCapabilityId: "platform.administration",
    name: "Platform Administration",
    description:
      "Tenant, member, role and invitation administration, user profile management and the platform test hub.",
    owner: "platform",
    consumingModules: ["platform"],
    frequentlyMiscounted: false,
    sourcePaths: ["src/platform/pages/", "src/pages/settings/UserManagement.tsx"],
    routes: [
      "/platform",
      "/platform/members",
      "/platform/roles",
      "/platform/tenant-settings",
      "/platform/test-hub",
      "/platform/modules",
    ],
    components: ["src/platform/components/CreateTenantDialog.tsx"],
    services: [],
    apis: ["invite-user", "admin-delete-user", "admin-reset-password", "user-login-history"],
    databaseEntities: ["profiles", "tenants", "tenant_memberships", "user_roles"],
    workflows: [],
    integrations: [],
    agents: [],
    permissions: [],
    evidence: ["Dedicated /platform route tree with its own layout, guarded by platform-admin checks"],
    evidenceStrength: "database-backed",
    status: "active",
    maturity: "hardened",
    knownLimitations: [],
  },
  {
    platformCapabilityId: "platform.audit-logging",
    name: "Audit Logging",
    description:
      "Audit event capture and the audit explorer used to review administrative and data-change activity.",
    owner: "platform",
    consumingModules: ["platform", "commercial", "cae"],
    frequentlyMiscounted: false,
    sourcePaths: ["src/platform/pages/AuditExplorer.tsx"],
    routes: ["/platform/audit"],
    components: [],
    services: ["list_audit_events"],
    apis: [],
    databaseEntities: ["etdm_record_audit_log"],
    workflows: [],
    integrations: [],
    agents: [],
    permissions: [],
    evidence: [
      "list_audit_events RPC consumed by src/platform/pages/AuditExplorer.tsx",
      "ETDM maintains its own etdm_record_audit_log table",
    ],
    evidenceStrength: "database-backed",
    status: "active",
    maturity: "established",
    knownLimitations: [
      "Audit coverage is not uniform: several modules write no audit events",
      "ETDM audit is a separate table rather than the platform audit stream",
    ],
  },
  {
    platformCapabilityId: "platform.notifications",
    name: "In-App Notifications and Email Delivery",
    description:
      "Toast notifications in the client, plus the transactional email queue and templates used for invitations, recovery and verification.",
    owner: "platform",
    consumingModules: ALL_MODULES,
    frequentlyMiscounted: true,
    sourcePaths: [
      "src/hooks/use-toast.ts",
      "src/components/ui/toaster.tsx",
      "supabase/functions/_shared/email-templates/",
      "supabase/functions/process-email-queue/",
    ],
    routes: [],
    components: ["src/components/ui/toaster.tsx"],
    services: [],
    apis: ["process-email-queue", "auth-email-hook"],
    databaseEntities: ["email_send_log"],
    workflows: [],
    integrations: [],
    agents: [],
    permissions: [],
    evidence: [
      "Single toast hook mounted globally in src/App.tsx",
      "Six email templates plus a queue processor edge function",
    ],
    evidenceStrength: "database-backed",
    status: "active",
    maturity: "established",
    knownLimitations: ["No user-facing notification centre or notification preferences"],
  },
  {
    platformCapabilityId: "platform.design-system",
    name: "Design System",
    description: "shadcn/Radix component library, Tailwind tokens and module theme layers.",
    owner: "platform",
    consumingModules: ALL_MODULES,
    frequentlyMiscounted: true,
    sourcePaths: ["src/components/ui/", "src/index.css", "src/avep/theme/", "src/runops/tokens.ts"],
    routes: [],
    components: [],
    services: [],
    apis: [],
    databaseEntities: [],
    workflows: [],
    integrations: [],
    agents: [],
    permissions: [],
    evidence: ["172 import sites from SRE pages alone; excluded from the implementation inventory by design"],
    evidenceStrength: "client-side-functional",
    status: "active",
    maturity: "hardened",
    knownLimitations: ["Three parallel token layers (platform, AVEP, RunOps) with no shared source"],
  },
  {
    platformCapabilityId: "platform.common-data-access",
    name: "Common Data Access",
    description:
      "Supabase client, generated database types, React Query configuration and cross-cutting data hooks.",
    owner: "platform",
    consumingModules: ALL_MODULES,
    frequentlyMiscounted: true,
    sourcePaths: [
      "src/integrations/supabase/",
      "src/hooks/useDataSource.ts",
      "src/hooks/useUserProfile.ts",
      "src/hooks/usePageActivityTracker.ts",
    ],
    routes: [],
    components: [],
    services: [],
    apis: [],
    databaseEntities: ["profiles"],
    workflows: [],
    integrations: [],
    agents: [],
    permissions: [],
    evidence: ["Single Supabase client instance; QueryClientProvider mounted once in src/App.tsx"],
    evidenceStrength: "database-backed",
    status: "active",
    maturity: "hardened",
    knownLimitations: [],
  },
  {
    platformCapabilityId: "platform.feature-flags",
    name: "Feature Flags",
    description: "Module-local feature-flag switches controlling optional runtime behaviour.",
    owner: "platform",
    consumingModules: ["runops", "cae"],
    frequentlyMiscounted: false,
    sourcePaths: ["src/runops/domain/featureFlags.ts"],
    routes: [],
    components: [],
    services: [],
    apis: [],
    databaseEntities: [],
    workflows: [],
    integrations: [],
    agents: [],
    permissions: [],
    evidence: [
      "RunOps declares its own flag module; CAE gates behaviour on provider-level flags",
      "No central flag service exists",
    ],
    evidenceStrength: "static-data",
    status: "proposed",
    maturity: "experimental",
    knownLimitations: [
      "Flags are compile-time constants per module, not a platform capability in practice",
      "Listed as 'proposed' precisely because the shared implementation does not exist yet",
    ],
  },
  {
    platformCapabilityId: "platform.error-handling",
    name: "Error Handling",
    description: "Error boundaries and user-facing failure states.",
    owner: "platform",
    consumingModules: ["runops", "cae", "platform"],
    frequentlyMiscounted: false,
    sourcePaths: [
      "src/runops/shell/RunOpsErrorBoundary.tsx",
      "src/platform/cae/ContextualAudioErrorBoundary.tsx",
      "src/platform/components/States.tsx",
    ],
    routes: [],
    components: ["src/platform/components/States.tsx"],
    services: [],
    apis: [],
    databaseEntities: [],
    workflows: [],
    integrations: [],
    agents: [],
    permissions: [],
    evidence: ["Two module-local error boundaries plus a shared loading/empty/error state component"],
    evidenceStrength: "client-side-functional",
    status: "active",
    maturity: "emerging",
    knownLimitations: [
      "No application-level error boundary; a crash outside RunOps or CAE unmounts the app",
    ],
  },
];

export const getPlatformCapability = (id: string) =>
  PLATFORM_CAPABILITIES.find((c) => c.platformCapabilityId === id);

/** Source paths owned by the platform, for exclusion from module counts. */
export const platformOwnedPaths = (): readonly string[] =>
  PLATFORM_CAPABILITIES.flatMap((c) => c.sourcePaths);
