
ALTER TABLE public.crm_stakeholders
  ADD COLUMN IF NOT EXISTS stakeholder_code text,
  ADD COLUMN IF NOT EXISTS stakeholder_type text,
  ADD COLUMN IF NOT EXISTS stakeholder_category text,
  ADD COLUMN IF NOT EXISTS organization_name text,
  ADD COLUMN IF NOT EXISTS department_name text,
  ADD COLUMN IF NOT EXISTS location text,
  ADD COLUMN IF NOT EXISTS region text,
  ADD COLUMN IF NOT EXISTS alternate_phone text,
  ADD COLUMN IF NOT EXISTS preferred_contact_method text,
  ADD COLUMN IF NOT EXISTS preferred_contact_time text,
  ADD COLUMN IF NOT EXISTS time_zone text,
  ADD COLUMN IF NOT EXISTS project_code text,
  ADD COLUMN IF NOT EXISTS project_name text,
  ADD COLUMN IF NOT EXISTS program_name text,
  ADD COLUMN IF NOT EXISTS portfolio_name text,
  ADD COLUMN IF NOT EXISTS account_name text,
  ADD COLUMN IF NOT EXISTS business_unit text,
  ADD COLUMN IF NOT EXISTS practice_area text,
  ADD COLUMN IF NOT EXISTS project_phase text,
  ADD COLUMN IF NOT EXISTS stakeholder_role text,
  ADD COLUMN IF NOT EXISTS responsibility text,
  ADD COLUMN IF NOT EXISTS ownership_area text,
  ADD COLUMN IF NOT EXISTS involvement_level text,
  ADD COLUMN IF NOT EXISTS start_date date,
  ADD COLUMN IF NOT EXISTS end_date date,
  ADD COLUMN IF NOT EXISTS internal_external text,
  ADD COLUMN IF NOT EXISTS primary_secondary text,
  ADD COLUMN IF NOT EXISTS direct_indirect text,
  ADD COLUMN IF NOT EXISTS decision_maker boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS approver boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS influencer boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS impacted_by_project boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS beneficiary boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS regulatory_or_compliance_role boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS power_level text,
  ADD COLUMN IF NOT EXISTS interest_level text,
  ADD COLUMN IF NOT EXISTS impact_level text,
  ADD COLUMN IF NOT EXISTS urgency_level text,
  ADD COLUMN IF NOT EXISTS legitimacy_level text,
  ADD COLUMN IF NOT EXISTS priority_level text,
  ADD COLUMN IF NOT EXISTS support_level text,
  ADD COLUMN IF NOT EXISTS attitude text,
  ADD COLUMN IF NOT EXISTS risk_sensitivity text,
  ADD COLUMN IF NOT EXISTS power_interest_category text,
  ADD COLUMN IF NOT EXISTS stakeholder_management_strategy text,
  ADD COLUMN IF NOT EXISTS current_engagement_level text,
  ADD COLUMN IF NOT EXISTS desired_engagement_level text,
  ADD COLUMN IF NOT EXISTS engagement_gap text,
  ADD COLUMN IF NOT EXISTS engagement_strategy text,
  ADD COLUMN IF NOT EXISTS engagement_owner text,
  ADD COLUMN IF NOT EXISTS relationship_health text,
  ADD COLUMN IF NOT EXISTS communication_method text,
  ADD COLUMN IF NOT EXISTS communication_frequency text,
  ADD COLUMN IF NOT EXISTS communication_format text,
  ADD COLUMN IF NOT EXISTS information_needs text,
  ADD COLUMN IF NOT EXISTS reporting_needs text,
  ADD COLUMN IF NOT EXISTS meeting_cadence text,
  ADD COLUMN IF NOT EXISTS communication_owner text,
  ADD COLUMN IF NOT EXISTS last_contacted_date date,
  ADD COLUMN IF NOT EXISTS next_followup_date date,
  ADD COLUMN IF NOT EXISTS communication_notes text,
  ADD COLUMN IF NOT EXISTS decision_authority text,
  ADD COLUMN IF NOT EXISTS approval_authority text,
  ADD COLUMN IF NOT EXISTS approval_areas text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS approval_limit text,
  ADD COLUMN IF NOT EXISTS signoff_required boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS signoff_stage text,
  ADD COLUMN IF NOT EXISTS escalation_required boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS escalation_path text,
  ADD COLUMN IF NOT EXISTS governance_role text,
  ADD COLUMN IF NOT EXISTS raci_role text,
  ADD COLUMN IF NOT EXISTS responsible_for text,
  ADD COLUMN IF NOT EXISTS accountable_for text,
  ADD COLUMN IF NOT EXISTS consulted_for text,
  ADD COLUMN IF NOT EXISTS informed_for text,
  ADD COLUMN IF NOT EXISTS key_expectations text,
  ADD COLUMN IF NOT EXISTS success_criteria text,
  ADD COLUMN IF NOT EXISTS key_concerns text,
  ADD COLUMN IF NOT EXISTS pain_points text,
  ADD COLUMN IF NOT EXISTS business_needs text,
  ADD COLUMN IF NOT EXISTS constraints text,
  ADD COLUMN IF NOT EXISTS assumptions text,
  ADD COLUMN IF NOT EXISTS stakeholder_risk_level text,
  ADD COLUMN IF NOT EXISTS risk_description text,
  ADD COLUMN IF NOT EXISTS possible_project_impact text,
  ADD COLUMN IF NOT EXISTS mitigation_plan text,
  ADD COLUMN IF NOT EXISTS issue_history text,
  ADD COLUMN IF NOT EXISTS open_actions text,
  ADD COLUMN IF NOT EXISTS escalation_notes text,
  ADD COLUMN IF NOT EXISTS change_impact_level text,
  ADD COLUMN IF NOT EXISTS change_readiness text,
  ADD COLUMN IF NOT EXISTS training_required boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS adoption_owner text,
  ADD COLUMN IF NOT EXISTS resistance_reason text,
  ADD COLUMN IF NOT EXISTS change_management_strategy text,
  ADD COLUMN IF NOT EXISTS attachments text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS related_documents text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS meeting_notes text,
  ADD COLUMN IF NOT EXISTS created_by uuid,
  ADD COLUMN IF NOT EXISTS updated_by uuid,
  ADD COLUMN IF NOT EXISTS approved_by uuid,
  ADD COLUMN IF NOT EXISTS approved_at timestamptz,
  ADD COLUMN IF NOT EXISTS archived_by uuid,
  ADD COLUMN IF NOT EXISTS archived_at timestamptz;
