
-- Prevent duplicate active standard domains per technology
CREATE UNIQUE INDEX IF NOT EXISTS etdm_domains_unique_active_master_per_tech
ON public.etdm_domains (technology_id, master_domain_id)
WHERE is_deleted = false;

-- Auto-Build Standard Domains RPC
CREATE OR REPLACE FUNCTION public.etdm_auto_build_domains(
  _technology_id uuid,
  _master_domain_ids uuid[]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tech public.etdm_technologies;
  v_master record;
  v_new_id uuid;
  v_slug text;
  v_slug_base text;
  v_slug_suffix int;
  v_desc text;
  v_crit public.etdm_domain_criticality;
  v_created uuid[] := ARRAY[]::uuid[];
  v_skipped_existing uuid[] := ARRAY[]::uuid[];
  v_skipped_inactive uuid[] := ARRAY[]::uuid[];
  v_uid uuid := auth.uid();
BEGIN
  IF NOT public.is_platform_admin(v_uid) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  SELECT * INTO v_tech
  FROM public.etdm_technologies
  WHERE id = _technology_id AND is_deleted = false;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'technology_not_found';
  END IF;

  -- Default criticality: inherit from tech if it maps to enum, else Standard
  BEGIN
    v_crit := (COALESCE(NULLIF(btrim(v_tech.business_criticality), ''), 'Standard'))::public.etdm_domain_criticality;
  EXCEPTION WHEN others THEN
    v_crit := 'Standard'::public.etdm_domain_criticality;
  END;

  FOR v_master IN
    SELECT id, name, display_order, is_active
    FROM public.etdm_master_domains
    WHERE id = ANY(_master_domain_ids)
    ORDER BY display_order
  LOOP
    IF v_master.is_active = false THEN
      v_skipped_inactive := array_append(v_skipped_inactive, v_master.id);
      CONTINUE;
    END IF;

    IF EXISTS (
      SELECT 1 FROM public.etdm_domains
      WHERE technology_id = _technology_id
        AND master_domain_id = v_master.id
        AND is_deleted = false
    ) THEN
      v_skipped_existing := array_append(v_skipped_existing, v_master.id);
      CONTINUE;
    END IF;

    -- Build unique slug
    v_slug_base := lower(regexp_replace(
      COALESCE(v_tech.slug, regexp_replace(lower(v_tech.technology_name), '[^a-z0-9]+', '-', 'g'))
      || '-' ||
      regexp_replace(lower(v_master.name), '[^a-z0-9]+', '-', 'g'),
      '-+', '-', 'g'
    ));
    v_slug_base := btrim(v_slug_base, '-');
    v_slug := v_slug_base;
    v_slug_suffix := 1;
    WHILE EXISTS (SELECT 1 FROM public.etdm_domains WHERE slug = v_slug) LOOP
      v_slug_suffix := v_slug_suffix + 1;
      v_slug := v_slug_base || '-' || v_slug_suffix::text;
    END LOOP;

    v_desc := 'Defines how the ' || v_master.name || ' domain applies to ' || v_tech.technology_name
           || ', including its scope, responsibilities, governance, and related capabilities.';

    INSERT INTO public.etdm_domains(
      tenant_id, technology_id, master_domain_id,
      domain_display_name, slug, description, display_order, tags,
      business_criticality, lifecycle_status, approval_status,
      is_active, is_deleted,
      governance_notes, source_of_record,
      created_by, updated_by, published_version
    ) VALUES (
      v_tech.tenant_id, _technology_id, v_master.id,
      v_master.name, v_slug, v_desc, v_master.display_order,
      ARRAY['ETDM','Technology Domain', v_tech.technology_name, v_master.name],
      v_crit,
      'Evaluation'::public.etdm_domain_lifecycle,
      'Draft'::public.etdm_domain_approval,
      false, false,
      'Auto-generated by ETDM Auto-Build on ' || to_char(now(), 'YYYY-MM-DD HH24:MI:SS TZ') ||
      '. Review and complete before activation.',
      'ETDM Standard Domain Auto-Build',
      v_uid, v_uid, 1
    )
    RETURNING id INTO v_new_id;

    v_created := array_append(v_created, v_new_id);
  END LOOP;

  -- Parent bulk audit event
  INSERT INTO public.etdm_record_audit_log(
    tenant_id, entity_type, entity_id, action, changed_by,
    new_values, source
  ) VALUES (
    v_tech.tenant_id, 'technology', _technology_id, 'auto_build_domains', v_uid,
    jsonb_build_object(
      'requested_master_ids', to_jsonb(_master_domain_ids),
      'created_domain_ids', to_jsonb(v_created),
      'skipped_existing_master_ids', to_jsonb(v_skipped_existing),
      'skipped_inactive_master_ids', to_jsonb(v_skipped_inactive)
    ),
    'portal'
  );

  RETURN jsonb_build_object(
    'created_ids', to_jsonb(v_created),
    'skipped_existing_ids', to_jsonb(v_skipped_existing),
    'skipped_inactive_ids', to_jsonb(v_skipped_inactive)
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.etdm_auto_build_domains(uuid, uuid[]) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.etdm_auto_build_domains(uuid, uuid[]) FROM anon;
