-- The ServiceNow intake schema is created by the earlier
-- 20260831210000_create_servicenow_intake migration and the demo status
-- constraint is added by 20260831213000_add_servicenow_demo_status.
--
-- This migration was generated again by the hosted project. Keep the
-- migration id in the history, but intentionally make it a no-op so a fresh
-- database does not attempt to create the same tables, policies, and indexes
-- twice.
